### ISSUE TITLE
 How to delete only one event of issue?

### ISSUE THREAD

**Issue by omidraha** [getsentry/sentry#24472] opened 2021-03-16 12:16 UTC
### Summary

Every issue has many events in the issue page of  panel.
And there is a delete option in the issue page of panel named `Delete and discard future event`, But this will delete and discard the issue and all related events of issue.
But there is no way to delete only current event or specific event of issue.

### Motivation

Add  one more `delete` option to delete only current event of issue.

**Comment by BYK** [comment] 2021-03-16 12:51
@omidraha can you answer the following question please:

>Why should this be worked on? What problems or use cases does it solve or
improve?

**Comment by omidraha** [comment] 2021-03-16 13:05
> Why should this be worked on? What problems or use cases does it solve or
 > improve?

The use cases that happening to me. I have one issue by same title but customized extra messages data within events of the issue from different users.
Some of them are not useful and I would like to delete them (some events of this  issue), and some of them  (some other events of this  issue)  is useful and I would like to keep them inside of issue.

**Comment by BYK** [comment] 2021-03-17 14:06
@omidraha thanks for sharing that. Pinging @getsentry/workflow for triage. Also pinging @untitaker as he may have ideas about this.

**Comment by untitaker** [comment] 2021-03-17 16:59
@omidraha can you elaborate on why you cannot just leave the events as they are?

In any case this is the same as that other issue about deleting transactions: Individual event deletion is probably not something we would ever like to implement.

**Comment by omidraha** [comment] 2021-03-17 20:15
Yes, this is exactly Individual event deletion option.
Because I have some type of issues, that the title of this type of these issues ares  fixed.
And their events of them are very low.
For example, less than ten events per month for each issue.
And I need to these types of issues to be always open.
And these issues are not resolved or closed.
And I need to look at these issue  sometimes again.
That is why some events that are not useful are annoying inside issue and I would like to delete them.

**Comment by chadwhitacre** [comment] 2021-04-01 21:01
>> Yes, this is exactly Individual event deletion option.
>
> Individual event deletion is probably not something we would ever like to implement.

Sounds like this is a "won't fix," sorry @omidraha. 😞

> this is the same as that other issue about deleting transactions

@untitaker Any chance you could dig up a link (my search attempts are either [too broad](https://github.com/getsentry/sentry/issues?q=is%3Aissue+delete+event) or [too narrow](https://github.com/getsentry/sentry/issues?q=is%3Aissue+deleting+transactions) 🐭), or provide additional rationale as to why we don't want to implement this?

> I need to these types of issues to be always open.

E.g., this sounds like maybe not how Sentry is designed to be used.

**Comment by omidraha** [comment] 2021-04-01 21:09
OK,
Is it possible to give a raw SQL query command to delete such events of issue from db manually?

**Comment by chadwhitacre** [comment] 2021-04-01 21:26
> Is it possible to give a raw SQL query command to delete such events of issue from db manually?

Binary answer? Yes. 😬

If you figure something out maybe share it here for the next self-hoster who has the same problem?

**Comment by untitaker** [comment] 2021-04-02 08:05
This is the reference for why this is costly to implement: https://blog.sentry.io/2019/10/25/how-to-mutate-data-in-a-system-designed-for-immutable-data

**Comment by BYK** [comment] 2021-04-02 08:49
Closing the issue to signal our intent: we don't see this happening any time soon if ever. Thanks a lot for bringing it up and sorry that we won't be working on this.

**Closed by BYK** 2021-04-02 08:49 UTC
Labels: Status: Untriaged, Team: Workflow, Type: User Feedback

**Comment by untitaker** [comment] 2021-04-02 08:57
@omidraha generally speaking you can re-insert a row into clickhouse with `deleted` changed to `1`, then Clickhouse will *eventually* replace the old row with the new one which will be *eventually* excluded from query results. In the meantime you will see inconsistent data. You can remove/null out almost all data from the newly row, just make sure the primary key stays intact and deleted=1.

**Comment by untitaker** [comment] 2021-04-02 11:10
@omidraha to be honest I still have a hard time understanding the usecase. It seems to me you have one, very long-standing issue which really contains multiple issues you want to triage. So for example in January you get a bunch of events that you then fix, then you close the issue, then in July you get a bunch of other events but the root cause is different and it's a separate bugfix. Is that accurate?

**Comment by chadwhitacre** [comment] 2021-04-02 13:46
> that other issue about deleting transactions

Found it! https://github.com/getsentry/sentry/issues/24472 :-)

**Comment by chadwhitacre** [comment] 2021-04-02 13:47
> that other issue about deleting transactions

Found it! https://github.com/getsentry/onpremise/issues/856 :-)
