### ISSUE TITLE
OAuth Error: Invalid client_id parameter

### ISSUE THREAD

**Issue by TachyonRSA** [getsentry/sentry#12579] opened 2019-03-28 12:30 UTC
I am trying to integrate Slack with sentry but I keep running into the error mentioned in the title when I click on configure for slack. Does anyone have a solution to this?

**Comment by ahmetkakici** [comment] 2019-04-01 08:22
Same issue: #9004

**Comment by EvanPurkhiser** [comment] 2019-05-13 20:41
Duplicate of #9004

**Closed by EvanPurkhiser** 2019-05-13 20:41 UTC
