### ISSUE TITLE
Add support to shared channels in MSteams integration

### ISSUE THREAD

**Issue by rbisol** [getsentry/sentry#41558] opened 2022-11-18 11:17 UTC
### Problem Statement

The current MSTeams integration does not support shared channels: https://support.microsoft.com/en-us/office/teams-can-have-standard-private-or-shared-channels-de3e20b0-7494-439c-b7e5-75899ebe6a0e

### Solution Brainstorm

add support to shared channels.

**Comment by zyv** [comment] 2022-11-30 08:55
Duplicate of #41641.

**Closed** 2022-11-30 17:36 UTC
