### ISSUE TITLE
Redmine integration backlink is broken

### ISSUE THREAD

**Issue by valipod** [getsentry/sentry#7024] opened 2018-01-22 16:18 UTC
On https://sentry.io, for redmine integrations that were already configured previously (currently this is no longer possible - issue [#7023](https://github.com/getsentry/sentry/issues/7023)) after creating a ticket via "Create Redmine Task", this button erroneously changes to "Link Issue Tracker" (as if no tracker were configured), instead of a message that the ticket was already created or even a backlink with the created redmine ticket.

![link-tracker](https://user-images.githubusercontent.com/1492705/35231108-93b50a8c-ffa0-11e7-85e2-2f6b3cffac95.png)

**Comment by blacksmith77** [comment] 2018-03-26 12:37
Same problem here... redmine 3.4.4

**Comment by BYK** [comment] 2020-10-21 18:56
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Closed by BYK** 2020-10-21 18:56 UTC

**Comment by valipod** [comment] 2020-10-22 07:53
I am sorry, what do you mean by stallness? No further comments on the issue? I is not something I can work on. The issue is still there, the Redmine integration is still broken. Indeed, 2 2/1 years later, but...

**Comment by BYK** [comment] 2020-10-22 08:51
@valipod - What I mean nobody commented or acted on this issue for over 2 years and it is very unlikely that it will be attended at all at this point. I do see the issue is there but Redmine integration is not a priority for the team at the moment.

If you are interested you can try submitting a PR and we'd do our best to guide you and get it merged.
