### ISSUE TITLE
[Discover] List complete collection of tags

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#44978] opened 2023-02-22 20:03 UTC
### Problem Statement

Currently when navigating from Sentry issue to Discover using the "Open in Discover" only 10 tags are listed on the [Tag Summary](https://docs.sentry.io/product/discover-queries/query-builder/#tag-summary-filters) when there could be much more associated to the issue.

### Solution Brainstorm

Ability to view all tags from the tag summary section in discover.

From Customer:
_A user should have the option to expand to all tags in Discover mode because it prevents me from doing the analysis I want to do. It can still default to 10, but then let's add an arrow option to expand._

**Comment by brentc** [comment] 2023-02-22 20:16
It's likely that this limit exists for performance reasons. Can you elaborate more on the kinds of analysis you can't complete with having more (or all?) of the tags from the matched results? What's your end-goal?

**Comment by JLuse** [comment] 2023-02-27 19:29
@brentc still waiting to hear back from the customer about your follow-up questions.

**Comment by JLuse** [comment] 2023-02-28 22:56
@brentc heard back and they mentioned:
> My end goal is to be able to identify the unique instances of that tag being affected by the bug. Discover Mode already offers this; however, because not all the tags appear, I had to export the data to Google Sheets and manually call the =UNIQUE function on that tag to complete my analysis.

**Comment by brentc** [comment] 2023-03-07 15:52
Thanks for that context. We'll add this to the backlog and review against other priorities for working on sometime in the future.

**Comment by DamGouz** [comment] 2023-05-16 08:48
This is a really important feature for us, as currently there is no visibility on tag distributions for anything other than full issues.
And even though that's helpful, we want to have the ability to see how tags are correlated to a single issue but for a subset of its events, or even across multiple issues that have something in common but can not be merged together.

**Comment by brentc** [comment] 2023-06-12 19:24
Talking with folks, I've confirmed now that the limit exists here because of performance reasons. Just doing the 10 we have now is already not great. 

I think there are some possible ways we can tackle this,

1. Allow users to load more tags on-demand.
    E.g. a "Load More" button that queries an additional 10 tags at a time

1. Consider using the same tag elevation that issues does to always include certain tags at the top of the tag summary (defined per project type)
    This is complicated by for queries when multiple projects are selected in the project selector though

1. Consider allowing users to identify certain tags to always load first.
    E.g. "Pin" a tag to always be at the top of the summary
    Lots of work flow questions to answer with this -- global vs session scoped? Save with the query? 

We're starting to look into some combination of the above

**Comment by narsaynorath** [comment] 2023-06-26 16:18
Hey there @JLuse, just wanted to give you a heads up that we've recently updated the tag summary in Discover with a "Show More" button that lets users load in more tags in pages of 10. They should be able to expand and see all of their tags now.

Example UI:
<img width="523" alt="Screenshot 2023-06-26 at 10 59 02 AM" src="https://github.com/getsentry/sentry/assets/22846452/15ab2c4e-85c1-4b0b-8ba5-399ea5d197d3">

Let us know if you have any feedback about this or if there's any interest in the other solutions in the comment above.

**Closed by narsaynorath** 2023-06-26 16:18 UTC
Labels: Status: Backlog, enhancement, Product Area: Discover

**Comment by DamGouz** [comment] 2023-06-26 18:51
Hello! I just used the new Show More feature. I have identified 2 issues with it that prevents us from utilizing it as we would want to.
1) The order of the tags is still random, so we need to keep clicking on Show More until we are randomly shown the tag we are looking for.
2) We need to go through the motions of clicking through those buttons every time we refresh the page, which means a lot of wasted time doing the same thing again and again.

Ideally, we would like to be able to specify which tags we want to see and sentry should remember our choices on future visits to the Discover page.

**Comment by narsaynorath** [comment] 2023-06-28 16:06
Hey @DamGouz, thanks for quickly testing the feature out and passing along your feedback. I've tried to capture it in #51798 and listed out some of the UX investigations we need to complete before we're able to fully commit to a solution.

If you had any comments about some of the cases I've listed, or if you feel like I've missed anything in my summary, please let us know in that issue. We appreciate having your feedback!
