### ISSUE TITLE
The page keep not responded

### ISSUE THREAD

**Issue by accelbyte-sdk** [getsentry/sentry#61022] opened 2023-12-04 08:18 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

-

### Expected Result

Can see the page

### Actual Result

![image](https://github.com/getsentry/sentry/assets/92429240/982f3d6c-284d-4f87-8901-cb87e5bbab50)

### Product Area

Other

**Comment by kerenkhatiwada** [comment] 2023-12-04 18:11
Duplicate of #61062. Please follow along there.

**Closed by kerenkhatiwada** 2023-12-04 18:11 UTC
Labels: Waiting for: Support
