### ISSUE TITLE
Ability to query replay data via API or export

### ISSUE THREAD

**Issue by vinayman** [getsentry/sentry#51687] opened 2023-06-27 08:28 UTC
### Problem Statement

It is important for us to be able to track our users usage of our application.

- We would like to view what items on the application they click on
- When they click on an item - they have some user actions, so it would be helpful for us to see the most important user actions
- We are aware of different users coming from different industries - so we could have some analytics on what items are more important for what industries by what they click on etc.

We could build something in-house that would emit some sort of event onClick that could be captured in a database to allow us to query this on a large scale. However, as far as I can tell, Sentry already has this data through ClickSearch in Replay. Is it possible for Sentry to expose the Replay metadata via API?

### Solution Brainstorm

For example, two API endpoints:
One giving us all session replay events with unique identifiers with some metadata on the session replay with some suitable query params and would return: e.g., a user (if available), IP address, date/period of the session etc.

Another with the API query param of the session replay identifier and perhaps for example, what we want, e.g., `?data=user-click`, returning: a time-series of user clicks (with the DOM elements).

I understand DOM elements might be challenging to return via API when they are excessively large. Perhaps we can have a query param that allows you to select what DOM elements to query, e.g., `?dom=only-children` -> where it would return the innermost DOM element/child or `?dom=id` -> where it would return the ID of the DOM elements only.

**Comment by bruno-garcia** [comment] 2023-06-27 14:17
Thanks for writing in @vinayman 

This issue is a duplicate of: https://github.com/getsentry/sentry/issues/44919 so I'm closing in favor of that.
I'll copy your description over to that issue for additional context.

**Closed by bruno-garcia** 2023-06-27 14:17 UTC
Labels: Status: Untriaged, Type: Improvement, Product Area: Replays, Waiting for: Product Owner
