### ISSUE TITLE
Can not create new jira ticket after mark the sentry issue as resolved

### ISSUE THREAD

**Issue by denghejun** [getsentry/sentry#79073] opened 2024-10-12 06:37 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Sentry and Jira integrated well
2. Sentry created an issue and then Jira create a ticket for this issue automatically by "a Alert rule", all good.
3. I change the Jira ticket as 'Done', then Sentry mark the sentry issue to "Resolved", all good.
4. One week later, Then the issue happen again, Sentry didn't create a new issue, but just add a new event for that issue, then Jira didn't create a new ticket for this issue/event, because the issue already linked to the previous Jira ticket(which is already marked to "Done")
5. So I can not see new ticket on Jira, nobody knows there is an issue happen again in Prod env.
6. How to fix this? any workaround?

### Expected Result

How to fix this? any workaround? At least I hop Jira can create a new Ticket if sentry issue has been marked as resolved.

### Actual Result

no Jira ticket created

### Product Area

Unknown

**Comment by sentaur-athena** [comment] 2024-10-16 21:54
Thanks for the feedback. We'll investigate and update the ticket

**Comment by GabeVillalobos** [comment] 2024-10-21 17:58
@denghejun Our integration does not create new tickets when a Jira linked issue is marked as `unresolved` in Sentry, but rather, attempts to update the ticket's status if sync settings are enabled for the project. This can be set via the Jira integration configuration page: https://docs.sentry.io/organization/integrations/issue-tracking/jira/#issue-sync

Something to keep in mind: the status transitions you configure must be valid workflow transitions in your Jira organization or this can fail to update the Jira ticket's status correctly.

Closing this as this isn't intended behavior of our integration, but please open a new issue if you encounter any problems with the issue sync settings I linked.

**Closed by GabeVillalobos** 2024-10-21 17:58 UTC
Labels: Product Area: Settings - Integrations

**Comment by denghejun** [comment] 2024-10-22 04:02
No，I mean the issue in sentry already been marked as resolved，but when the same issue happend again，only a new event was appended on the issue and no new ticket created in Jira，and then I checked the issue in sentry，still the old jira issue connected .  How can I create a new jira ticket after the same issue happen again？Do you understand me. I think the issue and event concept is over design in sentry，what i expected is when ever the event happend，sentry alert need to create a new jira ticket，so that I can assign the issue to people on jira every daily work.
Kind regards,
Hejun Deng

在 2024年10月22日，01:59，Gabe Villalobos ***@***.***> 写道：

﻿

@denghejun<https://github.com/denghejun> Our integration does not create new tickets when a Jira linked issue is marked as unresolved in Sentry, but rather, attempts to update the ticket's status if sync settings are enabled for the project. This can be set via the Jira integration configuration page: https://docs.sentry.io/organization/integrations/issue-tracking/jira/#issue-sync

Something to keep in mind: the status transitions you configure must be valid workflow transitions in your Jira organization or this can fail to update the Jira ticket's status correctly.

Closing this as this isn't intended behavior of our integration, but please open a new issue if you encounter any problems with the issue sync settings I linked.
