### ISSUE TITLE
symbolicator is skipping connections to internal IPs

### ISSUE THREAD

**Issue by maxp1256** [getsentry/sentry#16934] opened 2020-02-11 08:48 UTC
## Important Details

How are you running Sentry?

* [x] On-Premise docker [latest]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I'm trying to add our internal https symbol server to a sentry project, but there are no http requests done by symbolicator.

## Steps to Reproduce

1. I've defined our internal symbol server with https and Port 444 as Custom Repository, and Microsoft and Unity as Built-In-Repository.
2. I'm doing a tcpdump at the symbolicator container to verify the request from and to symbolicator.

```
{"url":"https://ourtfs.ourdomain.ourtld:444/","layout":{"casing":"default","type":"symstore"},"type":"http","id":"qa3xbk7ap4","name":"tfs"},
{"layout":{"type":"symstore"},"name":"Unity","url":"http://symbolserver.unity3d.com/","filters":{"filetypes":["pdb","pe"]},"is_public":true,"type":"http","id":"sentry:unity"},
{"layout":{"type":"symstore"},"name":"Microsoft","url":"https://msdl.microsoft.com/download/symbols/","filters":{"filetypes":["pdb","pe"]},"is_public":true,"type":"http","id":"sentry:microsoft"}]
```
3. I cannot see any communication to ourtfs.

### What you expected to happen
A lot of http requests to ourtfs

### Reason
The reason for this behavior is that symbolicator skips connections to RESERVED_IP_BLOCKS defined in https://github.com/getsentry/symbolicator/blob/94cdbb7b543ebe53744144305db21a56b6a0d5a8/src/utils/http.rs#L17

I think that this feature should be disabled for on-premise because it's likely that the symbol server doesn't have an external IP.

**Comment by untitaker** [comment] 2020-02-21 12:35
This is a duplicate of https://github.com/getsentry/symbolicator/issues/120. I do not think that we can just straight up disable for onprem.

**Closed by untitaker** 2020-02-21 12:35 UTC
