### ISSUE TITLE
Package section is moving itself without user interaction

### ISSUE THREAD

**Issue by d6u** [getsentry/sentry#3241] opened 2016-05-16 13:37 UTC
I've talked with Matt Robenolt through email, he suggested me to post here.

![may-11-2016 14-25-24](https://cloud.githubusercontent.com/assets/2153667/15290946/97665fb0-1b49-11e6-9ce7-f8222fe8ed81.gif)

Basically, the package section of error page is collapsing by itself after entering the route for a few sec. Unexpected movement of an UI is mostly a bad user experience, and Matt said that's unintentional. Thanks!

**Comment by nateberkopec** [comment] 2016-05-16 14:21
![2spooky](https://cloud.githubusercontent.com/assets/845662/15292193/e7a7d368-1b4f-11e6-999f-23735ac737db.gif)

sentry confirmed for demon possesion

**Comment by BYK** [comment] 2020-09-30 12:54
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Closed by BYK** 2020-09-30 12:54 UTC
