### ISSUE TITLE
OS detection gives conflicting info

### ISSUE THREAD

**Issue by LeEnno** [getsentry/sentry#6873] opened 2018-01-04 09:39 UTC
I'm using sentry.io and OS detection seems to be a little off.

- OS X 10.11 results in: os = Mac OS X 10.11 and os.name = Mac OS X
- Windows 10 results in: os = (empty) and os.name = Windows 10

![eingefugtes_bild_04_01_18__10_35](https://user-images.githubusercontent.com/2038814/34557577-04f21e2a-f13b-11e7-9dca-8cc57e81679b.png)

This results in weird stats in the event summary:

![image](https://user-images.githubusercontent.com/2038814/34557593-1b9ea594-f13b-11e7-807c-584087d4634f.png)

From that summary I can't really tell the percentage of windows vs mac users affected by the issue.
 
Edit: Issues are reported via JavaScript SDK.

**Comment by MaxBittker** [comment] 2018-01-05 01:06
thanks for the issue @LeEnno 
 
this is caused by the fact that tags don't show up in this breakdown when they're undefined. we could do a better job normalizing these default collected tags in the clients (such as using os.name when os is unknown) but that would be done per client. are you using raven-python?

**Comment by tkaemming** [comment] 2018-01-05 01:09
Related: GH-3862

**Comment by LeEnno** [comment] 2018-01-05 07:49
> are you using raven-python?

No, simply sentry.io with JavaScript SDK reporting errors.

**Comment by zsalzbank** [comment] 2019-01-10 13:23
This just bit me too - I was very confused when I saw that all my users that were having issues were on MS Lumina phones.

I think a decent stopgap solution would be to show the number of events that are affected along with the percentages. Or have the percentages include those with undefined values, since that is what would probably be expected in the first place.

**Comment by BYK** [comment] 2020-10-21 20:05
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Closed by BYK** 2020-10-21 20:05 UTC
