### ISSUE TITLE
Replay Details: Click inside video frame to play/pause replay video

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#46619] opened 2023-03-30 19:08 UTC
## **Problem**

Today, a user has to click a small button underneath the replay video in order to play or pause. This is different behaviour from other video players our customers are used to. This ticket suggests to change behaviour to where clicking inside the video player, plays or pauses a video.

## **Solution**

Click inside video frame to play/pause replay video

**Comment by billyvg** [comment] 2023-03-30 19:59
Note that this may make "right click and inspect DOM" a worse experience as they will be inspecting the play button.

**Comment by ryan953** [comment] 2024-02-07 18:31
duplicate of https://github.com/getsentry/sentry/issues/55493

**Closed by ryan953** 2024-02-07 18:31 UTC
Labels: Product Area: Replays
