### ISSUE TITLE
[User Feedback - Feature Request] Add Replay link (if available) to Ticket Integrations Pre-populated Descriptions (GH, Linear, Jira, etc.)

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#67143] opened 2024-03-18 14:56 UTC
From customer request: 

> There's, there's other content here that's, that's interesting that that like, like the, if the video is available for example 'cause we have the replay set up being able to like automatically set the linked replay a link on the linear ticket, right? So like just anything that smooths out or I don't have to manually like replicate information that we have one-to-one pairings with in the, in the system would be would be pretty helpful.

**Comment by michellewzhang** [comment] 2024-04-15 21:29
duplicate of https://github.com/getsentry/sentry/issues/61768#issue-2042170259

**Closed by michellewzhang** 2024-04-15 21:29 UTC
Labels: enhancement
