### ISSUE TITLE
Design: Layout of Enhance Workflow

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#59341] opened 2023-11-03 10:42 UTC
### Problem:
We don’t know when the trace table should be shown. Ideally, the time to insight should be as quick as possible, but what does that mean when you can generate multiple widgets in a single view?

### What we need to evaluate
How efficient is it to generate insights
How efficient is it to re-generate insights
How efficient to compare insights

**Comment by matejminar** [comment] 2023-11-27 16:01
Duplicate of https://github.com/getsentry/sentry/issues/58700

**Closed by matejminar** 2023-11-27 16:01 UTC
