### ISSUE TITLE
SentryNetworkTracker.m:5:9 'SentryDSN.h' file not found

### ISSUE THREAD

**Issue by wmalloc** [getsentry/sentry#52378] opened 2023-07-06 19:02 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

In a case sensitive Filesystem file is missing because the file is named `SentryDsn.h`. 

### Expected Result

To be able to import the correct file

### Actual Result

Not able to import the header

### Product Area

Releases

**Comment by lobsterkatie** [comment] 2023-07-06 21:57
Closing as a duplicate of https://github.com/getsentry/sentry-cocoa/issues/3115.

**Closed by lobsterkatie** 2023-07-06 21:57 UTC
Labels: Status: Untriaged, Product Area: Releases, Waiting for: Product Owner
