### ISSUE TITLE
Transaction information not displayed when it contains [ or ] in its name

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#60173] opened 2023-11-17 13:34 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Follow the steps on [this guide](https://docs.sentry.io/platforms/python/performance/instrumentation/custom-instrumentation/) to send eat pizza transactions and send a few transactions
2. Rename it [eat] pizza
3. send a few more transactions
4. View the information on each transaction in the Sentry UI

### Expected Result

Relevant information is displayed for both transactions.

### Actual Result

Sentry fails to display information for [eat] pizza. 
Links: 
- [[eat] pizza](https://dev-curumas.sentry.io/performance/summary/?project=5225844&query=&referrer=performance-transaction-summary&statsPeriod=7d&transaction=%5BEat%5D+Pizza&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29)
- [eat pizza](https://dev-curumas.sentry.io/performance/summary/?project=5225844&query=&referrer=performance-transaction-summary&statsPeriod=7d&transaction=Eat+Pizza&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29)

Screenshots:
![Screenshot 2023-11-17 at 14 32 21](https://github.com/getsentry/sentry/assets/64906376/4119cef1-f449-42b6-abff-73df00b44654)
![Screenshot 2023-11-17 at 14 32 12](https://github.com/getsentry/sentry/assets/64906376/a1b438c3-8d69-4185-98bd-35aededccaf9)

### Product Area

Performance

**Comment by k-fish** [comment] 2023-11-20 18:44
@rodolfoBee hey o/, we're looking into this, we think we know where the problem lies it was because of another edge case though so it'll take us a bit to resolve.

**Comment by narsaynorath** [comment] 2023-11-21 18:22
Hey @rodolfoBee, just a heads up I've reverted the PR that introduced this regression since we were trying to fix a smaller edge case. Thanks for the bug report because this will be useful to validate in the next attempt.

I'm going to close the issue now but if it doesn't seem resolved, please feel free to re-open this.

**Closed by narsaynorath** 2023-11-21 18:22 UTC
Labels: Product Area: Performance
