### ISSUE TITLE
The Alert Conditions of an alert do not reflect the alert configuration

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#46515] opened 2023-03-29 15:59 UTC
### Environment

SaaS (https://sentry.io/)

### Link

https://org2-w7.sentry.io/alerts/rules/react/14022143/details/

### Steps to Reproduce

Create an alert with the below condition:

![image](https://user-images.githubusercontent.com/99350819/228015668-72b21588-c685-43e2-b78e-2a66341c3119.png)

"Number of users affected by an issue is more than 10 in one hour"

### Expected Result

The Alert Condition on the alert page shows the correct condition:

"Number of users affected by an issue is more than 10 in one hour"

### Actual Result

The Alert Condition on the alert page shows the incorrect condition: "Number of events in an issue is more than 10 in 1h"

![image](https://user-images.githubusercontent.com/99350819/228015806-dfc91781-25ad-4c4b-8810-fc195829dce2.png)
![image](https://user-images.githubusercontent.com/99350819/228015900-7214e670-33ef-4745-8c2c-426a0d016a65.png)

**Comment by ceorourke** [comment] 2024-12-12 21:14
Closing as I can't reproduce, feel free to reopen if it's still occurring.

**Closed by ceorourke** 2024-12-12 21:14 UTC
