### ISSUE TITLE
Duplicated weekly reports sent on 20/06

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#74619] opened 2024-07-22 05:49 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

No specific steps to reproduce, emails are sent by Sentry.

### Expected Result

Users to receive one weekly report email for each Sentry organisation. 

### Actual Result

Users are getting two copies of the same weekly report email:

![Image](https://github.com/user-attachments/assets/7647211c-bb66-4942-bb7c-81363ba5ede7)

### Product Area

Settings - General

**Comment by MSchmidt** [comment] 2024-07-22 08:36
The reports/email are not exactly the same though. Numbers differ slightly. Might be good to know to track the issue down. My emails are 3 hours apart and the values of the 2nd email are greater.

**Comment by mrduncan** [comment] 2024-07-22 15:35
This seems to be a duplicate of #71855 - please reopen if not.

**Closed by mrduncan** 2024-07-22 15:35 UTC
Labels: Product Area: Settings - General, Waiting for: Product Owner
