### ISSUE TITLE
Sentry Alerts do not always create new JIRA issues

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#46241] opened 2023-03-23 10:32 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Install the JIRA cloud integration in Sentry SaaS
2. Create a new alert, configure the Issue Link Settings, and click on "Send Test Notification"

### Expected Result

A new JIRA test issue is created every time

### Actual Result

Test issues are not being created consistently.

Things that have been checked:
- The correct Project has been selected
- Manually creating a JIRA issue from the Issue Details page works fine
- When clicking on "Send Test Notification", there are no errors in the network tab
- Tried re-installing the integration in Sentry
- Using the Sentry app on version 1.1.2753-AC on JIRA's side
- There are no automations that could be influencing this
- Further testing was done by the customer on new JIRA projects and a separate JIRA instance

[Ticket on Zendesk](https://sentry.zendesk.com/agent/tickets/81655)

**Comment by huelsmc** [comment] 2023-05-17 18:57
We have the exact same behavior with Sentry and Jira Cloud.
For some projects it works but for some Sentry reports the ticket has been created but nothing to find in Jira.

**Comment by dneighbors** [comment] 2024-02-01 04:48
We have been experiencing this since at least Sept 7th, 2023 and have been watching this and waiting.

**Comment by theboz86** [comment] 2024-02-01 16:16
My team is also having the same issue, about 70% of our Sentry Alerts create a ticket in Jira. I reached out to support 6 months ago and am yet to hear back. This is spread throughout my company.

**Comment by malwilley** [comment] 2024-02-05 18:02
@theboz86 thanks for chiming in - I'm trying to reproduce this but have been unable to. Could you clarify a couple things to help with debugging this issue?

- Are you saying that 70% is the success rate of your alerts making jira tickets?
- If you could provide a link to an alert that is failing to create Jira that would be helpful in tracking this down

**Comment by MrLuna12** [comment] 2024-05-10 20:34
My team has been experiencing this issue for the past 8 months.

**Comment by dneighbors** [comment] 2024-05-10 20:40
@malwilley here is an example of a rule that exists and is live and creates JIRA tickets 70% of the time.  Included are two issues that fired within last 24hrs that did NOT create JIRA tickets from the rule.

[alert rule id:15093502](https://strongmind-4j.sentry.io/alerts/rules/course-builder/15093502/details/)
[issue id:5328199593 in last 24hr no JIRA ticket creation]( https://strongmind-4j.sentry.io/issues/5328199593/)
[issue id:5327281704 in last 24hr no JIRA ticket creation: ](https://strongmind-4j.sentry.io/issues/5327281704/)

**Comment by sentaur-athena** [comment] 2024-05-14 19:04
Thank you for reporting and providing examples. I started investigating and will provide update when I have one.

**Comment by sentaur-athena** [comment] 2024-05-15 17:01
@MrLuna12 (and everyone else experiencing this) there could be different reasons for a jira ticket not getting created depending on how the rule is setup. Would be great if you can provide me with the rule that is failing to create issues.

Meanwhile I work off the one example @dneighbors provided.

**Comment by sentaur-athena** [comment] 2024-05-15 18:28
@dneighbors what I can see in the logs is that your ticket creation fails on the Jira side with error: `{'customfield_10102': ["Team id 'JsonData{data={id=S*****}}' is not valid."]} `. Added stars to the name for privacy but is that possible that this is not a valid team in your Jira settings?

**Comment by dneighbors** [comment] 2024-05-15 22:48
@sentaur-athena will investigate here, is there anywhere in the interface or a log in sentry that is being exposed that we would be able to see?

**Comment by dneighbors** [comment] 2024-05-15 23:01
> @sentaur-athena When I look at that configuration of the rule it isn't passing a team. Where is it pulling team from in Sentry? Additionally, it is out that 70% of the time the rule works. Is there a way in sentry to view this error?

Okay we found in automation on the Jira side a team was being set incorrectly.  Im still curious why intermittent and would love to know if way to see logs on these things if we have additional issues, but this may resolve for us.

**Comment by sentaur-athena** [comment] 2024-05-15 23:20
> @sentaur-athena When I look at that configuration of the rule it isn't passing a team. 

That's something to be fixed on our side. It doesn't show any teams because there are no valid teams. Instead if we show you an error it would be more useful. I created an internal ticket for improving this experience.

>  Im still curious why intermittent

That I didn't figure out either. Please message again if this fix doesn't lead to 100% creation. This one the only failure I saw in the logs today.

> would love to know if way to see logs on these things

Not right now. But that's also a clear next step for us so I added it to our upcoming improvements.

**Comment by tpaulshippy** [comment] 2024-06-11 18:20
@sentaur-athena This is still not working for us. Is there any way for you to check the logs for us again?

**Comment by sparklepop** [comment] 2024-07-03 00:27
@sentaur-athena @malwilley We are still experiencing this issue. Is there any way to share the error in your logs with us to enable further troubleshooting? 
As tests we have tried 
1) disabling on create automations on the Jira side
2) Passing the Jira team GUID in the Sentry alert Team field
3) Removing any content in the Sentry alert Team field
4) Adding Team and customfield_10102 to the hide data in the Sentry Jira integration "Ignored Fields"

**Comment by leedongwei** [comment] 2024-07-04 00:07
Hi folks, are y'all from the same org? Can you share your Project DSN so we can identify the affected organization + project? Thanks

**Comment by tpaulshippy** [comment] 2024-07-04 00:42
Yes we are all from the same org.
Here is the DSN: https://41911b9a139d4652bf09f7f77e9b013b@o1169445.ingest.us.sentry.io/4505229541441536

**Comment by markng** [comment] 2024-07-15 20:03
The labels here seem to indicate that this has been deprioritised within your organisation. Will you let me know if that's the case? This is causing significant issues for us and our workflow, and is a feature that is supposed to work.

We are a paying customer, and this is beginning to create a sentiment to move to an alternate product. I understand that we're saying that JIRA is returning errors for you, but if so, we need to be able to understand what they are (and why they are inconsistent) so we can raise relevant support cases with Atlassian if that is the case.

**Comment by markng** [comment] 2024-07-15 20:14
Additionally, to other things we have mentioned here that we have tried is that we have stood up a local copy of the open source version of your product, and have been unable to replicate the issue.

**Comment by leedongwei** [comment] 2024-07-17 20:20
Hi, we've scheduled engineering time to address this. Don't read too much into the labels changing, I'm just trying to stop the internal bot from pinging me non-stop about it.

**Comment by markng** [comment] 2024-07-17 20:26
Thanks for the update. Honestly, even having your integrations for our org reporting into a sentry project ( I assume there are exceptions being raised here ) would be perfectly good for our needs.

**Comment by markng** [comment] 2024-07-17 20:28
and do you have any estimates in time? I believe we might even be prepared to devote some of our own developer time toward this, because the next steps are either we write something to crawl your API, or we start moving to something else, both of which are sub-optimal for us, and would likely cost us more time than helping out. (I assume the open source version of sentry is close enough to your hosted version?)

**Comment by leedongwei** [comment] 2024-07-18 21:54
I have an engineer scheduled to investigate + fix Jira bugs next week. This is the 2nd item on their priority list. IMO end of the month seems reasonable.

On the integration reporting errors into a Sentry project, we have floated similar ideas like an audit log of requests/responses between Sentry and your integration, but haven't fully fleshed it out yet.

**Comment by markng** [comment] 2024-07-19 20:39
> I have an engineer scheduled to investigate + fix Jira bugs starting next week. This is the 2nd item on their priority list. IMO end of the month seems reasonable.

Thanks. Again, we're invested in getting this fixed (I've failed a couple sprints now!) so if we can either help you test this or contribute to getting it done, please let me know.

**Comment by markng** [comment] 2024-07-26 21:19
Checking in to see if we're still in a good spot in terms of schedules, and whether we can be doing anything to help with the process.

**Comment by GabeVillalobos** [comment] 2024-07-31 16:32
@markng I started triaging the problem this week and am able to reproduce it. It's likely this gets fixed sometime later this week or early next week, but I'll provide better estimates on this when I have more information.

**Comment by markng** [comment] 2024-08-02 16:31
> [@markng](https://github.com/markng) I started triaging the problem this week and am able to reproduce it. It's likely this gets fixed sometime later this week or early next week, but I'll provide better estimates on this when I have more information.

fantastic! I appreciate the update.

**Comment by tpaulshippy** [comment] 2024-08-09 22:46
> [@markng](https://github.com/markng) I started triaging the problem this week and am able to reproduce it. It's likely this gets fixed sometime later this week or early next week, but I'll provide better estimates on this when I have more information.

Hi @GabeVillalobos - thanks for your work on this. Do you have any better estimates on this effort at this point?

**Comment by GabeVillalobos** [comment] 2024-08-12 21:34
Sorry for the delay. So I've been looking into the following problems:

1. We don't seem to propagate API level errors to the UI when issuing test alerts. This makes it difficult to diagnose when and why an alert isn't firing. [Fix in Progress]
2. Because many of the issue fields we in our alert configuration are dynamically provided by Jira, adding validation for them can be difficult. Unfortunately, this makes it very easy to set up invalid alert rules.

I'm hoping to have a patch ready for the 1st problem by end of week, although I can't make any guarantees on the granularity of the error messages we can propagate as these issue creation requests can fail for a variety of reasons, some of which may include sensitive information. As for the 2nd problem, I'll be looking into what it takes to add stricter validation to some of these fields (such as `Team` for example).

**Comment by GabeVillalobos** [comment] 2024-09-11 18:20
It's taken me quite a bit of time to fully get up to speed on our Jira integration so I appreciate your patience and apologize for the delays. Here are some updates on this:

1. We decided to refactor a decent portion of our Jira integration. Quite a few of the available custom fields users can configure have been broken for a while which contributes to these alerting failures.
2. We've added a data model to add more type safety to our integration code with the intention of making maintenance easier in the future.
3. We are currently testing our test alert error propagation changes from PR #76369 and will release these when we have more confidence that they provide helpful feedback.

We're hoping these changes fix the vast majority of your issues, or at the very least, provide some feedback as to why your alerts are not working correctly.

**Comment by njsaunders** [comment] 2024-09-20 09:41
Hi - 

Just been made aware of this issue via a support ticket (132950).

In our case:

Rule: https://coty-li.sentry.io/alerts/rules/yotpo-connector/27344/details/
Ticket without issue: https://coty-li.sentry.io/issues/7633517/?project=4507458680127568&referrer=project-issue-stream

Thanks,

Neil

**Comment by markng** [comment] 2024-10-07 18:59
Any news on this? Any way we can help move it forward?

**Comment by sentaur-athena** [comment] 2024-10-08 00:28
Yes, the work is in progress and some part of the fix will be deployed tomorrow. We will keep you posted.

**Comment by GabeVillalobos** [comment] 2024-10-08 23:23
Last week, we launched our refactor of our field parsing logic for Jira, which fixed a number of bugs related to Jira issue creation.

We released our notification test error display changes today from PRs #76369 and #78653 for Early Adopters (which you can opt into via the organization settings page if you haven't already), with plans to fully launch this feature by the end of the week.

Once you have access to this feature, you should be able to test your alert notifications for each of your misbehaving Jira alert rules to see if your rule is misconfigured in any way.

**Comment by sentaur-athena** [comment] 2024-10-10 21:58
Closing since this is now fully launched to everyone. Basically if there's a failure on Jira side it will now be more visible to the alert creator. If you still have an issue after this that you can't figure out, feel free to open specific tickets about the issue or file support tickets.

**Closed by sentaur-athena** 2024-10-10 21:58 UTC
Labels: Type: Bug, Product Area: Settings - Integrations
