### ISSUE TITLE
Resolved in major version (vs next release)

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#9818] opened 2018-09-19 19:44 UTC
Here's the relevant user story:

I version my apps using something like 8.19.12345. The last component is a build number, and whenever we release a new version to public (production) we bump the major component (so 8.20). That said we have many minor versions and we want to be able to use "Resolved in release" functionality during the development cycle. This would let us suggest it's fixed in 8.20, but not in 8.19.45678.

I want to be able to resolve an issue in an upcoming release, but not the guaranteed next release.

Some options which might help the situation:

- Resolved in the next [environment] release
- Resolved in the next [major|minor] version

**Comment by dcramer** [comment] 2018-09-19 21:28
One other note, there's 4 major versioning schemes we should consider in play:

1. sha-based (what Sentry does today)
2. semver
3. timestmap-based
4. sequential (e.g. deploy/build number)

- What we (Sentry) do is the least useful one for a human to consume.
- There are other non-semver schemes, but they're not major enough, or important enough, that we really need to focus on it. We could also support "Resolved in 8.20.*".

**Comment by lukasgraf** [comment] 2018-09-20 09:37
This would also help dealing with #9711 (*Regression logic going by release date_added instead of date_released*), which only really becomes an issue when doing backport releases (or otherwise creating releases out-of-order).

I've been reluctant to link up our git repository and have Sentry work with commit information exactly because with SHA hashes you lose human readability.

A first helpful step would be if the documentation was very precise about how Sentry is doing its version ordering. There's two main places that come to mind where the exact semantics of release version ordering come into play:

- Resolve in **next** [...] release
- Regressions (testing if `actual event version >= supposed resolution version`)

The [docs on releases](https://docs.sentry.io/learn/cli/releases/?platform=python) don't talk about version ordering in any detail, or if and how it relates to finalizing releases and creating deploys.

Using a user controlled timestamp (via REST API or `sentry-cli`) for release version ordering would also help to work around those kinks (`date_added` currently seems to be read-only). This option might be less complex to implement than `resolved in next [major|minor]` or full semver support.

**Comment by dcramer** [comment] 2018-09-20 19:52
A couple other notes here:

1. We can detect if a project is using sequential versions (e.g. ``version.split('.')[0].isdigit()``) and if so its very easy to say "the next release MUST be > [using version_compare] than the current release".

2. We can aggregate releases by major version numbers if we detect a semver-style scheme. This is a little tricky yet, and might require some indexing, since we'd want to show "heres all issues that were new in 8.19.*"

**Comment by dcramer** [comment] 2018-09-20 23:51
@mattrobenolt oh yeah because right now we mostly use hashes, so we don't have conflicts -- fair point. We could suggest [project]-[version] and base on that.

**Comment by BYK** [comment] 2020-10-22 19:16
I think we have this now so closing.

**Comment by leeandher** [comment] 2024-12-11 15:22
Closing, as this feature has been built out in https://github.com/getsentry/sentry/pull/80655 to allow for resolving in next semantic version!

**Closed by leeandher** 2024-12-11 15:22 UTC
Labels: Component: Workflow
