### ISSUE TITLE
Absolute time selector not working with default query

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#69386] opened 2024-04-22 09:09 UTC
save a default query with stats period of 14d, then try to open a link with aboslute date/time like [this](https://sentry.sentry.io/metrics/?end=2024-04-16T01%3A45%3A22&interval=15m&project=1&start=2024-04-16T00%3A31%3A33&utc=true)

**Comment by obostjancic** [comment] 2024-04-24 10:24
This happens because the link that is being opened contains no widgets. 
Seems to be [expected behavior](https://github.com/getsentry/sentry/blob/57cb0dde0b2592b2545e24e2fef18ae266d117c1/static/app/views/metrics/context.tsx#L192)
Closing

**Closed by obostjancic** 2024-04-24 10:24 UTC
