### ISSUE TITLE
Crons: Add support for timezone for crontab

### ISSUE THREAD

**Issue by azban** [getsentry/sentry#43518] opened 2023-01-20 22:25 UTC
### Problem Statement

**Crontab is UTC Only?**:
I couldn't find documentation for the crontab setting around which timezone this runs in by default, so I'm not sure how to make that out, but I'm assuming it is in UTC.

**Issue with UTC timezone**:
We currently have tasks that we run on a fixed hour of the day in standard and DST, and if the current implementation is in UTC, then we'll have failures, or need to move all of our monitors over at the right time when DST shifts happen.

### Solution Brainstorm

**Documentation**
If I'm not just missing something, it would probably be good to highlight the default/only TZ is UTC in the UX, and/or in the docs.

**UTC issue**
It would be useful to be able to set a timezone explicitly along with your interval

**Comment by gaprl** [comment] 2023-01-21 00:23
Hey @azban, thanks for your feedback -- and yes, Crons uses UTC at the moment. We hope to add timezone support in the near future, and I'll circle back when I have additional updates.

**Comment by azban** [comment] 2023-01-21 06:01
Awesome.. thank you

**Comment by evanpurkhiser** [comment] 2023-01-24 20:53
@gaprl should we go ahead and merge this with https://github.com/getsentry/sentry/issues/43625?

**Comment by gaprl** [comment] 2023-01-24 22:52
Duplicate of https://github.com/getsentry/sentry/issues/43625

**Closed** 2023-01-24 22:53 UTC
Labels: Status: Backlog, Team: Crons
