### ISSUE TITLE
Apply tags to events from within UI

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2265] opened 2015-11-03 21:30 UTC
> We would fine it very useful if we could apply "tags" from Sentry itself. For instance, we have about 6 different errors all falling under the same topic -- cache. It'd be nice if we could throw a "label" or a "tag" on these so we can visually see "okay, these 3 over there are the cache issues".

Re: https://sentry.zendesk.com/agent/tickets/939

**Comment by ajwhite** [comment] 2015-11-03 21:56
+1

**Comment by vanessa** [comment] 2020-01-22 15:29
That would be awesome to have! My project is having the same issue, we have different features that are more critical than others and we'd like to be able to filter them easily, that could be done if we had tags. 

Thanks for the great product btw

**Comment by BYK** [comment] 2020-10-26 10:51
Duplicate of #5572 (yes #5572 came later but it has a lot more context and discussion in it so closing this one in favor of that).

**Closed by BYK** 2020-10-26 10:51 UTC
Labels: On hold, Type: User Feedback
