### ISSUE TITLE
StrictClick breaking subitem-clicks

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#3519] opened 2016-06-17 22:41 UTC
I'm unable to click on the anchor tag in the new stacktrace headers.

**Comment by dcramer** [comment] 2016-06-17 22:41
![screenshot 2016-06-17 15 41 20](https://cloud.githubusercontent.com/assets/23610/16166660/023348fa-34a2-11e6-971d-a74c26523a7e.png)

**Comment by benvinegar** [comment] 2016-08-09 18:01
Dupe of #3620

**Closed by benvinegar** 2016-08-09 18:01 UTC
