### ISSUE TITLE
Feature Request: Telegram integration

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#56066] opened 2023-09-12 08:01 UTC
### Problem Statement

Our customer wants to have a Sentry-supported Telegram integration since they don't use Slack

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment] 2023-09-12 15:20
We'll add this to our backlog but we don't have any near term plans to do this

**Comment by Dhrumil-Sentry** [comment] 2024-02-18 00:20
Marking this as a duplicate of https://github.com/getsentry/sentry/issues/61998

**Closed by Dhrumil-Sentry** 2024-02-18 00:20 UTC
Labels: Product Area: Settings - Integrations
