### ISSUE TITLE
Link a Sentry Issue to an Alert Rule

### ISSUE THREAD

**Issue by SpotifyPhilipD** [getsentry/sentry#65074] opened 2024-02-13 15:12 UTC
### Problem Statement

We've got a Sentry Issue that caused an alert in PagerDuty, but the wrong team was alerted. We are trying to debug why the alert went to the wrong team, but we can't seem to see anything wrong with the alert rules that we've set up. It would be helpful if the Sentry Issue could provide a link to the Alert Rule that caused it. That would make this much easier to debug.

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2100) by [Unito](https://www.unito.io)

**Comment by roggenkemper** [comment] 2024-02-13 22:57
I'm not entirely sure I understand what "the Sentry issue could provide a link to the alert rule that caused it" means. Is that a request that issues in Sentry show the alerts it has been a part of?

**Comment by SpotifyPhilipD** [comment] 2024-02-15 14:41
Yes, that's correct. An alert triggered and it isn't obvious which alert rule triggered it. If possible, we'd like to be able to easily map the issue to the alert.

**Comment by roggenkemper** [comment] 2024-02-16 19:03
got it, that makes sense. i'll add this to our backlog so the team can look at it.

**Comment by ceorourke** [comment] 2024-12-12 22:06
@SpotifyPhilipD the notification itself links to the alert that fired, and the alert rule details page lists the issues that made it trigger. Was your notification missing the link to the alert?

**Comment by ceorourke** [comment] 2024-12-12 22:15
I found a duplicate of this request https://github.com/getsentry/sentry/issues/60971 so I'm going to close this one (unless I made a mistake and your request was different!)

**Closed by ceorourke** 2024-12-12 22:15 UTC
Labels: Sync: Jira, Product Area: Issues
