### ISSUE TITLE
[9.1.0] Cannot create projets anymore if the team is changed

### ISSUE THREAD

**Issue by the-glu** [getsentry/sentry#12749] opened 2019-04-12 07:36 UTC
## Important Details

How are you running Sentry?

* [X] On-Premise (Pip) [Version 9.10.0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I cannot create project anymore if I select a different team. If I leave the default one, it's working.

## Steps to Reproduce

1. Goes to /organizations/XXX/projects/new/
2. Enter information. Change the team.
3. Click on 'Create a project'

An error message is returned:

> The requested resource does not exist

The HTTP query done is a post on

/api/0/teams/XXX/[object Object]/projects/

It's working if the project is not changed, so there is probably something wrong during team selection ?

**Comment by msva** [comment] 2019-04-12 12:35
I can confirm the issue!
I've killed a bit less than week because of that issue (I thought, we doing something wrong, if it is only us who suffer of this, and it is no more reports)

**Comment by TimShilov** [comment] 2019-04-12 12:45
+1

**Comment by NullYing** [comment] 2019-04-17 15:36
confirm the issue!

**Comment by acdha** [comment] 2019-04-18 14:54
It looks like this was fixed in https://github.com/getsentry/sentry/pull/12631. In the meantime, I used the Firefox debugger: copy the failing request as Curl, change the URL to replace `[Object object]` with the slug of the team in question, and run it.

**Comment by dcramer** [comment] 2019-04-19 16:51
We're pulling in the related fix into the 9.1.1 release which should go out later today.

**Closed by dcramer** 2019-04-19 16:51 UTC
Labels: Type: Bug
