### ISSUE TITLE
Thread starting during runtime shutdown

### ISSUE THREAD

**Issue by scuzoutao** [getsentry/sentry#13927] opened 2019-07-09 02:32 UTC
java.lang.Thread in nativeCreate
java.lang.Thread in start at line 1063
java.util.concurrent.ThreadPoolExecutor in addWorker at line 921
java.util.concurrent.ThreadPoolExecutor in execute at line 1328
io.sentry.connection.AsyncConnection in send at line 96
io.sentry.connection.BufferedConnection$2 in send at line 193
io.sentry.SentryClient in sendEvent at line 135
io.sentry.SentryClient in sendEvent at line 176
io.sentry.SentryClient in sendException at line 203
io.sentry.Sentry in capture at line 156
com.mycompany.project.handler.AppCrashHandler$1 in onAppNotResponding at line 68
com.github.anrwatchdog.ANRWatchDog in run at line 212

crash when report sentry

**Comment by bruno-garcia** [comment] 2019-07-09 10:15
This is a duplicate of https://github.com/getsentry/sentry-java/issues/731

**Closed by bruno-garcia** 2019-07-09 10:15 UTC
