### ISSUE TITLE
Detail data of issue cannot load (loading GIF never disappears + JS errors)

### ISSUE THREAD

**Issue by josemariaruiz** [getsentry/sentry#4061] opened 2016-09-01 08:02 UTC
Hi, I upgraded to sentry 8.7.0 and now when I try to load the detailed data of a specific issue I get this two errors in the debugging window in Chrome:

`raven.js:262 Uncaught TypeError: Cannot read property '0' of undefined         ... raven.js 262`

and

`Uncaught TypeError: Cannot read property '_idCounter' of null ... ReactDOMComponent.js:415`

I've never seen these errors before and are turning my sentry useless as I cannot access the information about the issue.

**Comment by josemariaruiz** [comment] 2016-09-01 09:23
I've downgraded to sentry 8.6.0 and the problem disappears.

**Comment by dcramer** [comment] 2016-09-01 16:09
Any chance you have the full stack trace? It likely also was captured in the sentry internal project.

**Comment by josemariaruiz** [comment] 2016-09-01 22:16
One of the errors:

`TypeError: Cannot read property '_idCounter' of null
  at defineProperty(~/react/lib/ReactDOMTextarea.js:101:0)
  at Object.mountComponent(~/reflux/~/reflux-core/lib/utils.js:44:0)
  at SyntheticFocusEvent(~/react/lib/SyntheticKeyboardEvent.js:42:0)
  at clipboardData(~/react/lib/SyntheticFocusEvent.js:31:0)
  at h.updateChildren(~/react/lib/SyntheticClipboardEvent.js:23:0)
  at this(~/react/lib/ReactReconcileTransaction.js:13:0)
  at _reconcilerInstantiateChildren(~/react/lib/ReactMultiChild.js:298:0)
  at isFunction(~/react/lib/ReactMultiChild.js:232:0)
  at createElement(~/reflux/~/reflux-core/lib/utils.js:10:0)
  at Object.updateChildren(~/react/lib/ReactDOMComponent.js:470:0)
  at nativeEventTarget(~/react/lib/SimpleEventPlugin.js:540:0)
  at clipboardData(~/react/lib/SyntheticCompositionEvent.js:31:0)
  at h.updateChildren(~/react/lib/SyntheticClipboardEvent.js:23:0)
  at this(~/react/lib/ReactReconcileTransaction.js:13:0)
  at _reconcilerInstantiateChildren(~/react/lib/ReactMultiChild.js:298:0)
  at isFunction(~/react/lib/ReactMultiChild.js:232:0)
  at section(~/reflux/~/reflux-core/lib/utils.js:10:0)
  at _updateRenderedComponent(~/react/lib/ReactDOMFactories.js:127:0)
  at _performComponentUpdate(~/react/lib/ReactDOMFactories.js:108:0)
  at _nodeWithLegacyProperties(~/react/lib/ReactDOMFactories.js:51:0)
  at isFunction(~/react/lib/ReactDOMComponent.js:917:0)
  at createElement(~/reflux/~/reflux-core/lib/utils.js:10:0)
  at Object.updateChildren(~/react/lib/ReactDOMComponent.js:470:0)
  at nativeEventTarget(~/react/lib/SimpleEventPlugin.js:540:0)
  at clipboardData(~/react/lib/SyntheticCompositionEvent.js:31:0)
  at h.updateChildren(~/react/lib/SyntheticClipboardEvent.js:23:0)
  at this(~/react/lib/ReactReconcileTransaction.js:13:0)
  at _reconcilerInstantiateChildren(~/react/lib/ReactMultiChild.js:298:0)
  at isFunction(~/react/lib/ReactMultiChild.js:232:0)
  at createElement(~/reflux/~/reflux-core/lib/utils.js:10:0)
  at Object.updateChildren(~/react/lib/ReactDOMComponent.js:470:0)
  at nativeEventTarget(~/react/lib/SimpleEventPlugin.js:540:0)
  at clipboardData(~/react/lib/SyntheticCompositionEvent.js:31:0)
  at h.updateChildren(~/react/lib/SyntheticClipboardEvent.js:23:0)
  at this(~/react/lib/ReactReconcileTransaction.js:13:0)
  at _reconcilerInstantiateChildren(~/react/lib/ReactMultiChild.js:298:0)
  at isFunction(~/react/lib/ReactMultiChild.js:232:0)
  at createElement(~/reflux/~/reflux-core/lib/utils.js:10:0)
  at Object.updateChildren(~/react/lib/ReactDOMComponent.js:470:0)
  at nativeEventTarget(~/react/lib/SimpleEventPlugin.js:540:0)
  at clipboardData(~/react/lib/SyntheticCompositionEvent.js:31:0)
  at h.updateChildren(~/react/lib/SyntheticClipboardEvent.js:23:0)
  at this(~/react/lib/ReactReconcileTransaction.js:13:0)
  at _reconcilerInstantiateChildren(~/react/lib/ReactMultiChild.js:298:0)
  at isFunction(~/react/lib/ReactMultiChild.js:232:0)
  at section(~/reflux/~/reflux-core/lib/utils.js:10:0)
  at _updateRenderedComponent(~/react/lib/ReactDOMFactories.js:127:0)
  at _performComponentUpdate(~/react/lib/ReactDOMFactories.js:108:0)
  at getDOMNode(~/react/lib/ReactDOMFactories.js:51:0)
  at getDOMNode(~/react/lib/ReactDOMComponent.js:928:0)
`
and the other one:

`TypeError: Cannot read property '0' of undefined
  at className(./app/views/projectCspSettings.jsx:267:12)
  at getDefaultProps(./app/views/projectCspSettings.jsx:249:15)
  at properties(~/react/lib/ReactClass.js:347:0)
  at this(~/react/lib/ReactDOMComponent.js:754:7)
  at defineProperty(~/react/lib/ReactDOMComponent.js:668:0)
  at undefined(~/reflux/~/reflux-core/lib/utils.js:44:0)
  at instantiateChildren(~/react/lib/SimpleEventPlugin.js:559:0)
  at nativeEvent(~/react/lib/ReactMultiChild.js:203:0)
  at defineProperty(~/react/lib/ReactEventListener.js:195:0)
  at styleName(~/reflux/~/reflux-core/lib/utils.js:44:0)
  at this(~/react/lib/ReactDOMComponent.js:779:0)
  at defineProperty(~/react/lib/ReactDOMComponent.js:668:0)
  at undefined(~/reflux/~/reflux-core/lib/utils.js:44:0)
  at instantiateChildren(~/react/lib/SimpleEventPlugin.js:559:0)
  at nativeEvent(~/react/lib/ReactMultiChild.js:203:0)
  at defineProperty(~/react/lib/ReactEventListener.js:195:0)
  at undefined(~/reflux/~/reflux-core/lib/utils.js:44:0)
  at instantiateChildren(~/react/lib/SimpleEventPlugin.js:559:0)
  at nativeEvent(~/react/lib/ReactMultiChild.js:203:0)
  at defineProperty(~/react/lib/ReactEventListener.js:195:0)
  at undefined(~/reflux/~/reflux-core/lib/utils.js:44:0)
  at instantiateChildren(~/react/lib/SimpleEventPlugin.js:559:0)
  at nativeEvent(~/react/lib/ReactMultiChild.js:203:0)
  at defineProperty(~/react/lib/ReactEventListener.js:195:0)
  at styleName(~/reflux/~/reflux-core/lib/utils.js:44:0)
  at this(~/react/lib/ReactDOMComponent.js:779:0)
  at defineProperty(~/react/lib/ReactDOMComponent.js:668:0)
  at undefined(~/reflux/~/reflux-core/lib/utils.js:44:0)
  at instantiateChildren(~/react/lib/SimpleEventPlugin.js:559:0)
  at nativeEvent(~/react/lib/ReactMultiChild.js:203:0)
  at defineProperty(~/react/lib/ReactEventListener.js:195:0)
  at styleName(~/reflux/~/reflux-core/lib/utils.js:44:0)
  at this(~/react/lib/ReactDOMComponent.js:779:0)
  at defineProperty(~/react/lib/ReactDOMComponent.js:668:0)
  at time(~/reflux/~/reflux-core/lib/utils.js:44:0)
  at _updateRenderedComponent(~/react/lib/ReactDOMFactories.js:144:0)
  at _performComponentUpdate(~/react/lib/ReactDOMFactories.js:108:0)
  at getDOMNode(~/react/lib/ReactDOMFactories.js:51:0)
  at $(~/react/lib/ReactDOMComponent.js:928:0)
  at __WEBPACK_AMD_DEFINE_RESULT__(~/babel-core/~/core-js/modules/$.hide.js:4:0)
  at substring(~/classnames/index.js:1:0)
  at substring(~/marked/lib/marked.js:684:0)
  at __WEBPACK_AMD_DEFINE_RESULT__(~/marked/lib/marked.js:684:0)
  at __WEBPACK_AMD_DEFINE_RESULT__(~/classnames/index.js:1:0)
  at replace(~/classnames/index.js:1:0)
  at Error(~/marked/lib/marked.js:731:0)
  at phasedRegistrationNames(~/marked/lib/marked.js:691:0)
  at __WEBPACK_AMD_DEFINE_RESULT__(~/react/lib/SimpleEventPlugin.js:273:0)
  at getMethod(~/classnames/index.js:1:0)
  at getMethod(~/babel-core/~/core-js/modules/$.iter-define.js:58:0)`

**Comment by tghw** [comment] 2016-09-21 16:18
I'm seeing the same on 8.8.0. Everything is so heavily wrapped, it's hard to figure out where the issue is coming from.

**Comment by mattrobenolt** [comment] 2016-09-21 16:21
@tghw Is your stacktrace the same?

**Comment by tghw** [comment] 2016-09-21 16:23
Tracking it down now. Normally I'd use Sentry to get it (in the console, it just shows up as `r @ raven.js:290`), but the bug is preventing that. Let me grab it from the database.

**Comment by mattrobenolt** [comment] 2016-09-21 16:23
The full stack trace in the console would be useful. :)

**Comment by tghw** [comment] 2016-09-21 16:44
Here is the `_idCounter` error:

    ReactDOMComponent.js:415 Uncaught TypeError: Cannot read property '_idCounter' of null
        mountComponent	@	ReactDOMComponent.js:415
        mountComponent	@	ReactReconciler.js:49
        _mountChildAtIndex	@	ReactMultiChild.js:427
        _updateChildren	@	ReactMultiChild.js:343
        updateChildren	@	ReactMultiChild.js:303
        _updateDOMChildren	@	ReactDOMComponent.js:938
        updateComponent	@	ReactDOMComponent.js:767
        receiveComponent	@	ReactDOMComponent.js:723
        receiveComponent	@	ReactReconciler.js:131
        updateChildren	@	ReactChildReconciler.js:94
        _reconcilerUpdateChildren	@	ReactMultiChild.js:218
        _updateChildren	@	ReactMultiChild.js:315
        updateChildren	@	ReactMultiChild.js:303
        _updateDOMChildren	@	ReactDOMComponent.js:938
        updateComponent	@	ReactDOMComponent.js:767
        receiveComponent	@	ReactDOMComponent.js:723
        receiveComponent	@	ReactReconciler.js:131
        _updateRenderedComponent	@	ReactCompositeComponent.js:737
        _performComponentUpdate	@	ReactCompositeComponent.js:715
        updateComponent	@	ReactCompositeComponent.js:634
        receiveComponent	@	ReactCompositeComponent.js:534
        receiveComponent	@	ReactReconciler.js:131
        updateChildren	@	ReactChildReconciler.js:94
        _reconcilerUpdateChildren	@	ReactMultiChild.js:218
        _updateChildren	@	ReactMultiChild.js:315
        updateChildren	@	ReactMultiChild.js:303
        _updateDOMChildren	@	ReactDOMComponent.js:938
        updateComponent	@	ReactDOMComponent.js:767
        receiveComponent	@	ReactDOMComponent.js:723
        receiveComponent	@	ReactReconciler.js:131
        updateChildren	@	ReactChildReconciler.js:94
        _reconcilerUpdateChildren	@	ReactMultiChild.js:218
        _updateChildren	@	ReactMultiChild.js:315
        updateChildren	@	ReactMultiChild.js:303
        _updateDOMChildren	@	ReactDOMComponent.js:938
        updateComponent	@	ReactDOMComponent.js:767
        receiveComponent	@	ReactDOMComponent.js:723
        receiveComponent	@	ReactReconciler.js:131
        updateChildren	@	ReactChildReconciler.js:94
        _reconcilerUpdateChildren	@	ReactMultiChild.js:218
        _updateChildren	@	ReactMultiChild.js:315
        updateChildren	@	ReactMultiChild.js:303
        _updateDOMChildren	@	ReactDOMComponent.js:938
        updateComponent	@	ReactDOMComponent.js:767
        receiveComponent	@	ReactDOMComponent.js:723
        receiveComponent	@	ReactReconciler.js:131
        _updateRenderedComponent	@	ReactCompositeComponent.js:737
        _performComponentUpdate	@	ReactCompositeComponent.js:715
        updateComponent	@	ReactCompositeComponent.js:634
        performUpdateIfNecessary	@	ReactCompositeComponent.js:548
        performUpdateIfNecessary	@	ReactReconciler.js:165
        c	@	ReactUpdates.js:151
        perform	@	Transaction.js:138
        perform	@	Transaction.js:138
        perform	@	ReactUpdates.js:90
        x	@	ReactUpdates.js:173
        closeAll	@	Transaction.js:204
        perform	@	Transaction.js:151
        batchedUpdates	@	ReactDefaultBatchingStrategy.js:63
        s	@	ReactUpdates.js:201
        r	@	ReactUpdateQueue.js:25
        enqueueSetState	@	ReactUpdateQueue.js:209
        u.setState	@	ReactComponent.js:64
        success	@	groupEventDetails.jsx:53
        (anonymous function)	@	api.jsx:61
        l	@	jquery.js:3099
        fireWith	@	jquery.js:3211
        n	@	jquery.js:8264
        (anonymous function)	@	jquery.js:8605
        r	@	raven.js:286

**Comment by tghw** [comment] 2016-09-21 16:45
And the `Cannot read property '0' of undefined` error:

    raven.js:290 Uncaught TypeError: Cannot read property '0' of undefined
        fetchData	@	releaseStats.jsx:108
        componentWillMount	@	releaseStats.jsx:79
        (anonymous function)	@	ReactClass.js:534
        performInitialMount	@	ReactCompositeComponent.js:338
        mountComponent	@	ReactCompositeComponent.js:241
        mountComponent	@	ReactReconciler.js:49
        mountChildren	@	ReactMultiChild.js:242
        _createInitialChildren	@	ReactDOMComponent.js:704
        mountComponent	@	ReactDOMComponent.js:529
        mountComponent	@	ReactReconciler.js:49
        performInitialMount	@	ReactCompositeComponent.js:367
        mountComponent	@	ReactCompositeComponent.js:241
        mountComponent	@	ReactReconciler.js:49
        mountChildren	@	ReactMultiChild.js:242
        _createInitialChildren	@	ReactDOMComponent.js:704
        mountComponent	@	ReactDOMComponent.js:529
        mountComponent	@	ReactReconciler.js:49
        mountChildren	@	ReactMultiChild.js:242
        _createInitialChildren	@	ReactDOMComponent.js:704
        mountComponent	@	ReactDOMComponent.js:529
        mountComponent	@	ReactReconciler.js:49
        mountChildren	@	ReactMultiChild.js:242
        _createInitialChildren	@	ReactDOMComponent.js:704
        mountComponent	@	ReactDOMComponent.js:529
        mountComponent	@	ReactReconciler.js:49
        performInitialMount	@	ReactCompositeComponent.js:367
        mountComponent	@	ReactCompositeComponent.js:241
        mountComponent	@	ReactReconciler.js:49
        mountChildren	@	ReactMultiChild.js:242
        _createInitialChildren	@	ReactDOMComponent.js:704
        mountComponent	@	ReactDOMComponent.js:529
        mountComponent	@	ReactReconciler.js:49
        performInitialMount	@	ReactCompositeComponent.js:367
        mountComponent	@	ReactCompositeComponent.js:241
        mountComponent	@	ReactReconciler.js:49
        _updateRenderedComponent	@	ReactCompositeComponent.js:753
        _performComponentUpdate	@	ReactCompositeComponent.js:715
        updateComponent	@	ReactCompositeComponent.js:634
        performUpdateIfNecessary	@	ReactCompositeComponent.js:548
        performUpdateIfNecessary	@	ReactReconciler.js:165
        c	@	ReactUpdates.js:151
        perform	@	Transaction.js:138
        perform	@	Transaction.js:138
        perform	@	ReactUpdates.js:90
        x	@	ReactUpdates.js:173
        closeAll	@	Transaction.js:204
        perform	@	Transaction.js:151
        batchedUpdates	@	ReactDefaultBatchingStrategy.js:63
        s	@	ReactUpdates.js:201
        r	@	ReactUpdateQueue.js:25
        enqueueSetState	@	ReactUpdateQueue.js:209
        u.setState	@	ReactComponent.js:64
        onGroupChange	@	groupDetails.jsx:121
        n	@	PublisherMethods.js:44
        o.emit	@	index.js:137
        trigger	@	PublisherMethods.js:63
        loadInitialData	@	groupStore.jsx:41
        success	@	groupDetails.jsx:95
        (anonymous function)	@	api.jsx:61
        l	@	jquery.js:3099
        fireWith	@	jquery.js:3211
        n	@	jquery.js:8264
        (anonymous function)	@	jquery.js:8605
        r	@	raven.js:286

**Comment by mattrobenolt** [comment] 2016-09-21 16:48
Aha, so we tracked this down before to TSDB not running correctly. :) And we didn't handle that case.

So my guess is you have in your config the Dummy TSDB backend. Do you have missing graphs everywhere?

In theory, this was fixed with https://github.com/getsentry/sentry/pull/4098, but you shouldn't be running the dummy backend. This could have only really happened if your config has gone through many many upgrades from long ago.

Set:

```python
SENTRY_TSDB = 'sentry.tsdb.redis.RedisTSDB'
```

in your `sentry.conf.py` and this should fix itself.

**Closed by mattrobenolt** 2016-09-21 16:48 UTC

**Comment by mattrobenolt** [comment] 2016-09-21 16:51
I should also note that it's worth regenerating your config files entirely, and just porting over your changed settings with `sentry init`. Just to make sure nothing is missing and to keep up with updates when things get added, etc.

**Comment by tghw** [comment] 2016-09-21 16:52
That did it! Thanks.

Seems like a default value needs to be set or a warning should be output. It's hard to keep track of all the settings that need to be updated on an upgrade (assuming they're documented).

**Comment by mattrobenolt** [comment] 2016-09-21 16:55
Yeah, the default value is to use the Dummy backend, which technically works in all situations. Except this surfaced a bug since we never run it ourselves, for obvious reasons. A warning though, in retrospect would be useful now that we have a better way to surface warnings, since a dummy TSDB backend is effectively useless since you have no graphs anywhere.

But again, our install directions say to rebuild your config with `sentry init` and double check. :)

**Comment by tghw** [comment] 2016-09-21 16:59
Fair enough. Looks like those files have very little to do with each other now. Time for some diffing! :-)
