### ISSUE TITLE
sentry replay not found 

### ISSUE THREAD

**Issue by lmcccy** [getsentry/sentry#70638] opened 2024-05-10 06:14 UTC
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1、Main.js file is configated.
2、Sentry@vue version and sentry@replay version are newliest.
3、But interface is show 'Replay Not Found'.

### Expected Result

Replay Not Found

### Actual Result

Replay Not Found

### Product Area

Replays

**Comment by bruno-garcia** [comment] 2024-05-10 17:08
Which version of self hosted? Not a lot of details to help us debug ur set up, could u elaborate further please?

**Comment by lmcccy** [comment] 2024-05-11 02:16
> Which version of self hosted? Not a lot of details to help us debug ur set up, could u elaborate further please?

my sentry version is "@sentry/cli": "^2.31.2",

**Comment by billyvg** [comment] 2024-05-13 23:02
Can you post your `Sentry.init` (without DSN) and a link to a replay?

**Comment by billyvg** [comment] 2024-12-05 21:42
Closing due to lack of reproduction steps.

**Closed by billyvg** 2024-12-05 21:42 UTC
Labels: Product Area: Replays
