### ISSUE TITLE
 webhooks do not work

### ISSUE THREAD

**Issue by zs-dima** [getsentry/sentry#22782] opened 2020-12-17 19:47 UTC
Reproduced with Saas (sentry.io)

In case of several projects: .Net, Flutter, etc and setup webhooks for several projects at once - Flutter project webhooks do not work.
However 'Test' works well for all project + Alerts are the same.
And same webhooks works for other projects.

![img](https://user-images.githubusercontent.com/25195453/102535867-dd3fb780-40b9-11eb-9a50-73640b133f48.png)

**Comment by ceorourke** [comment] 2021-01-06 01:28
@zs-dima can you send a ticket to support@sentry.io referencing this so we can take a look at your specifics? I tested this out and can't reproduce the issue.

**Comment by McSneaky** [comment] 2021-01-15 21:50
Alright, similar problem on self-hosted. But non of the alerts work  when there are multiple organizations

How I got to that state:
- Started fresh instance of Sentry
- Noticed that I can't create organizations. Stopped the Sentry, sent that multi_organization env variable to true, started Sentry again
- Created new organization
- Made new project in that organization
- Set up alerting like this
![image](https://user-images.githubusercontent.com/6796697/104782051-46374f80-578c-11eb-977e-8f9cca310a28.png)
- Send error from NodeJS SDK to Sentry. Error appears nicely in dashboard, but no email is sent nor is legacy integration triggered (tried only legacy integration and only email, but that doesn't work either)

Went back to initial organization. Set up exactly the same alerting in new project in there and it works perfectly

**Comment by McSneaky** [comment] 2021-01-15 21:52
Alright, similar problem on self-hosted. But non of the alerts work  when there are multiple organizations

How I got to that state:
- Started fresh instance of Sentry
- Noticed that I can't create organizations. Stopped the Sentry, sent that multi_organization env variable to true, started Sentry again
- Created new organization
- Made new project in that organization
- Set up alerting like this
![image](https://user-images.githubusercontent.com/6796697/104782325-b34ae500-578c-11eb-9948-c470607b27da.png)

- Send error from NodeJS SDK to Sentry. Error appears nicely in dashboard, but nothing is triggered. Tried emails and legacy integrations. Nothing

Went back to initial organization. Set up exactly the same alerting in new project in there and it works perfectly

**Comment by ceorourke** [comment] 2021-01-15 22:42
@McSneaky great - can this be closed then? Are you also zs-dima?

**Comment by zs-dima** [comment] 2021-01-15 22:45
Still have this issue
Support looking into

**Comment by zs-dima** [comment] 2021-02-22 18:12
Still have this issue
Support still looking into...

**Comment by chadwhitacre** [comment] 2021-02-22 19:46
Thanks @zs-dima, sorry for the bot noise.

**Comment by liupcoder** [comment] 2021-02-24 08:47
I have the same problem. Sentry 20.12.1bade073

**Comment by zs-dima** [comment] 2021-02-24 08:52
Strange that it affects Flutter projects and .Net / .Net Core projects works well.

**Comment by BYK** [comment] 2021-03-04 11:12
Ping @getsentry/visibility

**Comment by BYK** [comment] 2021-03-04 16:48
Correction, @getsentry/workflow is the one responsible for alerts, notifications etc. :D

**Comment by wedamija** [comment] 2021-03-04 22:13
> Correction, @getsentry/workflow is the one responsible for alerts, notifications etc. :D

Is the issue here a specific integration isn't working, or that alerts aren't working in general? Wasn't clear after reading through this. If it's a specific integration, then @getsentry/ecosystem will be able to help.

**Comment by zs-dima** [comment] 2021-03-05 05:16
@wedamija alerts (WebHooks) does not work for the Flutter projects

**Comment by manuzope** [comment] 2021-03-08 20:47
Hi @zs-dima, just tested this out with a Flutter project and the webhooks worked fine for me. I have a few ways we can move forward:
1. Instead of creating a webhook, try creating an internal integration (Developer Settings > Internal integration). And then configure your alert rules to send to the internal integration. Internal integrations have a dashboard that you can see which events are sent and the response code we saw. Might help us narrow down what's happening.
2. If the above doesn't work, the best way for us to replicate this problem is if you could provide some code samples (ideally a repository with a button we can click to trigger an event) with which we can trigger events and see why these webhooks are not sending.

**Comment by zs-dima** [comment] 2021-03-09 13:30
@manuzope thanks a lot for looking into.
I sent Sentry support samples in previous year already - but looks support had no time to look into yet.
Here I created new flutter project and set it up according your documentation:
[stest.zip](https://github.com/getsentry/sentry/files/6108769/stest.zip)

Webhook still does not work.

I could share my dns url and etc in email or etc, just let me know please.

1. & 2. Webhook still does not work and I want to make then work therefore.

**Comment by paalandreassen** [comment] 2021-03-10 09:25
Can confirm that it seems webhooks are not triggered from sentry.io.

I've tested the URL via curl and it works as expected. 
When trying via the integration UI on sentry.io I get Test Results "No errors returned". But the URL is never called.

**Comment by manuzope** [comment] 2021-03-10 20:02
Hi @zs-dima, mind putting that on GitHub? I can't securely open zip files.

@paalandreassen: just want to confirm - after setting up the webhook, did you also configure an alert rule to send to that webhook?

**Comment by paalandreassen** [comment] 2021-03-11 07:33
> @paalandreassen: just want to confirm - after setting up the webhook, did you also configure an alert rule to send to that webhook?

Yes, but I've since setup a debug dump of the webhook contents and I see that sentry does indeed send a payload to the addresses specified, but the payload is not compatible with slack. There are many differences, like Slack expects a property "text" while sentry sends "message" etc. 

I was naive and though webhooks were using some kind of standard payload that were (mostly) compatible between apps, but that seems not to be the case.

**Comment by zs-dima** [comment] 2021-03-11 07:35
@manuzope 
Thanks for reply and looking into.
Sure I setup alert rule and etc the same as for the .Net Core projects 
(.Net Core projects Sentry webhooks works well - but Flutter posts issue to Sentry well but webhooks do not work)

I just created new Flutter project and added Sentry as described in your documentation:
main.dart:
https://gist.github.com/zs-dima/b65e4c7a0959d4b2de43d40fda26bb4c
pubspec.yaml:
https://gist.github.com/zs-dima/d5db289bbe47899958f61bf94d05cc8a

You could look at emails with Lovepreet Sangha (Sentry Support Engineer) I sent sentry.io account details and even created test project there.

Thanks in advance

**Comment by manuzope** [comment] 2021-03-17 19:59
Hi @zs-dima, I'm unfortunately unable to replicate this. The best I can suggest is to create an internal integration (`Developer Settings -> Internal integration`). And replacing the webhook alert action with one that goes to the internal integration. That way, we'll be able to see what response codes we're getting back, if any.

**Comment by zs-dima** [comment] 2021-03-17 20:06
@manuzope International integration doesn't work aw well.
Could I kindly ask you to try example I provided or share any examples that works on your side with sentry project dns I provided?

**Comment by BYK** [comment] 2021-03-17 20:40
@zs-dima we _know_ this works for many cases as we do not have anything special around Flutter (or any other platform) for integrations. "Doesn't work" is not enough for anyone here to work off of and trying out full code examples are not practical: unsafe as we are asked to run untrusted code, and time consuming, and many of us don't even know Dart or Fultter.

If you can isolate the issue so we can reproduce it, we'd be more than happy to find a fix for that. Otherwise I'm inclined to close this issue as it is not actionable and seems like we are going in circles here.

**Comment by zs-dima** [comment] 2021-03-19 09:29
@BYK Could I kindly ask you to provde any working solution for Flutter project then?
I do not know anyone who could confirm that webhooks works for Flutter projects - I tried many.
And I could confirm that webhooks works for .Net Core projects well on other hand.

**Comment by BYK** [comment] 2021-03-19 10:42
@zs-dima as we've mentioned earlier, webhooks should work for all projects. There is not project-type specific code around alerting or webhooks so let's shift our focus from "webhooks do not work with Flutter" to something else.

We need a lot more information to be able to assist you:

- Are you getting the events/new issues from your Flutter project into your Sentry project?
- How are your alert rules configured?

**Comment by zs-dima** [comment] 2021-03-19 16:38
@BYK 
> webhooks should work for all projects
Totally agree
> Are you getting the events/new issues from your Flutter project into your Sentry project?
Yes, as I told already
> How are your alert rules configured?
Just 1 rule: Send a notification (for all legacy integrations)
I provided sentry.io login details to Sentry support few months before already and projects samples, hope they will find time to look into.

**Comment by zs-dima** [comment] 2021-03-19 16:57
For example here 'bb76c1eca4b14124ae0b8b2280163dd7' printed out and I could see Sentry issue with the same event value:

```dart
    await sentry.SentryFlutter.init(
      (options) {
        options.dsn = 'https://***@***.ingest.sentry.io/***';
      },
    );

    try {
      throw Exception('Test exception');
    } catch (exception, stackTrace) {
      final ll = await Sentry.captureException(exception, stackTrace: stackTrace);
      print(ll);
    }
```

**Comment by BYK** [comment] 2021-03-19 20:31
@zs-dima do you allow us to add a custom webhook that we control to your project alert to do further testing and analysis? The webhook will be on a third-party service and the contents may be readable to that service but not to the public.

**Comment by zs-dima** [comment] 2021-03-19 20:37
@BYK Sure I will happy to do it to fix this strange issue finally.
Thanks a lot for care

**Comment by chadwhitacre** [comment] 2021-03-19 20:51
I still haven't seen a clear bug report here, with well-defined steps to reproduce, expected result, and actual result.

Here is what I think your steps to reproduce are, @zs-dima:

### Steps to Reproduce

1. Build a flutter app with [Sentry installed](https://docs.sentry.io/platforms/flutter/). `stest.zip` above contains this (yes?).
1. Configure a webhook ... here's how I'm doing this:
    1. Run [`httpdump`](https://gist.github.com/chadwhitacre/9344b8d58269c58e9644b8c1a832962e), expose via [ngrok](https://ngrok.com/).
    1. Sentry.io > Settings > Search > WebHooks > Project Configurations > add ngrok URL
    1. (Also make sure the plugin configuration is enabled I guess?)
    1. "Test Plugin", should see a `request-000` show up on local filesystem that [looks like this](https://gist.github.com/chadwhitacre/ca041612004df345987bd144cc80fbaa).
1. Configure an alert notification ...
    1. Alerts > Create Alert Rule
    1. Alert name: Whatever
    1. Alert Conditions: Then Perform These Actions > Send a notification via an integration > ... via WebHooks
1. Trigger an event from the Flutter app.

If this is not what you are doing then please advise.

> All .Net Core projects webhooks works well.
> All Flutter projects webhooks does NOT work.

Here is what I think your definitions of "works" (i.e., expected result) and "does not work" (i.e., actual result) are:

### Expected Result

Local `request-NNN` file captured [looks like this](https://gist.github.com/chadwhitacre/ca041612004df345987bd144cc80fbaa).

### Actual Result

No idea ... what is the actual result you are seeing?

**Comment by BYK** [comment] 2021-03-19 20:56
@zs-dima thanks for the consent. We have added our webhook to both of your projects so once you start triggering them, we should get some useful data for debugging.

Also if you can try to explain the issue in more detail as @chadwhitacre suggested, it would still help as the webhook debugging may not turn out to be productive.

**Comment by chadwhitacre** [comment] 2021-03-19 20:59
@zs-dima Are you running afoul of action interval?

<img width="955" alt="Screen Shot 2021-03-19 at 4 59 07 PM" src="https://user-images.githubusercontent.com/134455/111841515-74dcbe00-88d4-11eb-9f6c-3ee47f642bfc.png">

**Comment by chadwhitacre** [comment] 2021-03-19 21:01
@zs-dima I'm confused by your thumbs up on my comment above where I asked for clarification on your bug report. Kindly please answer these questions:

1. Are the steps to reproduce the problem accurate?
2. What is the actual result you are seeing, in detail?

**Comment by zs-dima** [comment] 2021-03-19 21:03
@BYK I just triggered webhook as before, Event Id is '41ee8cc575d440b6bee7939d283411da'
@chadwhitacre I will prepare more details for you shortly, as I have re-setup environment back.

**Comment by zs-dima** [comment] 2021-03-19 21:04
@chadwhitacre it is not action interval case as for the Net Core project I have the same settings and I tried to change action interval as well

**Comment by zs-dima** [comment] 2021-03-19 21:11
![image](https://user-images.githubusercontent.com/25195453/111842562-b4290000-8910-11eb-89f5-678420cf616d.png)
and by the way - 'Test Plugin' button works well for all projects, I just retested it.

**Comment by chadwhitacre** [comment] 2021-03-19 21:14
> I will prepare more details for you shortly, as I have to re-setup environment back.

Thank you. Please provide as much information as you can to help us debug.

My best hypothesis at this point is that you have a misconfiguration. I find it highly unlikely that the source of the issue/event is related to the failure of the webhook, but I've been surprised before. :o)

> it is not action interval case as for the Net Core project I have the same settings and I tried to change Flutter projects action interval as well

Say more about this ... is the alert shared between the Net Core and Flutter projects? Are you triggering the alert via Net Core, and then, within the alert interval, triggering it again from Flutter? If so is the alert interval suppressing the second webhook? In your steps to reproduce do you create the alert, then hit it immediately from the Flutter app?

**Comment by chadwhitacre** [comment] 2021-03-19 21:14
Zooming out @manuzope @BYK ... do we have an audit of integration payloads? I'm thinking of something like GitHub does with their webhooks:

<img width="905" alt="Screen Shot 2021-03-19 at 5 12 09 PM" src="https://user-images.githubusercontent.com/134455/111842711-419b2e80-88d6-11eb-82e4-0947929bcaf1.png">

Is there a possible product improvement around that to make this kind of thing easier to (self-service) debug in the future?

Another minor wart: I am seeing unrendered markdown in the WebHooks plugin description:

<img width="774" alt="Screen Shot 2021-03-19 at 5 10 13 PM" src="https://user-images.githubusercontent.com/134455/111842568-0ac51880-88d6-11eb-8ee6-022fadb82914.png">

**Comment by zs-dima** [comment] 2021-03-19 21:18
@chadwhitacre 
I triggered webhook few times but I could see nothing in the ngrok:
```
Version                       2.3.35                                                                                    Region                        United States (us)                                                                        Web Interface                 http://127.0.0.1:4040                                                                     Forwarding                    http://2f4c9de31a6b.ngrok.io -> http://localhost:7071                                     Forwarding                    https://2f4c9de31a6b.ngrok.io -> http://localhost:7071                                                                                                                                                            Connections                   ttl     opn     rt1     rt5     p50     p90                                                                             0       0       0.00    0.00    0.00    0.00                                              
```
However 'Test Plugin' button triggering well.

**Comment by manuzope** [comment] 2021-03-19 21:19
@chadwhitacre we have something like that for internal integrations (`Developer Settings -> Dashboard`) but not for webhooks. Internal integrations can also be used to send webhooks so we can get an audit log going if we move over to using those.

It will tell us response codes but not request/response bodies.

**Comment by chadwhitacre** [comment] 2021-03-19 21:23
> International integration doesn't work as well.

@zs-dima Why?

**Comment by BYK** [comment] 2021-03-19 21:27
>I triggered webhook few times but I could see nothing in the ngrok:

I can confirm that there is 0 activity on the webhook that we installed for our testing.

**Comment by zs-dima** [comment] 2021-03-19 21:33
@chadwhitacre I checked all steps you provided above and everything setup as you described
ngrok result I provided above
'International integration' - behave in the same way - nothing in the ngrok log

**Comment by zs-dima** [comment] 2021-03-19 21:34
@BYK 
> I can confirm that there is 0 activity on the webhook that we installed for our testing.
And you could see that projects had been setup correctly and 'Test Plugin' button triggering well

**Comment by chadwhitacre** [comment] 2021-03-19 21:36
> 'Test Plugin' button triggering well

To confirm: this means that you do get something in the ngrok log from "Test Plugin"?

Do you get something in the ngrok log when triggering the alert from Net Core?

**Comment by zs-dima** [comment] 2021-03-19 21:39
@chadwhitacre 
Sure I receive correct webhook with all details in the ngrok and my service from "Test Plugin"
And I receive correct webhook with all details for all my Net Core Sentry projects as well
It is quite strange

**Comment by chadwhitacre** [comment] 2021-03-19 21:40
I just sent an event, `name 'heck' is not defined`, did it arrive in your ngrok log?

**Comment by zs-dima** [comment] 2021-03-19 21:45
@chadwhitacre I just received event but looks it is related to 'Test exception 8' I fired to test 'International integration'
however json format for this event looks a bit different

**Closed** 2021-03-19 23:54 UTC
Labels: Component: Notifications, Component: Workflow, Status: Needs More Information, Team: Workflow

**Comment by zs-dima** [comment] 2021-03-19 23:55
@chadwhitacre @BYK @manuzope Thanks a lot for care and help, all projects work well now :)
