### ISSUE TITLE
Archive an issue until it appears in a new environment

### ISSUE THREAD

**Issue by vhtkrk** [getsentry/sentry#57446] opened 2023-10-04 08:52 UTC
### Problem Statement

We have some periodic tasks that keep occasionally failing in our staging environments due to resource limits and other random stuff like external APIs being unavailable. But since it's just staging we don't really mind all that much - it's expected that stuff breaks there from time to time. I would like to archive these issues, but still be aware if similar ones prop up in our production environment.

### Solution Brainstorm

An ability to archive an issue until it is seen in a new environment.

### Product Area

Issues

**Comment by jangjodi** [comment] 2023-10-05 21:25
Thank you for the feature request! I've added it to our backlog.

**Comment by therealarkin** [comment] 2023-10-05 23:04
Thank you, we should get to it... same feedback here - https://github.com/getsentry/sentry/issues/12341

**Comment by runspired** [comment] 2024-01-12 08:21
+1 in our case we have a service that doesn't always exist in staging environments but should always exist in live ones. Would be great to ignore forever in staging and be alerted to it in live.

**Comment by rhys-steele** [comment] 2024-05-29 23:02
+1 for this!

**Comment by faroukcharkas** [comment] 2024-08-03 23:25
+1 for this as well!

**Comment by jangjodi** [comment] 2024-12-10 23:34
I'm going to close this issue, as it is a duplicate of this more popular one: https://github.com/getsentry/sentry/issues/12341

**Closed by jangjodi** 2024-12-10 23:34 UTC
Labels: Feature: Errors, Product Area: Issues
