### ISSUE TITLE
the feedback form fails to submit on Firefox due to a CORS error

### ISSUE THREAD

**Issue by matthargett** [getsentry/sentry#65180] opened 2024-02-14 19:59 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. use the Sentry.feedbackIntegration()
2. deploy your app, and load it into Firefox 122 on macOS, and the Firefox-based browser on the HTC Vive XR Elite (other OSes are likely also affected)
3. fill in the feedback form In your web UI
4. click submit

### Expected Result

The correct headers should be supplied by the sentry SaaS server-side so that feedback submission works like it does on Safari and Chrome. 

### Actual Result

The feedback form prints an error in red (first picture), which is a CORS error (second picture):
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o4506186963812352.ingest.sentry.io/api/4506187330158592/envelope/?sentry_key=0005794356bc50a7836fc7306c0e6978&sentry_version=7&sentry_client=sentry.javascript.react%2F7.100.1. (Reason: CORS request did not succeed). Status code: (null).
```
<img width="398" alt="Screenshot 2024-02-13 at 9 44 47 AM" src="https://github.com/getsentry/sentry/assets/1550766/da6413c9-ca07-40c8-aa4b-322bd4628f3c">

<img width="1155" alt="Screenshot 2024-02-13 at 9 45 28 AM" src="https://github.com/getsentry/sentry/assets/1550766/c43b7878-f33b-4851-951d-5df0661673a1">
 
On Chrome/Edge, there is a *warning* in dev tools that mentions this CORS issue.

### Product Area

User Feedback

**Comment by mydea** [comment] 2024-02-15 16:16
Hey,

so I just tried this and it worked fine for me in Firefox?

Do you have a reproduction for this - is the site public where this has failed for you?

**Comment by matthargett** [comment] 2024-02-15 16:58
> so I just tried this and it worked fine for me in Firefox?
> 
> Do you have a reproduction for this - is the site public where this has failed for you?

It's a publicly available URL, but I'm not ready for mass onslaught of random users yet 😅  Is there a place I can DM you the URL?

**Comment by Crismon96** [comment] 2024-08-29 10:13
Guys, this is still happening on a bigger scale for our users.
It works for me on Mac Firefox but doesn't for our windows firefox users.

I will get the specific versions from my guy who has the issue. I wasn't able to reproduce any warnings personally either but the error is the same for users experiencing the CORS issue.

**Comment by souredoutlook** [comment] 2024-08-29 13:02
Hi @matthargett - head of Support for North America here 👋 

You can send us more context by opening a request and referencing this issue (ask for Nick M specifically) -> [https://sentry.zendesk.com/hc/en-us](https://sentry.zendesk.com/hc/en-us)

My quick thoughts on this issue:
- it is possible to Firefox directly into "Strict" privacy settings on install
- It is expected that Sentry features will fail in this environment
- If you are bundling Sentry with your app the widget will load but submission should fail

You can check to see if the install you're using is in strict mode by navigating to your Privacy preferences in Firefox (found at about:preferences#privacy)

If you want to circumvent tools that block potentially tracking scripts like this you can use a tunneling option: https://docs.sentry.io/platforms/javascript/troubleshooting/ ( you need to expand the section titled "using the tunnel option" - this page doesn't seem to support deep linking)

**Comment by souredoutlook** [comment] 2024-08-29 13:16
@Crismon96 I can confirm after putting Firefox (on Mac) into strict mode I can recreate this failure to report when navigating to https://www.jassets.org/ 

![Image](https://github.com/user-attachments/assets/ce8fc5e2-42b7-47f6-a3f2-d35d24681fba)

Normally this is a non-issue for the Sentry SDK because events will simply be dropped in background without incident. The Feedback form failure makes this issue quite apparent.

I can see your "disable ad blockers" toast appearing (very nice btw) but again I'd recommend tunneling to avoid the issue altogether.

Some notes about tunneling:
- this effectively causes your price-per-event to go up because you need to ingest the event yourself, and then pay for the egress of said event from your server to Sentry's servers
- it's not currently possible to configure tunneling to work on only some data (for example, tunneling only Feedback but omitting Replays which are much larger payloads in aggregate) I'll follow up this post with another Issue that enumerates some of these perceived issues with tunneling

**Comment by Crismon96** [comment] 2024-09-02 16:22
Thanks  for the in-depth information, which makes sense to me. We will consider tunneling and for now I can at least improve the error message.
I think we can close this issue now.

**Closed** 2024-09-03 16:13 UTC
Labels: Product Area: User Feedback, Waiting for: Product Owner
