### ISSUE TITLE
Sentry to pass event ID to Jira and Slack when integrating

### ISSUE THREAD

**Issue by raqsilva8** [getsentry/sentry#62254] opened 2023-12-22 08:51 UTC
### Problem Statement

We have Jira and Slack integrated with Sentry. I have created a rule that sends a slack notification and creates a jira ticket when a specific issue is found, although those issues do not target the specific event. Is there a way to send the specific link to the event instead of the issue?

For instance I want
`https://cybersmart.sentry.io/issues/{ISSUE ID}/events/{EVENT ID}/`
instead of
`https://cybersmart.sentry.io/issues/{ISSUE ID}/?project={PROJECT ID}`

Thanks!

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment] 2024-01-02 17:20
Hi @raqsilva8 

Sentry's [Recommended Event](https://changelog.getsentry.com/announcements/recommended-event-in-issue-details) shows the most relevant event based on what you've searched or the alert trigger, so when you click on the issue it should already show you the event you care about. 

Could you please provide more details about the rule that you have created and the types of filters/triggers you are using?

**Comment by raqsilva8** [comment] 2024-01-03 16:09
Hello,

Not sure I made myself clear, I do not want the latest event but rather the specific issue/event that was caught on the rule.
The rule in question does the following:
`
WHEN an event is captured
IF all of these filters match
The event's exception.value value contains Superscript
THEN perform these actions
Send a notification to the XXXXX Slack workspace to errors-superscript and show tags [Event] in notification
Create a Jira issue in JIRA with these
`

Let's say an event occurs today (event 1) and then tomorrow we have event 2. The jira ticket with event 1 will have the URL https://cybersmart.sentry.io/issues/{ISSUE ID}/?project={PROJECT ID} which will lead you to the latest event/issue (event 2) instead of the specific event URL https://cybersmart.sentry.io/issues/{ISSUE ID}/events/{EVENT ID}/ for event 1.

Hope this is clearer,
Thank you

**Comment by rachrwang** [comment] 2024-01-03 17:37
@raqsilva8 - for the example you gave, can you share more about why the event-level link is important for your use case? If I understand it correctly - are you trying to create a unique jira issue for each new event?

**Comment by malwilley** [comment] 2024-01-03 18:44
Related issues: https://github.com/getsentry/sentry/issues/21315, https://github.com/getsentry/sentry/issues/33678

**Comment by raqsilva8** [comment] 2024-01-04 08:59
@rachrwang sure! The data linked to the raised issue is important and it changes. Basically we are trying to do some business logic on the application and if it fails, then an issue is raised in order to handle it manually in which case we want the specific data linked to the issue.

**Comment by malwilley** [comment] 2024-01-05 23:35
@raqsilva8 thanks for describing your use case! I'll close this issue as a duplicate of https://github.com/getsentry/sentry/issues/33678 which you can track for updates.

**Closed by malwilley** 2024-01-05 23:35 UTC
Labels: Product Area: Settings - Integrations, Waiting for: Product Owner
