### ISSUE TITLE
Cronjob using the SDK

### ISSUE THREAD

**Issue by Azkae** [getsentry/sentry#42767] opened 2023-01-04 16:52 UTC
### Problem Statement

I would like to setup cronjob using the SDK.

My use case: I have a celery task in Python that must run everyday and I want to monitor it.
Since my task runs in celery, I don't have an entrypoint to use `sentry-cli monitors run [...]`.

I would like to call a function in the sentry SDK to start monitoring a cronjob.

I could also call the two HTTP requests directly but I didn't find them in the docs.

### Solution Brainstorm

An usage could be:
```
# This function is called everyday
def my_task():
    with sentry_sdk.start_cronjob("<monitor_id>"):
        ...
```

**Comment by bruno-garcia** [comment] 2023-01-05 00:57
Likewise, I'd like to do that for [Hangfire jobs](https://www.hangfire.io)

**Comment by davidenwang** [comment] 2023-01-11 19:25
Hi there, thanks for your interest in our new crons product. We are actively working on improving support for framework specific installations and possibly integrating with our existing SDK. Unfortunately, in the meantime the best we can do is offer our crons API through HTTP. Here is additional documentation on setting up crons via HTTP.

https://docs.sentry.io/product/crons/getting-started/#step-2-set-up-health-checks

https://docs.sentry.io/api/crons/create-a-new-checkin/
https://docs.sentry.io/api/crons/update-a-checkin/

**Comment by gaprl** [comment] 2023-02-15 22:49
Hi there, thank you for your feedback! We are actively planning Crons support for our Python SDK, and you can track our progress through our [roadmap](https://github.com/orgs/getsentry/projects/60) with the following issues: https://github.com/getsentry/sentry/issues/44687 https://github.com/getsentry/sentry/issues/44689

Duplicate of https://github.com/getsentry/sentry/issues/44687

**Closed by gaprl** 2023-02-15 22:49 UTC
Labels: Status: Backlog, Team: Crons
