### ISSUE TITLE
Archive sub-menu on smaller screens doesn't work

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#54134] opened 2023-08-03 21:46 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open an issue on a small screen (such as mobile)
2. Click on the [...] button at the top right corner of the screen
3. Click on Archive

Nothing will happen.

![CleanShot 2023-08-03 at 14 40 44 2@2x](https://github.com/getsentry/sentry/assets/1308394/48bb03e4-1cf8-4ac7-9df1-e8463553653e)

### Expected Result

To open the archive menu with its options.

### Actual Result

Nothing happens.

### Product Area

Issues

**Comment by malwilley** [comment] 2023-08-03 22:03
Duplicate of https://github.com/getsentry/sentry/issues/54134

**Closed by malwilley** 2023-08-03 22:03 UTC
