### ISSUE TITLE
Consider all stack traces for grouping

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#60184] opened 2023-11-17 16:35 UTC
### Problem Statement

At the moment it seems Sentry groups using only one stack trace. This is an issue when there are two stack traces for an issue that are completely different.

### Solution Brainstorm

Consider all stack traces for grouping

### Product Area

Issues

**Comment by lobsterkatie** [comment] 2023-11-17 19:43
@kerenkhatiwada, can you please share some links to events which show this behavior? And when you say "multiple stacktraces," do you mean events with error groups or chained errors, or something else?

**Comment by kerenkhatiwada** [comment] 2023-11-17 21:54
[Here](https://francisorg.sentry.io/issues/4643411556/?project=4504089864830976&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d&stream_index=0) is an event where we were able to reproduce it. This occurs for javascript error.cause issues. However, AggregateErrors are grouped by all stack traces.

**Comment by lobsterkatie** [comment] 2023-11-17 22:44
Thanks for that. And yeah, this is just a slight twist on https://github.com/getsentry/sentry/issues/59679 from earlier this week. As it happens, `AggregateErrors` aren't grouped on _all_ stacktraces, just potentially more of them than in this case. (See the second example [here](https://github.com/getsentry/rfcs/blob/main/text/0079-exception-groups.md#sentry-issue-grouping).) Regardless, we handle this case incorrectly right now.

Question: The current fix for the linked issue is to consider the top error rather than the wrapped one. Would that serve your purposes, or would you actually want both stacks to be included?

**Comment by thatguydan** [comment] 2024-05-13 01:37
Hi there! I'd like to argue for the wrapped error being used for grouping. In the screenshot below you can see an Axios error from inside its library. However, you can expect that Axios will be called from all over a codebase in different contexts, and then any Axios issues will be grouped together. 

<img width="1156" alt="image" src="https://github.com/getsentry/sentry/assets/714300/a4213d46-334e-47bb-a4b4-094087ecccd4">

**Comment by eps1lon** [comment] 2024-05-29 11:35
React 19 will start leveraging the `cause` property.

Unfortunately, in Sentry, issues are grouped by the actual error message ("There was an error while hydrating but React was able to recover by") not by the cause. I think having the parent as an issue is still nice as an umbrella issue. But the cause should be in a separate issue as well. Ideally with the same trace parent.

![Screenshot 2024-05-29 at 13 21 36](https://github.com/getsentry/sentry/assets/12292047/08e65e29-7e4e-4235-9a0c-09537a80a76c)
![Screenshot 2024-05-29 at 13 21 52](https://github.com/getsentry/sentry/assets/12292047/28cafea0-44f9-4706-8b7c-b106da83a26d)

**Comment by JoshFerge** [comment] 2024-05-30 06:47
thank you @eps1lon -- will get with the team internally and figure out next steps here.

**Comment by AbhiPrasad** [comment] 2024-06-13 18:53
React 19 concerns fixed with https://github.com/getsentry/sentry/pull/72593

**Comment by lobsterkatie** [comment] 2024-12-11 05:28
In the case of a chained exception, it turns out we do in fact consider all stacktraces, so I'm going to close this. Please feel free to reopen if there's still a problem.

**Closed by lobsterkatie** 2024-12-11 05:28 UTC
Labels: Component: Grouping, Product Area: Issues
