### ISSUE TITLE
Experiment: Issues tab to show Backend & Frontend errors in a replay session

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#37368] opened 2022-08-02 17:53 UTC
Problem: We don't have backend errors associated with replays.

Idea: Can we hack around that issue by making N+1 queries on the front-end?

The task is to query for all errors that've happened within a replay

Currently we can query for all errors, and find that have `event.replayId` set. But in practice these are only front-end error. 

We could find errors if we query for the list of traces within a replay first, but this could be slow.
This wouldn't work if the org doesn't have tracing enabled.

**Comment by ryan953** [comment] 2022-09-06 19:21
cc @jas-kas

**Comment by jas-kas** [comment] 2022-09-06 20:32
**Problem**

Today you can see all issues that belong to errors found in a replay in the Issues tab on Replay Details. However, there are no timestamps on the issue to bring users to that exact moment in the replay video (unlike the other tabs on Replay Details). What makes this more complicated is an issue may have multiple errors in the same Replay. 

Here's an example where there were 3 different issues, and 8 error events for a given replay. There's no way for a user to easily navigate to the errors belonging to a specific issue in the Issues tab. As a result, users need to dig through the timeline or breadcrumbs to find the relevant error events.

![Screen Shot 2022-09-06 at 4 25 14 PM](https://user-images.githubusercontent.com/77064737/188731378-82e7c67b-2e34-46e2-b823-3742ec5c19bf.png)

**Solution**

TBD on Design.

**Comment by ryan953** [comment] 2022-09-09 22:59
We're going to have to do some work to put the table filters (console, dom, network, etc) into the url, so that we can deep link into the details page and have only errors shown in the console tab.

**Comment by ryan953** [comment] 2023-03-15 19:39
This is an epic now, spec'd out: https://github.com/getsentry/sentry/issues/45529

closing because this ticket is a duplicate of that.

**Closed by ryan953** 2023-03-15 19:39 UTC
Labels: Status: Backlog, Team: Replay
