### ISSUE TITLE
sentry can not delete release bug

### ISSUE THREAD

**Issue by xgqfrms** [getsentry/sentry#23286] opened 2021-01-25 07:02 UTC
## Important Details

How are you running Sentry?

Other, version x.y.z, [briefly describe your environment]

> npm

```js
        "@sentry/browser": "5.29.2",
        "@sentry/integrations": "5.29.2",

```

## Description

[What happened]

> sentry can not delete release bug

1. UI not work

![image](https://user-images.githubusercontent.com/7291672/105671855-5aaee100-5f1e-11eb-8493-78423b8d5ca7.png)

2.  CLI not work, too

![image](https://user-images.githubusercontent.com/7291672/105671731-276c5200-5f1e-11eb-869c-9327ecf0e4a7.png)

### What you expected to happen

[What you think should be happening]

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by xgqfrms** [comment] 2021-01-25 07:02
# cli not work

https://github.com/getsentry/sentry/issues/4969

**Comment by BYK** [comment] 2021-01-25 07:31
Duplicate of #5701

**Closed by BYK** 2021-01-25 07:31 UTC
