### ISSUE TITLE
Add a button or command to cleanup old source map

### ISSUE THREAD

**Issue by AvailCat** [getsentry/sentry#20119] opened 2020-08-03 06:42 UTC
## Summary

Add a button or command to give user ability to remove old source map files

## Motivation

Old artifacts like source map eats a lot of disk space, this will cause service was down, we need upgrade disk size repeatly, but this cost money and old source map is useless.

And `sentry cleanup` did not delete old old artifacts, this command only delete events.

**Comment by mattrobenolt** [comment] 2020-08-03 07:30
> And sentry cleanup did not delete old old artifacts, this command only delete events.

It does delete old files if they are unreferenced anywhere. The issue is that files like this are attached to Release objects in the database. So they maintain a reference forever since a release exists forever. If you delete releases, the attached files will also be deleted. 

You could also do something more clever and just delete files on disk that are older than X days and do that simply with `find ... -delete`. Or if you use S3 or something, you can just apply a TTL to every object in the bucket.

**Comment by AvailCat** [comment] 2020-08-03 07:39
@mattrobenolt But this way can't filter file by projects...

**Comment by mattrobenolt** [comment] 2020-08-03 08:58
I’d suggest using the API then or something to do your own cleanup logic. Even if we added something like this to `sentry cleanup`, it likely wouldn’t take individual projects into account. Files aren’t bound to projects anyways, they’re bound to organizations.

**Comment by BYK** [comment] 2020-10-26 13:14
Closing as this is not really actionable on our end.

**Closed by BYK** 2020-10-26 13:14 UTC
