### ISSUE TITLE
Assigned team(s) lost after invitation accept

### ISSUE THREAD

**Issue by floqqi** [getsentry/sentry#5759] opened 2017-07-24 19:41 UTC
If I invite a member into my sentry installation and check a team in invitation screen the assignment is lost after the member registers on my server. I have to tick the team box again for every invited member.

**Comment by nimishsinghal** [comment] 2017-10-01 19:42
Hi @floqqi ,
I am unable to reproduce the above issue. The member has access only for the teams for which he was invited. Can you please tell the steps to reproduce the above issue.

**Comment by floqqi** [comment] 2017-10-02 06:32
Hi @nimishsinghal,

take the following steps to reproduce the issue:

1. Invite user "test@example.com" as member and tick an existing team (e. g. "Test")
2. Follow invitation link and register user "test@example.com"
3. After successful registration, accept invitation
4. Login with "test@example.com"

Result: User "text@example.com" has no access to any team or project. You have to login as admin again and have to manually select the team "Test" again.

This happens on two on-premise installations. Haven't tried on sentry.io.

**Comment by dcramer** [comment] 2017-10-02 17:03
What version of Sentry? I can't see how this could be broken unless its not playing well with the single organization flow.

**Comment by nimishsinghal** [comment] 2017-10-02 17:52
@dcramer The issue is reproducible in the current version. After logging in from invite link, the rows corresponding to organizationmember_id gets deleted. I am trying to look into the issue.

**Comment by nimishsinghal** [comment] 2017-10-04 21:01
@dcramer I think I got the issue, `organization.member_set.create(user=user, **defaults)` on line 51 in auth_organization_login.py creates a new user and overwrites the existing mapping in OrganizationMember models. Please correct me if I am wrong.

**Comment by dcramer** [comment] 2017-10-09 17:24
Fixed in master as we removed the auto-join behavior intended for single orgs.

**Closed by dcramer** 2017-10-09 17:24 UTC
Labels: Easy Task
