### ISSUE TITLE
A fatal issue disappeared from issue list for no reason.

### ISSUE THREAD

**Issue by froy001** [getsentry/sentry#5523] opened 2017-06-06 08:21 UTC
I was looking into a fatal crash on Sentry today. 30 min later I returned to the issue list and could not find the issue. I included all issues including resolved etc. 

Going through logentries I can see the issue has been sent e.g. event id 03aa40e415cf4ee6be7fe1f30b0f11f2

The issue that is missing is ActionController::RoutingError No route matches [POST] /api/v1/users 

I am using Ruby gem sentry-raven 2.4

**Comment by mattrobenolt** [comment] 2017-06-06 08:35
There are many reasons it could go away. Maybe it was merged or deleted, etc. there's not a bug in Sentry, rather something explains it. There's just no information here to help you identify why.

**Closed by mattrobenolt** 2017-06-06 08:35 UTC

**Comment by costa** [comment] 2017-06-06 13:41
Hey @mattrobenolt, the short and precise answer is actually, fyi, Rails' `ActionController::RoutingError`s all have the same stacktrace, and as such, they are all grouped together by Sentry, by default.
