### ISSUE TITLE
Samsung Internet browser identified as Google Chrome

### ISSUE THREAD

**Issue by carestad** [getsentry/sentry#8110] opened 2018-04-19 12:26 UTC
This is rather annoying and confusing. Users that have and use the Samsung Internet browser are identified in issues with the browser Chrome Mobile.

It is likely the User Agent filter that is used to apply this that doesn't take into account the `SamsungMobile/X.X` part of the UA.

Example of UA from my Samsung Galaxy S5:

`Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G900F Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.4 Chrome/56.0.2924.87 Mobile Safari/537.36`

**Comment by b4stien** [comment] 2018-07-12 09:22
I second this, we've lost some days trying to reproduce on Chrome Mobile last week.

Another user agent:

`Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-A310F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/7.2 Chrome/59.0.3071.125 Mobile Safari/537.36`

**Comment by BYK** [comment] 2020-10-21 19:14
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Closed by BYK** 2020-10-21 19:14 UTC
