### ISSUE TITLE
Sentry not grouping errors with same message, exception type, and stack trace

### ISSUE THREAD

**Issue by ba7op** [getsentry/sentry#15802] opened 2019-11-25 14:50 UTC
We have a sentry on premise setup. Some errors are not being properly grouped.
As you can see below, different issues are being created for the errors with the same message, exception type, and stack trace.
I visually compared the details of the two issues, and the only differences are the Event id, timestamp, server name and some fields on additional data.
Any help will be more than appreciated.

![image](https://user-images.githubusercontent.com/57264484/69548980-297ffd00-0f77-11ea-93d7-03821d926237.png)

### issue 305
MESSAGE
`Generic descartes error`
EXCEPTION(most recent call first)
```
AttributeError: 'str' object has no attribute 'is_digit'
  File "lambda_function.py", line 78, in lambda_handler
    criterion['results'] = evaluate(channel_user_id, criterion['file_name'], listing_id)
  File "dashboards_manager.py", line 210, in evaluate
    results = dash5.evaluate(channel_user_id, jobConfig, listingId)
  File "dashboard_5_0.py", line 629, in evaluate
    users[user]["answers"][answer_key]["answer"] = module['logic'](users[user]["answers"])
  File "fdashboard_1140.py", line 830, in scoring_logic
    exp_time = get_max_user_experience_time(user)
  File "fdashboard_1140.py", line 805, in get_max_user_experience_time
    if time_months.is_digit() and int(time_months) > experience_time_months:
```

### issue 306
MESSAGE
`Generic descartes error`
EXCEPTION(most recent call first)
```
AttributeError: 'str' object has no attribute 'is_digit'
  File "lambda_function.py", line 78, in lambda_handler
    criterion['results'] = evaluate(channel_user_id, criterion['file_name'], listing_id)
  File "dashboards_manager.py", line 210, in evaluate
    results = dash5.evaluate(channel_user_id, jobConfig, listingId)
  File "dashboard_5_0.py", line 629, in evaluate
    users[user]["answers"][answer_key]["answer"] = module['logic'](users[user]["answers"])
  File "fdashboard_1140.py", line 830, in scoring_logic
    exp_time = get_max_user_experience_time(user)
  File "fdashboard_1140.py", line 805, in get_max_user_experience_time
    if time_months.is_digit() and int(time_months) > experience_time_months:

```

**Comment by BYK** [comment] 2019-11-25 20:23
@mitsuhiko - any ideas on this?

**Comment by tkaemming** [comment] 2019-11-25 22:58
This might be related to/a duplicate of #5085.

**Comment by ba7op** [comment] 2019-11-26 12:46
In case it's helpful: #5085 case appears to be a 15 mins burst, and thousands of errors being aggregated into just a few groups, where as our errors are being span over several days and are not being grouped at all.

**Comment by ba7op** [comment] 2019-11-26 20:50
We solved this. Although I'm still thing sentry should have grouped the errors.

We had a custom logging handler to send emails on errors. We removed it and it just works now.

No longer a blocker, but in case it help you guys find anything fishy, here's the logger code that was causing the trouble:

```
# -*- coding: utf-8 -*-
import os

import logging
import logging.handlers
try:
	import config
except ImportError:
	pass
    
logging.basicConfig()

server_name = os.environ.get('SERVER_NAME') or "server_name"
username = os.environ.get('SMTP_USERNAME') or "username"
password = os.environ.get('SMTP_PASSWORD') or "password"



class MySMTPHandler(logging.handlers.SMTPHandler):

    # A custom subject can be set by sending an extra param:
    # eg: logger.exception('Unhandled Exception', extra={"subject": "This is my subject 🤓"})
    def getSubject(self, record):
        new_subject = self.subject
        if hasattr(record, "subject"):
            new_subject = new_subject+" - "+record.levelname+" - "+record.subject
        elif record.levelname == "ERROR":
            new_subject = new_subject+" - "+record.levelname+" - "+"New error! 😬 "

        return new_subject


smtp_handler = MySMTPHandler(mailhost=("***", 25),
                    fromaddr="***@holaemi.com",
                    toaddrs="***@holaemi.com",
                    subject="["+server_name+"]",
                    credentials=(username, password),
                    secure=())

smtp_handler.setLevel(logging.ERROR)

logger = logging.getLogger()
logger.addHandler(smtp_handler)
logger.setLevel(logging.INFO)

```
I can close the issue if you want me too.

**Comment by gamefundas** [comment] 2020-04-20 18:36
I am seeing something similar, where the exact same exception gets recorded in different groups. The stack trace is identical. I don't understand how @ba7op was able to solve this by removing the custom hander. To me it seems Sentry should handle this since it must be using a hashing strategy of some sort to identify uniqueness. 

I am using sentry-logback in my case and there is only one server sending logs.

**Comment by ba7op** [comment] 2020-04-21 16:03
I'm not 100% sure that the logging handler was the causing the issue. We also started directly catching and re throwing all the exceptions into a new Exception type (I wasn't aware of this at the time), which fixed the storm of sentry issues.

What appears to be the cause of the issue, in our case, is that we have a lambda that fetches python files from s3, store them as temp files, and run them. The stack trace looks exactly the same in the UI, but there are probably differences that prevents Sentry from grouping them as expected. I recall doing some research at the time and finally trying to set up other group strategies somehow, but with no good results.

Hope this helps.

**Comment by kanai0618** [comment] 2021-02-24 03:09
Hi @ba7op , using logback all tags are not properly setting up whatever i have defined in application.yml eg : 
```
sentry:
      environment : {dev}
```

Can you tell me how to add tags using logback legacy (1.7.0 ) implementation ?

**Comment by lobsterkatie** [comment] 2024-12-10 23:20
I'm going to close this, as it seems like the problem was solved, but feel free to re-open if it comes up again. And for anyone who lands here in the future, to see details of how an event was grouped, look at the Grouping Info section down at the bottom of the page. It will show you exactly which values are being used and why.

**Closed by lobsterkatie** 2024-12-10 23:20 UTC
Labels: Component: Issues
