### ISSUE TITLE
Issue details page not listing all associated replays (only lists the last 14days)

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#62609] opened 2024-01-04 12:29 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open an issue that has replays:
2. Click on the replays tab to see associated replays

### Expected Result

To see the list of associated replays. In the screenshot below the issue has 1 replay but nothing is shown.

### Actual Result

<img width="1203" alt="Screenshot 2024-01-04 at 13 11 24" src="https://github.com/getsentry/sentry/assets/64906376/780f6d22-8e79-4a61-bd88-471a58ddf472">

This is a result of [this line](https://github.com/getsentry/sentry/blob/master/static/app/views/issueDetails/groupReplays/useReplaysFromIssue.tsx#L41) that sets the statsPeriod to 14d. If the issue only has older replays the query does not find any replay, thus no replay is listed:

```
GET https://us.sentry.io/api/0/organizations/dev-curumas/replay-count/?data_source=discover&project=-1&query=issue.id%3A%5B4725219596%5D&returnIds=true&statsPeriod=14d
Response: {}
```

Changing it to 90d, i get one result as expected:

```
GET https://us.sentry.io/api/0/organizations/dev-curumas/replay-count/?data_source=discover&project=-1&query=issue.id%3A%5B4725219596%5D&returnIds=true&statsPeriod=90d
Response:
{
"4725219596": [ "9d524534ef8e4f349c3ffb302063f88d"]
}
```

Suggestion fix: remove the hardcoded 14 days period and use the organisation's retention period (30days for free plans, 90d for paid plans, custom for self-hosted). A more complex idea is to make it (and the counter on the replays tab) reflect the filters currently being used by the user. 

### Product Area

Issues

### Link

https://dev-curumas.sentry.io/issues/4725219596/replays/?project=5278835&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=2

**Comment by bruno-garcia** [comment] 2024-01-09 20:42
This was by design IIRC, to align with another tab (All Events I believe). @ryan953 knows how this works.

Perhaps performance was a concern originally too. I wonder if we could reconsider that decision now.

**Comment by ryan953** [comment] 2024-01-09 21:16
Yes. I think perf and the complexity of the query were two problems with this page. The page makes two queries to collect the list of replays and then for the actual data so it's a bit slow, which you can see in that linked file above [useReplaysFromIssue](https://github.com/getsentry/sentry/blob/master/static/app/views/issueDetails/groupReplays/useReplaysFromIssue.tsx). Also, because of this two-queries thing pagination is extremely hard to implement, so the idea was that we'd keep it simple, remove the date picker, and let the page be a fixed look at related replays.

I don't think the queries are going to be much faster today than before, but i can check on that. The pagination challenge is still there, but we might be able to incrementally load data until the first page is filled up.

**Comment by bruno-garcia** [comment] 2024-01-09 21:25
Thanks for the context @ryan953, makes sense.

> I don't think the queries are going to be much faster today than before, but i can check on that.

Maybe @cmanallen has insight here, since there were improvements [such as these](https://sentry.engineering/blog/lost-in-the-haystack)

**Comment by billyvg** [comment] 2024-12-10 21:01
I think this gets resolved with the new issue details layout. We only count up to 50 replays and show "50+" when more than 50. The replays tab no longer has a count badge and we only show a count in a dropdown.

![Image](https://github.com/user-attachments/assets/0547a8d5-7cce-486a-b392-53cc05c76ddf)

I brought up the discrepancy with the Replays dropdown when changing the date selector and @leeandher has this to say:

> As for the replay tab, its something im working on right now to make the filters (env/date/query) apply to it, but for now it does not — only all events, and attachments. though hopefully that’ll be fixed up soon :fix-it-bufo:

**Closed by billyvg** 2024-12-10 21:01 UTC
Labels: Product Area: Replays
