### ISSUE TITLE
Customer sees fewer User Feedback reports on the new page than on the old page, given the same filter criteria

### ISSUE THREAD

**Issue by yuval-sentry** [getsentry/sentry#70094] opened 2024-05-01 21:07 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Use a project that has good dataset of genuine user feedbacks, open the new and old UI and use the exact same filter criteria, you will see that the number of results don't match.

### Expected Result

Customer expects to see the same reports in either new or old UI.

### Actual Result

Use a project that has good dataset of genuine user feedbacks, open the new and old UI and use the exact same filter criteria, you will see that the number of results don't match.

### Product Area

User Feedback

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2164) by [Unito](https://www.unito.io)

**Comment by bruno-garcia** [comment] 2024-05-03 20:08
Seems related to:
* https://github.com/getsentry/sentry/issues/70138

**Comment by lbernick** [comment] 2024-05-09 14:27
@bruno-garcia I have also observed this happening. in my case, we use two ways of submitting user feedback (both through the [user feedback api endpoint](https://docs.sentry.io/api/projects/submit-user-feedback/)):
- If a crash occurs, we allow someone to submit user feedback and associate it with the event ID of the crash (generated with `sentry.CaptureException`). This seems to show up in both the new and old user feedback UIs.
- The user can also submit feedback at any time. In this case, we call `sentry.CaptureMessage` (via the Go SDK), and associate the user feedback with the newly generated message. This shows up in the old user feedback UI but not the new one.

Is it possible that the new UI is filtering out user feedback associated with sentry "messages" rather than sentry "errors"? Is this intended behavior?

N.B. we haven't been using this feature very long, so we have a limited set of events; I could be wrong about what the cause is for this but I can generate some more events to test this out.

**Comment by bruno-garcia** [comment] 2024-05-10 22:05
could you please provide you org slug? some orgs were flagged as potentially abusing as for blocked so we'd like to check

**Comment by bruno-garcia** [comment] 2024-05-10 22:06
OK please let us know if it seems like data is dropped

**Comment by bruno-garcia** [comment] 2024-09-11 17:53
Closing this since last update was in May and seems resolved.
Feel free to open a new issue if you're experiencing any problems

**Closed by bruno-garcia** 2024-09-11 17:53 UTC
Labels: Sync: Jira, Product Area: User Feedback
