### ISSUE TITLE
Audit log doesn't show that the user was removed

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#77468] opened 2024-09-13 12:42 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Some users experienced that their access to the org was removed, but the audit log doesn't share information on this.

Please check the internal Jira ticket for more information

### Expected Result

the information should show up in the audit log

### Actual Result

the information does not show up in the audit log

### Product Area

Unknown

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2289) by [Unito](https://www.unito.io)

**Comment by shellyvo** [comment] 2024-09-16 18:51
another related ticket here
https://sentry.zendesk.com/agent/tickets/132036

**Comment by huda-kh** [comment] 2024-09-19 00:22
I should note that it is extremely unlikely my membership was removed by the owner of the organisation, and I don't know if it's even possible for a user to disconnect themselves. I think the bug is not in the audits.

**Comment by InterstellarStella** [comment] 2024-09-23 08:41
The affected users and relevant tickets can be found in [the shadow ticket](https://getsentry.atlassian.net/browse/ISSUE-1715).

**Comment by leedongwei** [comment] 2024-09-25 19:19
We have an engineer working on this right now.

**Comment by sentaur-athena** [comment] 2024-10-04 19:37
closing since the issue is fixed and we sent out comms to users about this.

**Closed by sentaur-athena** 2024-10-04 19:37 UTC
Labels: Sync: Jira, Product Area: Settings - Teams
