### ISSUE TITLE
Replay: IP address showing `0.0.0.0` without filter enabled

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#43509] opened 2023-01-20 17:54 UTC
I was getting the server’s IP (I’m tunneling and not forwarding X-Forwarded-For) and now I see 0.0.0.0This is a result of PII stripping added recently, right?
The project doesn’t have any custom filters in Settings. On Security & Privacy tab it doesn’t have Prevent Storing of IP Addresses

![image](https://user-images.githubusercontent.com/1633368/213772257-2ef32efc-a078-45bc-8968-352e91408d0e.png)

<img width="808" alt="image" src="https://user-images.githubusercontent.com/1633368/213772293-c0f59795-8b8f-457a-9ea1-acc203c69a95.png">

<img width="643" alt="image" src="https://user-images.githubusercontent.com/1633368/213772326-be20b3f7-8feb-4b5e-8801-4c2023407b98.png">

### Expected Result

Be able to control IP address stripping

**Comment by nunucardoso** [comment] 2023-01-25 11:21
If the IP is stripped could a tag be used to display some relevant information?

**Comment by zapic0** [comment] 2023-01-26 17:18
Is there a way to title the session? I'd prefer to have datetime or something like that...

**Comment by LKNSI** [comment] 2023-01-27 07:00
Experiencing same result

**Comment by cmanallen** [comment] 2023-01-31 21:53
This is probably a display error.  The data was written to clickhouse correctly.  If the issue re-appears after we deploy let me know!

**Comment by cmanallen** [comment] 2023-01-31 22:21
Did anyone in this issue (other than Bruno) have ip-address scrubbing disabled and saw this behavior?  E.g. we returned an empty ip (0.0.0.0) but you expected the user's ip-address to be present?

**Comment by cmanallen** [comment] 2023-02-01 15:53
Hey everyone.  We think we've solved the problem and hopefully we'll have something deployed soon.  The two relevant PRs are linked to this issue.  tl;dr we weren't handling ip-addresses properly on ingest and we were not returning them properly on the HTTP API.

Going forward you'll see the ip-addresses populated.  If you enabled ip-address scrubbing you should see a pleasing fallback identifier.  Unfortunately, because this was an ingest error, your historical replays will not have an ip-address associated and will have to use the fallback.  Sorry about that!

If the problem persists (once this issue is closed) please feel free to re-open this one or create a new one.

**Comment by lforst** [comment] 2023-02-06 21:03
I am seeing this in a project of mine too. I can help reproduce if necessary.

**Comment by nunucardoso** [comment] 2023-02-07 09:09
I am also seeing the initial issue reported. I was trying to understand where the ip stripping is done but I believe my project is not stripping it. Can someone look into this?

**Comment by bruno-garcia** [comment] 2023-02-09 13:50
@cmanallen did the fix get shipped? I can also reproduce it. Example: https://nugettrends.sentry.io/settings/projects/spa/security-and-privacy/
https://nugettrends.sentry.io/replays/?query=duration%3A%3E%3D5

**Comment by cmanallen** [comment] 2023-02-09 15:06
@bruno-garcia No it unfortunately hasn't shipped yet.  This issue unfortunately auto-closed when on PR was merged.  There's a PR on getsentry/relay that needs to be merged.

**Comment by cmanallen** [comment] 2023-02-09 15:07
This is the pull that will fix the ip-address issue for anyone whose interested in following the progress: https://github.com/getsentry/relay/pull/1805

**Closed** 2023-02-10 13:42 UTC
Labels: Type: Bug, Status: Backlog, Team: Replay

**Comment by cmanallen** [comment] 2023-02-10 14:59
Should be done.  We'll get `0.0.0.0` values  translated to something more useful soon.  But I think the issue of all the ip-addresses being this value should be solved.
