### ISSUE TITLE
Sentry 7.3.2 + OperationalError: (2006, 'MySQL server has gone away')

### ISSUE THREAD

**Issue by jie** [getsentry/sentry#1441] opened 2015-02-27 09:37 UTC
Any idea about this, thx.

[ERROR] Error processing 'get_rules' on 'JavascriptPlugin': (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sentry/utils/safe.py", line 25, in safe_execute
    with transaction.atomic():
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 280, in **enter**
    connection.set_autocommit(False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/**init**.py", line 340, in set_autocommit
    self._set_autocommit(autocommit)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 461, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 461, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 243, in autocommit
    _mysql.connection.autocommit(self, on)
OperationalError: (2006, 'MySQL server has gone away')

**Comment by dcramer** [comment] 2015-02-27 17:22
Your MySQL server is dropping the connection

**Comment by vaal-** [comment] 2015-02-27 18:04
I have the same problem with last version.
Version 6.4.4 works fine on the same server, with the same base.

**Comment by dcramer** [comment] 2015-02-27 18:07
I assume this is happening in workers only? If so it would seemingly appear possible that the connection has been open too long, but that's not supposed to be true as it's supposed to get closed frequently.

We should be seeing this in Postgres too though, so I'm not certain this is actually a Django issue.

**Comment by vaal-** [comment] 2015-02-27 18:15
A workers = handlers incoming events? It seems that yes.
Sentry web interface works, but in the logs recorded this error when it comes to any event (404 for example).


p.s. sorry for my english

**Comment by dcramer** [comment] 2015-02-27 18:15
Workers are the Celery workers which are processing the async tasks.

**Comment by vaal-** [comment] 2015-02-27 18:20
I'm not sure whose it is logs. I run Sentry by supervisor, and errors are written to the log supervisor.

**Comment by jie** [comment] 2015-02-28 02:02
I figure out it after remove WAIT_TIMEOUT settings in my.ini

https://code.djangoproject.com/ticket/21597

**Comment by christophlehmann** [comment] 2015-03-01 13:53
I have the same error too. events are accepted, but not displayed in the webinterface...

Is there a hotfix?

**Comment by guoqiao** [comment] 2015-03-05 06:49
I install sentry on 2 servers today, both have this issue.

**Comment by sixdays** [comment] 2015-03-05 13:47
Same problem here:

Raven sends errors. Sentry gets them and raven displays a msg ID. 
On sentry-web some errors are shown, others are not. The counter to the left is always at one. 
If I search for an ID that isn't shown, it appears. 

If I click clear on the "SINCE" dropdown, It shows them. WIth a counter of 1. 

If I click resolve on a "hidden" item, it pops back up if I give it an error again. Regardless how many times, the counter remains at 1.

Database is Amazon RDS. I will try and see if it is possible to do "jie"'s WAIT_TIMEOUT fix.

**Comment by sixdays** [comment] 2015-03-05 14:13
Check the value on the RDS, it 28800 seconds (8hrs).
Seems strange that it should be the cause of this.

**Comment by sixdays** [comment] 2015-03-09 10:46
Made some progress. 
Commented out
SENTRY_BUFFER and SENTRY_BUFFER_OPTIONS

Now regression works. Counter is increasing, messages are shown. 

But there is a mail problem, if counter is 99 and marked as resolved it will increment to 100, set the status as new/unresolved and send a mail. 

If it gets another hit it will increment to 101 but no new mail will be sent. Ever. 

If I resolve the issue it will send a mail if it is triggered again. 

I don't know if this is a bug, miss-configuration or if this is the intended way sentrys mail alert works?

**Comment by dcramer** [comment] 2015-03-09 17:56
We only send events based on rules, and the default rules are for regression or brand new events.

**Comment by sixdays** [comment] 2015-03-10 16:37
Ok. What counts as a regression? Is that if the problem has been marked as resolved and then pops up again? 

I think I was thinking on "escalation" (english is not my native language).

**Comment by dcramer** [comment] 2015-03-10 17:02
Yeah a regression is resolved => unresolved (its seen after it was resolved).

**Comment by habitissimo** [comment] 2015-03-18 13:18
I have the same problem, after upgrading from Sentry 6.4.4 to 7.4.1 connecting to a mysql database with a wait_timeout of 1200.

**Comment by servomac** [comment] 2015-03-18 13:19
I have the same problem, after the upgrade from a Sentry 6.4.4 to 7.4.1. I'm using a mysql server with a wait_timeout of 600.

**Comment by dcramer** [comment] 2015-03-18 20:57
Can I get someone to try this:

http://stackoverflow.com/questions/26958592/django-after-upgrade-mysql-server-has-gone-away

**Comment by SLv99** [comment] 2015-03-19 10:58
Same error with Sentry 7.4.1. I added wait_timeout = 10 and interactive_timeout = 10 to my mysql config, but it's still not working.

**Comment by anka-sirota** [comment] 2015-03-19 17:18
Same error while running `sentry upgrade` with Sentry 7.4.1 

Settings CONN_MAX_AGE to a value lower then MySQL 'wait_timeout', or to 0 to disable persistent connections doesn't help

**Comment by dcramer** [comment] 2015-03-19 17:39
@anka-sirota you are hitting the timeout on sentry upgrade?

**Comment by anka-sirota** [comment] 2015-03-19 17:48
@dcramer yes

My issue has just solved itself after mysql instance has been restarted.
Though there was nothing wrong with mysql, it was working with sentry 6.5.x right before `pip install sentry --upgrade`

**Comment by LeaFin** [comment] 2015-03-24 15:50
I got the same problem after upgrading to 7.4.1. I set CONN_MAX_AGE. The error occurs as soon as i call /organizations/org/stats/.
Here i got the errors "There was an error loading statistics." and "There was an error loading project data."

**Comment by tarjei** [comment] 2015-04-08 07:50
Hi, I'm getting this problem as well. 

This is when running the web interface, NOT celery.

**Comment by meteozond** [comment] 2015-04-08 12:44
Same for me (7.4.2), 6.4.4 runs fine. It's quite strange, sentry (or django?) requests connection close itself just after the autocommit=0/commit, autocommit=1/commit sequence. No packet loss or timeout.

![Strange](http://i.gyazo.com/9eb354e2080f98c76daf9fe648c74d96.png)

**Comment by tarjei** [comment] 2015-04-08 17:36
Could this be a library issue? I.e. that it is solved by upgrading Django or MySQL-python?

**Comment by tarjei** [comment] 2015-04-09 04:39
Update: By adding logging[1] I found out that my main problem was that I was missing ALLOWED_HOSTS[2].  Now at least I got sentry up and answering my requests :)

Also, I ended up switching to postgres. That might come back and bite my tail.

1. http://ianalexandr.com/blog/getting-started-with-django-logging-in-5-minutes.html
2. http://getluky.net/2013/02/21/django-debugfalse-and-allowed_hosts/

**Comment by meteozond** [comment] 2015-04-09 05:28
@tarjei, I confirm, ALLOWED_HOSTS fixes the problems, I can see login page. But now I see error messages from JavascriptPlugin in console.

    [ERROR] Error processing 'get_rules' on 'JavascriptPlugin': (2006, 'MySQL server has gone away')
    Traceback (most recent call last):
      File "/var/www/sentry/env/local/lib/python2.7/site-packages/sentry/utils/safe.py", line 25, in safe_execute
        with transaction.atomic():
      File "/var/www/sentry/env/local/lib/python2.7/site-packages/django/db/transaction.py", line 280, in __enter__
        connection.set_autocommit(False)
      File "/var/www/sentry/env/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 340, in set_autocommit
        self._set_autocommit(autocommit)
      File "/var/www/sentry/env/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 461, in _set_autocommit
        self.connection.autocommit(autocommit)
      File "/var/www/sentry/env/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "/var/www/sentry/env/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 461, in _set_autocommit
        self.connection.autocommit(autocommit)
      File "/var/www/sentry/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 243, in autocommit
        _mysql.connection.autocommit(self, on)

**Comment by meteozond** [comment] 2015-04-09 06:12
As I see `JavascriptPlugin` is only `lang` plugin in a default `INSTALLED_APPS` configuration. Removing it takes away exceptions. Adding it back gives me random `JavascriptPlugin` exceptions without any JavaScript messages sent to the sentry from browser.

**Comment by tarjei** [comment] 2015-04-09 07:17
Is JAvascriptPlugin needed if I want to use Raven-js?

2015-04-09 8:13 GMT+02:00 Alexander Klimenko <notifications@github.com>:

> As I see JavascriptPlugin is only lang plugin in a default INSTALLED_APPS
> configuration. Removing it takes away exceptions. Adding it back gives me
> random JavascriptPlugin exceptions without any JavaScript messages sent
> to the sentry from browser.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getsentry/sentry/issues/1441#issuecomment-91124992>.
>



-- 
__________________
Tarjei Huse
Mobil: 920 63 413

**Comment by yadongwen** [comment] 2015-04-23 09:07
Got the same error following the QuickStart document.

```
Performing upgrade before service startup...
Loading help page tagging.md
Loading help page sampling.md
Loading help page organizations.md
Loading help page teams_and_projects.md
Loading help page quotas.md
Running service: 'http'
[2015-04-23 09:03:18 +0000] [39056] [INFO] Starting gunicorn 19.3.0
[2015-04-23 09:03:18 +0000] [39056] [INFO] Listening at: http://0.0.0.0:9000 (39056)
[2015-04-23 09:03:18 +0000] [39056] [INFO] Using worker: sync
[2015-04-23 09:03:18 +0000] [39065] [INFO] Booting worker with pid: 39065
[2015-04-23 09:03:18 +0000] [39066] [INFO] Booting worker with pid: 39066
[2015-04-23 09:03:18 +0000] [39067] [INFO] Booting worker with pid: 39067
[ERROR] Error processing 'get_rules' on 'JavascriptPlugin': (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/utils/safe.py", line 25, in safe_execute
    with transaction.atomic():
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/transaction.py", line 280, in __enter__
    connection.set_autocommit(False)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 340, in set_autocommit
    self._set_autocommit(autocommit)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 461, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 461, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/www/sentry/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 243, in autocommit
    _mysql.connection.autocommit(self, on)
OperationalError: (2006, 'MySQL server has gone away')
```

**Comment by realityking** [comment] 2015-04-29 16:05
@dcramer 
We're also seeing this problem using 7.4.3. We've reduced CONN_MAX_AGE all the way down to 600 but it still happens in the Web Interface.  I can trigger the stack trace seconds after start up simply by opening the Web Interface.

Here's our stack trace. 
```
[2015-04-29 16:10:56 +0000] [24765] [INFO] Starting gunicorn 19.3.0
[2015-04-29 16:10:56 +0000] [24765] [INFO] Listening at: http://0.0.0.0:8000 (24765)
[2015-04-29 16:10:56 +0000] [24765] [INFO] Using worker: sync
[2015-04-29 16:10:56 +0000] [24783] [INFO] Booting worker with pid: 24783
[2015-04-29 16:10:56 +0000] [24784] [INFO] Booting worker with pid: 24784
[2015-04-29 16:10:56 +0000] [24785] [INFO] Booting worker with pid: 24785
[ERROR] Error processing 'load_user_conf' on 'SentryLocaleMiddleware': (2014, "Commands out of sync; you can't run this command now")
Traceback (most recent call last):
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/utils/safe.py", line 26, in safe_execute
    result = func(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/transaction.py", line 359, in __exit__
    connection.set_autocommit(True)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 340, in set_autocommit
    self._set_autocommit(autocommit)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 461, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 461, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/www/sentry/local/lib/python2.7/site-packages/MySQL_python-1.2.5-py2.7-linux-x86_64.egg/MySQLdb/connections.py", line 243, in autocommit
    _mysql.connection.autocommit(self, on)
ProgrammingError: (2014, "Commands out of sync; you can't run this command now")
[ERROR] Error processing 'get_rules' on 'JavascriptPlugin': (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/utils/safe.py", line 25, in safe_execute
    with transaction.atomic():
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/transaction.py", line 280, in __enter__
    connection.set_autocommit(False)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 340, in set_autocommit
    self._set_autocommit(autocommit)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 461, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 461, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/www/sentry/local/lib/python2.7/site-packages/MySQL_python-1.2.5-py2.7-linux-x86_64.egg/MySQLdb/connections.py", line 243, in autocommit
    _mysql.connection.autocommit(self, on)
OperationalError: (2006, 'MySQL server has gone away')
[ERROR] Error processing 'load_user_conf' on 'SentryLocaleMiddleware': (2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/utils/safe.py", line 25, in safe_execute
    with transaction.atomic():
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/transaction.py", line 280, in __enter__
    connection.set_autocommit(False)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 340, in set_autocommit
    self._set_autocommit(autocommit)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 461, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/www/sentry/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 461, in _set_autocommit
    self.connection.autocommit(autocommit)
  File "/www/sentry/local/lib/python2.7/site-packages/MySQL_python-1.2.5-py2.7-linux-x86_64.egg/MySQLdb/connections.py", line 243, in autocommit
    _mysql.connection.autocommit(self, on)
OperationalError: (2006, 'MySQL server has gone away')
```

Any other ideas?

**Comment by freefcw** [comment] 2015-05-06 05:47
I meet this problem 2, But when I use domain instead of ip, the web access is ok

**Comment by AGovorukha** [comment] 2015-05-12 14:44
the same problem.

**Comment by TheSavior** [comment] 2015-05-21 00:48
I'm running into this as well. Keeps us from getting our server set up at all with MySQL.

**Comment by mbrunthaler** [comment] 2015-05-22 13:02
This may also be related to the maximum allowed packet size for mysql. Increasing the default solved the issue for us:

```conf
[mysqld]
max_allowed_packet = 16M
```

**Comment by dcramer** [comment] 2015-05-26 05:52
To be very clear, if someone has a fix for this, we'll happily support it, but we (the Sentry team) do not support MySQL. I've spent several spare hours trying to find a resolution for this, and while it's most certainly related to Django's persistent connections, there's nothing obvious to me on how to fix it.

**Comment by gibas** [comment] 2015-05-28 18:50
I have had this problem also with version 7.5.2, but with newest version 7.5.3 I cannot reproduce it now. Sentry is working fast as always, without any problems in log files.

**Comment by decklord** [comment] 2015-05-29 20:06
I can reproduce the error with version 7.5.3.

**Comment by dcramer** [comment] 2015-05-29 20:07
7.5.3 is the same as 7.5, is the same as 7.0 which introduced Django 1.6 which likely is what introduced this behavior.

Patches still welcome.

**Comment by dcramer** [comment] 2015-06-29 20:14
FYI I'd like to get this resolved. I personally dont have much free time to own this, and as I mentioned before we don't use MySQL ourselves.

If there's any support/help needed we're happy to provide it. Generally we're always on IRC in the #sentry room (freenode).

**Comment by vitaliyf** [comment] 2015-07-10 01:46
I've been experimenting with various things over the past few weeks.. 

Couple days ago I hacked this into sentry/utils/safe.py:
```
def safe_execute(func, *args, **kwargs):
    ...
        if _with_transaction:
            django.db.close_connection()   # <-- here
            with transaction.atomic():
```

that seemed to make problems go away until tonight.  I am seeing these in sentry logs:

```
Traceback (most recent call last):
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/sentry/utils/logging.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/sentry/event_manager.py", line 356, in save
    event.save()
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 902, in execute_sql
    for sql, params in self.as_sql():
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 860, in as_sql
    for obj in self.query.objs
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 350, in get_db_prep_save
    prepared=False)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 342, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/sentry/db/models/fields/node.py", line 127, in get_prep_value
    value.id = app.nodestore.create(value.data)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/sentry/nodestore/base.py", line 22, in create
    self.set(node_id, data)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/sentry/nodestore/django/backend.py", line 42, in set
    'timestamp': timezone.now(),
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/sentry/db/models/query.py", line 69, in create_or_update
    affected = objects.filter(**kwargs).update(**defaults)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/django/db/models/query.py", line 493, in update
    rows = query.get_compiler(self.db).execute_sql(None)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 980, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 776, in execute_sql
    sql, params = self.as_sql()
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 945, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 350, in get_db_prep_save
    prepared=False)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 342, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/sentry/db/models/fields/gzippeddict.py", line 50, in get_prep_value
    return compress(pickle.dumps(value))
RuntimeError: maximum recursion depth exceeded while pickling an object
```
and netstat is showing tens of thousands TIME_WAIT connections to 3306.  Presumably, Sentry was spamming the hell out of MySQL, perhaps from within recursive call?

**Comment by vitaliyf** [comment] 2015-07-10 01:47
Found this in logs as well:

```
Traceback (most recent call last):
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/raven/utils/serializer/manager.py", line 69, in transform
    return serializer.serialize(value, **kwargs)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/raven/utils/serializer/base.py", line 73, in serialize
    in itertools.takewhile(lambda x: x[0] < list_max_length, enumerate(value))
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/raven/utils/serializer/base.py", line 72, in <genexpr>
    for n, o
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/raven/utils/serializer/base.py", line 62, in recurse
    return self.manager.transform(value, max_depth=max_depth, _depth=_depth, **kwargs)
  File "/opt/sentry.eng.upsight.com/env/lib/python2.7/site-packages/raven/utils/serializer/manager.py", line 71, in transform
    logger.exception(e)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1182, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1175, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1267, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1241, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/usr/lib64/python2.7/logging/__init__.py", line 266, in __init__
    self.levelname = getLevelName(level)
  File "/usr/lib64/python2.7/logging/__init__.py", line 167, in getLevelName
    return _levelNames.get(level, ("Level %s" % level))
RuntimeError: maximum recursion depth exceeded while getting the str of an object
```

**Comment by ye** [comment] 2016-04-07 16:20
Re: [MySQL support](#issuecomment-105406091)

> ... but we (the Sentry team) do not support MySQL. ...

@dcramer Care to elaborate why Sentry doesn't officially support MySQL?

**Comment by mattrobenolt** [comment] 2016-04-07 17:05
@ye It's mostly because of issues like this that we don't have the capacity to resolve effectively.

With that said, users do maintain running MySQL, but there are generally issues with migrations, which require someone to manually intervene. But we don't go out of our way to break MySQL, we just only battle test again PostgreSQL exclusively.

If bugs pop up related to MySQL, we do accept patches and will help provide assistance and support, but since we don't run it ourselves, it's hard to "officially" support it.

**Comment by ye** [comment] 2016-04-07 17:45
@dcramer That's fair and I suspected exactly so as [this](#1441) and [that](#316), etc since MySQL still has tons of quirks (e.g.[1],[2]) to be a solid RDMS like PostgreSQL does.

As much as I love PostgreSQL much more personally, please don't forget MySQL is [**still predominantly popular**](http://db-engines.com/en/ranking) out there. For instance, [GCP doesn't even offer non-MySQL for their SQL offering](https://cloud.google.com/sql/) as of this writing, **unfortunately**. And as we all witnessed, the non-official MySQL support (aka community support) is sporadical at best (when was this ticket first opened? How long has it been opened?).

Let me give you another reason to reconsider: I have been googling around for the past few days and was go though all the documentations and was able to tweak [the official docker receipt](https://hub.docker.com/_/docker/) to get MySQL integration sort of working: migrations ran, WebUI is loading okay except it keeps kicking me back to this welcome screen/setup dialog:
![setup-dialog](https://cloud.githubusercontent.com/assets/133924/14360899/745d06b4-fcc6-11e5-884f-cc99306a6140.png). Now what do I do? I could go on to IRC but I am sure people would probably tell to use PostgreSQL and be done with it; or I could enter an issue here but will you (the Sentry team) be willing to dedicate time to help resolve? And I am sure I am not the only one who encounter roadblocks like these ... frustrated? You bet!  


[1] http://stackoverflow.com/questions/6578777/
[2] http://stackoverflow.com/questions/1814594#1814594

**Comment by dcramer** [comment] 2018-11-13 21:11
Old issue is old.

**Closed by dcramer** 2018-11-13 21:11 UTC
