### ISSUE TITLE
not getting any events

### ISSUE THREAD

**Issue by nadihagh** [getsentry/sentry#22999] opened 2021-01-09 17:33 UTC
I'm running sentry On-Premise, the problem is sentry web panel not updating for 10 hours, I watched all logs of docker containers, there were no error,
restarted all containers (docker-compose down ; docker-compose up -d) and the problem still exists,
how can I find out where the problem is?

**Comment by lufylegend** [comment] 2021-01-11 06:26
me too

**Comment by CNMathon** [comment] 2021-01-11 07:13
me too

**Comment by lloydowen** [comment] 2021-01-17 23:48
I'm also getting this from a clean install of sentry on-premise.

Using the bash CLI tool:
```
curl -sL https://sentry.io/get-cli/ | bash
export SENTRY_DSN=https://a15a5cef24a9478992ea8b455c4709c1@********/2
sentry-cli send-event -m "Something happened"

950904ea-64aa-4d74-90e9-e73ad96d9b96
```
I get a GUID in the response, but nothing showing in the quotas in the admin panel & no events under the project.

**Comment by BYK** [comment] 2021-01-19 21:08
Closing as a duplicate of getsentry/onpremise#805

@nadihagh please refrain from double-posting across repositories.

**Comment by BYK** [comment] 2021-01-19 21:08
@lloydowen you need to file a new issue and follow the issue template to provide us the necessary information to help you such as the sentry version you are using and the log outputs.

**Closed by BYK** 2021-01-19 21:08 UTC
