### ISSUE TITLE
When showing raw stack trace, it errors "There was an error loading data."

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry#48763] opened 2023-05-09 05:45 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I have been seeing this for a long time in my sentry panel. When enabling "raw stack trace", it errors like:

![image](https://user-images.githubusercontent.com/5236035/237004938-ca1d98de-a154-419d-9ccc-9662bfdfda18.png)

### Expected Result

no error

### Actual Result

has error

### Product Area

Unknown

**Comment by armenzg** [comment] 2023-05-11 16:18
Hi @fzyzcjy do you have a link to one of your issues so I can have a look?

**Comment by fzyzcjy** [comment] 2023-05-11 23:38
@armenzg It is private project. Can you look at it?

**Comment by fzyzcjy** [comment] 2023-05-11 23:42
In addition, it would be great if I could send it to (e.g.) your private email since showing it on github may leak information IMHO

**Comment by armenzg** [comment] 2023-05-12 11:52
If you provide the project ID and group ID I can go have a look (instead of sharing the full URL).

For instance, for a URL like this, if you give me 4171878154 and 11276 I can figure out your org slug and the specific issue you want me to look at:
https://sentry.sentry.io/issues/4171878154/?project=11276

If you would rather share the information privately, you can do so by clicking on Help -> Contact Support -> type something -> Contact Support and then Product & Technical Support. This will create a private Zendesk ticket. Customer support would then share that link with me.
<img width="279" alt="image" src="https://github.com/getsentry/sentry/assets/44410/d4eb4fbc-b432-49e7-bc9c-7f4683b7fc32">
<img width="623" alt="image" src="https://github.com/getsentry/sentry/assets/44410/9a532f8c-fec0-4362-8ab8-57f480757d17">
<img width="359" alt="image" src="https://github.com/getsentry/sentry/assets/44410/7f7c9155-5f6d-44d9-b10d-1fd7a1a325de">

**Comment by fzyzcjy** [comment] 2023-05-12 14:45
@armenzg Thanks, I have sent it through zendesk, and mentioned this github issue as well.

Do I need to give explicit permission (e.g. tick some boxes?) to you such that you can see that issue, or you already can see all issues and I do not need to do anything?

**Comment by armenzg** [comment] 2023-05-12 19:50
All good. I will look at it next week. Thank you!

**Comment by fzyzcjy** [comment] 2023-05-12 23:41
You are welcome!

**Comment by armenzg** [comment] 2023-05-18 17:17
@fzyzcjy I can reproduce your issue. Thanks for taking the time to file it!

I'm consulting others and get back to you once I hear back.

**Comment by fzyzcjy** [comment] 2023-05-18 23:09
@armenzg You are welcome and looking forward to the fix!

**Comment by mrduncan** [comment] 2024-10-28 16:36
I'm going to close this issue due to it's age, please reopen if you're able to reproduce.

**Closed by mrduncan** 2024-10-28 16:36 UTC
Labels: Type: Bug, Product Area: Issues
