### ISSUE TITLE
[Mobile Replay - Bug] Video player flickering when pressing play/pause

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry#75635] opened 2024-08-06 14:49 UTC
The video flickers (like starts from a different segment) when pressing play/pause. Can be reproduced with this replay: https://sentry-sdks.sentry.io/replays/a10c2b45083e4bc7bf347b6bd5d18bee/?project=5428559&query=&referrer=%2Freplays%2F%3AreplaySlug%2F&statsPeriod=7d&yAxis=count%28%29&t=0

https://github.com/user-attachments/assets/d6a69356-7ea2-47a0-98e4-fafa75527c4b

**Comment by c298lee** [comment] 2024-09-19 20:21
Duplicate of https://github.com/getsentry/team-replay/issues/465 and has been fixed by https://github.com/getsentry/sentry/pull/77018

**Closed by c298lee** 2024-09-19 20:21 UTC
