### ISSUE TITLE
KeyError: u'properties' when sentry celery worker

### ISSUE THREAD

**Issue by timeseer** [getsentry/sentry#2548] opened 2016-01-13 23:56 UTC
I got this message when I ran background worker for sentry via command `sentry celery worker`.

```
[2016-01-13 23:52:31,942: WARNING/MainProcess] celery@CentOS-7 ready.
[2016-01-13 23:52:32,079: ERROR/MainProcess] Unrecoverable error: KeyError(u'properties',)
Traceback (most recent call last):
  File "/home/user/.virtualenvs/sentry/lib/python2.7/site-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/home/user/.virtualenvs/sentry/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/user/.virtualenvs/sentry/lib/python2.7/site-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/home/user/.virtualenvs/sentry/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/home/user/.virtualenvs/sentry/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/home/user/.virtualenvs/sentry/lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/home/user/.virtualenvs/sentry/lib/python2.7/site-packages/celery/worker/loops.py", line 70, in asynloop
    next(loop)
  File "/home/user/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
  File "/home/user/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/transport/redis.py", line 972, in on_readable
    self._callbacks[queue](message)
  File "/home/user/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 532, in _callback
    message = self.Message(self, raw_message)
  File "/home/user/.virtualenvs/sentry/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 242, in __init__
    properties = payload['properties']
KeyError: u'properties'
```

Sentry version is 8.0.1.
`sentry start` and `sentry celery beat` are working fine.

```
(sentry) ✔ user  ~/repo  pip freeze | grep sentry
sentry==8.0.1
(sentry) ✘ user  ~/repo  pip freeze | grep celery
celery==3.1.18
```

T_T

**Comment by timeseer** [comment] 2016-01-14 01:41
I don't know who have responsibility about this issue. Maybe it can be my environment, sentry or celery.

Anyway, when I was debugging for this issue, I found celery consumer got below `payload`.
```
{
    "bd\u0000\u0000": "eyJzd19zeXMiOiAiTGludXgiLCAiY2xvY2siOiAyLCAidGltZXN0YW1wIjogMTQ1MjczMzYwNy4xMDU1MzksICJob3N0bmFtZSI6ICJjZWxlcnlAQ2VudE9TLTciLCAicGlkIjogNjY2MSwgInN3X3ZlciI6ICIzLjEuMTgiLCAidXRjb2Zmc2V0IjogMCwgImxvYWRhdmciOiBbMC41NywgMC41NCwgMC41N10sICJwcm9jZXNzZWQiOiAwLCAiYWN0aXZlIjogMCwgImZyZXEiOiAyLjAsICJ0eXBlIjogIndvcmtlci1oZWFydGJlYXQiLCAic3dfaWRlbnQiOiAicHktY2VsZXJ5In0=",
    "cnetecdn\u0000\u7f6d\u0001\u0000\u4660\u0000\u0002\u0000": "utf-8",
    "cnettp\u0000\u0000bd_n": "application/json",
    "haespr\u0000": {
        "hostname": "celery@CentOS-7"
    },
    "poete\u0000lclo": {
        "body_encoding": "bs6\u0000ha",
        "delivery_mode": 2,
        "delivery_tag": "15929def-6694-47c7-991c-f1e9f40ea60f",
        "dlvr_no\u0000cnett": {
            "exchange": "celeryev",
            "pirt\u0000\u0000po": 0,
            "routing_key": "worker.heartbeat"
        }
    }
}
```

`poete\u0000lclo` which is key of `payload` should be `properties` in normal case. Other keys and values in `payload` dictionary are broken too. And this seems like same phenomenon which occurred in #2546.

Sorry for my bad English.

**Comment by timeseer** [comment] 2016-01-14 03:00
<img width="609" alt="2016-01-14 11 49 29" src="https://cloud.githubusercontent.com/assets/16537998/12314499/fd5f6f5a-bab4-11e5-8b6b-4e3220b12ed5.png">

Email address which I input during install progress is broken at sentry start page.
And I got this message from chrome debug console.

<img width="909" alt="2016-01-14 11 56 27" src="https://cloud.githubusercontent.com/assets/16537998/12314624/113e2808-bab6-11e5-9b53-0aaaab1643fc.png">
```
Uncaught RavenConfigError: Invalid DSN: ://fd50c577cd6a45c2a307bff9ff6a9603@/1
"\uD8C0\uDC61\uDA00\uDC6D\uDA00\uDC6E\uD8C0\uDC73\uD800\uDC72\uDB80\uDC74\uDBC0\uDC72\uD800\uDC6D\uD800\uDC6E\uDB40\uDC61\uDBC0\uDC73\uD880\uDC61e\uFFFD\uD8DA\uDD70\u7F5F\uDBD1\uDC70\u7F5F\uDBBF\uDFFD\uDBBF\uDFFF\uD90E\uDDA8\uDB6C\uDE63\u0001\uFFFD\uDB02\uDF00" is not a valid email address.
```

My system locale is ko_KR.UTF-8.

**Comment by mattrobenolt** [comment] 2016-01-15 20:45
@timeseer I'm not sure what's going on here, but it looks like there's something severely misconfigured with your OS and I'm not sure what the problem is.

Basically everything is being handled with a wrong encoding.

/cc @mitsuhiko thoughts?

**Comment by dcramer** [comment] 2016-01-21 18:34
Can we confirm the system locale isnt the issue? We run utf-8 locale, but definitely not ko_KR. I'm closing this out unless we come up with something more actionable, and I'd suggest we approach resolving this simply by enforcing the OS (Ubuntu) and suggesting Docker.

**Closed by dcramer** 2016-01-21 18:34 UTC
