### ISSUE TITLE
Alert for Metric won't load

### ISSUE THREAD

**Issue by bmulholland** [getsentry/sentry#70930] opened 2024-05-15 10:57 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

We created an alert for a metric a while ago, and now we can't view or change it.

To repro, just open https://recital.sentry.io/alerts/metric-rules/recital-backend/237346/#

### Expected Result

Page loads

### Actual Result

Infinite spinner

### Product Area

Alerts

### Link

https://recital.sentry.io/alerts/metric-rules/recital-backend/237346/#

### DSN

https://dcb648f7653e49c4b47e2eb60946c479@o419267.ingest.us.sentry.io/5495041

**Comment by ceorourke** [comment] 2024-05-15 16:46
This is a duplicate of https://github.com/getsentry/sentry/issues/70730 so I'm going to close this, but we are looking into it!

**Closed by ceorourke** 2024-05-15 16:46 UTC
Labels: Product Area: Alerts, Waiting for: Product Owner
