### ISSUE TITLE
user misery not consistent between dashboard widget and performance all transactions user misery graph

### ISSUE THREAD

**Issue by rudi-cilibrasi** [getsentry/sentry#33555] opened 2022-04-12 20:09 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Instrument a simple react FE site with sentry. look at user misery number in dashboard. compare to user misery graph in performance all transactions graph. notice they are very different and do not converge over time even checking several times a day.

in our website we see 0.05 in the performance all transactions graph.
in our user misery dashboard number we see 0.22
why aren't these numbers ever consistent?

### Expected Result

expected to see approximately or exactly the same numbers on the user misery dashboard widget and user misery graph under performance | all transactions for a specific project in a specific environment.

already noticed dashboard widget threshhold ms could be different than project settings ms threshhold but we checked to make sure both are set identically.

### Actual Result

in our website we see 0.05 in the performance all transactions graph.
in our user misery dashboard number we see 0.22

**Comment by masinette** [comment] 2022-04-13 17:43
Duplicate of https://github.com/getsentry/sentry/issues/33555

**Comment by masinette** [comment] 2022-04-13 17:43
https://github.com/getsentry/sentry/issues/33556

**Comment by silent1mezzo** [comment] 2022-04-14 15:39
So, I actually think this is an underlying usability issue. By default, the performance homepage will set your user misery as 4x the value set (https://sentry.io/settings/{org_slug}/projects/{project name}/performance/). Dashboards defaults user_misery to 300, if you multiple this by 4 it should get you the number. Again, sending a [support case](https://github.com/getsentry/sentry/issues/33556#issuecomment-1099306881) through will help me look into the data.

**Closed** 2023-02-22 22:00 UTC
Labels: Type: User Feedback, Status: Backlog, Team: Visibility
