### ISSUE TITLE
Saving an alert with a Slack channel ID does not seem to work

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#48861] opened 2023-05-10 13:40 UTC
The screenshot shows that I was not able to save the alert with just the channel ID.
This is necessary when a channel name or user name is not found when paginating through the Slack API and Slack does not let us paginate anymore (e.g. there are too many channels and users).

Some [related work](https://github.com/getsentry/sentry/pull/37121) that may be able to help get this work started for whoever picks this up.

![image](https://github.com/getsentry/sentry/assets/44410/767b1fd2-4582-4555-9ba9-9a4b0630174c)

**Comment by scefali** [comment] 2023-05-25 19:46
@armenzg are you sure that's not because the name is empty? I can't tell from the screenshot.

**Comment by ceorourke** [comment] 2023-05-25 20:23
I looked at this a bit and then double checked the docs: https://docs.sentry.io/product/integrations/notification-incidents/slack/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2F# not sure why in my memory you _only_ entered the channel ID, but you need to enter both. It works for me when I enter both, and I get the same error as you @armenzg when I only do the ID. Seems like it's working as intended :)

**Comment by ceorourke** [comment] 2023-06-07 23:13
Gonna close this as working as intended unless there's something else I missed, feel free to reopen!

**Closed by ceorourke** 2023-06-07 23:13 UTC
Labels: Component: Integrations, Status: Backlog, Scope: Backend, Product Area: Settings - Integrations

**Comment by golimer** [comment] 2023-06-15 06:46
hello guys still getting error Too Many Requests
`"container_name":"/worker","source":"stdout","log":"06:36:05 [INFO] sentry.integrations.client: integration.http_response (integration='slack' status_string='429' error='429 Client Error: Too Many Requests for url: https://slack.com/api/conversations.list?exclude_archived=False&exclude_members=True&types=public_channel%2Cprivate_channel&cursor=dGVhbTpDMDNQVUw5ME1HVw%3D%3D&limit=1000')","container_id":"c6e129fa9a33df887a0c7b1439f5b9d0c3420e737e472d4afd7ac5f4df63fd40"}`
we have a lot of chanells more than 1500
