### ISSUE TITLE
Cannot upload user avatar

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#51918] opened 2023-06-29 20:20 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Currently, it appears you cannot upload an image as a user avatar. No network errors indicate a failure even with a properly formatted image.

Steps:
1. Navigate to your user settings - https://{org_slug}.sentry.io/settings/account/details/
2. Attempt to upload an image under avatar

### Expected Result

Avatar to be uploaded image

### Actual Result

The image does not upload or indicate there is an issue.

### Product Area

Unknown

**Comment by scttcper** [comment] 2023-07-11 20:17
seems to be working for me, just doesn't show a success banner

**Comment by vaidas-lungis** [comment] 2023-07-26 10:11
I having the same issue.
After selecting `Upload an Image`, choosing image (JPG) and clicking Save Avatar, I get 2xx HTTP 3 responses but nothing showing for my account.

**Request**   
<img width="508" alt="Screenshot 2023-07-26 at 13 07 33" src="https://github.com/getsentry/sentry/assets/5111555/c7983294-b2a7-4586-9ad2-22c3b4f95d85">

**Response** 
<img width="262" alt="Screenshot 2023-07-26 at 13 07 00" src="https://github.com/getsentry/sentry/assets/5111555/28f952ff-f5f3-4ff1-a366-9444102a763f">

Tho, previously I had chosen the Gravatar, but then switched to other option, but `/me` endpoint response still has the  
```
"avatarUrl": "https://secure.gravatar.com/avatar/{hash}
```
🤷

**Comment by GabeVillalobos** [comment] 2023-07-28 20:07
This issue should be resolved by PR #53638. I was able to reproduce the upload issue and am seeing my previously uploaded avatar appearing correctly. New avatar uploads also appear to be working now.

**Closed by GabeVillalobos** 2023-07-28 20:07 UTC
Labels: Product Area: Settings - General
