### ISSUE TITLE
Allow to reserve a volume of cron monitors

### ISSUE THREAD

**Issue by xavfernandez** [getsentry/sentry#73359] opened 2024-06-26 08:39 UTC
### Problem Statement

Monthly invoices are a PITA for our accountant.

But when using multiple cron monitors, you can only have 1 included monitor meaning that you have to use on-demande budget meaning that you end-up with monthly invoices.

### Solution Brainstorm

Either:
- allow to set a reserved volume for cron monitors (just like for errors, performance units, replays & attachments)
- allow to set a yearly on-demand budget (paid in advance & ideally with a monthly cap) with the yearly subscription to only have single invoice

### Product Area

Settings - Subscription

**Comment by brianthi** [comment] 2024-06-26 18:34
Hi @xavfernandez, thanks for the feedback. I'm adding this request to our backlog for crons billing improvements. Will post here if we have any updates.

**Comment by brianthi** [comment] 2024-12-04 17:21
Duplicate of https://github.com/getsentry/sentry/issues/74133, closing.

**Closed by brianthi** 2024-12-04 17:21 UTC
Labels: Type: Improvement, Product Area: Settings - Subscription
