### ISSUE TITLE
Can't hide/show environment that has `%` symbol in it's name

### ISSUE THREAD

**Issue by TimShilov** [getsentry/sentry#12956] opened 2019-04-26 15:57 UTC
## Important Details

How are you running Sentry?

* [x] On-Premise [Version 9.1.0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I have and environment called `%APP_ENVIRONMENT%`.
And when I'm trying to hide/show it I'm getting an `Unable to update %App_environment%` error message and in DevTools request are received `400 Bad Request` in response.

## Steps to Reproduce

1. Create an environment called `%APP_ENVIRONMENT%`
2. Go to "Manage Environments" page.
3. Click "hide" (or "show").

Here's the URL of request that it's trying to make:
```
https://sentry.domain.com/api/0/projects/<team>/<project>/environments/%APP_ENVIRONMENT%/
```

### What you expected to happen

Environment should be successfully hidden/shown.

### Possible Solution

I managed to make it working by encoding environment name with `encodeURIComponent` which resulted in this URL that is working good:
```
https://sentry.domain.com/api/0/projects/<team>/<project>/environments/%25APP_ENVIRONMENT%25/
```

**Comment by markstory** [comment] 2019-04-26 17:58
Yeah you need to encode `%` because it is used for % encoded bytes in URLs.

**Comment by TimShilov** [comment] 2019-04-28 18:54
@markstory Sorry but how is that I should do that?

Sentry allows me to create environment with such name via JavaScript SDK without any problems but gives error when I'm trying to work with it in UI.
Is that okay? That's not a bug?

**Comment by markstory** [comment] 2019-04-29 14:28
My mistake, I misread the issue and thought that you were having problems with the API calls.

**Comment by xeor** [comment] 2019-08-08 09:04
Is this suposed to be fixed in `9.1.2`? I'm getting similar behavior if the environment have an `\` in it.
The url it tries is getting a 404 with a url like `https://sentry..../environments/%22/%22///%22dev-something///%22/%22%22/` for an environment that is called `"\"\\\"dev-something\\\"\""` (ended up in there by a mistake....).

The `\` characters should end up as `%5C`, but they seam to end up as `/` instead.

The url that works in this case is `https://sentry..../environments/%22%5C%22%5C%5C%5C%22dev-something%5C%5C%5C%22%5C%22%22/`

**Comment by grousseaufr** [comment] 2020-02-05 03:41
I also have this issue : On-premise [10.0.0.dev0]

I have this environment that also ended up here by mistake : ${appsetting:appName\:Environment}

Resulting Url is : https://sentry..../environments/%24%7Bappsetting%3AappName%5C%3AEnvironment%7D/

I'm unable to hide this environment and I get same error message : "Unable to update ${appsetting:appName\:Environment}"

**Comment by markstory** [comment] 2020-03-02 18:20
I attempted to reproduce this locally against the current master and wasn't able to.

**Closed by markstory** 2020-03-02 18:20 UTC

**Comment by grousseaufr** [comment] 2020-03-17 03:05
@markstory Thank you

But on our side we still have this issue and cannot get ride of these environments added by mistake. Any workaround ? A way to delete them manually directly from our server ?

**Comment by markstory** [comment] 2020-03-17 03:32
The environments will be stored in sentry_environment if you want to remove them via the django shell it postgres queries.
