### ISSUE TITLE
The dashboard is not alive

### ISSUE THREAD

**Issue by mrwnmonm** [getsentry/sentry#4844] opened 2017-01-28 14:47 UTC
first time using the service
i got everything working, but the error don't show up immediately
i tested it and i have to reload the page to see the errors
do i miss something?

note: the (play, pause) button in the project page in ON
also adding tooltips for these buttons would be very helpful

**Comment by benvinegar** [comment] 2018-10-01 04:09
Likely a duplicate of #4689

**Closed by benvinegar** 2018-10-01 04:09 UTC
