### ISSUE TITLE
Microsoft Teams integration with onpremise installation

### ISSUE THREAD

**Issue by kfkawalec** [getsentry/sentry#22417] opened 2020-12-03 07:14 UTC
Hi, can anyone confirm that this integration works in onpremise installation?
https://develop.sentry.dev/integrations/msteams/

I can add bot, I see message "Welcome to Sentry for Microsoft Teams" and I have button "Complete Setup".
This button open me page with "Finish integration installation", but when I click "Install Microsoft Teams" the page is reloading (with 302 status code ) and I still see the sam page.
Integration in visible as "Not Installed".
There in no informatin in logs, only 302 redirect.

I use Sentry v20.10.

**Comment by BYK** [comment] 2020-12-03 10:42
Duplicate of #20834.

**Closed by BYK** 2020-12-03 10:42 UTC
