### ISSUE TITLE
Alerts across 2 or more projects, or Org-wide

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#79151] opened 2024-10-15 20:55 UTC
### Problem Statement

For example, Discover Queries show the top occurring Sentry error counts across all projects, which is quite valuable to monitor. Separate alerts per each project could be set up, but given the potential for sheer # of projects, it could become a cumbersome task for large organizations.

### Solution Brainstorm

It'd be great to set an alert in the creation wizard that could scan across multiple projects. In the context of users/teams, this could streamline alerting to allow a single alert configured for a single messaging channel.

### Product Area

Alerts

**Comment by ceorourke** [comment] 2024-10-15 21:24
I'm closing this because it's a duplicate of https://github.com/getsentry/sentry/issues/30059

**Closed by ceorourke** 2024-10-15 21:24 UTC
Labels: Product Area: Alerts, Waiting for: Product Owner

**Comment by kpujjigit** [comment] 2024-10-15 21:25
@ceorourke No worries, Thank you.
