### ISSUE TITLE
GitHub Integration: Integration gets approved but doesn't show up under settings

### ISSUE THREAD

**Issue by bill-pairaktaridis** [getsentry/sentry#13082] opened 2019-05-07 12:54 UTC
As the title suggests, I get the approval for the integration from our organization admin but it never shows up. It shows up on GitHub's end under "Installed GitHub Apps" and the repo I want is authorized. What more do we need to do about this?

**Comment by hackel** [comment] 2019-06-07 16:02
Looks like a dupe of #9936 which I also just experienced.  Seems like Sentry doesn't like it when you aren't an admin on the Github account and need to go through the request approval flow.

**Comment by markstory** [comment] 2019-06-10 14:10
Closing as a dupe.

**Closed by markstory** 2019-06-10 14:10 UTC
