### ISSUE TITLE
Tech Debt: Cleanup hierarchical grouping stack trace code

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#61731] opened 2023-12-13 23:20 UTC
## Problem

There are currently 3 stack trace components: normal, native, and hierarchical grouping. The hierarchical stack trace, AFAICT, is not used. We should remove it if that is the case.

[See here for the code path](https://github.com/getsentry/sentry/blob/23.11.2/static/app/components/events/interfaces/crashContent/stackTrace/index.tsx#L73-L91)

## Solution

Before removing the stack trace we should verify that it isn't being used. Add analytics first and wait for any events to come in. If. none do, proceed with removing all references to hierarchical grouping.

**Comment by lobsterkatie** [comment] 2024-01-09 20:41
This is a duplicate of https://github.com/getsentry/sentry/issues/61641.

**Closed by lobsterkatie** 2024-01-09 20:41 UTC
