### ISSUE TITLE
Unable to access administration areas in the same session after enabling 2FA

### ISSUE THREAD

**Issue by Nessworthy** [getsentry/sentry#24205] opened 2021-03-03 12:27 UTC
## Important Details

On-premise w/ Docker, version 21.2.0 (1dedf39)

## Description

Unable to access administration areas in the same session after enabling 2FA - UI prompts for password, but when entered correctly it will re-prompt. Repeats until you cancel out. No error messages.

Resolved by logging out, and logging back in with a 2FA code.

## Steps to Reproduce

1. Create a superuser account & log in as that user.
2. Enable 2FA.
3. Try to access an administration area which requires a password (in this case, /manage/settings)

### What you expected to happen

One or more of:

Preventative: Enabling 2FA should not block admin access in the same session (probably working as intended).
Proactive: A warning on enabling 2FA to explain that a log out may be required.
Reactive: An error message to explain why, even with a valid password, I was unable to access the administration area when attempting to do so.

**Comment by chadwhitacre** [comment] 2021-03-03 14:54
Thanks @Nessworthy, routing to @getsentry/enterprise for [triage](https://www.notion.so/sentry/How-to-Process-Issues-PRs-e9657c0fa77d407ebe7c878076f63e35#0b4da6c630c84c26beafc0f9bb3b4844) [internal].

**Comment by BYK** [comment] 2021-03-04 10:36
Could this also be resolved by #11499? (I know they are not directly related but let's call this a gut feeling :D)

**Comment by leedongwei** [comment] 2021-03-11 03:02
Thanks for the report! I'm able to replicate the issue and have created a ticket internally to track this. We'll will update this issue once we're able to prioritize this feature

**Comment by nhsiehgit** [comment] 2022-04-25 22:59
Hi all
I'm taking a look at this now and cannot reproduce this bug anymore.
There have been a lot of changes in the past year wrt authentication so its possible that this may have been resolved.

I'm going to close this ticket now, but if you see that this is still an issue, please reopen with new steps on how to reproduce 🙏

**Closed by nhsiehgit** 2022-04-25 22:59 UTC
Labels: Status: Backlog, Team: Enterprise
