### ISSUE TITLE
Issues not being unignored after first next occurrence

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#53161] opened 2023-07-19 16:41 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Ignore an issue until it occurs one more time from now
the issue below was ignored until it happens 1 time(s) at 3:41
![image](https://github.com/getsentry/sentry/assets/99350819/122d7fab-8622-4786-b36c-2b77d4adcba6)

2. Observe the same error comes in and the issue is not unignored
an issue came in at 3:46 and it was not unignored
![image](https://github.com/getsentry/sentry/assets/99350819/5eb5fe5a-9241-4d26-ba8a-3609e1d2fad4)

3. Observe the same error come in a second time, only then is the issue unignored
another issue came in at 3:51, and only then was the issue unignored
![image](https://github.com/getsentry/sentry/assets/99350819/f7694a29-a8ae-49fd-82fc-72a578d27c7a)

### Expected Result

The issue should be unignored after the first next occurrence of the issue

### Actual Result

The issue is not unignored after the first next occurrence of the issue

### Product Area

Issues

### Link

https://org2-w7.sentry.io/issues/4326339835/activity/?referrer=issue-stream&stream_index=0

**Comment by armenzg** [comment] 2023-07-21 20:19
Scott pointed that this code may be the right one to investigate:
https://github.com/getsentry/sentry/blob/master/src/sentry/rules/filters/assigned_to.py#L34

I've placed this in the backlog.

**Comment by vartec** [comment] 2024-03-13 22:41
@kerenkhatiwada @armenzg I've tried reproducing it locally and in SaaS, dozen times in each and I cannot reproduce this at all. Turns to _"escalating"_ with a **single** new event within seconds.  


![Screenshot 2024-03-13 at 3 36 15 PM](https://github.com/getsentry/sentry/assets/2284726/6dc569c9-926f-4f58-be12-775083c9d6d8)

 Are there steps to reproduce that I'm missing? 

OTOH,  escalating code has been changed for the priority work, so it might have been fixed?

**Comment by vartec** [comment] 2024-03-13 23:21
I'm going to try forcing it to transition `archived -> ongoing` rather than going through escalation logic, to see if it's reproducible then

**Comment by vartec** [comment] 2024-03-14 00:33
Currently post process _always_ sets ignored (aka snoozed) issues to be escalating when the condition is a count, rather than expiration time. 

https://github.com/getsentry/sentry/blob/2498ed7e7ef2a982d30b078ea4097d45d5c950ce/src/sentry/tasks/post_process.py#L1011-L1016 

Even forcing events _not_ to go through escalation path this error is still not reproducible.

![Screenshot 2024-03-13 at 5 27 18 PM](https://github.com/getsentry/sentry/assets/2284726/32816107-96f4-4603-8a74-1946c9664530)

**Comment by armenzg** [comment] 2024-03-14 19:03
Thanks for looking into it.
If you can't reproduce it anymore let's close it.

**Closed** 2024-03-15 17:40 UTC
Labels: Type: Bug, Product Area: Alerts
