### ISSUE TITLE
Alert rule should include a condition when a user submits issue via user feedback dialogue

### ISSUE THREAD

**Issue by mchamps** [getsentry/sentry#5055] opened 2017-03-08 22:50 UTC
This is more of a feature request, currently notifications are solely based around events. I understand that user feedback is a relatively new feature. 

[](https://docs.sentry.io/learn/user-feedback/)

As a user of Sentry I would like to able to create an alert rule condition that fires when new user feedback is captured so that I can quickly address the issue or reach out to the user who reported the issue.

**Comment by benvinegar** [comment] 2017-03-22 05:56
We've been burned by this ourselves – user feedback feels a little buried, and you need to stumble upon it.

Totally +1.

**Comment by pierresauvignon** [comment] 2017-11-14 23:56
+1 It's too easy to see user feedback fall through the cracks.
A short term improvement for us would be to filter sentry notifications and be able to redirect the user feedback ones into one of our slack channels (at the moment it's all notifications or nothing)..

**Comment by mcchang** [comment] 2018-04-24 18:26
+1, it would be great to have a way to have an alert rule for events that have associated user feedback

**Comment by jdelStrother** [comment] 2020-06-10 11:08
Yes please, especially when the User Feedback tab doesn't give any indication that there's new feedback.

**Comment by stephent** [comment] 2020-09-07 20:36
This seems like a major gap - if a user bothers to submit feedback, it's extra important to try to respond. It should be possible to have an alert whenever feedback is submitted so submissions aren't missed.

When you can drive the rest of your Sentry error response workflow via alerts, but not this, it undermines the whole alerts system as there's still something you constantly have to go back to check manually.

Hope this can be prioritised.

**Comment by kettunen** [comment] 2020-10-01 05:46
We started to use Sentry about two months ago in production and today found that there was two unhandled user feedbacks. Those are the most important ones because they should be responded in most cases. I thought that alert for user feedback would be by default but it seems you can't even set alert for that.

PS. This feature request has been there over three years and it shouldn't be too hard to implement one more optional trigger for alert conditions.

**Comment by kurtwheeler** [comment] 2020-10-08 19:35
Is it even possible to filter for events/issues that have user feedback? I was trying to test this feature and I could barely find the issue I gave feedback on. The only way I could tell was by clicking on each event and seeing if it had any user feedback.

This seems worse than not taking user feedback at all...

**Comment by akilham** [comment] 2020-10-15 01:27
I agree, we recently implemented user feedback and this is a major problem for us as our users will think that we're ignoring them.

Would be great to hear from someone at Sentry as this seems like a huge problem with a pretty simple fix...

**Comment by danstreeter** [comment] 2020-10-22 18:22
👍🏻  On this one from me too!

Just upgraded from 9.1.2 to 20.10.1 (_onprem_) I used to get feedback emails - cant seem to see them coming in any more...

But the option to add when "A user submits feedback" as an alert rule condition to trigger alerts seems a pretty foundational element missing here 😬

**Comment by adhiraj** [comment] 2020-10-23 20:14
User feedback is currently what we call a [workflow notification](https://docs.sentry.io/product/sentry-basics/guides/alert-notifications/notifications/#workflow-notifications), which goes to email. By default you'll receive these notifications for issues you're subscribed to, a setting you can change in your user settings at /settings/account/notifications/.

Is the problem here that:
1. You want to send it to slack / other integrations
2. Email is fine but you're not getting those emails
3. You're getting those emails but they include all other workflow notifications which you don't want
4. Something else?

**Comment by stephent** [comment] 2020-10-23 20:29
For me it would be 1) (I would want it in Slack, for example) and,  I imagine 3) now that I've just turned this on for all issues (which seems the only viable option to ensure I receive user feedback notifications - right?).

**Comment by danstreeter** [comment] 2020-10-23 22:43
@adhiraj - would be number 1 I guess. To have in the alert triggering options an item ‘when a user submits feedback’ so that I can then decide what to do..

With the current way it works, and having to be subscribed to an issue to get the user feedback - what happens when a new issue occurs and the user submits feedback. I would not have had a chance to go and subscribe to that issue so could miss the feedback.

**Comment by adhiraj** [comment] 2020-11-07 00:56
> For me it would be 1) (I would want it in Slack, for example) and, I imagine 3) now that I've just turned this on for all issues (which seems the only viable option to ensure I receive user feedback notifications - right?).

Yes, unfortunately. Being able to customize it is a reasonable thing to expect, but out of curiosity, which workflow notifications are you receiving that you don't want to?

@danstreeter yes unless you change your settings to receive workflow notifications for all issues like stephent mentioned.

**Comment by denismedly** [comment] 2021-01-05 17:09
I want to be able to create an alert that reacts to user feedback and send it to page duty. So far I don't see a solution or an option on Sentry to accomplish this.

**Comment by hugomn** [comment] 2021-02-22 17:19
I agree that this is a pretty foundational feature. We currently don't have a way to report user feedback other than receiving e-mails. Our customer success team doesn't have access to our sentry email, and for that, we'd need to send a Slack notification, for example. Also, being able to filter issues with feedback or at least being able to reply to the issues would be a big plus.

**Comment by vadviktor** [comment] 2021-04-29 09:57
We just missed a few user issues and I can't find any alert rules nor tags to know if an event was received with user feedback. We report alerts to our Slack and would need to see if any of the issues were actually commented on by a customer so we could jump on it much quicker. Please don't close this and at least give us a tag to see if it has user feedback, thanks!

**Comment by NikolaiGulatz** [comment] 2021-09-22 08:50
This would be relevant for us as well.. Any plans on implementing the possibility to configure specific alerts for user feedback? We would like to receive the feedback via Slack.

**Comment by GiancarlosIO** [comment] 2021-11-22 20:29
Agree 100%

**Comment by MakhBeth** [comment] 2022-01-21 12:23
Isn't it a way to send even an email when the user reports a crash?
Do I have to scrape the feedback page with a bot?

**Comment by entretechno-jeremiah** [comment] 2022-03-18 22:09
We're working around this by creating a separate user that only subscribes to [workflow notifications](https://docs.sentry.io/product/alerts/notifications/#workflow-notifications) and doesn't do anything else.

**Comment by SlyDave** [comment] 2022-07-08 09:08
Any update on this? 

Should be able to target feedback as a independent type of notification so when creating an alert you can decide what to do with it - be that email, slack, etc.

![image](https://user-images.githubusercontent.com/1842611/177958530-87484df1-f7bb-4f69-9a48-4a998da0e7f6.png)

**Comment by chabou** [comment] 2022-11-09 09:22
@MakhBeth Did you create a bot? :) I need it haha

**Comment by souredoutlook** [comment] 2023-01-19 21:34
cc @therealarkin I came across this issue earlier when looking for something else and thought I'd add some additional feedback I put together on the topic: https://www.notion.so/sentry/User-Feedback-Feedback-3d9bdbcf86da4a8e930629afbb8c37dc

**Comment by therealarkin** [comment] 2023-01-25 07:15
@davidenwang dumb question - how did we set a slack alert for our Cron feedback :-)? Do you know if this is already enabled somehow?

**Comment by scttcper** [comment] 2023-01-26 22:01
@therealarkin the feedback button is creating an issue in the feedback project. https://sentry.io/organizations/sentry/issues/?project=6356259 Slack can be added via issue alert

**Comment by MarcoPrins** [comment] 2023-04-03 15:27
Is there still no way to set up a Slack alert for user feedback? Can't believe this!

**Comment by souredoutlook** [comment] 2023-04-03 15:58
> Is there still no way to set up a Slack alert for user feedback? Can't believe this!

Hey @MarcoPrins it's possible to receive personal notifications in Slack: https://docs.sentry.io/product/integrations/notification-incidents/slack/#personal-notifications

Currently this is the only way to receive notifications for submitted User Feedback via Slack. This is considered a [workflow notification](https://docs.sentry.io/product/alerts/notifications/#workflow-notifications) which likely means that you will may only be receiving them for subscribed issues by default. You can override the global defaults and fine-tune by project, you can read more about that here: https://docs.sentry.io/product/alerts/notifications/notification-settings/#workflow

**Comment by MarcoPrins** [comment] 2023-04-03 17:27
@souredoutlook It's not clear how to make these notifications go to slack?

**Comment by MarcoPrins** [comment] 2023-04-03 17:49
@souredoutlook Is it not possible to be notified about user feedback while keeping other workflow notifications (resolution status, etc.) turned off?

**Comment by souredoutlook** [comment] 2023-04-03 19:23
> @souredoutlook Is it not possible to be notified about user feedback while keeping other workflow notifications (resolution status, etc.) turned off?

@MarcoPrins that's correct - you would need to allow all kinds of Workflow notifications - this is just a bit of a work around. Your original point still stands, it's not possible set up an alert, via an alert rule, and receive this notification on Slack.

We don't seem to [expose the Webhook resource](https://docs.sentry.io/product/integrations/integration-platform/webhooks/#event-types) either, so you can't brew your own solution.

cc @therealarkin for awareness

**Comment by MarcoPrins** [comment] 2023-04-04 09:25
@therealarkin Please add this feature, pretty please 🙏

**Comment by pimterry** [comment] 2023-04-20 10:59
I've just found urgent user feedback that was ignored for multiple weeks, because of the lack of these notifications. When users enter feedback into a box like this, they expect it to be sent directly to somebody to read & handle! Treating it as general issue metadata or a workflow event doesn't really make sense imo.

I've heard from multiple users that they didn't get in touch via normal channels about issues they were having, because they thought they'd already got in contact by filling out the user feedback form.

Being able to receive an alert for all user feedback (independent of other workflow events, including on new issues) would be super super useful :+1:. In the meantime, I'm going to have to disable Sentry user feedback entirely to avoid this happening again in future.

**Comment by georgiosd** [comment] 2023-05-22 06:52
Surprised this hasn't been implemented yet after 5 years! Seems to be relatively easy to implement no?

I got in touch with support first and they said it's hard because user is feedback is associated with the error after the error is sent, which makes sense, but without reading pages and pages of comments above, I think what we want is just an alert on the feedback posted.

**Comment by jas-kas** [comment] 2023-08-17 18:06
Hey folks,

We're revisiting how our User Feedback product works today. Given all the feedback over the years, we're making sure we take better alerting into account.

Please see this [GitHub discussion](https://github.com/getsentry/sentry/discussions/54956) to learn more and leave your thoughts there. Your feedback is much appreciated!

**Comment by sanalkv** [comment] 2023-08-21 14:07
Is it possible to stop receiving notification for all exceptions and only receive email when a user feed
back is created ?

**Comment by bruno-garcia** [comment] 2023-11-07 03:32
> Is it possible to stop receiving notification for all exceptions and only receive email when a user feed back is created ?

You'll be able to configure that. You can have a rule for runtime exceptions (errors) and a different rule for user feedback.

**Comment by bruno-garcia** [comment] 2024-02-16 21:08
I see @rodolfoBee's 👎 , to explain:

We're currently only alerting on Feedback sent by the [new Widget](https://docs.sentry.io/platforms/javascript/user-feedback/#user-feedback-widget).
So for folks using the Crash Report Modal, or the SDK's `captureUserFeedback` API there's no way to turn on alerts yet.
Sorry for the confusion, I realize this ticket is old so most folks here expect exactly that use case.

We're working on now on alerting also for this latter use case. And for existing projects, it'll be an **opt-in** feature. For new projects, it'll be on by default. This is because there are lots of odl projects out there that get a ton of feedbacks already from what it seems automated crash modal (e.g: Unreal Engine) and would be pretty spammer from the get go.

**Comment by jas-kas** [comment] 2024-03-05 22:54
Hey all 👋 

Here with an exciting update ✨ We've built a way to opt into alerts from the **Crash-Report Modal and User Report API** feedback submissions. Simply go to your...
- Settings > Projects (Select the relevant project) > Under "SDK Setup" click "User Feedback"
- Toggle on "Enable Crash Report Notifications"

<img width="1287" alt="Screenshot 2024-03-05 at 5 46 21 PM" src="https://github.com/getsentry/sentry/assets/77064737/9e1e6ed8-5e42-4259-a7ca-c4dc23cd9e09">


Note that we're still working on improving our email alert template so expect some changes soon to make it easier to parse the user message.


Let me know your feedback below or if you encounter any issues. 👇

**Comment by rodolfoBee** [comment] 2024-04-29 07:50
@jas-kas was the option above removed / enabled by default? 

Feedback sent using `User Feedback API` (such as in the [Flutter SDK](https://docs.sentry.io/platforms/flutter/user-feedback/)) do not trigger alerts.

**Comment by bruno-garcia** [comment] 2024-05-01 14:24
> @jas-kas was the option above removed / enabled by default?

On projects created before March 2024, this option is **off** by default because there are thousands of apps already using the "crash report" API that suddenly would start getting notifications.

But users can turn it on, on that settings page Jasmin shared above.

Projects created from now on will have this option **on** by default.

> Feedback sent using User Feedback API (such as in the [Flutter SDK](https://docs.sentry.io/platforms/flutter/user-feedback/)) do not trigger alerts.

If that option is set to **on**, feedback alerts should be sent to feedbacks received by any SDK. If that's not happening we need a bug report.


We'll close this and lock since alerting on feedback from the widget and crash reports are working. And the default value for the notification in settings is clarified in the comment above.

Please open a new ticket if you have issues so we can fix any gaps or bugs. We plan to GA User Feedback next week and there are no known bugs at this time.

**Closed by bruno-garcia** 2024-05-01 14:24 UTC
Labels: Type: User Feedback, Component: Rules, Type: Feature Request, Type: Improvement, Product Area: Alerts

**Comment by bruno-garcia** [comment] 2024-05-01 15:33
> Feedback sent using User Feedback API (such as in the [Flutter SDK](https://docs.sentry.io/platforms/flutter/user-feedback/)) do not trigger alerts.

Btw I just confirmed this doesn't seem to work. Please follow this ticket for that specific topic: 
* https://github.com/getsentry/sentry/issues/70041
