### ISSUE TITLE
Cannot Use Event Filter "title" in Performance Alert

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#67013] opened 2024-03-14 21:09 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Go to step #2 "Filter Events" in metric alert. Try and filter events by title:eventName. You will receive the error message that "Invalid key. ''title" is not a supported search key." You're prompted to go to the Searchable property docs and title is still listed as a searchable key; see [here](https://docs.sentry.io/product/reference/search/searchable-properties/events/#title). Customer also shared that this "title" key was being used previously. Also have confirmed that "title" key works when searching Issues page successfully. 

<img width="1347" alt="Screenshot 2024-03-14 at 2 03 07 PM" src="https://github.com/getsentry/sentry/assets/100724053/e5ae21d1-6c3d-4069-a0b6-812951b45b16">

### Expected Result

Be able to use "title" key to filter events in alerts

### Actual Result

Error message received even though "title" key is a searchable property.
<img width="1096" alt="Screenshot 2024-03-14 at 2 02 41 PM" src="https://github.com/getsentry/sentry/assets/100724053/0270b1ff-9b9b-4b50-a358-f3bd9c0badc1">

### Product Area

Alerts

**Comment by ceorourke** [comment] 2024-12-12 20:58
@ReneGreen27 I'm not able to reproduce this, so I'm going to close the issue. Feel free to reopen if it's still occurring though.

**Closed by ceorourke** 2024-12-12 20:58 UTC
Labels: Product Area: Alerts
