### ISSUE TITLE
Alert on a Span from a Transaction

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry#63197] opened 2024-01-15 15:36 UTC
### Problem Statement

Platform: Android and iOS

Transaction has 100 spans

10 of those spans are for HTTP Requests

User wants to set an alert for the duration of one of those HTTP Request (Spans)
User is not looking for an alert on total duration of the transaction, but of one of the HTTP Request Spans in side of it

### Solution Brainstorm

Maybe an option for Performance Span Duration
![image](https://github.com/getsentry/sentry/assets/8920574/61536ba2-e414-4463-a9ab-d5178424d595)
If you choose Transaction Duration, try to write for specific span.duration conditions:
![image](https://github.com/getsentry/sentry/assets/8920574/c45bd245-37de-47f0-a8e1-b1e8a9967162)

### Product Area

Alerts

**Comment by ceorourke** [comment] 2024-12-09 20:37
Closing as a solution has been provided and there has been no followup. Feel free to reopen if the problem isn't solved.

**Closed by ceorourke** 2024-12-09 20:37 UTC
Labels: Product Area: Alerts
