### ISSUE TITLE
Attachments to an issue don't load

### ISSUE THREAD

**Issue by kolchurinvv** [getsentry/sentry#60782] opened 2023-11-29 14:30 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I've noticed that in a bunch of my issues the attachments don't load. I have these errors instead.
![Screenshot 2023-11-29 at 15 26 06](https://github.com/getsentry/sentry/assets/18503099/b8c096a9-c202-401b-a0dd-3640f096b6b4)
reloading and reloading with cleared cache doesn't help.
i'm pretty sure the attachments in question are the payloads for the manually triggered error, however i might be wrong.

### Expected Result

attachments are shown

### Actual Result

attachments to the issues are missing

### Product Area

Issues

### DSN

https://sticky-ventures.sentry.io/issues/4464045080/events/87e4ca0414d34af9877a190ee5927996/?project=4504894285348864

**Comment by kolchurinvv** [comment] 2023-12-04 14:06
https://sticky-ventures.sentry.io/issues/4524764596/events/3cad4e90bd2e4d5688254e2a3189c7cf/?project=4504894285348864
is another issue that has this error.

**Comment by kolchurinvv** [comment] 2023-12-04 14:17
@snigdhas Tbh, i'm not really sure what you're looking for. this is my first time having an issue in Sentry. So if you could let me know what exactly you're looking for, I'd love to be more helpful in resolving this.

I can give you a context of the app: it's a vue2 app with webpack 5 implementation. some of the issues are fired manually and for the convenience of it i've implemented a globally accessible function in our store to be triggered in come `catch` clauses. on the component it looks like this (this snippet pertains to the issue linked above)
```
try {
        this.eventEnded = this.$moment(
          this.event.date + " " + this.event.end,
          "dddd, MMMM Do YYYY h:mm a"
        ).isBefore()
      } catch (e) {
        this.$store.dispatch("sentryError", {
          error: e,
          message: "Error in event detail date parsing",
          eventId: this.event.id,
          userId: this.userId,
          extra: {
            event,
            eventKeys,
            eventDate: this.event.date,
            eventEnd: this.event.end,
          },
        })
      }
```

then in the `~/store/index.js`

```
     actions: {
     sentryError(_, error) {
      // _ is context
      this._vm.$sentryC(error)
    },{} ...}
```
and in the `main.js` this function is registered like so:
```
Sentry.init(...)

const sentryPlugin = {
    install(Vue) {
      Vue.prototype.$sentryC = Sentry.captureException
    },
  }
  Vue.use(sentryPlugin)
```
  hopefully this helps

**Comment by malwilley** [comment] 2023-12-04 20:50
@kolchurinvv thanks for the bug report!

Looking at your example issues, something definitely seems wrong. However, removing the `/events/<event_id>` portion of the URL seems to work fine. How did you find these broken links?

**Comment by kolchurinvv** [comment] 2023-12-05 10:58
@malwilley I've setup auto-reporting of issues to our team's Linear instance. this is how the come to me

**Comment by kolchurinvv** [comment] 2023-12-05 15:22
@malwilley , i tried changing the initial issue to this: https://sticky-ventures.sentry.io/issues/4464045080/?project=4504894285348864  - which actually got rid of the error on the bottom.

however when i went to the other link after it's been through the same treatment https://sticky-ventures.sentry.io/issues/4524764596/?project=4504894285348864 - this one doesn't load for me
<img width="896" alt="Screenshot 2023-12-05 at 16 21 55" src="https://github.com/getsentry/sentry/assets/18503099/0f25b56b-7ff8-4e65-82fa-732b90383f04">

**Comment by kolchurinvv** [comment] 2023-12-06 14:05
> For the most recent issue you shared, it's 2 months old and all events have expired the 30 day retention limit, so it shouldn't show up anywhere in the UI.

ok, got it. as for the Linear integration, this is what's been setup:
<img width="1304" alt="Screenshot 2023-12-06 at 15 04 54" src="https://github.com/getsentry/sentry/assets/18503099/3d872442-1579-4937-9683-a90e2761c034">
<img width="1159" alt="Screenshot 2023-12-06 at 15 04 18" src="https://github.com/getsentry/sentry/assets/18503099/391b1feb-0093-4256-8fea-994a8688f4b0">
<img width="565" alt="Screenshot 2023-12-06 at 15 04 25" src="https://github.com/getsentry/sentry/assets/18503099/dd46b854-0334-48d7-8b06-09826160c95b">

**Comment by malwilley** [comment] 2023-12-06 22:09
@kolchurinvv everything looks right in your Linear setup. I tried to reproduce an issue with the links myself, but it appears that the Linear integration is working as intended.

I _believe_ that the problem here is that the links created in the Linear tickets are pointing to events that have exceeded your 30 day retention, which breaks some of the functionality (despite exceeding retention, the events have not yet been deleted but will be eventually). 

This is a UI issue, so I've made a separate ticket to address it https://github.com/getsentry/sentry/issues/61309. I'll go ahead and close this one. In the meantime, you can always remove the `/event/...` portion of the URL or click the "Details" tab to go to the correct event when you see this.

**Closed by malwilley** 2023-12-06 22:09 UTC
Labels: Product Area: Issues, Waiting for: Product Owner

**Comment by kolchurinvv** [comment] 2023-12-11 09:51
thanks for your help!
