### ISSUE TITLE
ingestion bug

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#75130] opened 2024-07-29 09:02 UTC
this is not ingested as metrics even though [spans are there](https://telex-sandbox.sentry.io/performance/trace/e9bdd90d5ac2273192a16e43e02f7e50/?node=span-9200be865e41cb67&node=txn-502bacf348be46058704b59ac7714bd1&pageEnd&pageStart&project=4507660835225680&source=traces&statsPeriod=1h&timestamp=1721888260.143)

```
{
"category":"span",
"mri":"d:custom/span_attribute_85@none",
"field":"span.data.numericAttr",
"tags":[
{
"key":"environment",
"field":"span.sentry_tags.environment"
},
{
"key":"release",
"field":"span.sentry_tags.release"
},
{
"key":"vip",
"field":"span.data.vip"
},
{
"key":"vip_string",
"field":"span.data.vip_string"
}
],
"condition":null
}
```

**Comment by obostjancic** [comment] 2024-07-30 14:35
Can't reproduce anymore. Closing

**Closed by obostjancic** 2024-07-30 14:35 UTC
