### ISSUE TITLE
[Replays tab count on Transaction Summary]

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#42375] opened 2022-12-15 16:26 UTC
Depends on https://github.com/getsentry/replay-backend/issues/230

**Comment by jas-kas** [comment] 2023-01-11 00:59
Still observing drastically different counts between Replays tab count and number of replays in the table anytime I view the Txn Summary page

Example [here](https://sentry.io/organizations/sentry/performance/summary/replays/?project=11276&query=transaction.op%3Apageload&statsPeriod=24h&transaction=%2Forganizations%2F%3AorgId%2Fperformance%2Fsummary%2Fevents%2F)

_(Can open a different ticket depending on source of the issue)_

**Comment by ryan953** [comment] 2023-01-12 16:35
I'm going to close this because the newest version of this is a duplicate of https://github.com/getsentry/sentry/issues/42818

**Closed by ryan953** 2023-01-12 16:35 UTC
Labels: Status: Backlog, Team: Emerging Technology
