### ISSUE TITLE
New users provisioned Explicitly with Member role leads to unrestricted role

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#45588] opened 2023-03-09 18:05 UTC
### Environment

SaaS (https://sentry.io/)

[Linked Jira Ticket with customer info and some more details](https://getsentry.atlassian.net/browse/FEEDBACK-1772)

[Link To Zendesk Ticket](https://sentry.zendesk.com/agent/tickets/81340)

[*relates to Github issue 45594](https://github.com/getsentry/sentry/issues/45594)
### Steps to Reproduce

1. Provision new user with Member Role

2.  New user accepts invite

3. Go to new user member page and see that the roles are still changeable through the Sentry UI

Customer has tried provisioning with Admin member role and has sent a screenshot (in linked Jira ticket) showing that the role is now only manageable through IDP as expected.

### Expected Result

User role should be restricted and only manageable through the IDP

### Actual Result

User role is unrestricted and manageable through the UI

**Comment by cathteng** [comment] 2023-05-01 17:53
hello, i'm looking into this. i'm unable to reproduce this issue with the Sentry Okta integration, but i will keep digging

**Comment by leedongwei** [comment] 2023-06-09 21:30
Closing due to lack of information.

**Closed by leedongwei** 2023-06-09 21:30 UTC
Labels: Team: Enterprise, Sync: Jira
