### ISSUE TITLE
Be able to prevent mail from being send about regressed issues from old releases

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#50732] opened 2023-06-12 13:59 UTC
### Problem Statement

Context: Currently when for instance when project A has 7.0.0 as last release, but an fixed error happens again in a version that is very old like version 5.0.0. Sentry will still send out an email notification about this.

Problem: You are only able to disable the mail notifications in it's entirety. As off and On or issues that you're subscribed to.
Which is to aggressive.

### Product Area

Settings - Developer Settings

**Comment by scttcper** [comment] 2023-07-20 00:15
@Angelodaniel are you using what sentry considers to be semantic versions? [docs.sentry.io/platforms/rust/guides/actix-web/configuration/releases/#bind-the-version](https://docs.sentry.io/platforms/rust/guides/actix-web/configuration/releases/#bind-the-version)

Using semantic versions along with resolving the issue in a specific release should do what you're expecting.
![image](https://github.com/getsentry/sentry/assets/1400464/f3ca87b3-7f77-4a23-8f67-66ead0eb9c1d)

**Comment by Angelodaniel** [comment] 2023-07-21 13:03
@scttcper Yes, I think the problem here is that by default the Notifications on the Account settings ![Screenshot 2023-07-21 at 15 02 39](https://github.com/getsentry/sentry/assets/25929053/3a244b2b-cff3-4db0-a5bf-2d84a669773c) - You can only put this on on or off if you only receive the email as a default. 
Would you recommend setting this to off and then work only with alerts?

**Comment by Dhrumil-Sentry** [comment] 2023-12-07 07:38
@Angelodaniel any reason why they don't just filter away errors from very old releases?

**Comment by lobsterkatie** [comment] 2023-12-07 18:17
@Angelodaniel - I'd come back to Scott's question, though: _Is_ 'resolve in release x' being used? If an issue is marked as resolved in version 7, and happens again in version 6, we don't consider that a regression and don't send notifications about it.

**Comment by ceorourke** [comment] 2024-12-09 19:36
I'm going to close this since it's unclear that this is actually a problem and not misconfiguration on the user's part and there's been no reply in a year. Feel free to reopen if it's still important and the clarity can be reached.

**Closed by ceorourke** 2024-12-09 19:36 UTC
Labels: Product Area: Alerts
