### ISSUE TITLE
GitHub Integration Problem

### ISSUE THREAD

**Issue by mrgingles** [getsentry/sentry#49575] opened 2023-05-22 21:02 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I have two different accounts on Sentry, with two different emails, and a single GitHub account.

I linked successfully my GitHub Account (via Integrations) on the first Sentry Account. Now I'm trying to to the same with the second Sentry Account.

I get redirected to my application pages on GitHub where I can choose what repositories Sentry should get access to but, after adding the new repo, nothing happens and the connection between Sentry and GitHub does not get created.

### Expected Result

My GitHub account should be linked to my second Sentry Account.

### Actual Result

![image](https://github.com/getsentry/sentry/assets/6815630/200ff0fd-a8e3-4d34-b36b-8d34f5589b90)

### Product Area

Settings - Integrations

**Comment by brianthi** [comment] 2023-05-23 22:43
Hi @mrgingles, just wanting to confirm when you say "two different accounts on Sentry", you mean two different Sentry organizations correct? I ask because we currently have a constraint in which you cannot have more than one Sentry organization connect to a single Github.

**Comment by brianthi** [comment] 2023-06-26 16:03
Correct, currently this is not possible, and there's no workaround available. I'll raise this up with the PM team once more, it's been a long standing issue. Apologies for the _super_ late response!

**Comment by GabeVillalobos** [comment] 2024-12-09 23:38
Duplicate of https://github.com/getsentry/sentry/issues/47246, closing this.

**Closed by GabeVillalobos** 2024-12-09 23:38 UTC
Labels: Product Area: Settings - Integrations
