### ISSUE TITLE
500 on creation user via admin

### ISSUE THREAD

**Issue by RinKiruko** [getsentry/sentry#15951] opened 2019-12-05 14:07 UTC
## Important Details

How are you running Sentry?
On-Premise docker [Version 9.1.2]

## Description
Got 500 error on creating user via sentry.foo.bar/admin/users/add/

## Steps to Reproduce

1. Login with superuser
2. Click create user
3. Fill in all fields correct
4. Get error

## Usefull
Stacktrace:
ProgrammingError: ProgrammingError('column auth_user.last_name does not exist\nLINE 1: ..."auth_user"."username", "auth_user"."first_name", "auth_user...\n                                                             ^\nHINT:  Perhaps you meant to reference the column "auth_user.first_name".\n',)
SQL: SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "a...
  File "django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/contrib/admin/options.py", line 465, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "django/views/decorators/debug.py", line 75, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "sentry/admin.py", line 268, in add_view
    return super(UserAdmin, self).add_view(request, form_url, extra_context)
  File "django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "django/contrib/admin/options.py", line 1146, in add_view
    if form.is_valid():
  File "django/forms/forms.py", line 129, in is_valid
    return self.is_bound and not bool(self.errors)
  File "django/forms/forms.py", line 121, in errors
    self.full_clean()
  File "django/forms/forms.py", line 273, in full_clean
    self._clean_fields()
  File "django/forms/forms.py", line 291, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()
  File "django/contrib/auth/forms.py", line 98, in clean_username
    User._default_manager.get(username=username)
  File "django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "django/db/models/query.py", line 304, in get
    num = len(clone)
  File "django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "sentry/db/postgres/decorators.py", line 80, in inner
    raise_the_exception(self.db, e)
  File "sentry/db/postgres/decorators.py", line 78, in inner
    return func(self, *args, **kwargs)
  File "sentry/db/postgres/decorators.py", line 22, in inner
    return func(self, *args, **kwargs)
  File "sentry/db/postgres/decorators.py", line 101, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "sentry/db/postgres/decorators.py", line 94, in inner
    return func(self, sql, *args, **kwargs)
  File "sentry/db/postgres/base.py", line 74, in execute
    return self.cursor.execute(sql, clean_bad_params(params))

### What you expected to happen
Added new user

### Possible Solution
Add to class UserCreationForm [177] : 
class Meta:
     model= User
     fields=("username", "password", "password_confirm")

**Comment by BYK** [comment] 2019-12-05 20:07
Seems like your db migrations had an issue. Try running `sentry upgrade` or `docker-compose run --rm web upgrade` if you are using the Docker Compose based install.

Gonna close this issue as it is not a bug or anything we can do about. Please use [the forums](https://forum.sentry.io) in the future for similar inquiries.

**Closed by BYK** 2019-12-05 20:07 UTC
