### ISSUE TITLE
Performance tab does not surface query in URL or support filtering in the "search transactions" input

### ISSUE THREAD

**Issue by md384** [getsentry/sentry#49294] opened 2023-05-17 03:59 UTC
### Problem Statement

I want to be able to easily filter performance results (for all transactions). Currently the performance overview page only allows you to filter via the "search transactions" input box and that appears to only support filtering by transaction name.

This is important for us since we want to see an overview of web vitals performance for all transactions for mobile and separately for desktop. We also would like to compare bot vs non-bot in a similar fashion as well as some other cases.

It actually does seem possible to filter the results by a query to the url - for example
https://try.sentry-demo.com/organizations/endless-ocelot/performance/?landingDisplay=frontend_pageload&query=os.name%3A%5BAndroid%2CiOS%5D - filters to android or iOS but that information is not surfaced anywhere on the page. I would like to be able to see those filters in the UI.

### Solution Brainstorm

Use the filter widget that is available on the individual transaction page on the performance overview page - i.e. 

<img width="1185" alt="Screen Shot 2023-05-16 at 8 56 45 PM" src="https://github.com/getsentry/sentry/assets/4070250/57ad1305-67f0-40d0-8859-3196c83e38e3">

### Product Area

Performance

**Comment by DominikB2014** [comment] 2024-12-09 19:47
@md384 Thanks for bringing this to our attention! This issue appears to be a duplicate of https://github.com/getsentry/sentry/issues/81045 so i'm going to close this one in favour of that.

Feel free to re-open the issue if I misunderstood anything.

**Closed by DominikB2014** 2024-12-09 19:47 UTC
Labels: Product Area: Performance
