### ISSUE TITLE
self-hosted sentry:sourcemap does not work

### ISSUE THREAD

**Issue by zhangyongjian986** [getsentry/sentry#14847] opened 2019-09-27 03:44 UTC
Hi, please help
we self host sentry in a docker container,and upload our sourcemap to self-hosted sentry.but it does not work.
#### First condition
1. we upload sourcemap and js files to sentry use following command:
```
sentry-cli releases files v1.0.0 upload-sourcemaps ./webapps/static/js --url-prefix https://test-stream.huya.com/static/js --validate  
sentry-cli releases finalize v1.0.0
```
2. sentry artifacts look like this:
![image](https://user-images.githubusercontent.com/21262448/65739167-f22bd600-e116-11e9-9678-2a5e9766c63f.png)

3. trigger an error on web app, and it's error stacktrace is like this:
![image](https://user-images.githubusercontent.com/21262448/65739332-6ebeb480-e117-11e9-9c77-ad88e2ddbd5e.png)

4. sentry processes this error is like this:
![image](https://user-images.githubusercontent.com/21262448/65739393-acbbd880-e117-11e9-9759-4a34a10f1ebc.png)

#### Second condition
base on first condition, I change the -url-prefix to `~/static/js`,and upload sourcemap/js files again.
```
sentry-cli releases files v1.0.0 upload-sourcemaps ./webapps/static/js --url-prefix '~/static/js' --validate
sentry-cli releases finalize v1.0.0
```
artifacts look like this:
![image](https://user-images.githubusercontent.com/21262448/65741035-61a4c400-e11d-11e9-800c-007a970c9278.png)

error stacktrace is the same as the first condition
![image](https://user-images.githubusercontent.com/21262448/65740428-56509900-e11b-11e9-8785-52c84a71794a.png)

and sentry still is 404 like the first condition when to fetch the map source

so ,I want to know what's happening, and how to solve this problem, can you help me please?

**Comment by juan-imares** [comment] 2019-11-05 03:06
I have the same problem with you... I use @sentry/webpack-plugin to upload js and js.map files to sentry(Own server)，get an error 404. BUT, when I use sentry's public server without any problem! and my upload code not any difference，the only difference : own server or public server. I want to know what's happening tooooo.

**Comment by BYK** [comment] 2019-11-18 15:08
Did you upload the source maps before the errors happened? (trying to verify https://docs.sentry.io/platforms/javascript/sourcemaps/#verify-artifacts-are-uploaded-before-errors-occur is not the cause)

**Comment by Rennzh** [comment] 2019-11-25 13:23
I have the same problem, and I also use @sentry/webpack-plugin to upload js and js.map. I am sure upload the source maps before the errors happened

**Comment by Rennzh** [comment] 2019-11-26 05:45
> I have the same problem with you... I use @sentry/webpack-plugin to upload js and js.map files to sentry(Own server)，get an error 404. BUT, when I use sentry's public server without any problem! and my upload code not any difference，the only difference : own server or public server. I want to know what's happening tooooo.

me too! I use own server and get 404 when fetch any .js.map

**Comment by Rennzh** [comment] 2019-11-26 05:55
> Did you upload the source maps before the errors happened? (trying to verify https://docs.sentry.io/platforms/javascript/sourcemaps/#verify-artifacts-are-uploaded-before-errors-occur is not the cause)

I had the same problem, I am sure upload the source maps before the errors happened and I check the artifacts list. sentry version is 8.19.0 and using ravenjs-3.17.0

**Comment by arangelp** [comment] 2019-11-29 13:22
Having the same problem here.
If i have public sourcemaps, it works
I i just upload the sourcemap to sentry, it doesnt work.

**Comment by BYK** [comment] 2020-08-31 14:59
Hey there! I think this was fixed with #16353 so I'll be closing this issue. Feel free to reopen a new issue over at [getsentry/onpremise](https://github.com/getsentry/onpremise) if you are still having similar problems with newer versions of Sentry.

**Closed by BYK** 2020-08-31 14:59 UTC

**Comment by cuttino001** [comment] 2020-09-15 07:04
docker 的worker 容器需要针对静态资源的cdn地址添加host
--add-host=cdnhostname:10.180.8.1

**Comment by BYK** [comment] 2020-09-15 10:02
@cuttino001 I don't think that's the case here but thanks for sharing what worked for you anyway.

Will be locking this conversation as this specific issue has been resolved.
