### ISSUE TITLE
Support for Clubhouse.io integration on self-hosted Sentry

### ISSUE THREAD

**Issue by SimplyPhy** [getsentry/sentry#15719] opened 2019-05-29 16:11 UTC
<img width="757" alt="Screenshot 2019-05-29 11 46 11" src="https://user-images.githubusercontent.com/7506223/58573016-d36e0f00-820a-11e9-8a91-db74e5e3eaea.png">

Is there any hope of this changing?

**Comment by erviker** [comment] 2020-04-30 12:28
Any update on this issue? 
Any plans to make this available for hosted?

**Comment by ovalenzuela19** [comment] 2020-09-17 22:36
Looking for the same thing as above^^. Any update on this?

**Comment by jjblumenfeld** [comment] 2021-03-04 18:50
Bump! This would be great. Willing to test it out if there is some way to do that.

**Comment by BYK** [comment] 2021-03-04 19:08
@manuzope @philipphofmann ping for triage/official word from the team :)

**Comment by jonesphillip** [comment] 2021-03-08 23:15
We are aware of this. It isn't on our immediate roadmap, but if we end up moving forward with adding self-hosted support for Integration Platform integrations we'll update this issue.

**Comment by nMustaki** [comment] 2023-12-08 09:36
In the meantime, has anyone tried to recreate the integration, either as a public or internal ?

**Comment by nMustaki** [comment] 2023-12-11 17:43
> @nMustaki There's no way to do this because of the way [webhook validation works ](https://docs.sentry.io/product/integrations/integration-platform/webhooks/)which Linear likely implements to prevent non-Sentry actors from using the endpoints they have specified. Which means integrations created from 3rd parties like this only works in a SaaS environment. 

OK thanks you for the pointer. So the issue is that Shortcut do not accept requests not coming from sentry.io? 
I can reach out to them and see what can be done on their side, that doesn't seem impossible to add an option on their side.

**Comment by scefali** [comment] 2023-12-11 21:24
@nMustaki Yea, you could definitely talk to Clubhouse/Shortcut and see if they can support you.

**Comment by nMustaki** [comment] 2023-12-12 05:38
If they commit to this change, would Sentry publish the existing integration code?

**Comment by scefali** [comment] 2023-12-12 17:40
@nMustaki There is no code that enables the integration except on Clubhouse's/Shortcut's side. There is a configuration to make the integration happen which they can share with you as well.

**Comment by nMustaki** [comment] 2023-12-12 18:43
OK so to check :
- on Sentry codebase there's nothing to do 
- Shortcut needs to authorize webhooks from  selfhosted url
- Shortcut needs to enable the sentry integration on their side for a self hosted url
- when that's done, it's possible to setup the integration on sentry self hosted instance, it will work out of the box

If that's the case, I don't understand why this issue has been opened for 3 years on Sentry's bug tracker ? 

Thanks!

**Comment by scefali** [comment] 2023-12-12 22:21
@nMustaki

Here's what I would do if I were you:

1. Contact Shortcut and ask them for their integration config
2. Create an internal integration that has an identical config
3. Take the client secret from that internal integration and ask Shortcut to make a code change to do signature verification that also works for your secret as well
4. Validate everything works

> If that's the case, I don't understand why this issue has been opened for 3 years on Sentry's bug tracker ?

Well, because Shortcut still has to make a non-trival code change. They basically have to do multiple checks if a webhook payload can be trusted.

**Comment by nMustaki** [comment] 2023-12-13 06:14
OK thanks again for the pointers, I'll ask again Shortcut with yours answers. It seems both companies were waiting for each other, so hopefully we can move forward.

**Comment by scefali** [comment] 2023-12-13 17:19
@nMustaki great, I'm going to close the issue as I think you have a path forward. Would be interested in any updates you have (and feel free to re-open if something doesn't work and you need help).

**Closed by scefali** 2023-12-13 17:19 UTC
Labels: Product Area: Settings - Integrations, Waiting for: Product Owner
