### ISSUE TITLE
pip install -U sentry error

### ISSUE THREAD

**Issue by machenchn** [getsentry/sentry#13910] opened 2019-07-08 09:00 UTC
## Important Details
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting sentry==9.1.1
  Downloading http://mirrors.aliyun.com/pypi/packages/22/62/3a88cf7edbd17b4d9050f1da4ecf176c8876d8e285663be3b9688c7d6a71/sentry-9.1.1-py27-none-any.whl (27.2MB)
     |████████████████████████████████| 27.2MB 3.8MB/s
Collecting parsimonious==0.8.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/4a/89/32c55944cd30dff856f16859ee325b13c83c260d0c56c0eed511e8063c87/parsimonious-0.8.0.tar.gz
Collecting python-dateutil<3.0.0,>=2.0.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
     |████████████████████████████████| 235kB 45.6MB/s
Collecting boto3<1.4.6,>=1.4.1 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/fb/8a/95ae869835746b8ff51fd7cd799e19e7ecd10b4c668fbc3d187dcf8db27e/boto3-1.4.5-py2.py3-none-any.whl (128kB)
     |████████████████████████████████| 133kB 45.3MB/s
Collecting mock==2.0.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/e6/35/f187bdf23be87092bd0f1200d43d23076cee4d0dec109f195173fd3ebc79/mock-2.0.0-py2.py3-none-any.whl (56kB)
     |████████████████████████████████| 61kB 38.5MB/s
Collecting unidiff>=0.5.4 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/68/52/c7278fc3c17d1aaade84597968d88f97f0f4ec7288ddedb6970a341c5170/unidiff-0.5.5-py2.py3-none-any.whl
Collecting setproctitle<1.2.0,>=1.1.7 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/5a/0d/dc0d2234aacba6cf1a729964383e3452c52096dc695581248b548786f2b3/setproctitle-1.1.10.tar.gz
Collecting semaphore<0.5.0,>=0.4.21 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/45/df/911e139d35b4a736101f06b6cdb4a310bc175bbbe3f92e2f1af548534d42/semaphore-0.4.39-py2.py3-none-manylinux1_x86_64.whl (12.1MB)
     |████████████████████████████████| 12.1MB 43.0MB/s
Collecting lxml>=3.4.1 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/af/31/47cce58942bbf4b8f1c975ec2d1ab52141f7b7cf8cdecb58f25546d2c4fd/lxml-4.3.4-cp27-cp27mu-manylinux1_x86_64.whl (5.6MB)
     |████████████████████████████████| 5.6MB 43.8MB/s
Collecting djangorestframework<2.5.0,>=2.4.8 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/f9/fd/00c8b6764cac6cfc2c2ef1df53849cd597384da135fb0d5055354a2c1f38/djangorestframework-2.4.8-py2.py3-none-any.whl (193kB)
     |████████████████████████████████| 194kB 38.0MB/s
Collecting requests-oauthlib==0.3.3 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/0f/8a/a7afc508dd7cf6883fb318bdf0c2a0fd65443e396ccd27977c6f146040a3/requests-oauthlib-0.3.3.tar.gz
Collecting pytest-html<1.10.0,>=1.9.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/f7/08/225d5929808239856890cc797215ecaa4894c5dc2cf843f193192928e9c5/pytest_html-1.9.0-py2.py3-none-any.whl
Collecting Django<1.7,>=1.6.11 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/80/86/f52eec28e96fb211122424a3db696e7676ad3555c11027afd9fee9bb0d23/Django-1.6.11-py2.py3-none-any.whl (6.7MB)
     |████████████████████████████████| 6.7MB 43.6MB/s
Collecting statsd<3.2.0,>=3.1.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/fc/29/b935cacecab8bd6b20d3895a69592cca76711229e7d9a0b2e18234652beb/statsd-3.1-py2.py3-none-any.whl
Collecting uwsgi<2.1.0,>2.0.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/e7/1e/3dcca007f974fe4eb369bf1b8629d5e342bb3055e2001b2e5340aaefae7a/uwsgi-2.0.18.tar.gz (801kB)
     |████████████████████████████████| 808kB 45.5MB/s
Collecting redis<2.10.6,>=2.10.3 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/08/c1/457428f7507e27ba7144758a7b716ea35766e6d602f4a0c16e443ab3d381/redis-2.10.5-py2.py3-none-any.whl (60kB)
     |████████████████████████████████| 61kB 35.8MB/s
Collecting python-u2flib-server<4.1.0,>=4.0.1 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/e7/d6/40a633fdd36669bca7753fad22a8b82351c62387fac9da3391b1702eae7d/python-u2flib-server-4.0.1.tar.gz
Collecting selenium==3.141.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl (904kB)
     |████████████████████████████████| 911kB 31.0MB/s
Collecting toronado<0.1.0,>=0.0.11 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/72/7d/988c46ca0405b1bc86d87314d81151b814f67608288cae0c19aed1c170a7/toronado-0.0.11.tar.gz
Collecting pytest<3.6.0,>=3.5.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/76/52/fc48d02492d9e6070cb672d9133382e83084f567f88eff1c27bd2c6c27a8/pytest-3.5.1-py2.py3-none-any.whl (192kB)
     |████████████████████████████████| 194kB 42.5MB/s
Collecting cffi<2.0,>=1.11.5 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/8d/e9/0c8afd1579e5cf7bc0f06fbcd7cdb954cbc0baadd505973949a99337da1c/cffi-1.12.3-cp27-cp27mu-manylinux1_x86_64.whl (415kB)
     |████████████████████████████████| 419kB 43.7MB/s
Collecting symbolic<7.0.0,>=6.0.4 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/25/2a/7ddd3d3b9369c9361dd6c6c3a38fbb6814296a0d9d4f9145a55fb11ac1cb/symbolic-6.1.3-py2.py3-none-manylinux1_x86_64.whl (11.6MB)
     |████████████████████████████████| 11.6MB 44.4MB/s
Collecting django-picklefield<0.4.0,>=0.3.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/b1/67/0f7f24e61f71aa7c604dab55497495f599906a20187e92edf70939c71d80/django_picklefield-0.3.2-py2.py3-none-any.whl
Collecting qrcode<6.0.0,>=5.2.2 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/39/71/c01d42a3fc1a9c768c93980f26159ec682dc7bd49407e756f671b52b8344/qrcode-5.3-py2.py3-none-any.whl
Collecting honcho<1.1.0,>=1.0.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/12/c2/95faf9e062e37f50fb685972692395bef019a554c08447282a81e35bf031/honcho-1.0.1-py2.py3-none-any.whl
Collecting strict-rfc3339>=0.7 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/56/e4/879ef1dbd6ddea1c77c0078cd59b503368b0456bcca7d063a870ca2119d3/strict-rfc3339-0.7.tar.gz
Collecting Pillow<=4.2.1,>=3.2.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/43/5a/904f2cc20ef9f9ba05f9ff1fb3dfadb1e6923e3bf6f8c8363d5dc3a179ab/Pillow-4.2.1-cp27-cp27mu-manylinux1_x86_64.whl (5.8MB)
     |████████████████████████████████| 5.8MB 43.7MB/s
Collecting oauth2>=1.5.167 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/a0/6f/86db603912ecd04109af952c38bc08928886cf0e34c723481fa7db98b4b5/oauth2-1.9.0.post1-py2.py3-none-any.whl
Collecting progressbar2<3.11,>=3.10 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/aa/13/7fc75289f0f6a46d83913bfbe3db8003f0d56fd96a8564f6b334b830d461/progressbar2-3.10.1-py2.py3-none-any.whl
Collecting sqlparse<0.2.0,>=0.1.16 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/9c/cc/3d8d34cfd0507dd3c278575e42baff2316a92513de0a87ac0ec9f32806c9/sqlparse-0.1.19.tar.gz (58kB)
     |████████████████████████████████| 61kB 36.7MB/s
Collecting percy>=1.1.2 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/d6/39/528e689e21baa4d625cecc326c0d56c976d63855f9d114c07ccaed8a73eb/percy-2.0.2-py2.py3-none-any.whl
Collecting croniter<0.4.0,>=0.3.26 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/c8/4c/04dea44f87b963d5c3f2bbc391e6c69d0a14aa896e35590be56213a04e4f/croniter-0.3.30-py2.py3-none-any.whl
Collecting ipaddress<1.1.0,>=1.0.16 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting mmh3<2.4,>=2.3.1 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/87/a9/d15efdb230b1588b9427c77ce4b608aaf478bd0ebd47b2f6a7a1bc7cce4b/mmh3-2.3.1.tar.gz
Collecting requests[security]<2.21.0,>=2.20.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl (57kB)
     |████████████████████████████████| 61kB 35.9MB/s
Collecting exam>=0.5.1 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/c7/bd/c15ce029540bb1b551af83c0df502ba47e019ce7132a65db046ad16b8eda/exam-0.10.6.tar.gz
Collecting django-sudo<3.0.0,>=2.1.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/a2/89/10a6e48ced1bf78ccd18c8b291a6a04906a8ad8950894b43929adb5f2ff5/django_sudo-2.1.0-py2.py3-none-any.whl
Collecting django-templatetag-sugar>=0.1.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/72/61/ec7b883ff5f8d0641eea522b23e382918d214b27c1f63c5449ac0bcba1e7/django_templatetag_sugar-1.0-py2.py3-none-any.whl
Collecting sentry-sdk>=0.7.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/e1/eb/a738ab2e06d10f457a239091bd7119880080bd256f1f56a97b180bd7ee95/sentry_sdk-0.10.0-py2.py3-none-any.whl (75kB)
     |████████████████████████████████| 81kB 40.5MB/s
Collecting PyYAML<3.12,>=3.11 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/75/5e/b84feba55e20f8da46ead76f14a3943c8cb722d40360702b2365b91dec00/PyYAML-3.11.tar.gz (248kB)
     |████████████████████████████████| 256kB 43.4MB/s
Collecting botocore<1.5.71 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/b4/87/7ca29ef8d210de618b4510d3c98131edd17ba1e2617f80e6f6bd3498caa6/botocore-1.5.70-py2.py3-none-any.whl (3.5MB)
     |████████████████████████████████| 3.5MB 44.8MB/s
Collecting celery<3.1.19,>=3.1.8 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/94/50/2b824c2a2b53a05763a71138fa494f913b272511ead9757522a9ab3c0077/celery-3.1.18-py2.py3-none-any.whl (515kB)
     |████████████████████████████████| 522kB 42.5MB/s
Collecting futures<4.0.0,>=3.2.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Collecting django-jsonfield<0.9.14,>=0.9.13 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/a4/93/0d881e8f32043c65454a0980e8472fc831e2e75ae05607ef4d406cbe123f/django-jsonfield-0.9.13.tar.gz
Collecting urllib3==1.24.2 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/df/1c/59cca3abf96f991f2ec3131a4ffe72ae3d9ea1f5894abe8a9c5e3c77cfee/urllib3-1.24.2-py2.py3-none-any.whl (131kB)
     |████████████████████████████████| 133kB 41.4MB/s
Collecting functools32<3.3,>=3.2.3 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/5e/1a/0aa2c8195a204a9f51284018562dea77e25511f02fe924fac202fc012172/functools32-3.2.3-2.zip
Collecting msgpack<0.7.0,>=0.6.1 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/6f/74/06f950e5a4c1fb94b676640b8fea839b80bffdc247144bd054dd5eed250e/msgpack-0.6.1-cp27-cp27mu-manylinux1_x86_64.whl (231kB)
     |████████████████████████████████| 235kB 43.0MB/s
Collecting click<7.0,>=5.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71kB)
     |████████████████████████████████| 71kB 40.1MB/s
Collecting PyJWT<1.6.0,>=1.5.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/8a/a6/4d931a2c77a224d27c78382f4ce8ec07542d4426ea2793bea77a689273c2/PyJWT-1.5.3-py2.py3-none-any.whl
Collecting simplejson<3.9.0,>=3.2.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/f0/07/26b519e6ebb03c2a74989f7571e6ae6b82e9d7d81b8de6fcdbfc643c7b58/simplejson-3.8.2.tar.gz (76kB)
     |████████████████████████████████| 81kB 41.0MB/s
Collecting querystring-parser<2.0.0,>=1.2.3 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/57/64/3086a9a991ff3aca7b769f5b0b51ff8445a06337ae2c58f215bcee48f527/querystring_parser-1.2.3.tar.gz
Collecting mistune<0.9,>0.7 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/09/ec/4b43dae793655b7d8a25f76119624350b4d65eb663459eb9603d7f1f0345/mistune-0.8.4-py2.py3-none-any.whl
Collecting cssutils<0.10.0,>=0.9.9 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/92/4f/02b84160055ac51c4c7bb654aca3a0724c4e90b2e124088d7e24b39ea0b1/cssutils-0.9.10.zip (430kB)
     |████████████████████████████████| 440kB 2.2MB/s
Collecting ua-parser<0.8.0,>=0.6.1 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/28/a6/9c4d9a1da685376e369312ac522c13725dd29cf7d5354e69baa19c7c188f/ua_parser-0.7.3-py2.py3-none-any.whl
Collecting jsonschema==2.6.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting pytest-django<2.10.0,>=2.9.1 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/c8/b7/550b718674971059d1f3a33db3991380a8ae3aa02b42f2b51edc02fd71ec/pytest_django-2.9.1-py2.py3-none-any.whl
Collecting python-memcached<2.0.0,>=1.53 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/f5/90/19d3908048f70c120ec66a39e61b92c253e834e6e895cd104ce5e46cbe53/python_memcached-1.59-py2.py3-none-any.whl
Collecting hiredis<0.2.0,>=0.1.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/27/d2/5e4d2ac0b3161f00ce7251f51c7cb86dfc51a6fe309e550cabddd6926f65/hiredis-0.1.6.tar.gz (45kB)
     |████████████████████████████████| 51kB 35.2MB/s
Collecting redis-py-cluster==1.3.4 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/a3/61/4b649ad8caab6b42724d09db14fba8476adc8a67b8dde1765f0f6dbb636b/redis_py_cluster-1.3.4-py2.py3-none-any.whl
Collecting python-openid>=2.2 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/7b/8a/e94d18c666073280b8c0614b7e38cfaf0b129989e42f4ca713942b862f0a/python-openid-2.2.5.tar.gz (301kB)
     |████████████████████████████████| 307kB 48.6MB/s
Collecting psycopg2<2.8.0,>=2.6.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/51/89/7490c48abf2ea89b65140c3c77023f7ea623031389a8e0cd0788c1625b06/psycopg2-2.7.7-cp27-cp27mu-manylinux1_x86_64.whl (2.7MB)
     |████████████████████████████████| 2.7MB 36.4MB/s
Collecting rb<2.0.0,>=1.7.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/4c/a5/bab74a0ea263cdd4954c6784cbbed9787d3dec2341b23a7448f40f718be2/rb-1.7-py2-none-any.whl
Collecting structlog==16.1.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/c5/bf/f87b8273e5016618d750e79a2dae7f42b0a6310bc1f4368dcb217b426e8e/structlog-16.1.0-py2.py3-none-any.whl
Collecting six<1.11.0,>=1.10.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/c8/0a/b6723e1bc4c516cb687841499455a8505b44607ab535be01091c0f24f079/six-1.10.0-py2.py3-none-any.whl
Collecting django-crispy-forms<1.5.0,>=1.4.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/cc/aa/8b8d7f440acb2b2094a3240b691bf065c02df26d88525a8be06cc43fafab/django-crispy-forms-1.4.0.tar.gz (47kB)
     |████████████████████████████████| 51kB 31.1MB/s
Collecting loremipsum<1.1.0,>=1.0.5 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/55/8e/f75963c116c72bb81d2e22ec64ff3837e962cc89bae025ab60698dd83160/loremipsum-1.0.5.tar.gz
Collecting BeautifulSoup>=3.2.1 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz
Collecting kombu==3.0.35 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/34/e6/a81b9cbcb107fc45af2d77b9f4b9745448be42b9952cc4c974f69a9239e7/kombu-3.0.35-py2.py3-none-any.whl (240kB)
     |████████████████████████████████| 245kB 35.2MB/s
Collecting enum34<1.2.0,>=1.1.6 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting email-reply-parser<0.3.0,>=0.2.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/96/1b/a6c9acd8e78e758a7a2f4a30dbcfbf38063a58363b1086d3e5fcdd54fc51/email_reply_parser-0.2.0.tar.gz
Collecting petname<2.1,>=2.0 (from sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/d9/a7/aab8825075230b706b58d59fa23171cfa066ca62507242ff91270bb33fca/petname-2.0.tar.gz
Collecting jmespath<1.0.0,>=0.7.1 (from boto3<1.4.6,>=1.4.1->sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3<1.4.6,>=1.4.1->sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/d7/14/2a0004d487464d120c9fb85313a75cd3d71a7506955be458eebfe19a6b1d/s3transfer-0.1.13-py2.py3-none-any.whl (59kB)
     |████████████████████████████████| 61kB 34.1MB/s
Collecting funcsigs>=1; python_version < "3.3" (from mock==2.0.0->sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock==2.0.0->sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/f1/f3/9c1fa6496f0adf575441eda21baa6d936395df6c8473c8465d2c525585f6/pbr-5.4.0-py2.py3-none-any.whl (108kB)
     |████████████████████████████████| 112kB 39.9MB/s
Collecting milksnake>=0.1.2 (from semaphore<0.5.0,>=0.4.21->sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/27/be/e10e73f857ac98ef43587fa8db37a3ef6de56e728037a7b9728de26711c7/milksnake-0.1.5-py2.py3-none-any.whl
Collecting oauthlib>=0.4.2 (from requests-oauthlib==0.3.3->sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/58/5e/289e98ff5ad1a321945803000c5f10f5f90eba346d13139ecdd075cfbe17/oauthlib-3.0.2-py2.py3-none-any.whl (143kB)
     |████████████████████████████████| 153kB 11.7MB/s
Collecting cryptography>=1.2 (from python-u2flib-server<4.1.0,>=4.0.1->sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/e6/68/50698ce24c61db7d44d93a5043c621a0ca7839d4ef9dff913e6ab465fc92/cryptography-2.7-cp27-cp27mu-manylinux1_x86_64.whl (2.3MB)
     |████████████████████████████████| 2.3MB 41.2MB/s
Collecting cssselect (from toronado<0.1.0,>=0.0.11->sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/7b/44/25b7283e50585f0b4156960691d951b05d061abf4a714078393e51929b30/cssselect-1.0.3-py2.py3-none-any.whl
Collecting setuptools (from pytest<3.6.0,>=3.5.0->sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl (575kB)
     |████████████████████████████████| 583kB 45.2MB/s
Collecting py>=1.5.0 (from pytest<3.6.0,>=3.5.0->sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl (83kB)
     |████████████████████████████████| 92kB 43.4MB/s
Collecting more-itertools>=4.0.0 (from pytest<3.6.0,>=3.5.0->sentry==9.1.1)
  Downloading http://mirrors.aliyun.com/pypi/packages/78/4c/86c3a664e39771a498eee60cd395ace855d5c793d42dfb1ca58d4dbc6dff/more-itertools-7.1.0.tar.gz (71kB)
     |████████████████████████████████| 71kB 39.6MB/s
ERROR: more-itertools requires Python '>=3.4' but the running Python is 2.7.15
How are you running Sentry?
pip install -U sentry error
* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

[What happened]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. and so on.

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration when relevant

### What you expected to happen

[What you think should be happening]

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by LRFeng** [comment] 2019-07-09 07:29
Just now, I had the same problem. but find in the logs：more-itertools>=4.0.0.
So, I install more-itertools=5.0.0 (python2.7 can support) firstly. run:
`pip install more-itertools==5.0.0`
and then install again, it will be successful!

**Comment by BYK** [comment] 2019-07-24 13:28
Not sure why this happened but I'm unable to reproduce this neither with 9.1.1 nor with 9.1.2 so closing it out. If you still have issues, please come over to [the forums](http://forum.sentry.io/) and share more information regarding your setup for us to be able to help you.

**Closed by BYK** 2019-07-24 13:28 UTC
