### ISSUE TITLE
Integration Problem

### ISSUE THREAD

**Issue by abhishek-loop** [getsentry/sentry#78829] opened 2024-10-09 09:47 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

alerts not being sent to OpsGenie, sending test alerts but no alerts seen on OpsGenie
https://loop-health.app.opsgenie.com/alert/list

### Expected Result

Alerts are created on OpsGenie

### Actual Result

no alerts

### Product Area

Alerts

### Link

https://loop-health.sentry.io/settings/integrations/opsgenie/

### DSN

https://314e8e0686a64fc2acf45e9c4b60111b@o572839.ingest.us.sentry.io/5722755

**Comment by mifu67** [comment] 2024-10-09 21:47
Hi @abhishek-loop,

Unfortunately, I cannot reproduce this, and I don't see any record of the test alert being sent/failing to be sent in our logs. Are you sending tests alerts via the issue alert creation form?

**Comment by abhishek-loop** [comment] 2024-10-09 22:08
> Hi [@abhishek-loop](https://github.com/abhishek-loop),
> 
> Unfortunately, I cannot reproduce this, and I don't see any record of the test alert being sent/failing to be sent in our logs. Are you sending tests alerts via the issue alert creation form?

I tried sending from the "Send Test Notification" button while editing alert rule.

**Comment by sentaur-athena** [comment] 2024-10-09 22:50
This could have been because something went wrong with the alert config on the opsgenie side. For example if the recipient doesn't exist or anything else that would lead OpsGenie API to throw an error leads to silent fail on our side. We have a fix where the error will bubble up and be more visible to the users which will be merged tomorrow.

I will ask you to try again then.

**Comment by sentaur-athena** [comment] 2024-10-28 17:03
@abhishek-loop are you still experiencing this?

**Comment by abhishek-loop** [comment] 2024-10-30 06:56
We are good with the integration now. Haven't checked the changes where the test notification if it fails sending, sentry UI is giving the error details or not. We are able to sent test notifications also successfully so couldn't check.

**Closed** 2024-10-31 18:22 UTC
Labels: Product Area: Settings - Integrations, Waiting for: Product Owner
