### ISSUE TITLE
New team provisioned when Contributer adds project (SCIM integration enabled)

### ISSUE THREAD

**Issue by MikeBlomm** [getsentry/sentry#80978] opened 2024-11-19 10:50 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Teams within Sentry are provisioned with the SCIM integration, connected to Entra ID groups.
2. On creation/first sync of the Entra ID group, a new team is provisioned within Sentry.
3. By default, when members get added to the Entra ID group, they will get the Contributor role within Sentry.
4. When a Contributor tries to add a new project to the team (which is not allowed), it will automatically create a new team based of the Contributors user.

**Context**
We are running into some unwanted "bugs" when we onboard teams via the SCIM integration.This initially works fine and as intended, we request new Entra ID groups and those are automatically synced with our Sentry Organization for the creation of teams. 

By default each user is given the role Contributer, which in theory is what we would like. If needed, we give certain users the Team Admin role, so they can start creating projects within their team. However, when someone who has the role Contributor tries to create a new project (which is not allowed), it automatically creates a new team based on that specific user. This is somewhat unexpected, as the creation of teams should be explicitly controlled by Entra ID and the SCIM integration. This results in manual cleanup of the (by accident created) team, and the users are sometimes not even aware this happens.

We would like to see a fix that when SCIM integration is enabled, it is not possible to create new teams manually or as a result when Contributors try to create/setup a new project within Sentry. We do not support personal projects within our Organization. **This has a high priority for us, as it can lead to a lot of manual work**

### Expected Result

When SCIM integration is responsible for the provisioning of teams within Sentry, a Contributor should only get an error when trying to add a new project for the team.

### Actual Result

When a Contributor tries to add a project within a team, which is not allowed, a new team is automatically created based in the Contributors user.

### Product Area

Settings - Teams

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2357) by [Unito](https://www.unito.io)

**Comment by sentaur-athena** [comment] 2024-11-21 21:24
@MikeBlomm when you say
> When a Contributor tries to add a new project to the team (which is not allowed)

How is this not allowed? If you go to organization settings is project creation by member setting off? For context when members create a project we create a new personal team for them to put that project in. That way the member only has access to modify that project not any other project out of that team.

**Comment by sentaur-athena** [comment] 2024-11-26 00:54
They can because of their org level permissions. You can see them here: https://docs.sentry.io/organization/membership/#permissions
Basically this person is a team contributor in the team you allocated to them and can't create projects there but is admin in their personal team so can create projects there.
If this behavior is not wanted for your organization, admins can turn it off from settings. For now, I close the issue since this is not a bug.

**Closed by sentaur-athena** 2024-11-26 00:54 UTC
Labels: Sync: Jira, Product Area: Settings - Integrations, Waiting for: Product Owner

**Comment by MikeBlomm** [comment] 2024-11-26 14:09
@sentaur-athena This is not the behaviour that we would expect, nor would like. Ideally, we would have the option to disable automatic creation of personal teams as team provisioning should only happen through the SCIM integration.

We disabled the option to allow project creation by Members, but this leads to the issue that Team Adminds also are not able to create new projects within their team anymore.

**Comment by Angelodaniel** [comment] 2024-11-26 14:58
Hey @sentaur-athena, so the use case right now is Person A has role Member (lowest role) and is in Team A as a Contributor.
This person is still able to create a personal Team and is then able to freely create projects in their personal team. (because they become the team admin)

According to both [https://docs.sentry.io/organization/membership/#permissions](url) and [https://docs.sentry.io/organization/membership/#permissions-1](url) a member is **Never able to create teams**
![Image](https://github.com/user-attachments/assets/2234f2f3-cdf1-4490-bad0-b610bafffaa8)
![Image](https://github.com/user-attachments/assets/6ac1cca0-b38b-4440-a7ca-677e0be0ddec)

I can move the info above to a feature request, but we also need to improve the docs on this because the possibility to create a team freely is something that was unexpected and is blocking the customer's now when using SCIM as it still creates this wild growth of projects due to people being able to start their own teams with their own projects. 

Ideally that needs to be blocked somehow

**Comment by Angelodaniel** [comment] 2024-11-26 15:06
https://github.com/getsentry/sentry/issues/81310

**Comment by sentaur-athena** [comment] 2024-11-27 17:58
Members can create 1 team only and that's through project creation flow. That would be their personal team. We will update the docs to reflect this better.
