### ISSUE TITLE
Linking issue to JIRA server failing

### ISSUE THREAD

**Issue by dachakra** [getsentry/sentry#53013] opened 2023-07-17 21:07 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

> This only happens with certain projects. The Jira integration is definitely working since many work fine and can create issues.
I noticed that some of the Jira projects in the configuration section were blank. This led me to believe that some of the projects may have been removed or Sentry no longer had access to them, so I ensured that the required projects had access by re-requesting access for the service account used to access those projects, and I deleted the blank entries. However this did not fix the problem.
I then tried linking to an existing Jira ticket and this worked fine. This leads me to believe that the cached last used project might be the problem. The Sentry Issue pulls the last project used and fails because it no longer exists

### Expected Result

Linking issue to Jira ticket.

### Actual Result

![image](https://github.com/getsentry/sentry/assets/86369415/c370e46e-a683-41bb-90e8-24c12692165c)

This bug was reported a while ago in this issue https://sentry.sentry.io/issues/4130565830/?project=1 and a more recent event can be seen in this issue: https://sentry.sentry.io/issues/4267026714/events/e6c5ccc91a694b45824d96d56ee260c0/?project=1

### Product Area

Issues

**Comment by armenzg** [comment] 2023-07-18 19:25
@dachakra FYI If you need to share any private data, there's a Private Data field for our board.

This is the code I believe is related:
https://github.com/getsentry/sentry/blob/805821d9c333638be7f997c3ce675e09ee0709c5/src/sentry/integrations/jira_server/integration.py#L705-L712

**Comment by armenzg** [comment] 2023-07-20 15:56
@dachakra could you please paste a link to a customer's issue where this happens?
(Under "Private Data" and let us know when you do)

The event you point me to shows a 400 error, could you please confirm that the `jira_project_id` is correct?
https://<jira_deployment>/rest/api/2/issue/createmeta/<jira_project_id>/issuetypes

If you can't get me a URL to an issue where this happens, could you please get me the API payload and response? (You can use private data if PII is contained)
In my case this is what I hit the Sentry API with:
```
{components: ""
description: "Sentry Issue: [SENTRY-10QN|https://sentry.sentry REDACTED"
issuetype: "10004"
priority: "4"
project: "10374"
reporter: "REDACTED"
title: "Test ticket feel free to delete"
```

Can you please confirm that they're using this prompt to create the Jira links?
<img width="469" alt="image" src="https://github.com/getsentry/sentry/assets/44410/7fa730a3-79bf-4225-9d78-04852cb9e20a">

I do not know how the UI would not send the project ID if they selected it.
The code would fall back to the first project if no value is passed:
```
        jira_projects = self.get_projects()

        if not project_id:
            project_id = jira_projects[0]["id"]
```

**Comment by dachakra** [comment] 2023-07-21 16:34
I created a shadow JIRA ticket here that contains the details: https://getsentry.atlassian.net/browse/ISSUE-1673

**Comment by riot-sschott** [comment] 2023-09-03 23:18
Hey, I was just wondering if there was any update on this issue?

**Comment by armenzg** [comment] 2023-09-07 11:31
Hi @riot-sschott , a fix was deployed last night. Is this now working for you?

**Comment by riot-sschott** [comment] 2023-09-07 22:59
Hmm unfortunately no.

[image: image.png]

Request URL:
https://riotgames.sentry.io/api/0/groups/4115422384/integrations/26353/?action=create
Request Method:
GET
Status Code:
500
Remote Address:
35.186.247.156:443
Referrer Policy:
strict-origin-when-cross-origin
{"detail":"Internal Error","errorId":"8b0fafc688d14cdca69c1b86cf8ce974"}

It's not part of a blue/green deployment or anything like that?

**Comment by riot-sschott** [comment] 2023-09-07 23:24
Hey this might be a red herring but I only noticed this now. Danny
Abou-Chakra messaged me about the error they were getting and it was for an
old project (RGM), which I told him was odd, since we don't have that
project in our integrations. I didn't hear back from him and then I got the
notification that a code fix had been merged.

When I got your last email I decided to double-check the list of
integrations in case they had changed, or I had missed something. While I
was checking each one (they were fine), I noticed the RGM was at the top of
the list of the "Add Jira Server Project" pulldown:

[image: image.png]

This immediately made me think of the fix.


[image: image.png]
>

This calls self.get_projects() which I assumed was the list of projects for
your integration. But I had a look at the called function:


[image: image.png]

And this just calls the client for a complete project list, which the first
entry will be RGM. Surely this should use the list of projects in the
integration list, since they are the ones that will be configured and have
the correct permissions for the service account.

Again, this may just be a red herring, but it might be something to look at.

**Comment by ceorourke** [comment] 2023-09-07 23:32
Hi @riot-sschott unfortunately I can't see your screenshots (I think because you replied via email rather than on GH) but I do have another stab at fixing it up: https://github.com/getsentry/sentry/pull/55889 where instead of using the cached projects list I get it fresh if we run into the error you're seeing - I'm hoping this means we won't have projects that cause the issuecreate error in that list.

**Comment by ceorourke** [comment] 2023-09-11 18:29
Reopening since my attempts were unsuccessful 😭

**Comment by ceorourke** [comment] 2023-09-27 20:03
I also looked into what @riot-sschott was saying, but unfortunately we use the same endpoint for the list of projects in the integration configuration page. We fetch the projects for that dropdown [here](https://github.com/getsentry/sentry/blob/master/src/sentry/integrations/jira_server/integration.py#L356), and in the issue creation modal we do the same thing in [get_projects()](https://github.com/getsentry/sentry/blob/master/src/sentry/integrations/jira_server/integration.py#L653). The only difference is that in the integration configuration we show the "name" and in the modal we show the "key".

**Comment by feryardiant** [comment] 2023-10-10 06:28
Currently facing kinda similar issue, except I can link some issues to Jira without any error,

![Screenshot 2023-10-10 at 13 21 47](https://github.com/getsentry/sentry/assets/508665/25436a86-e4e1-4e07-bdac-0d6351b83e3f)

But when I check on Jira, none of them appears

![Screenshot 2023-10-10 at 13 28 07](https://github.com/getsentry/sentry/assets/508665/7d0e605f-e7e8-4a6a-87da-1cea7815bc5b)

Relate: #56348

**Comment by riot-sschott** [comment] 2023-12-04 22:05
Hi, just wanted to know if there is any traction on this. If not, is there an ETA for when it could be looked at with a view of having it resolved.

**Comment by lobsterkatie** [comment] 2023-12-07 01:52
@ceorourke - Have you had a chance to make any more progress on this?

**Comment by ceorourke** [comment] 2023-12-07 17:00
@lobsterkatie I have not, I have been trying when it pops up when I'm on triage rotation, and Steve tried a couple times too with no luck.

**Comment by dachakra** [comment] 2023-12-08 16:07
Hey @riot-sschott, is your team integrating Sentry to Atlassian Data Center via the Jira Server integration? Or are you using Jira Server and experiencing this issue? CC @brianthi

**Comment by riot-sschott** [comment] 2023-12-10 21:26
We are using Jira Server.

**Comment by rachrwang** [comment] 2023-12-11 20:51
@riot-sschott - do you plan on making any changes to your integration based on Atlassian stopping support for Server products? https://www.atlassian.com/migration/assess/journey-to-cloud

**Comment by rachrwang** [comment] 2023-12-12 17:09
@riot-sschott - that would be great, since we've had a difficult time reproducing this problem on our side with multiple devs looking into it, and we haven't seen any of the problems reported for our cloud integration. Thank you for the quick follow-up!

**Comment by riot-sschott** [comment] 2024-01-10 22:51
@rachrwang We have completed the migration and are no longer experiencing the issue. Thanks for your assistance.

**Closed** 2024-01-12 00:17 UTC
Labels: Type: Bug, Product Area: Settings - Integrations, Waiting for: Product Owner
