### ISSUE TITLE
Adding info from the error to a Slack alert

### ISSUE THREAD

**Issue by alon-loris** [getsentry/sentry#69181] opened 2024-04-18 08:49 UTC
### Problem Statement

Today when creating an alert rule that sends a notification to a Slack channel, it only allows you to set which tags to show in the Slack message. It would be very helpful to be able to show more info from the error in the Slack alert.
Our use case: we send slack alerts for certain errors to a non-engineering team. Since they are not engineers they don't have access to Sentry, so although they get the alert they can't actually see the details of the error. The super inconvenient flow that we resort to now is that whenever they get the alert they ask the engineers to pull the info from Sentry. 

### Solution Brainstorm

Just allow adding all the data attached to the error.

### Product Area

Alerts

**Comment by Dhrumil-Sentry** [comment] 2024-04-18 18:20
Closing this as a duplicate of https://github.com/getsentry/sentry/issues/58921

**Closed by Dhrumil-Sentry** 2024-04-18 18:20 UTC
Labels: Product Area: Alerts, Waiting for: Product Owner
