### ISSUE TITLE
Search content of stacktrace(s)

### ISSUE THREAD

**Issue by tsondergaard** [getsentry/sentry#7163] opened 2018-02-04 10:25 UTC
it would be very useful to be able to search for stacktrace content. Both in the main "stacktrace" field and in the "stacktrace" fields in "events".

The primary use case is to find events with a similar cause but stacktraces are not similar enough to be grouped by Sentry.

**Comment by tsondergaard** [comment] 2018-02-04 10:26
This issue possibly overlaps with #3755, I'm not quite sure.

**Comment by benvinegar** [comment] 2018-08-29 23:40
Duplicate of #3755, closing.

**Closed by benvinegar** 2018-08-29 23:40 UTC
