### ISSUE TITLE
[Replay - Angular] Enabling Replay is breaking user's on-screen keyboard. 

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#65018] opened 2024-02-12 18:34 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Creating this issue on behalf of a user @stnor.  Attaching a link to the user's production site (currently with replays disabled), along with a clip showing the problem when replay is enabled in [linked Jira ticket.](https://getsentry.atlassian.net/browse/FEEDBACK-2099)

User has an on screen keyboard.  When the replay integration is enabled, clicks on the on screen keyboard will sometimes skip inputs, or input the wrong value.

Removing the replay integration fixes the issue.

### Expected Result

Replay does not affect user's app

### Actual Result

Enabling the replay integration causes issues with user's app.

### Product Area

Replays

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2099) by [Unito](https://www.unito.io)

**Comment by bruno-garcia** [comment] 2024-02-13 18:11
Thanks for raising, we'll need to dig into it

**Comment by bruno-garcia** [comment] 2024-02-13 18:13
SDK version: SDK 7.98.0

**Comment by c298lee** [comment] 2024-02-15 15:09
I wasn't able to repro this. I added replay to the site, let it run, set the dimensions to mobile, and clicked on the keyboard, but everything worked fine (eg. no skipped inputs or wrong values).

**Comment by stnor** [comment] 2024-02-15 15:29
HThe issue only occurs when you press very quickly. Did you watch the video I sent in the JIRA?

**Comment by bruno-garcia** [comment] 2024-02-16 17:09
I could see the repro on the video @stnor thanks for sharing that. We're still digging

**Comment by bruno-garcia** [comment] 2024-02-16 17:12
Couldn't repro but I realize that Replay is not on the site (which makes sense if ti was causing problems)

![image](https://github.com/getsentry/sentry/assets/1633368/abfdac71-4ade-43c7-a89b-9737f8914261)


We can try to inject Replay with tampermonkey to see if we can repro this

**Comment by c298lee** [comment] 2024-02-17 01:45
I tried to repro again using an auto clicker, but I wasn't able to.
I tried to replicate the video on my laptop, here is what I did:
1. Inject replay on the site
2. Set the dimensions to mobile
3. Set up an autoclicker to click the numbers very quickly:
I tried the numbers in the video, 258, repeatedly
I tried to do the same number several times and then cleared then repeated this several times
I tried two numbers close together, 5 and 6, clearing and then repeated this several times

Since replay was on, you could find a replay of me trying to repro this issue, however nothing I tried resulted in wrong or missed inputs.

**Comment by stnor** [comment] 2024-02-18 12:11
Hi Cathrine,
Thanks so much for looking into it again.
I will investigate further and see if I can reproduce it in production, now without Replay,  and locally with or without Replay.

/Stefan

**Comment by stnor** [comment] 2024-02-18 13:28
I did some more testing.

With Replay (on ios 17):
1) Made a single button that sent a burst of ten values to the rxjs observable programaticallty. No issue.
2) Made a single button that sent a burst of ten values us using `document.getElementById('key-1').click();` No issue.
3) Manual testing on the keyboard. Can reproduce with Replay, and not without. It's too hard to click the elements fast enough with the mouse, so hard to tell if related to touch or not. 

I raised this as a courtesy, if you had a bug that needed ironing our due to fast interactions in the UI. If so you should probably be able to reproduce it using a mouse automation software and click elements quickly.

This issue is not a blocker for us, so feel free to close it if you feel you've given it your best shot. :)

Thanks

Stefan

**Comment by bruno-garcia** [comment] 2024-02-21 19:06
> I raised this issue mostly as a courtesy, if you had a bug that needed ironing our due to fast interactions in the UI. If so you should probably be able to reproduce it using a mouse automation software and click elements quickly.

@stnor we appreciate you raising this! we want to make sure we can squash any bugs in the product and if this could be one, we also want to fix it.

With the video @c298lee attached where 3 keys are clearly pressed but only 2 numbers show (on mobile), even without Replay, this possibly isn't a Replay specific situation but rather something that's very hard to reproduce and debug, specially because we can't reproduce on desktop.

We can leave this ticket open see if anyone else experiences something similar. Hopefully with a repro on desktop and a better way to get to the culprit of how this happens.

**Comment by stnor** [comment] 2024-02-21 19:07
Sounds good to me.

**Comment by cmanallen** [comment] 2024-12-09 15:27
Closing as this appears to not be caused by session replay.

**Closed by cmanallen** 2024-12-09 15:27 UTC
Labels: Product Area: Replays
