### ISSUE TITLE
GitLab Integration doesn't work

### ISSUE THREAD

**Issue by unformatt** [getsentry/sentry#16898] opened 2020-02-08 22:13 UTC
How are you running Sentry?

* [x] Saas (sentry.io)

## Description

Followed instructions:

![image](https://user-images.githubusercontent.com/157132/74092629-a90c6b00-4a94-11ea-9975-51d78cbb0631.png)

![image](https://user-images.githubusercontent.com/157132/74092632-b1fd3c80-4a94-11ea-97ca-d27d8dfeaa46.png)

## Steps to Reproduce

Log into https://gitlab.com

u: 7feo3gmhjl@privacy-mail.top
p: 7feo3gmhjl@privacy-mail.top

1. 
![image](https://user-images.githubusercontent.com/157132/74092688-86c71d00-4a95-11ea-93f8-d6eee27991d4.png)

2.
![image](https://user-images.githubusercontent.com/157132/74092707-c7269b00-4a95-11ea-941c-4ee9b4186efa.png)

![image](https://user-images.githubusercontent.com/157132/74092712-db6a9800-4a95-11ea-8f7a-e1910f088023.png)

3. See error 

![image](https://user-images.githubusercontent.com/157132/74092613-867a5200-4a94-11ea-8ad8-1c3fb9fe32f1.png)

### What you expected to happen

Should work

### Possible Solution

?

**Comment by alystair** [comment] 2020-02-26 22:11
Same issue here

**Comment by alystair** [comment] 2020-02-26 22:42
Ok solved it - needs additional rights, I'm guessing it's 'openid'. The documentation/steps should be corrected.

**Comment by markstory** [comment] 2020-02-26 22:44
Is your user account tied to an SSO provider?

**Comment by alystair** [comment] 2020-02-26 22:51
Nope. I also added `read_repository` (Allows read-only access to the repository),
and `profile` (Allows read-only access to the user's personal information using OpenID Connect)... maybe it was one of those. ¯\\\_(ツ)_/¯

**Comment by alystair** [comment] 2020-03-25 17:05
Has the documentation been updated with correct rights? If so this could be closed...

**Comment by markstory** [comment] 2020-03-26 13:29
I've not updated the documentation as I'm not able to reproduce your problem with my GitLab account and sentry.io.

**Comment by alystair** [comment] 2020-03-26 14:34
Sorry about that! Perhaps it's a private group issue... I'll try to tighten the reproduction and get back to you.

**Comment by BYK** [comment] 2020-10-25 20:26
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Closed by BYK** 2020-10-25 20:26 UTC
