### ISSUE TITLE
is there any way to delete release manually?

### ISSUE THREAD

**Issue by Chengshihao1018** [getsentry/sentry#63813] opened 2024-01-25 03:10 UTC
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

i was trying to delete an release, but i can`t find any deleted button.
![image](https://github.com/getsentry/sentry/assets/31720199/cac9eae7-7230-49d9-8654-2232e046f057)

### How are you getting stuck?

i find there are only get and post method in OrganizationReleasesEndpoint class,
![11745f78-b706-4f2e-bc5e-c252e5e32137](https://github.com/getsentry/sentry/assets/31720199/21c9843a-7dab-4778-a9a6-2829516efa67)
![2f5e4d15-4424-4f63-9b5a-0c8287cb6171](https://github.com/getsentry/sentry/assets/31720199/95a62cc8-9e75-4d0e-b472-5281964fd58d)
is there any way to delete release?

### Where in the product are you?

Releases

### Version

22.10.0

**Comment by Chengshihao1018** [comment] 2024-01-25 03:15
i find api document,https://docs.sentry.io/api/releases/delete-an-organizations-release/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2F,so it can`t be deleted via the UI?

**Comment by 17hogeju** [comment] 2024-01-25 17:11
Hi @Chengshihao1018 Are you looking to archive the release? If so, the archive button is in the triple dot menu at the top right of the release details page.

**Comment by Chengshihao1018** [comment] 2024-01-29 01:42
> Hi @Chengshihao1018 Are you looking to archive the release? If so, the archive button is in the triple dot menu at the top right of the release details page.

i want to delete the whole release.

**Comment by scttcper** [comment] 2024-01-29 17:42
duplicate of #5701 we don't plan on allowing deletion of releases currently

**Closed by scttcper** 2024-01-29 17:42 UTC
Labels: Product Area: Issues, Waiting for: Product Owner
