### ISSUE TITLE
Missing support for SMTP with SSL

### ISSUE THREAD

**Issue by alexandervlpl** [getsentry/sentry#4252] opened 2016-10-01 17:52 UTC
See [forum topic](https://forum.sentry.io/t/smtp-connection-timeout-with-correct-email-config/180).

It turns out Sentry only supports TLS (and not SSL) for outgoing email. This is not immediately apparent (or documented). Settings like the ones below (though correct in Django) don't actually work in Sentry:

```
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.privateemail.com'
EMAIL_HOST_USER = 'info@ookmijnbedrijf.nl'
EMAIL_HOST_PASSWORD = '***'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
SERVER_EMAIL = EMAIL_HOST_USER
```

When I try to send a test email I get this:

**Connection unexpectedly closed: timed out**

**Comment by tkaemming** [comment] 2016-10-07 22:11
Looks like [SSL support was introduced in Django 1.7](https://github.com/django/django/commit/59ebe39812858ba37e83ab0ee886f676980d472d), but [we're stuck on Django 1.6 for the time being](https://github.com/django/django/commit/48e0866705994b976ec19f81cd42b481efe29c55), so this might be case for a while, unfortunately.

**Comment by mattrobenolt** [comment] 2016-10-07 23:11
Oh, TIL. I was assuming this would be an easy fix that I somehow overlooked when porting this stuff to use options. :(

**Comment by tkaemming** [comment] 2016-10-07 23:15
> I was assuming this would be an easy fix that I somehow overlooked when porting this stuff to use options.

Me too — I was halfway through implementing it, then looked at the Django source for what the SSL constructor parameter to the email backend was… and realized it wasn't there. 😕

**Comment by dirkdevriendt** [comment] 2016-10-20 17:20
We have a nice case as well :-)
I "borrowed" from https://github.com/creativ/docker-sentry-aws-ses to set Sentry up with SSL support:

- install `django-smtp-ssl==1.0`
- add `    SENTRY_OPTIONS['mail.backend'] = 'django_smtp_ssl.SSLEmailBackend'` to `sentry.conf.py`
- use appropriate ENV variables

Seemed like all was well, since a mail sent from https://.../manage/status/mail/ "Send a test mail" yields no errors and the test mail arrives

However: when I go on https://.../account/settings/ and click a "Resend Verification Email" link, I get the error below. So it seems different mail function have different levels of SSL support?

Should I make a separate issue for this?

```
SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
  File "celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "sentry/tasks/email.py", line 72, in send_email
    send_messages([message])
  File "sentry/utils/email.py", line 396, in send_messages
    sent = connection.send_messages(messages)
  File "django/core/mail/backends/smtp.py", line 87, in send_messages
    new_conn_created = self.open()
  File "../django_smtp_ssl.py", line 12, in open
    local_hostname=DNS_NAME.get_fqdn())
  File "python2.7/smtplib.py", line 801, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "python2.7/smtplib.py", line 807, in _get_socket
    new_socket = ssl.wrap_socket(new_socket, self.keyfile, self.certfile)
  File "python2.7/ssl.py", line 933, in wrap_socket
    ciphers=ciphers)
  File "python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
```

**Comment by alexandervlpl** [comment] 2017-03-28 15:08
@dirkdevriendt : thanks for the workaround! Unfortunately, I can't get this to work. `django-smtp-ssl==1.0` is installed and my `sentry.conf.py` looks like this now:

```
SENTRY_OPTIONS['mail.backend'] = 'django_smtp_ssl.SSLEmailBackend'
SENTRY_OPTIONS['mail.host'] = 'mail.domain.com'
SENTRY_OPTIONS['mail.port'] = 465
SENTRY_OPTIONS['mail.username'] = 'noreply@domain.com'
SENTRY_OPTIONS['mail.password'] = '*****'
SENTRY_OPTIONS['mail.use-tls'] = False
SENTRY_OPTIONS['mail.from'] = SENTRY_OPTIONS['mail.username']
SENTRY_OPTIONS['mail.list-namespace'] = 'domain.com'
```

I no longer see any errors when sending a test email or account verification email. According to my sentry worker log, messages are sent:

```
15:00:59 [INFO] sentry.mail: mail.sent (message_id='<20170328150059.13381.76920@domain.com>')
```

However, no emails are actually received and it looks like something is failing silently. What am I doing wrong? Does anyone have any tips?

**Comment by alexandervlpl** [comment] 2017-03-30 19:32
Thanks for the tip! I switched on TLS, but not luck. Something is still failing silently. What version of Sentry are you running?

In the meantime, back to refreshing the Sentry page on my phone to avoid missing new issues. :frowning_face:

@tkaemming , @mattrobenolt : it would be great to have some kind of officially documented workaround for this, while we wait for the jump to a newer Django version. In any case, thanks for your hard work!

**Comment by alexandervlpl** [comment] 2017-03-31 08:17
Actually, I found my workaround: the excellent [Slack plugin](https://slack.com/apps/A0F814BEV-sentry)!

**Comment by tyan4g** [comment] 2017-05-11 01:46
so the problem is still there??I want to use sentry.io but , sentry io is kind of slow in my place .and sometimes it's blocked .so we need to deploy on my local server..

**Comment by dcramer** [comment] 2017-05-11 16:36
@tyan4g we're still on Django 1.6, so it looks like this is sitll a problem

**Comment by jstdoit** [comment] 2017-07-26 05:43
+1

**Comment by l33klin** [comment] 2017-11-08 07:19
+1

**Comment by ElliotCui** [comment] 2017-11-22 16:02
@tkaemming 
I have the same problem, too. 
And I tried to solve this buy only updating django from 1.6 to 1.11, in my self built docker image.
But after i finished updating django. 

```
$ docker run --rm sentry config generate-secret-key
$ docker run -it --rm -e SENTRY_SECRET_KEY='t7*-1&t*e_o-wyw+y4g6v!95qb9b_77tdc5&ppfvr!+xz^xgu%' --link sentry-postgres:postgres --link sentry-redis:redis sentry upgrade
```
The error occurs like this:
```
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 11, in <module>
    sys.exit(main())
...
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/importer.py", line 44, in load_module
    mod = self._load_module(fullname)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/importer.py", line 62, in _load_module
    from django.utils.importlib import import_module
sentry.runner.importer.ConfigurationError: ImportError: No module named importlib
...
```

How should I solve this problem or I can just wait for sentry docker image updating ?
Wish your reply. Thx!

**Comment by mattrobenolt** [comment] 2017-11-22 17:48
> And I tried to solve this by only updating django from 1.6 to 1.11, in my self built docker image.

This is definitely not going to work, as you found out. This is not a trivial change, and in Django land, this is 5 major releases. There are many reasons why we’re locked into 1.6. 

> How should I solve this problem or I can just wait for sentry docker image updating ?

If `django-smtp-ssl` doesn’t work or solve the problem, there’s unfortunately nothing we’re going to be able to do until we upgrade Django ourselves, which will be a long time away, if ever.

**Comment by lilydjwg** [comment] 2018-01-26 11:35
This issue happens to me, and I find the name of this setting are surprisingly confusing.

There are two kinds of encryption a SMTP connection can use:

* Use a `STARTTLS` command over a plain connection to negotiate. This scheme can reuse the port for unencrypted traffic
* Use a dedicated port like HTTPS, and do TLS handshake on connecting. All SMTP commands are encrypted. This is usually referred to as `SMTPS`.

Sentry's `mail.use-tls = True` actually means the former, but the doc doesn't say that. I configured a SMTPS port for it, so Sentry tried to talk plain commands while the mail server expected a TLS handshake, and it hanged there. Setting the right port solves the issue.

**Comment by lambdaq** [comment] 2018-04-13 10:04
incase anyone else is having the same problem:

`smtp.exmail.qq.com:465` only supports SSL, so you will get an error:

    SMTPServerDisconnected 
    sentry.tasks.email.send_email
    errorConnection unexpectedly closed: timed out

**Comment by RichardW42** [comment] 2018-04-27 02:01
@Qinzm Maybe you can try set port to 25.

**Comment by Wirone** [comment] 2018-07-02 14:12
@dirkdevriendt's solution works for me. Just added package to requirements, changed mailer backend in config, started everything with `--build` and messages were sent :)

But this is not something I expected, it should work out of the box ;-)

**Comment by duxinxiao** [comment] 2018-11-09 07:16
So it's still not resolved? I think TLS support is really important

**Comment by ElliotCui** [comment] 2018-11-09 09:07
@duxinxiao 
Use TLS and 587 port solve the problem
```bash
$> docker run -d --name cb-sentry \
  -e SENTRY_SECRET_KEY='s7*-1&t*e_o-wyw+y4g6v!95qb9b_77tdc5&ppfvr!+xz^xgu%' \
  -e SENTRY_EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'\
  -e SENTRY_EMAIL_HOST='smtp.exmail.com' \
  -e SENTRY_EMAIL_PORT=587 \
  -e SENTRY_EMAIL_USER='noreply@xxx.com' \
  -e SENTRY_EMAIL_PASSWORD='xxxx' \
  -e SENTRY_EMAIL_USE_TLS=True \
  -e SENTRY_SERVER_EMAIL='noreply@xxx.com' \
  -e SENTRY_TIME_ZONE='Asia/Shanghai' \
  --link sentry-redis:redis \
  --link sentry-postgres:postgres \
  sentry
```

**Comment by duxinxiao** [comment] 2018-11-10 07:49
@ElliotCui Thanks! I will have a try

**Comment by Wirone** [comment] 2018-11-16 17:37
@ElliotCui how TLS can solve SSL issue? These are [2 different protocols](https://luxsci.com/blog/ssl-versus-tls-whats-the-difference.html). Our mail server does not support TLS and we had to create custom Sentry image supporting SSL (based on [this comment](https://github.com/getsentry/sentry/issues/4252#issuecomment-255170587)) and we're using it for few months. Your advice isn't related to this issue, which explicitly states that there isn't support for SSL (and it's true).

**Comment by Eduard-gan** [comment] 2019-02-08 13:37
I don't know why by for Yandex i use 465 port and SSL in postclient and the only config that worked for me on Sentry 9 is : 

```
mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
mail.host: 'smtp.yandex.ru'
mail.port: 25
mail.username: 'sentry@mydomain.ru'
mail.password: 'mypassword'
mail.use-tls: true
mail.from: 'sentry@mydomain.ru'
```

**Comment by chreck** [comment] 2019-12-04 12:27
If you look into it more deeply what django with the SMTP library does you you will come to the following.

**Not working example**
The example below does not work, because the following read on the socket gives no answer and runs in a timeout. My guess is that the socket channel is not encrypted yet and so it does not work correctly. Run python shell for testing.

```
import smtplib
import socket
socket.setdefaulttimeout(10)
smtpObj = smtplib.SMTP('smtp.yandex.ru', 465)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "smtplib.py", line 318, in connect
    (code, msg) = self.getreply()
  File "smtplib.py", line 366, in getreply
    + str(e))
smtplib.SMTPServerDisconnected: Connection unexpectedly closed: timed out
```

**Working example**

If you connect over port 25 it is possible to do a login and send the mail. The example is not complete but the connection can be established.

```
import smtplib
import socket
socket.setdefaulttimeout(10)
smtpObj = smtplib.SMTP('smtp.yandex.ru', 25)
smtpObj.starttls()
```

**Comment by AndreyMashukov** [comment] 2020-05-26 18:07
###############
# Mail Server #
###############

mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
mail.host: 'smtp.yandex.ru'
mail.port: 587
mail.username: 'username@your.host'
mail.password: 'password'
mail.use-tls: true
# The email address to send on behalf of
mail.from: 'username@your.host'

It works for me!

**Comment by Wirone** [comment] 2020-05-26 20:52
@AndreyMashukov TLS != SSL 🙄 It was pointed out before.

**Comment by caugner** [comment] 2020-07-03 23:09
To me it seems that Sentry only supports **START**TLS, whereas TLS is actually **not** supported and SSL (the predecessor of TLS) should not be necessary.

**Comment by BYK** [comment] 2020-09-04 19:08
Closing this as we are now on Django 1.11 which should support both SSL and TLS (and you really shouldn't be using SSL 🙂 )

**Closed by BYK** 2020-09-04 19:08 UTC
