### ISSUE TITLE
"Monitor failure" not bringing up search results

### ISSUE THREAD

**Issue by rachrwang** [getsentry/sentry#51093] opened 2023-06-15 21:42 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Go to the Sentry organization, and click into custom search.

See an example of this search working:
<img width="741" alt="Screenshot 2023-06-15 at 2 38 00 PM" src="https://github.com/getsentry/sentry/assets/82916311/0ce44184-396e-41ca-8157-b4646d0eab96">

When the user searches for the key words "Monitor failure" - nothing shows up:
<img width="921" alt="Screenshot 2023-06-15 at 2 38 34 PM" src="https://github.com/getsentry/sentry/assets/82916311/1169fc58-9c69-4f62-9957-de9424738647">

### Expected Result

Issues like this one should be showing up in the search (they do show up in the Issue Stream without any search terms added):
<img width="1099" alt="Screenshot 2023-06-15 at 2 41 45 PM" src="https://github.com/getsentry/sentry/assets/82916311/7f02c860-f8d0-4c2a-b71d-929442d5aeae">

### Actual Result

See above

### Product Area

Issues

**Comment by wedamija** [comment] 2023-06-15 22:03
Duplicate of https://github.com/getsentry/sentry/issues/50345

**Closed by wedamija** 2023-06-15 22:03 UTC
