### ISSUE TITLE
When setting up Sentry for a frontend app and a backend app, should I create a single Sentry project and use the same DSN for both apps? Should I create two separate Sentry projects? What are the benefits/drawbacks of each option?

### ISSUE THREAD

**Issue by edgariscoding** [getsentry/sentry#62029] opened 2023-12-19 20:27 UTC
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

I set up Sentry for our frontend app and our backend app recently. While reading some Sentry docs I realized that the docs suggest using the same DSN for both apps. 

I have already created two separate Sentry projects and set them up individually. 

This is still early enough that I can make the change. It would also make it easier to use Sentry rather than keep having to switch projects. 

### How are you getting stuck?

Should I change this so that both the Angular front end and the ASP.NET Core web api backend share the same DSN? 

Are there any benefits to combining? Any benefits to separating them?

Does distributed tracing work even if the two projects are separate?

### Where in the product are you?

Other

### Version

23.11.0.dev0

**Comment by bondress** [comment] 2023-12-21 07:47
Sentry Project Configuration Options
1. Single Sentry Project for Both Frontend and Backend Apps
Advantages:

Simplified Setup: Configure both frontend and backend applications to use the same Sentry project and DSN for consolidated error tracking.
Unified Error Monitoring: Easily monitor and manage errors from both apps in one location.
Ease of Correlation: Simplified tracing of issues across the entire application stack.
Considerations:

Limited Isolation: Frontend and backend errors are mixed, potentially making it harder to isolate specific issues.
Potential Clutter: Managing a large volume of errors might complicate the differentiation between frontend and backend issues.
2. Two Separate Sentry Projects for Frontend and Backend
Advantages:

Isolated Error Tracking: Independent projects for frontend and backend provide clear insights into respective app issues.
Granular Monitoring: Focus on each app's errors independently for precise debugging.
Considerations:

Complex Configuration: Requires setting up and managing two separate projects, potentially increasing maintenance overhead.
Correlation Challenges: Manually correlating frontend and backend errors without a unified view might require additional effort.
Distributed Tracing Consideration
In a Single Project: Distributed tracing is more seamless within a single project, enabling easier correlation of traces with errors across the entire application.

Across Separate Projects: Distributed tracing functionalities might have limitations when working across separate projects, potentially hindering the correlation of traces with errors.

Recommendation
Consider the following when choosing Sentry project configuration:

Simplicity and Consolidation: Use a single Sentry project for easy correlation and centralized tracking if seamless integration and correlation between frontend and backend errors are crucial.

Granularity and Isolation: Opt for two separate Sentry projects for distinct tracking and clearer isolation of frontend and backend issues if independent monitoring is a priority.

Configuring Distributed Tracing
In a Single Project: Provide guidance on setting up distributed tracing within a single Sentry project for optimal trace and error correlation.

Across Separate Projects: Mention limitations and potential challenges in achieving comprehensive distributed tracing across separate Sentry projects.

**Comment by hubertdeng123** [comment] 2023-12-22 17:33
Thank you for chiming in here @bondress. Summing it up pretty well. Does that answer your question @edgariscoding ?

**Comment by edgariscoding** [comment] 2023-12-22 17:42
Thanks @bondress!

@hubertdeng123 It does to an extent. It seems like either configuration works just fine, is there any guidance on what needs to be configured for distributed tracing to work if the projects are separated?

Also, regarding the point about having all issues mixed together in a scenario where two projects are combined into one, couldn't we add a dropdown filter to allow filtering by frontend and backend?

We already do that in the Performance dashboard, there's frontend and backend tabs at the top. 

<img width="634" alt="image" src="https://github.com/getsentry/sentry/assets/12093243/b31cd083-a7ae-47cb-9654-96fc5d4de2f0">

Seems like this would be a fairly easy filter to add to the Issues list. Maybe even add an icon to differentiate frontend vs backend issues in the list of rows below when the user is displaying frontend and backend issues mixed.

**Comment by hubertdeng123** [comment] 2024-01-02 19:24
Let's see what the issues team has to say about this.

**Comment by malwilley** [comment] 2024-01-02 20:57
@edgariscoding I'm curious, where in the docs does it encourage using the same DSN for the backend and frontend? On the [docs page for projects](https://docs.sentry.io/product/projects/), it says this:

> A Project represents your service or application in Sentry. For example, you might have separate projects for your API server and frontend client.

Projects are generally scoped to a particular service, so I think the way you have it currently set up is correct. Distributed tracing was designed to work across projects, so that's not a concern.

**Comment by edgariscoding** [comment] 2024-01-02 21:26
On this tutorial page for setting up backend monitoring:

https://docs.sentry.io/product/sentry-basics/integrate-backend/getting-started/

Step 3.4 states:

“ In the Sentry SDK configuration, enter the DSN key value you copied from the
project
Represents your service in Sentry and allows you to scope events to a distinct application.
created in the project creation tutorial<https://docs.sentry.io/guides/integrate-frontend/create-new-project/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2Fproduct%2Fsentry-basics%2Fintegrate-backend%2F%3Foriginal_referrer%3Dhttps%253A%252F%252Fdocs.sentry.io%252F>.”

The link to the project creation tutorial links to the frontend monitoring tutorial. So I understood this step to mean that I should use the same DSN key on both front and backends.

On Jan 2, 2024, at 2:57 PM, Malachi Willey ***@***.***> wrote:

﻿

@edgariscoding<https://github.com/edgariscoding> I'm curious, where in the docs does it encourage using the same DSN for the backend and frontend? On the docs page for projects<https://docs.sentry.io/product/projects/>, it says this:

A Project represents your service or application in Sentry. For example, you might have separate projects for your API server and frontend client.

Projects are generally scoped to a particular service, so I think the way you have it currently set up is correct. Distributed tracing was designed to work across projects, so that's not a concern.

**Comment by malwilley** [comment] 2024-01-03 18:54
@edgariscoding ah I see. I _believe_ the intention of that part of the docs was not that you should use the frontend DSN, but that the frontend tutorial shows you how to create a project, which you also need to do for creating the backend project.

I'll close this since the question is answered. And a ping to @lizokm that the docs here are a bit misleading, we could certainly improve that page.

**Closed by malwilley** 2024-01-03 18:54 UTC
Labels: Product Area: Issues, Waiting for: Product Owner
