### ISSUE TITLE
Jira sync should set issue resolved in next version

### ISSUE THREAD

**Issue by jboulter11** [getsentry/sentry#66363] opened 2024-03-05 21:52 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

We had a ticket which showed a regression introduced in v367.1.2.

1. Have one jira ticket linked to one sentry issue.  Both unresolved.
2. Set up Jira sync where marking Jira ticket as `Done` marks sentry issue as `Resolved`
3. Mark Jira ticket as done.
4. Sentry marks the issue as resolved.
5. Sentry reopens the issue (and therefore the Jira ticket) as regressed in 367.1.2, even though that's the version we already knew about when we marked resolved.
6. In Sentry, mark ticket as Resolved in Next Version

### Expected Result

Jira marked as Done should sync to Sentry as fixed in next version.

We'll pretty much never have the code shipped when we mark the ticket as done.  We want to mark it as done before we ship so it will tell us if it's indeed not yet fixed in when the next version ships.

### Actual Result

The Sentry issue was not marked as resolved in next version, it immediately re-opened for some reason.

![Screenshot by Dropbox Capture](https://github.com/getsentry/sentry/assets/6633472/81268d16-42f7-40f8-b59d-5262c0e5e22e)

### Product Area

Issues

### Link

https://dropbox.sentry.io/issues/5026221022/activity/?project=4505546600087552&project=4505546602381312&query=is:resolved&sort=freq&statsPeriod=30d&stream_index=3

**Comment by leedongwei** [comment] 2024-03-06 23:52
Hello. Definitely agree that this is not the right UX. We'll address it when we are reviewing our Jira integration.

**Comment by Dhrumil-Sentry** [comment] 2024-03-25 17:33
This ticket is a duplicate of an existing feature request: https://github.com/getsentry/sentry/issues/19673

Please use the ticket above to track this request. Closing this issue as a duplicate

**Closed by Dhrumil-Sentry** 2024-03-25 17:33 UTC
Labels: Product Area: Settings - Integrations
