### ISSUE TITLE
Capability to filter issues with one tag and not the other tag.

### ISSUE THREAD

**Issue by nimishsinghal** [getsentry/sentry#10761] opened 2018-11-26 12:58 UTC
## Summary
Lets say we have tags T1 and T2, we want to filter out issues which are part of T1 and not part of T2.

## Motivation
1) Incase of A/Bs we are pushing multiple tags, we want to filter issues with particular tag only. Is there a possible way to do this?
2) Find issues only in one particular browser and not in other browsers.

**Comment by tkaemming** [comment] 2018-11-26 19:31
This is more or less a duplicate of GH-2646, and something we're working on.

**Closed by tkaemming** 2018-11-26 19:31 UTC

**Comment by nimishsinghal** [comment] 2018-11-26 20:57
@tkaemming thanks for reply, just wanted to check if there is any work around for finding issues that are only happening in particular browser versions or with a particular tag. We require such use cases a lot while debugging the issues in production environment.

**Comment by tkaemming** [comment] 2018-12-05 01:04
Not at the moment — you can search for issues that happened in a particular version, but not exclusively that version. We're working towards being able to support this kind of query.
