### ISSUE TITLE
Migration 0015 fails on PostgreSQL when using different schema than “public”

### ISSUE THREAD

**Issue by jirutka** [getsentry/sentry#2916] opened 2016-03-26 21:28 UTC
When I use schema named `public` (owned by the sentry user, not postgres as is by default), everything works. But when I create a different schema, e.g. `main`, and add it to the `search_path` for the sentry user (i.e. on the DB side, not modifying any Sentry configuration), then running `sentry upgrade` on empty database fails at `0015_auto__add_field_message_project__add_field_messagecountbyminute_project`. The only difference is in the schema name and `search_path` on the DB side, all privileges and Sentry settings are exactly the same.

```log
sentry upgrade
...
Running migrations for sentry:
 - Migrating forwards to 0240_fill_onboarding_option.
 > sentry:0001_initial
 > sentry:0002_auto__del_field_groupedmessage_url__chg_field_groupedmessage_view__chg
 > sentry:0003_auto__add_field_message_group__del_field_groupedmessage_server_name
 > sentry:0004_auto__add_filtervalue__add_unique_filtervalue_key_value
 > sentry:0005_auto
 > sentry:0006_auto
 > sentry:0007_auto__add_field_message_site
 > sentry:0008_auto__chg_field_message_view__add_field_groupedmessage_data__chg_field
 > sentry:0009_auto__add_field_message_message_id
 > sentry:0010_auto__add_messageindex__add_unique_messageindex_column_value_object_id
 > sentry:0011_auto__add_field_groupedmessage_score
 > sentry:0012_auto
 > sentry:0013_auto__add_messagecountbyminute__add_unique_messagecountbyminute_group_
 > sentry:0014_auto
 > sentry:0014_auto__add_project__add_projectmember__add_unique_projectmember_project
 > sentry:0015_auto__add_field_message_project__add_field_messagecountbyminute_projec
Error in migration: sentry:0015_auto__add_field_message_project__add_field_messagecountbyminute_projec
[ERROR] Failed processing signal create_default_projects
Traceback (most recent call last):
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/receivers/core.py", line 31, in wrapped
    return func(*args, **kwargs)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/receivers/core.py", line 46, in create_default_projects
    verbosity=verbosity,
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/receivers/core.py", line 63, in create_default_project
    user = User.objects.filter(is_superuser=True)[0]
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 96, in __iter__
    self._fetch_all()
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    raise_the_exception(self.db, e)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 73, in inner
    return func(self, *args, **kwargs)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 21, in inner
    return func(self, *args, **kwargs)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 88, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 44, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: column auth_user.is_managed does not exist
LINE 1: ...th_user"."is_active", "auth_user"."is_superuser", "auth_user...
                                                             ^

SQL: SELECT "auth_user"."password", "auth_user"."last_login", "auth_user"."id", "auth_user"."username", "auth_user"."first_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."is_superuser", "auth_user"."is_managed", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."is_superuser" = %s  LIMIT 1
[ERROR] Unable to fetch internal project
Traceback (most recent call last):
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/utils/raven.py", line 59, in send
    project = Project.objects.get_from_cache(id=settings.SENTRY_PROJECT)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/models/manager.py", line 259, in get_from_cache
    result = self.get(**kwargs)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    raise_the_exception(self.db, e)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 73, in inner
    return func(self, *args, **kwargs)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 21, in inner
    return func(self, *args, **kwargs)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 88, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 44, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: column sentry_project.slug does not exist
LINE 1: SELECT "sentry_project"."id", "sentry_project"."slug", "sent...
                                      ^

SQL: SELECT "sentry_project"."id", "sentry_project"."slug", "sentry_project"."name", "sentry_project"."organization_id", "sentry_project"."team_id", "sentry_project"."public", "sentry_project"."date_added", "sentry_project"."status", "sentry_project"."first_event" FROM "sentry_project" WHERE "sentry_project"."id" = %s

Would you like to create a user account now? [Y/n]: ^C[ERROR] Unable to fetch internal project
Traceback (most recent call last):
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/utils/raven.py", line 59, in send
    project = Project.objects.get_from_cache(id=settings.SENTRY_PROJECT)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/models/manager.py", line 259, in get_from_cache
    result = self.get(**kwargs)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
    raise_the_exception(self.db, e)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 73, in inner
    return func(self, *args, **kwargs)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 21, in inner
    return func(self, *args, **kwargs)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 88, in inner
    return func(self, sql, *args, **kwargs)
  File "/usr/lib/bundles/sentry/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 44, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: column sentry_project.slug does not exist
LINE 1: SELECT "sentry_project"."id", "sentry_project"."slug", "sent...
                                      ^

SQL: SELECT "sentry_project"."id", "sentry_project"."slug", "sentry_project"."name", "sentry_project"."organization_id", "sentry_project"."team_id", "sentry_project"."public", "sentry_project"."date_added", "sentry_project"."status", "sentry_project"."first_event" FROM "sentry_project" WHERE "sentry_project"."id" = %s
Aborted!
```

**Comment by mattrobenolt** [comment] 2016-03-26 22:42
Do you mean you did an `ALTER ROLE sentry SET search_path TO main;` ? Or something else?

Can you provide the sql used to create your roles/schema? Also your `DATABASES` configuration inside of `sentry.conf.py`? (obviously censor password, etc)

**Comment by jirutka** [comment] 2016-03-26 22:47
> Do you mean you did an ALTER ROLE sentry SET search_path TO main; ? Or something else?

Actually I have this in global (i.e. cluster-wide) configuration: `search_path = '"$user", main, public'`.

> Can you provide the sql used to create your roles/schema?

```sql
CREATE SCHEMA main AUTHORIZATION sentry;
```

> Also your DATABASES configuration inside of sentry.conf.py?

```py
DATABASES = {
    'default': {
        'ENGINE': 'sentry.db.postgres',
        'NAME': 'sentry',
        'USER': 'sentry',
        'PASSWORD': 'top-secret',
        'HOST': 'db.example.org',
        'PORT': '5432',
    }
}
```

**Comment by mattrobenolt** [comment] 2016-03-26 23:28
When you run the migration, where does it put the tables? It obviously created some since it made it past 0001. Did they go into the `public` schema? Or correctly into `main`?

Also, we have never tested this path before, so not sure what could be wrong without digging into it, which is why I'm asking questions. :)

**Comment by mattrobenolt** [comment] 2016-03-26 23:32
For reference, it's actually failing here: https://github.com/getsentry/sentry/blob/master/src/sentry/receivers/core.py#L63, not inside the migration itself.

**Comment by jirutka** [comment] 2016-03-27 00:29
They where created correctly in the `main` schema.

**Comment by mattrobenolt** [comment] 2016-03-27 18:33
Can you dump a `pip freeze` something seems odd here unrelated to the schema. Since it shouldn't even be running that code for that migration.

**Comment by mattrobenolt** [comment] 2016-04-22 21:41
@jirutka Any more information here? If not, I'm going to close this out since I'm not sure what we could be doing wrong here and unable to reproduce.

**Comment by mdaniel** [comment] 2016-09-07 04:00
I can reproduce this for you, using [docker-compose](https://github.com/docker/compose#readme) and the most recent image out on hub

```sh
#! /bin/bash
cat > docker-compose.yml<<COMP
---
version: '2'
services:
  sentry:
    image: sentry:8.7.0
    command: |
      bash -c 'set -x;
       # give PG time to boot up
       sleep 15
       sentry upgrade -v 1000 --traceback --noinput
       '
    environment:
      - SENTRY_POSTGRES_HOST=postgres
      - SENTRY_POSTGRES_PORT=5432
      - SENTRY_DB_USER=sentry
      - SENTRY_DB_NAME=sentry
      - SENTRY_DB_PASSWORD=hunter22
      - SENTRY_SECRET_KEY=s00persekr1t
      - SENTRY_REDIS_HOST=redis
      - SENTRY_REDIS_PORT=6379
    links:
      - redis
      - "db:postgres"
    depends_on:
      - redis
      - db
  redis:
    image: redis:3
    expose:
      - "6379"
  db:
    image: postgres:9.5
    expose:
      - "5432"
    volumes:
      - ./pginit.sql:/docker-entrypoint-initdb.d/sentry.sql
    environment:
      - POSTGRES_DB=sentry
COMP
cat > pginit.sql<<SQL
CREATE USER sentry WITH ENCRYPTED PASSWORD 'hunter22' LOGIN;
GRANT sentry TO postgres;
CREATE SCHEMA sentry AUTHORIZATION sentry;
SQL
docker-compose up
```

One will observe the error in both the sentry logs as well as the error logged by PG:
```
sentry_1  | Error in migration: sentry:0015_auto__add_field_message_project__add_field_messagecountbyminute_projec
sentry_1  |  - Sending post_syncdb signal for sentry: ['FilterValue', 'MessageFilterValue', 'MessageCountByMinute', 'GroupedMessage', 'Project', 'MessageIndex', 'User', 'Message', 'ProjectMember']
...>8--snip-->8...
sentry_1  | ProgrammingError: column auth_user.is_managed does not exist
sentry_1  | LINE 1: ...th_user"."is_active", "auth_user"."is_superuser", "auth_user...
```

It's kind of discouraging that South doesn't choose to bring the upgrade to a halt on the first `ProgrammingError` since I would not expect anything beyond that exception to go very well.

_You can press control-c to bring down the 3 docker containers it starts_

**Comment by dcramer** [comment] 2016-09-07 04:02
I'm going to close this issue in an effort to remove inactive tickets. We're open to pull requests here, but the core issue identified here is not currently a feature we will be prioritizing internally.

**Closed by dcramer** 2016-09-07 04:02 UTC

**Comment by mdaniel** [comment] 2016-09-07 04:54
_apologies for the email this is going to send, but_

If someone finds this ticket and wants to run sentry on Amazon's RDS, the magic sauce seems to be:

```sql
GRANT ALL PRIVILEGES ON DATABASE sentry TO sentry; -- substituting your own db and user, of course
GRANT ALL PRIVILEGES ON SCHEMA public TO sentry;
```
(as RDS does not give out the "superuser" role, but those statements appear to be a close enough approximation for South to complete)
