### ISSUE TITLE
Slack Integration: Interacting with notifications displays lots of escaped HTML

### ISSUE THREAD

**Issue by bgribble** [getsentry/sentry#15603] opened 2019-11-14 15:05 UTC
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

We have a rule configured to send notifications to a specific Slack channel for a subset of our Sentry alarms.  When we interact with the notification by clicking "Resolve", "Ignore", or selecting an assignee, the displayed notification is replaced by several hundred lines of escaped literal HTML:

<img width="760" alt="Screen Shot 2019-11-14 at 9 44 53 AM" src="https://user-images.githubusercontent.com/1790529/68867300-9831a080-06c3-11ea-9505-9c41151a599c.png">

(and several pages more of similar)

I'm guessing that because of the Cloudflare reference in the header of the HTML, this is an API call under the hood that is returning an HTML-formatted error message instead of the expected JSON payload. 

## Steps to Reproduce

Click on Ignore, Resolve, or select a person to assign in any notification that is displayed in the Slack channel. 

## Configuration

Here's the rule configuration for these notifications: 

<img width="895" alt="Screen Shot 2019-11-14 at 10 03 18 AM" src="https://user-images.githubusercontent.com/1790529/68868789-1f801380-06c6-11ea-9de8-5d4b858d9cbe.png">

**Comment by manuzope** [comment] 2019-11-20 17:55
Hey @bgribble, I'm unable to reproduce this on my account.

You might be right about an error message being returned.

Would you be able to bring up this issue with our support team by logging into your account and then, in the left nav, clicking `Help -> Contact Support`. In the ticket, if you could mention your organization and the time that you ran into the issue, it'll help us debug the issue. A video of you running into the issue might be helpful too so that we can see the complete error message. Also, would be good to put down if this happens consistently or intermittently.

Thanks!

**Comment by bgribble** [comment] 2019-11-20 18:55
When I couldn't find a Help link anywhere, I checked with our platform team and found that we are running Sentry on-premise, version 9.0.0, so my mistake thinking we were using the cloudish version.  I don't know if that changes anything in your response. The only help-like thing I can find through our version of Sentry is a link to the "Support Forum", is that what you mean?

**Comment by BYK** [comment] 2019-11-20 19:04
@bgribble - hi, https://forum.sentry.io/c/on-premise is the place for on-premise discussion and support, yeah.

Gonna say 9.0.0 sounds pretty old (latest stable is 9.1.2 and we are currently trialing v10 beta) so I'd recommend upgrading to 9.1.2 first to see if that fixes the issue. There are at least 2 fixes related to Slack after 9.0.0 if I remember correctly.

I'll be closing this issue in favor of a forum discussion so feel free to open a new topic there if upgrading doesn't fix your issue.

**Closed by BYK** 2019-11-20 19:04 UTC
Labels: Component: Integrations
