### ISSUE TITLE
Download Debug Files with Team Admin role for Business Plans

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#55975] opened 2023-09-11 08:28 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

- Having a Business Plan, go to Organization Settings > Membership > Debug Files Access, set the role required to Admin
![image](https://github.com/getsentry/sentry/assets/81985895/f626fbe4-e116-492b-a1d9-d21666cbc05c)

- Give an organization member the role of "Team Admin" to an Organization team
![image](https://github.com/getsentry/sentry/assets/81985895/22002d3b-6fd9-45d1-9e95-68f48eee55b2)

- As that member, got to a project that their team owns > Debug Files > Download

### Expected Result

Since the minimum role requirement is Admin, the Team Admin should be able to download the project's Debug Files.

### Actual Result

The team admin is unable to download the debug files and sees this message instead:
![image](https://github.com/getsentry/sentry/assets/81985895/7614ba81-4e68-4b69-aa79-b2f7f52cd060)

Since team admin/contributor roles were introduced, it is not possible to set someone's role as "Organization Admin", so the minimum role requirement to download debug files would have to be lowered, which is not desirable.

### Product Area

Settings - General

**Comment by Dhrumil-Sentry** [comment] 2023-09-11 16:07
This issue is a duplicate of https://github.com/getsentry/sentry/issues/53919 and is in our backlog

**Comment by schew2381** [comment] 2024-09-27 19:21
> This issue is a duplicate of [#53919](https://github.com/getsentry/sentry/issues/53919) and is in our backlog

This GH issue is for downloading files, while the linked one is for deleting them. This is actually a duplicate of https://github.com/getsentry/sentry/issues/78229

**Closed** 2024-09-27 19:20 UTC
Labels: Product Area: Settings - Projects
