### ISSUE TITLE
sentry: unable to receive chunked part

### ISSUE THREAD

**Issue by a0923** [getsentry/sentry#14554] opened 2019-09-01 15:39 UTC
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/web/api.py", line 498, in post
    data = request.body
  File "/usr/local/lib/python2.7/site-packages/django/http/request.py", line 190, in body
    six.reraise(UnreadablePostError, UnreadablePostError(*e.args), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/site-packages/django/http/request.py", line 188, in body
    self._body = self.read()
  File "/usr/local/lib/python2.7/site-packages/django/http/request.py", line 244, in read
    six.reraise(UnreadablePostError, UnreadablePostError(*e.args), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/site-packages/django/http/request.py", line 242, in read
    return self._stream.read(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/middleware/proxy.py", line 66, in readinto
    chunk = self.fp.read(Z_CHUNK)
  File "/usr/local/lib/python2.7/site-packages/sentry/middleware/proxy.py", line 30, in readinto
    self._internal_buffer = uwsgi.chunked_read()
UnreadablePostError: unable to receive chunked part
15:33:50 [ERROR] sentry: unable to receive chunked part
47.75.222.66 - - [01/Sep/2019:15:33:46 +0000] "POST /api/2/store/ HTTP/1.1" 400 408 "-" "sentry.php.laravel/1.1.0"
103.17.213.243 - - [01/Sep/2019:15:36:06 +0000] "POST /api/2/store/ HTTP/1.1" 200 366 "-" "sentry.python/0.11.2"

**Comment by attaining** [comment] 2019-09-01 15:46
import sentry_sdk
sentry_sdk.init('http://0632d464242c427ba9367dc98b9b266a@xxxx.group:9000/2')
sentry_sdk.capture_exception(Exception("This is an example of an error message."))
print('end')
-----------------laravel 
Route::get('/debug-sentry', function () {
    throw new Exception('My first Sentry error!');
});
--------------logging.php
 'channels' => [
        'stack' => [
            'driver'            => 'stack',
            'channels'          => ['daily', 'sentry'],
            'ignore_exceptions' => false,
        ],......
        'sentry'   => [
            'driver' => 'sentry',
            'level'  => 'notice',
            'bubble' => true,
        ],
    ],

**Comment by yuriyprysyazhnyuk** [comment] 2019-09-06 16:58
![Screenshot from 2019-09-06 17-33-02](https://user-images.githubusercontent.com/25881449/64446147-bb970880-d0e0-11e9-8a8c-76fe14df6a82.png)
![Screenshot from 2019-09-06 17-32-47](https://user-images.githubusercontent.com/25881449/64446148-bb970880-d0e0-11e9-94fc-f714b3f3d402.png)

**Comment by jbbr** [comment] 2019-09-09 07:41
This seems to be fixed in https://github.com/getsentry/sentry-php/pull/877

I can confirm that I don't have any issues after upgrading sentry-php to 2.1.3

**Comment by BYK** [comment] 2020-10-22 20:50
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Closed by BYK** 2020-10-22 20:50 UTC
