### ISSUE TITLE
"Resolved in next release" doesn't seem to be working in some cases

### ISSUE THREAD

**Issue by teeberg** [getsentry/sentry#4072] opened 2016-09-02 18:18 UTC
I love the new "Resolved in next release" feature in later versions, but it doesn't seem to work in a few cases. We have one issue that has been resolved a month ago, but one user doesn't refresh the page and keeps triggering it. When I resolve an issue as resolved in the next release, the next time the same user hits the endpoint in the same release again, it gets marked as a regression:

![image](https://cloud.githubusercontent.com/assets/199071/18213691/5b3f0400-70fe-11e6-8460-b5787fb39509.png)

I think releases are set up properly:
![image](https://cloud.githubusercontent.com/assets/199071/18213706/72fbf008-70fe-11e6-8cca-fb393e1523b1.png)

Am I being stupid or is this a bug?

We're self-hosting.

**Comment by dcramer** [comment] 2016-09-02 18:20
What version? The regression message in the feed isn't what I'd expect to see if you're using the resolved in next release action (it should show a version).

**Comment by teeberg** [comment] 2016-09-02 18:24
We're running 8.7.0. I know what you mean, in some other cases it shows the release in both messages:
![image](https://cloud.githubusercontent.com/assets/199071/18214008/c0422642-70ff-11e6-848d-fc963ab73c18.png)
(You can't see it anymore here since it got replaced with the topmost one)

**Comment by eBeyond** [comment] 2016-10-18 08:37
I'm using the 8.10.0.dev0 on sentry.io and I've got the same issue. Release management is enabled and there are also releases shown but it's not possible to klick on the "Resolved in next release"

**Comment by dcramer** [comment] 2016-10-18 08:44
I'm closing this out as there's no obvious bug.

Resolved in Release requires the 'release' parameter to be passed in the SDK. Any other release data present is simply to inform the system of additional details.

**Closed by dcramer** 2016-10-18 08:44 UTC

**Comment by teeberg** [comment] 2016-10-18 15:45
I don't understand why this was closed. Am I sending bad data? We are always sending a release. What should I do to fix this?

**Comment by dcramer** [comment] 2016-10-18 17:17
This is closed because there's no issues with the sentry service and the we don't provide general support here. You're either not sending the data or you're using a misconfugured onpremise install.

**Comment by teeberg** [comment] 2016-10-18 17:19
alright... I'm fairly sure that we always send it, but I'll double-check
