### ISSUE TITLE
Discover showing an event in some time periods but not in longer time periods that encompass the shorter one

### ISSUE THREAD

**Issue by liamjones** [getsentry/sentry#61835] opened 2023-12-15 11:55 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Recorded a transaction at 100% sampling rate in an RN app
2. Within a few minutes, went to look at Discover to see the results

### Expected Result

Event visible in all timescales (from "last 1 hour" up to "last 90 days")

### Actual Result

Event visible in "last hour" to "last 14 days" but not in "last 30 days" or "last 90 days"

![image](https://github.com/getsentry/sentry/assets/521341/0ba32c6e-adf3-4cee-871e-1ed9c168d07b)
![image](https://github.com/getsentry/sentry/assets/521341/995170c7-8c81-4171-98f6-87190a0d9d29)

Event in question: https://living-with.sentry.io/discover/living-with-test:f07c9ddc018041f28f07c9e6ed866046/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&name=All+Events&project=5536148&query=JWT&sort=-timestamp&statsPeriod=1h&yAxis=count%28%29

### Product Area

Performance

### Link

https://living-with.sentry.io/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&name=All+Events&project=5536148&query=JWT&sort=-timestamp&statsPeriod=1h&yAxis=count%28%29

### DSN

https://1814908d7eb547a089103cb8b8c33cf4@o169785.ingest.sentry.io/5536148

**Comment by gggritso** [comment] 2023-12-19 16:27
@liamjones thanks for raising this! I'm having some trouble reproducing the issue, would you mind posting a link to the exact Discover view where you're expecting to see the event, but it's missing?

**Comment by liamjones** [comment] 2023-12-20 08:18
@gggritso Oh, I neglected to mention there was a search for `JWT`. Maybe that matters?

Just recreated it with a new event:

1 hr: https://living-with.sentry.io/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&name=All+Events&project=5536148&query=JWT&sort=-timestamp&statsPeriod=1h&yAxis=count%28%29

![image](https://github.com/getsentry/sentry/assets/521341/31c42b9b-fa02-4352-b3cc-21a272276ac6)

(again, shows the 20th's event in all views up to the "14 days" view)

30 days: https://living-with.sentry.io/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&name=All+Events&project=5536148&query=JWT&sort=-timestamp&statsPeriod=30d&yAxis=count%28%29

![image](https://github.com/getsentry/sentry/assets/521341/b7fbf87f-9f55-4e8a-847a-0cc46f48b1f7)

**Comment by gggritso** [comment] 2023-12-28 19:32
@liamjones gotcha, understood! Thanks for raising this, I reproduced it locally. The cause is Sentry's caching. For long time durations (> 30 days) we do some clever caching that creates a delay for new events of up to 15 minutes.

If this delay is a major problem, using lower time ranges (< 30 days) reduces the delay to 1 minute. In the meantime I'm working on removing the delay in #62348. Thanks for your patience!

**Comment by gggritso** [comment] 2024-01-04 19:53
@liamjones update: I merged a PR that makes the caching _slightly_ more clever. If you open the Discover page at 5:58 you'll get all the up-to-date events, but those results will be cached until the next 15 minute interval (i.e., until 6:00 in this case), so any event sent in at 5:59 won't show up until 6:00 when the cache expires.

As usual, you can still drop down to lower time ranges to get more up-to-date individual events. That's the best we can do for now. Thanks!

**Closed by gggritso** 2024-01-04 19:53 UTC
Labels: Product Area: Discover

**Comment by liamjones** [comment] 2024-01-05 08:27
Thanks @gggritso!
