### ISSUE TITLE
cannot delete release

### ISSUE THREAD

**Issue by webdq** [getsentry/sentry#19629] opened 2020-06-30 07:49 UTC
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

cannot delete release

## Steps to Reproduce

1. the release has an issues 
2. go to page ISSUES , delete the issues
3. go to page RELEASE , delete the release
4. delete faild , "This release is referenced by active issues and cannot be removed."

### What you expected to happen

delete release success

**Comment by tengos** [comment] 2020-07-17 04:03
me too

**Comment by BYK** [comment] 2020-10-26 11:06
Duplicate of #5701

**Closed by BYK** 2020-10-26 11:06 UTC
