### ISSUE TITLE
Stack trace “tooltip” makes it difficult to navigate Issues view

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#70857] opened 2024-05-14 15:02 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Reported by user:
When I look at my unresolved issues in the “Issues” page, hovering over an issue link will show a stack trace popup.

If I then try to look at another issue — say the one immediately above or below it — that first popup continually appears, and blocks my ability to click on that link.  I can get the bug to happen at a variety of sizes. If I make the window too small, however, the tooltip doesn’t appear at all.

https://github.com/getsentry/sentry/assets/99350819/590015fa-4863-43f5-bb17-763731cd78c4

Video above was reproduced in a minimized window.

### Expected Result

I should be able to click on the Error above the TypeError.

### Actual Result

I can't click on the Error above the TypeError.

### Product Area

Issues

### Link

https://org2-w7.sentry.io/issues/?statsPeriod=90d

**Comment by roggenkemper** [comment] 2024-12-11 20:53
Can't reproduce this right now so closing the issue. feel free to re-open if this pops back up

**Closed by roggenkemper** 2024-12-11 20:53 UTC
Labels: Type: Design, Component: UI, Product Area: Issues
