### ISSUE TITLE
MS Team integration doesn't send Welcome message to General channel

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#66678] opened 2024-03-11 10:30 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to integrations, select the Teams integration and install it by following the installation guide: https://docs.sentry.io/product/integrations/notification-incidents/msteams/

2. According to our documentation, Teams should send a Welcome message to the General channel, and users should be able to click on Complete setup there

3. The Welcome message is never sent

### Expected Result

Users should be able to complete their installation by clicking on Complete Setup

### Actual Result

Since the message is never sent, the integration cannot be successfully installed

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment] 2024-03-12 21:06
We've linked this to a related issue and will investigate this

**Comment by Fwang36** [comment] 2024-03-28 18:49
Hey @Dhrumil-Sentry,

Can we have an update on this issue?  I received a request in Support of this exact problem, and looking through other tickets, I see another recent ticket as well.

[Link to my Zendesk ticket](https://sentry.zendesk.com/agent/tickets/117418)

**Comment by ykamo001** [comment] 2024-03-28 23:39
Hi! Thank you for bringing this to our attention, I'll take a look at this and notify here when the problem is fixed.

**Comment by Dhrumil-Sentry** [comment] 2024-04-01 21:49
@dalnoki @Fwang36 - @ykamo001 has applied a fix for this problem, Can you please let the user know about this

**Comment by llama0815** [comment] 2024-04-02 11:11
I was struggling with this too. I had to remove all traces of Sentry from MSTeams. After a fresh install I got the welcome message in the channel.

**Comment by alxsavard** [comment] 2024-04-02 19:38
I'm seeing this issue as well. The Sentry post is going to a personal chat even if I select "add to a team". Not sure if it's the same issue or not 🤔

**Comment by ykamo001** [comment] 2024-04-02 20:53
@alxsavard please see if this post helps: https://github.com/getsentry/sentry/issues/66130#issuecomment-2016161538

**Comment by madan** [comment] 2024-04-05 17:05
> @alxsavard please see if this post helps: [#66130 (comment)](https://github.com/getsentry/sentry/issues/66130#issuecomment-2016161538)

Works after following the post and re adding the integration

**Closed** 2024-04-08 16:04 UTC
Labels: Product Area: Settings - Integrations
