### ISSUE TITLE
Permissions Error when Adding "Monitors" as Admin

### ISSUE THREAD

**Issue by hexa2k9** [getsentry/sentry#42709] opened 2023-01-02 11:13 UTC
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.10.0

### Steps to Reproduce

We experience permission based Issues when adding "Monitors" in Sentry 22.10.0. When adding a Monitor while being Logged in as a User having "Admin" Permissions on our Org (Sentry On Premises running on GKE) we receive running the following Request through the Sentry UI:

URL: `https://<redacted>/api/0/organizations/<redacted>/monitors/`

Payload: 
```json
{"project":"<redacted>","name":"Test as Admin","type":"cron_job","config":{"max_runtime":"30","schedule_type":"crontab","schedule":"0 4 * * *","checkin_margin":"5"}}
```

Once the Monitor was added (as Manger or Owner) it's still available to be edited as an Admin. From the [Docs perspective on Permissions](https://docs.sentry.io/product/accounts/membership/) I would expect this Functionality to be available as Admin

### Expected Result

Same as when running the Request as "Manager":

Response: 

```json
{
    "id": "nnnnnnnn-nnnn-nnnn-nnnn-nnnnnnnnnnnn",
    "status": "active",
    "type": "cron_job",
    "name": "Test as Manager",
    "config": {
        "schedule_type": "crontab",
        "schedule": "0 4 * * *",
        "checkin_margin": 5,
        "max_runtime": 30
    },
    "lastCheckIn": null,
    "nextCheckIn": null,
    "dateCreated": "2023-01-02T11:06:04.161090Z",
    "project": {
        "id": "18",
        "slug": "<redacted>",
        "name": "<redacted>",
        "isPublic": false,
        "isBookmarked": false,
        "color": "#bf3f5c",
        "dateCreated": "2022-11-25T16:44:50.192637Z",
        "firstEvent": "2022-11-30T10:10:46.173450Z",
        "firstTransactionEvent": true,
        "hasSessions": false,
        "hasProfiles": false,
        "features": [
            "alert-filters",
            "custom-inbound-filters",
            "data-forwarding",
            "discard-groups",
            "minidump",
            "rate-limits",
            "servicehooks",
            "similarity-indexing",
            "similarity-indexing-v2",
            "similarity-view",
            "similarity-view-v2",
            "releases"
        ],
        "status": "active",
        "platform": "php",
        "isInternal": false,
        "isMember": true,
        "hasAccess": true,
        "avatar": {
            "avatarType": "letter_avatar",
            "avatarUuid": null
        }
    }
}
```

### Actual Result

Response when running Request as "Admin":
```json
{
    "detail": "You do not have permission to perform this action."
}
```

**Comment by hexa2k9** [comment] 2023-01-03 14:10
Meanwhile we've upgraded to Sentry 22.11.0 (latest available through the [Helm Chart](https://github.com/sentry-kubernetes/charts/tree/develop/sentry). 

The issue persists.

**Comment by davidenwang** [comment] 2023-01-03 15:35
Hey @hexa2k9, thanks for writing in about this issue. We have recently been doing some permissions changes on the crons product so it is likely we may have missed something here. We will add this to our taskboard and see what's going on.

**Comment by evanpurkhiser** [comment] 2023-01-19 00:39
Hey @hexa2k9, I was investigating this but can't seem to reproduce. Is there any chance you could record a video of how you're able to produce the permissions error? Thanks!

**Comment by hexa2k9** [comment] 2023-01-20 08:04
Hi @evanpurkhiser, please Videos here at the Links below.

Create Monitor as Admin: https://drive.google.com/file/d/1AsERdMFHnB7twZbJQ_hFY0bYQiGRHdjq/view?usp=share_link
I did another one with the same settings after changing permissions for my test user to Manager (available here: https://drive.google.com/file/d/1E5pvX4LD01LsBO_bEewpzL_m0Ko94PV9/view?usp=share_link)

**Comment by gaprl** [comment] 2023-08-01 20:47
Hey @hexa2k9, we're closing this issue for now as we are not able to reproduce it, however, please let us know if you're still facing issues and we can reopen. Thank you.

**Closed by gaprl** 2023-08-01 20:47 UTC
