### ISSUE TITLE
[acceptance] Test focus area can change tabs

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#38849] opened 2022-09-14 22:46 UTC
- no need to mock data, empty state for each tab would be fine
- click through tabs, check that the right component (even if it’s empty) is called and rendered
- assert that url is updated after changing each tab

**Comment by ryan953** [comment] 2023-08-07 21:06
Duplicate of https://github.com/getsentry/sentry/issues/38850, closing.

**Closed by ryan953** 2023-08-07 21:06 UTC
Labels: Product Area: Replays
