### ISSUE TITLE
Alert Rules Autofill Tags Not Working As Expected

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#78986] opened 2024-10-11 00:24 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I am able to replicate this in latest Chrome version

- Navigate to Alerts -> Create an Alert -> Number of Errors -> Set Conditions -> Step 2 Filter Events

- While typing in a filter, not all expected tags will show in autofill

- Navigate to Project Settings -> Tags and Content

- Select Alerts from lefthand column

- Again attempt to Create an Alert -> Number of Errors -> Set Conditions -> Step 2 Filter Events

- Now all expected tags will show in autofill

A screen recorded example of this can be found in internal ticket #134669

### Expected Result

For all expected/related tags to autofill

### Actual Result

Project Settings -> Tags and Content page is needed to be viewed in the correct order to allow for these expected/related tags to autofill

### Product Area

Alerts

**Comment by ceorourke** [comment] 2024-12-09 20:35
Closing as a duplicate of https://github.com/getsentry/sentry/issues/60320

**Closed by ceorourke** 2024-12-09 20:35 UTC
Labels: Product Area: Alerts
