### ISSUE TITLE
Colorization / Syntax Highlighting for Source Context

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry#47598] opened 2023-04-18 22:09 UTC
### Problem Statement

When [Source Context](https://docs.sentry.io/platforms/dotnet/guides/google-cloud-functions/data-management/debug-files/source-context/) is displayed on the issue details page, it's presently just black text on white background.  Most editors (IDEs, GitHub, StackOverflow, etc.) apply some sort of language-specific colorization - aka "syntax highlighting".  It would be helpful if Sentry did so as well.

### Solution Brainstorm

- Consider [Prism](https://prismjs.com/) or a similar library
- Sentry already detects the language.  Map that to the language code of the syntax highlighting library.

**Comment by evanpurkhiser** [comment] 2023-04-18 22:15
I think this might be a duplicate of something somewhere.

It is hard without the full source code context (we could maybe integrate with GitHub to do this, but it's tricky)

**Comment by mattjohnsonpint** [comment] 2023-06-07 01:36
In addition to source context, we should try to colorize certain breadcrumbs and span details also. For example, when we know we have SQL (such as with [this feature](https://changelog.getsentry.com/announcements/improved-sql-readability)), we should colorize as SQL with Prisma.

**Closed** 2023-12-07 21:58 UTC
Labels: Type: Feature Request, Product Area: Issues
