### ISSUE TITLE
Clickhouse reporting error after updating to 21.8.0

### ISSUE THREAD

**Issue by christopherowen** [getsentry/sentry#28304] opened 2021-08-31 13:23 UTC
### Environment

self-hosted (`onpremise` deployment)

### Version

21.8.0

### Steps to Reproduce

- update docker-compose
- git checkout tags/21.8.0
- ./install.sh
- docker-compose up -d
- docker-compose logs -f --tail=10

### Expected Result

error log free ingestion of events

### Actual Result

clickhouse_1                                | 2021.08.31 13:20:00.315403 [ 408 ] {} <Error> ServerErrorHandler: Code: 101, e.displayText() = DB::NetException: Unexpected packet from client, Stack trace (when copying this message, always include the lines below):
clickhouse_1                                | 
clickhouse_1                                | 0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x105351b0 in /usr/bin/clickhouse
clickhouse_1                                | 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8f4172d in /usr/bin/clickhouse
clickhouse_1                                | 2. ? @ 0x90263ad in /usr/bin/clickhouse
clickhouse_1                                | 3. DB::TCPHandler::runImpl() @ 0x90239e0 in /usr/bin/clickhouse
clickhouse_1                                | 4. DB::TCPHandler::run() @ 0x9025470 in /usr/bin/clickhouse
clickhouse_1                                | 5. Poco::Net::TCPServerConnection::start() @ 0xe3ac69b in /usr/bin/clickhouse
clickhouse_1                                | 6. Poco::Net::TCPServerDispatcher::run() @ 0xe3acb1d in /usr/bin/clickhouse
clickhouse_1                                | 7. Poco::PooledThread::run() @ 0x105c3317 in /usr/bin/clickhouse
clickhouse_1                                | 8. Poco::ThreadImpl::runnableEntry(void*) @ 0x105bf11c in /usr/bin/clickhouse
clickhouse_1                                | 9. ? @ 0x105c0abd in /usr/bin/clickhouse
clickhouse_1                                | 10. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
clickhouse_1                                | 11. __clone @ 0x12188f in /lib/x86_64-linux-gnu/libc-2.27.so
clickhouse_1                                |  (version 20.3.9.70 (official build))

**Comment by BYK** [comment] 2021-08-31 13:29
Duplicate of getsentry/onpremise#1058, fixed by getsentry/onpremise#1069.

**Closed by BYK** 2021-08-31 13:29 UTC
Labels: Status: Unrouted

**Comment by yangmeng66** [comment] 2021-09-14 09:04
hi, @BYK @christopherowen, After upgrading to clickhouse-21.8.3.44, I use Spark to work with the third-party native-JDBC driver to write data, and encounter this problem.  I'm not using Docker to deploy clickhouse, but using tag packages. How can I solve this problem?
![image](https://user-images.githubusercontent.com/51857567/133228739-b6c7c881-2f5f-4baa-985f-ef44298ff278.png)

**Comment by BYK** [comment] 2021-09-14 09:55
By upgrading the repo here. You can see the fix referred right above.
