### ISSUE TITLE
Please make "structured context" render better - not as a tag/label

### ISSUE THREAD

**Issue by nicholashead** [getsentry/sentry#65583] opened 2024-02-21 22:33 UTC
### Problem Statement

I realize that Sentry recently stopped rendering "Additional Data" and instead moved it up near the stack trace as "structured context" - which looks like a label/tag (sorry, don't know what ya'll call it):

![iboIExlMR0](https://github.com/getsentry/sentry/assets/1168659/f5a1b0bd-98fe-4f54-8477-39e3e5dfbaaf)

This is coming from Sentry's .NET SDK, where we've added to the Data dictionary on an Exception. It does not render nicely anymore and is cut off as you can see. Can we make some improvements here? Possibly render as a table or something? Or should we be doing something different when attaching to the Data dictionary in .NET?

Even could try and detect if the data looks to be JSON then show it formatted?

I can see the full data if I view the raw JSON for the issue, but that's not ideal.

Thanks!

### Solution Brainstorm

Perhaps format this data as a nice table?

### Product Area

Issues

**Comment by malwilley** [comment] 2024-02-22 23:18
@nicholashead could you share how you added this data to the event? Did you follow the steps here? https://docs.sentry.io/platforms/javascript/enriching-events/context/#structured-context

We should be rending context at the bottom of the page. This data looks like it's in the [exception mechanism](https://develop.sentry.dev/sdk/event-payloads/exception/#exception-mechanism) which isn't what I would expect.

**Comment by malwilley** [comment] 2024-02-22 23:27
@nicholashead sorry for the wrong link, this is the .NET version: https://docs.sentry.io/platforms/dotnet/enriching-events/context/#structured-context

If you send us data using this method, it will be displayed in an easier-to-read manner at the bottom of the page.

**Comment by nicholashead** [comment] 2024-02-22 23:50
@malwilley thanks for the link. This is what the sentry SDK does with the Exception data: https://github.com/getsentry/sentry-dotnet/blob/main/src/Sentry/Internal/MainExceptionProcessor.cs#L203 - it puts it into the "Mechanism" data.

This data used to be shown under the "Additional Data" on a Sentry issue, I believe? But recently in the past few weeks (month?) it seems like it shifted to be shown as these like tags/labels near the stack trace.

**Comment by malwilley** [comment] 2024-02-23 00:16
@nicholashead ah, I think I understand now. Thanks for linking to the code.

We haven't updated the UI to display this data differently, if you used to see it at the bottom of the page it must be because this data is being stored in the exception mechanism now instead of event context. Perhaps you've updated the SDK recently and that is the cause for the change in behavior?

Either way, structured data in this field is something we _should_ display better. Will put this on our backlog.

**Comment by nicholashead** [comment] 2024-02-23 01:41
@malwilley that makes sense! We have been trying to keep up with the updates. I didn't think to check if that code had changed on your end. Thanks for taking my feedback. Appreciate it!

**Comment by mrduncan** [comment] 2024-10-22 01:03
We've made some changes to how context is rendered since this was opened - going to close this for now to tidy things up but please re-open if the new layout isn't sufficient, we're continuing to iterate on the entire page.

**Closed by mrduncan** 2024-10-22 01:03 UTC
Labels: Product Area: Issues
