### ISSUE TITLE
upload sourcemap error,  no such file or directory: '/var/lib/sentry/files'

### ISSUE THREAD

**Issue by witcsmartian** [getsentry/sentry#61664] opened 2023-12-13 09:03 UTC
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

Can upload sourcemap normally

### How are you getting stuck?

Sentry was built on the company's internal cluster. When uploading the sourcemap, the sourcemap file cannot be seen.

![image](https://github.com/getsentry/sentry/assets/18660803/488f11ba-46d9-4f52-a0fd-a4942e459705)

- error msg
```bash
FileNotFoundError
 
sentry.tasks.assemble.assemble_artifacts

Regression
Level: Error
[Errno 2] No such file or directory: '/var/lib/sentry/files/26/f2f4/ecc3954434902351e0215f05bd'
```

### Where in the product are you?

Issues

### Version

23.11.0

```[tasklist]
### Tasks
```

**Comment by lforst** [comment] 2023-12-18 08:27
Hi, release bundles are deprecated and they only show up for backwards compatibility. You need to look at artifact bundles instead.

**Comment by witcsmartian** [comment] 2023-12-19 12:18
> Hi, release bundles are deprecated and they only show up for backwards compatibility. You need to look at artifact bundles instead.
thx,，where to find artifacts ?

**Comment by lforst** [comment] 2023-12-19 13:58
What do you mean exactly?

**Comment by witcsmartian** [comment] 2023-12-20 01:47
i mean i can not find my uploaded artifact on my self-hosted sentry websize，but the sentry-cli prompt me Upload successful

**Comment by lforst** [comment] 2023-12-20 09:20
Can you reproduce the same on SaaS? If not I recommend checking your self-hosted logs.

**Comment by MichaelSun48** [comment] 2024-12-10 00:30
Closing due to ~1 year of activity. If you are still experiencing the same issue, feel free to reopen with repro steps.

**Closed by MichaelSun48** 2024-12-10 00:30 UTC
Labels: Product Area: Issues - Source Maps
