### ISSUE TITLE
Slack Integration: Inability to connect private channel

### ISSUE THREAD

**Issue by tkharuk** [getsentry/sentry#7897] opened 2018-04-03 15:45 UTC
## Reporting Bugs
New sentry plugin cannot be connected to private channel even though sentry is added to it.
- raven v3.22.3

> The slack resource "sentry-notifications" does not exist or has not been granted access in the *{workspace-name}* Slack workspace.

<img width="610" alt="screen shot 2018-04-03 at 6 35 20 pm" src="https://user-images.githubusercontent.com/1205052/38259542-f805b9c8-376d-11e8-8e7b-b4d114c75a06.png">

Additional Notes:
- old sentry notifications worked with private channels
- old sentry notifications have a button to test the connection with dummy event
- the new plugin seems to connect to public channel

**Edit by @EvanPurkhiser:** See @wedamija's comment here: https://github.com/getsentry/sentry/issues/7897#issuecomment-500616932

**Comment by EvanPurkhiser** [comment] 2018-04-03 18:45
Thanks for the report!

We added support for reporting to private channels just yesterday https://github.com/getsentry/sentry/commit/18ae4993bc0a55ecfb9b50b094bbe1c2a2aafc4c. 

Because of how Slack apps work, and because the ability to verify that the integration has access to private channels requires a new permission, you will need to re-install the integration. You can simply click 'Add Integration' and go through the setup again (without needing to remove the already configured workspace) and it will grant you the new permissions.

You've already got the app added into the private channel, but for other private channels you might want to add it into you can simply issue `/invite @Sentry` in your slack workspace!

Let me know if there's any problems!

**Comment by TuxujPes** [comment] 2018-04-04 07:51
Hi, thanks for quick response.

I had to remove workspace and to add it anew for it to work.
But it was quick since alert rules and everything else was intact.

Probably not a place to mention this, but maybe you can give me a quick reference:
- I've added a comma-separated list of tags but it did not seem to affect notification format. I've used "project, release, environment, url, user"

**Comment by SuEric** [comment] 2018-04-04 14:30
hey @TuxujPes , I just added the integration this morning (1 hour ago). And I'm getting same error message. It is first time I added Sentry Slack integration; no looks like it is not fixed..?

**Comment by SuEric** [comment] 2018-04-04 14:49
Actually this is what I see for my Sentry Slack app settings:

<img width="624" alt="screen shot 2018-04-04 at 9 47 45 am" src="https://user-images.githubusercontent.com/3435477/38315136-71d5a55e-37ed-11e8-9cfd-a3b99c7955ac.png">

So why do I get the error when trying to setup the alert rule?

**Comment by TuxujPes** [comment] 2018-04-04 14:53
@SuEric what helped in my case:
- remove workspace
- add new workspace
- grant permissions to all public channels

My previously added via slack private channel was already listed in settings as added individually.

**Comment by ericjeker** [comment] 2019-01-24 02:42
To me this still does not work. I have added the workspace in my sentry integrations, then invited the Sentry app to the private channel but I still have the same error.

![image](https://user-images.githubusercontent.com/979397/51650783-87912c00-1fc4-11e9-8548-fe17ba9a9356.png)

![image](https://user-images.githubusercontent.com/979397/51650792-9081fd80-1fc4-11e9-9f18-4e20be9a643b.png)

I tried to reference the channel with # or  @ but that doesn't change anything. What am I doing wrong?

**Comment by EvanPurkhiser** [comment] 2019-01-24 17:24
You're able to add it to public channels right @ericjeker ?

**Comment by ericjeker** [comment] 2019-01-25 00:20
> 
> 
> You're able to add it to public channels right @ericjeker ?

Yes, public channels are fine. But not the private ones. I tried to reinstall the workspace also but it didn't work.

**Comment by EvanPurkhiser** [comment] 2019-01-25 21:21
@ericjeker how many slack ch

**Comment by EvanPurkhiser** [comment] 2019-01-25 21:22
@ericjeker does your slack have a lot of channels?

**Comment by ericjeker** [comment] 2019-01-26 01:55
Currently we have about 30 private channels and hidden channels.

**Comment by twidii** [comment] 2019-01-31 04:20
Yasss, what should you guys do is just click on "All Public Channels" on Sentry Settings 
![image](https://user-images.githubusercontent.com/26539839/52030377-27f9ca00-254a-11e9-9d18-1fbe35f0aaa7.png) thanks @EvanPurkhiser  👍

**Comment by NerdyParker** [comment] 2019-03-04 16:01
I'm still having this issue. I've tried removing/adding the workspace. Kicking/inviting the app from the channel. Still getting the error mentioned above.

**Comment by tomjennings100** [comment] 2019-03-05 14:51
I have the same issue, Sentry is explicitly added to our *shared* workspace but cannot see it.

**Comment by lcmartinezdev** [comment] 2019-03-09 16:11
I have the same issue, I 've tried removing and adding the sentry slack app but didn't work.

**Comment by juancarlosfarah** [comment] 2019-03-21 13:59
I'm actually seeing the same issue as well.

**Comment by lcmartinezdev** [comment] 2019-03-21 16:16
@EvanPurkhiser Can we do something? Can we help you with something?

**Comment by jwarlander** [comment] 2019-03-22 10:34
Seeing problems adding Sentry to private channels here, too, @EvanPurkhiser..

It's not unlikely that our workspace might have > 1000 channels (how would I even know?) as we're around 8k users, so possibly we're affected by #11064 - any work happening there? It seems to have stalled a bit :)

**Comment by Aarbel** [comment] 2019-03-26 23:09
Can't send alerts to private channels too.

## Do you know a way to fix it ? 

**SENTRY SCREENSHOT**
![image](https://user-images.githubusercontent.com/25119847/55039393-464ce500-5024-11e9-9e10-f1c2ba573777.png)

**SLACK SCREENSHOT**
![image](https://user-images.githubusercontent.com/25119847/55039411-4f3db680-5024-11e9-893a-90a39566c5b7.png)

**Comment by lcmartinezdev** [comment] 2019-03-26 23:53
I have checked and its because sentry uses old endpoint: (does not include private channels.)

https://api.slack.com/methods/channels.list

https://github.com/getsentry/sentry/blob/8bcd04136a8ff3bdcf976ff58c98b5685dfe4565/src/sentry/integrations/slack/notify_action.py#L185

**Comment by Aarbel** [comment] 2019-03-27 08:38
@EvanPurkhiser

**Comment by EvanPurkhiser** [comment] 2019-03-28 02:15
@lcmartinezdev keep reading :)

https://github.com/getsentry/sentry/blob/8bcd04136a8ff3bdcf976ff58c98b5685dfe4565/src/sentry/integrations/slack/notify_action.py#L196-L201

However, I can also reproduce this in production.

We're unfortunately a little bit at the mercy of slack right now, as we're on their "new-but-depcreated" workspaces API (See https://github.com/getsentry/sentry/issues/9004). But it very well could be that slack has made some kind of breaking change.

We're working with slack right now to get some fixes in (which requires their intervention with our "legacy worksapce app"

**Comment by lcmartinezdev** [comment] 2019-03-28 02:19
I didn't see it.
So thanks for your help.

**Comment by alcohol** [comment] 2019-05-15 09:13
Is a fix for this still in progress?

**Comment by EvanPurkhiser** [comment] 2019-05-29 21:59
I'd actually love to hear from you guys again specifically from those who are:

 * Using sentry.io (not on-premise)
 * Don't have a lot of slack channels
 * See this error

Let em know your sentry organization slug and @wedamija or myself can take a closer look at what's going on.

**Comment by lcmartinezdev** [comment] 2019-05-29 22:20
@EvanPurkhiser My organization slug is:
`acuasoft`

Let me know if I can help with some action.

Thanks

**Comment by EvanPurkhiser** [comment] 2019-05-29 22:26
@lcmartinezdev if it's not a problem to ask publicly, what is the name of the private channel you're trying to add?

**Comment by lcmartinezdev** [comment] 2019-05-29 22:30
@EvanPurkhiser 
The channel name is: `dev_acuasoft`
The full url is: https://acuasoft.slack.com/messages/CDCDZBE0Y/

**Comment by wedamija** [comment] 2019-06-10 22:24
@lcmartinezdev I've been investigating your issue. When I tested this with my own private channel I was unable to reproduce, but I could easily reproduce it with yours, and so reached out to Slack to figure out what's going wrong.

Unfortunately, it turns out that this is a known bug on Slack's side. The issue occurs only with channels that were previously public and then converted over to private, and we're just not able to access them via our workspace app due to this bug.

For the moment there's not a lot we can do to help you out. Slack will let us know when they've resolved the issue, and as a workaround you could create a new private channel and that should work as expected with our app.

**Comment by lcmartinezdev** [comment] 2019-06-13 13:35
@wedamija Thanks.

I will ask to Slack support in order to know how to fix the issue.

**Comment by fabriciols** [comment] 2019-07-10 22:27
have the same problem here, hoping for a fix...

**Comment by ivan-pomortsev** [comment] 2019-07-12 11:16
What helped me is creating new private channel and then adding Sentry app (`/invite @Sentry`).

**Comment by iagomelanias** [comment] 2019-07-16 07:26
@EvanPurkhiser actually, [the documentation says this behavior is intentional](https://api.slack.com/methods/groups.list).

> Don't use this method. Use conversations.list instead.
> ...
> **Does not include private shared channels or channels that have been converted from public to private. Use the Conversations API instead.**

While deleting the channel and creating it again should be a good way to go, we lose all the channel history. The only option available is to use corporate exports, which requires a Plus plan and manual approval...

It would be great if the new `conversations.list` API was implemented. It has been extremely frustrating not to be able to integrate Sentry into some of our channels. 🙁

**Comment by silvez-dh** [comment] 2019-08-14 15:14
Hello, no news on this issue? Tks :)

**Comment by silvez-dh** [comment] 2019-08-14 15:35
Btw, it works for private channels (created a new one here and worked) but not for public ones

**Comment by silvez-dh** [comment] 2019-08-14 17:29
Contacted Slack support and here are their answer (although i not sure it the person understood the issue very well).

`i Bruno,

Thanks for writing in and sorry for the troubles. Unfortunately this is something that Sentry will need to support in their app. Based on what I'm reading in that Issue thread, it looks like they're still using the channels.* and groups.* API methods instead of the conversations.* methods.

Once that's implemented, it should be able to support private conversations. If Sentry is not responsive in that GitHub issue, you can try reaching them at support@sentry.io.

Sorry that I don't have better news for you today, but let me know if you have any questions.

Cheers,`

**Comment by berik** [comment] 2019-10-24 00:56
> What helped me is creating new private channel and then adding Sentry app (`/invite @Sentry`).

This method helped me

**Comment by gonengar** [comment] 2019-11-05 17:36
Didn't manage to integrate newly created public channel(Altough in sentry.io it works like a charm)

**Comment by omaraltayyan** [comment] 2020-01-25 14:17
still an issue, can integrate with public channels, but not private ones, i have added many permissions to the slack app, and added the sentry app to my private channel, still shows this error:

```
The slack resource "...." does not exist or has not been granted access in the ... Slack workspace.
```

**Comment by w3box** [comment] 2020-02-10 15:48
> still an issue, can integrate with public channels, but not private ones, i have added many permissions to the slack app, and added the sentry app to my private channel, still shows this error:
> 
> ```
> The slack resource "...." does not exist or has not been granted access in the ... Slack workspace.
> ```

same here

**Comment by flowdee** [comment] 2020-03-16 05:55
Will this ever be possible? Really annoying

**Comment by flyte** [comment] 2020-03-24 13:44
Ugh. I had this working for months, but then I needed to change the alert settings to only send alerts on specific environments. I removed our existing integration and now I'm not able to configure alerts to private channels either.

We cannot post sentry alerts to public channels because of potential sensitive information held within them. This is a crucial feature in my opinion, and it sucks that we've just lost it, having had it before.

**Comment by kkmuffme** [comment] 2020-04-05 22:22
You can actually easily fix it by manually adding the private channel to the integration.

Open slack in your browser & navigate to the apps. Select Sentry => Settings => click on "Add App to channel" button. Search for the private channel in the input field that shows, then click it to add.
Now you can create alerts for the private channel without getting that error.

**Comment by dmitrygusev** [comment] 2020-04-20 23:47
There's a trick to make it post to a private channel that was public before, if you really need it, by directly updating alert rule configuration in DB.

Suppose you have a channel name: `#channel-name`

1. Find ID of the channel. The simplest way is probably open the slack channel in a browser, and take ID from the URL, i.e.: `https://app.slack.com/client/xxx/CHANNELID`

2. Create a rule with desired configuration in your project, just temporarily put a channel name that works, i.e. new private channel you just created. We will replace it soon.

3. Connect to Sentry DB and find the rule you created at previous step, `label` and `project_id` columns should help you identify the right one, assuming our record has `id = 1`:

    ```sql
    sentry => SELECT data FROM sentry_rule WHERE id = 1;

    eF5VUD1vgzAU3N+viNSBDAmqgUAYadShS1UJyStyzQux4hjXNlT5933Op7pxd+be3S17y6BN5Gh6FdRofAI2g6W2OSx7WwA/iSAPYDfA5Qi2BM9FCE59TwHBVsDRzMqN5oQmgN2SrHqwNXBPhDunbtLo06d9ijMJ3cMjfY+4ucPd/SFY9kpms9AT3WGMDIMYlBkIZOCFb5O9w58JjTxTZJbDBysK+qVNhIwG3SV4lArqJ7SOn5unHouyMjZlVazKtsDpgie2/tdqtXCoUXhcLaxTRior9Grh0c3oOiNOxOtxGNDRcJf78iCMQd2pPm5JyXdN/VbVX3lJkLLz39EdvRWSimU58Pw2WlY8VlMm4ODEdTGvhTymZgxqf+6u4dM2cp8XqqUkSmIjr7Nl1JHfIhAqgb8IjS74db5+TJhVccIU/gAhvqmm
    ```

4. The data is [base64 encoded deflated text](https://forum.sentry.io/t/how-to-decrypt-sentry-message/6271/2) in a special text format. We need to extract it into a file as text for editing. One way to do it on Mac OS is just copy above string to clipboard and run:

    ```bash
     pbpaste | base64 -D | pigz -d > data
    ```

5. Edit the `data` file preserving line endings (i.e. using `vim`): replace fields `p21` and `p26` with correct `channel-id` and name; note channel ID should be prefixed with `V`, same as channel name, i.e.:

    ```
    ...
    sS'channel_id'
    p21
    VCHANNELID
    p22
    sVworkspace
    p23
    V3
    sVid
    p24
    Vsentry.integrations.slack.notify_action.SlackNotifyServiceAction
    p25
    sVchannel
    p26
    V#channel-name
    p27
    ...
    ```

6. Encode the file back to the Sentry format, i.e. to get encoded data in clipboard for Mac OS:

    ```bash
    cat data | pigz -z | base64 | pbcopy
    ```

7. Update record in DB:

    ```sql
    UPDATE sentry_rule SET data = '<paste new payload>' WHERE id = 1;
    ```

This should be everything.

You will not be able to edit the form again as it will keep failing validation on save, but Sentry should be able to use stored value. If you need to change anything, just repeat above steps.

**Comment by haganf** [comment] 2020-05-20 22:55
I had a similar problem, ended up we have two sentry apps installed in our slack workspace: @Sentry (orange icon) and @sentry (pink icon). The @sentry is the new version which worked for us.

**Closed** 2020-06-19 18:44 UTC
Labels: Component: Integrations

**Comment by nominalista** [comment] 2020-07-17 11:18
Still experiencing this issue. I created a private channel, invited @sentry to the channel and when I try to create a new rule I get: `The slack resource "my-channel" does not exist or has not been granted access in the My Workspace Slack workspace.`

Is it possible that I should wait for Slack to make the new channel available for other apps?
