### ISSUE TITLE
onpremise 8.22.0 multiple broken links in project settings

### ISSUE THREAD

**Issue by YannickteK** [getsentry/sentry#6753] opened 2017-12-13 18:13 UTC
Hello

I'm running the on premise 8.22.0 version. I have multiple broken links on the project settings page:
http://localhost:9000/sentry/blablabla/settings/sentry/blablabla/settings/install/
http://localhost:9000/sentry/blablabla/settings/sentry/blablabla/settings/csp/
http://localhost:9000/sentry/blablabla/settings/sentry/blablabla/settings/user-feedback/
http://localhost:9000/sentry/blablabla/settings/sentry/blablabla/settings/filters/
http://localhost:9000/sentry/blablabla/settings/sentry/blablabla/settings/keys/
http://localhost:9000/sentry/blablabla/settings/sentry/blablabla/
http://localhost:9000/sentry/blablabla/settings/sentry/blablabla/dashboard/
http://localhost:9000/sentry/blablabla/settings/sentry/blablablap/releases/
http://localhost:9000/sentry/blablabla/settings/sentry/blablabla/settings/alerts/
http://localhost:9000/sentry/blablabla/settings/tags/sentry/blablabla/settings/processing-issues/

**Comment by billyvg** [comment] 2017-12-19 18:40
@YannickteK I believe this was fixed in https://github.com/getsentry/sentry/pull/6386

**Comment by cajbecu** [comment] 2018-01-08 17:44
same here

**Comment by a-hab** [comment] 2018-03-12 11:50
I can still reproduce this bug on premise 8.22.0. Any updates?

**Comment by alternativshik** [comment] 2019-04-17 08:27
same in 9.1.0

**Comment by BYK** [comment] 2019-06-20 15:17
Closing due to staleness and 8.22 is not even a thing anymore.

@alternativshik - Please file a new issue with some logs to the [getsentry/onpremise](https://github.com/getsentry/onpremise) repo if you are still having this issue.

**Closed by BYK** 2019-06-20 15:17 UTC
