### ISSUE TITLE
Receiving Internal Error when adding Filter to Metric Alert

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#74030] opened 2024-07-09 19:29 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Customer attempts to add a third "AND" condition in Metric Alert Step 2 "Filter Events" that looks like the following:

!http.status_code:[200] AND http.method:GET AND http.url:https://theirurlofchoice.com/

When saving the Metric Alert changes they receive the message:

"Unable to save alert: Internal Error, c77d6d8ad8074bfd8d3a8c0af8a46327"

I am able to replicate this error and have linked the Sentry internal error in the associated Zendesk ticket #126259, along with link to test alert

### Expected Result

To be able to save this condition

### Actual Result

Unable to save, internal error 

### Product Area

Alerts

**Comment by rachrwang** [comment] 2024-07-10 17:26
Thanks for filing, we'll work to get this prioritized

**Comment by ceorourke** [comment] 2024-12-09 20:11
Closing as I'm not able to reproduce - I could save the alert just fine with that filter. Feel free to reopen if the customer is still experiencing the issue.

**Closed** 2024-12-09 20:40 UTC
Labels: Product Area: Alerts
