### ISSUE TITLE
In stack trace, can't copy file path because it only shows on hover

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#79077] opened 2024-10-13 03:51 UTC
I only get the full file path if I hover.
Once I try to move the mouse over to the hover to copy the text the hover disappears.

![Image](https://github.com/user-attachments/assets/66ee9718-5618-411d-99dd-96309be8ab3b)

Is there a way to copy the full file path?

[Example event](https://sentry.sentry.io/issues/5987941785/events/2cfbc16f066d48789da2c5d9ab1d9d58/?project=5905698&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issues_trace_timeline&sort=date&statsPeriod=1h&stream_index=6)

**Comment by jangjodi** [comment] 2024-10-15 20:18
Hi [bruno-garcia](https://github.com/bruno-garcia), you can copy the full path by viewing the JSON for the event - the full path should be there

**Comment by bruno-garcia** [comment] 2024-11-05 04:08
> Hi [bruno-garcia](https://github.com/bruno-garcia), you can copy the full path by viewing the JSON for the event - the full path should be there

I copy the path all the time, to go from Sentry to my editor to fix bugs.
Downloading a JSON for that is not ideal to say the least

**Comment by mrduncan** [comment] 2024-11-05 17:10
I believe this is a dupe of #60032 - going to close this in favor of that one for now.

**Closed by mrduncan** 2024-11-05 17:10 UTC
Labels: Product Area: Issues, Waiting for: Product Owner
