### ISSUE TITLE
Better alert rule thresholds

### ISSUE THREAD

**Issue by qqii** [getsentry/sentry#51435] opened 2023-06-22 08:55 UTC
### Problem Statement

The percent change threshold does not work well if the historical period contains times with 0 events. For example consider this graph.

```
|          .     .
|      .   . .   .
|   .  .   . . . .
| . .  . . . . . . 
--------------------
```

Since the 3rd time period is 0, no matter what is set for a % threshold and time period this will always trigger. 

### Solution Brainstorm

It would be useful to have smarter alert thresholds. This is a wide topic with many avenues to explore.

### Product Area

Alerts

**Comment by ceorourke** [comment] 2024-05-29 23:08
I'm closing this as a duplicate of https://github.com/getsentry/sentry/issues/59984, please follow along there for updates.

**Closed by ceorourke** 2024-05-29 23:08 UTC
Labels: Product Area: Alerts
