### ISSUE TITLE
[Cron Monitors] Monitor failure: job (duration)

### ISSUE THREAD

**Issue by d0niek** [getsentry/sentry#42806] opened 2023-01-05 10:44 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I've setup a job and from some time is start notice me about that error `Monitor failure: job (duration)`. Maybe is related with #42771?

Now my config for job looks like:

```
{
    checkin_margin: 1, 
    max_runtime: 0, 
    schedule: 0 * * * *, 
    schedule_type: 1
}
```

First setup when everything worked and in some time stop looked like:

```
{
    checkin_margin: null, 
    max_runtime: null, 
    schedule: 0 * * * *, 
    schedule_type: 1
}
```

For sure my job doesn't work longer.

### Expected Result

No error.

### Actual Result

Monitor failure: job (duration)

**Comment by d0niek** [comment] 2023-01-05 17:32
Hi @davidenwang!

Thanks for your comment. My job runs in 1-2 seconds? I'm using curl. See #42771

**Comment by davidenwang** [comment] 2023-01-05 17:36
Oh I see, didn't realize the other issue was from you as well, in that case I would say this is being caused by the fact that the check-ins aren't moving to a completed state -> `ok` or `error` in which case Sentry thinks your job never finishes running and then marks them as having exceeded their duration. Let me have a look at your curl code on the other issue.

**Closed** 2023-01-18 08:32 UTC
Labels: Status: Backlog, Team: Crons
