### ISSUE TITLE
On-Premise docker 9.1.1 - event timestamp with incorrect timezone

### ISSUE THREAD

**Issue by gdong42** [getsentry/sentry#13887] opened 2019-07-03 06:36 UTC
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.1.1-onbuild]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

running with PostgreSQL and RabbitMQ.

## Description

After upgrading from 9.0.0 to 9.1.1, all event timestamps become incorrect:

on an event page, I see (in JSON format):
```
datetime: "2019-07-03T13:26:01.000000Z",
...
received: 1562131561.433,
```

The `received` timestamp is correct, but `datetime` is 8 hours behind the actual time.  It should be something like `2019-07-03T13:26:01.000000+8000` or `2019-07-03T05:26:01.000000Z` (I'm at timezone of +8000).  And the UI shows a warning of 8 hours latency.

I also checked:
*  `events.process_event` message queue in RabbitMQ, it has correct event timestamp (`datetime` field);
* `sentry_message` table in Postgres DB, the datetime column has incorrect values

There might be something wrong with logic of process the event and saving to DB.

## Steps to Reproduce

I tried to reproduce with a fresh docker on premise install locally, but everything seemed OK. It might be specific to RabbitMQ usage I suppose.

### What you expected to happen

The event occurred time and received time to be the same, or close.

**Comment by ibm5155** [comment] 2019-07-05 14:06
I'm also suffering with that

**Comment by BYK** [comment] 2019-07-24 13:01
We have released 9.1.2 yesterday. Are you able to try that and see if the issue is still there?

**Comment by gdong42** [comment] 2019-07-26 16:09
Just upgraded to 9.1.2, the same problem exists.

**Comment by BYK** [comment] 2019-07-29 14:25
@gdong42 thanks for verifying. Will give this a look soon.

**Comment by urbanc** [comment] 2019-09-04 07:44
We have the same problem On-Premise docker 9.1.2.
Datetime is 8 hours behind the actual time.

**Comment by BYK** [comment] 2020-10-22 20:49
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

FYI we expect all services to run on UTC for correct timestamp handling across them.

**Closed by BYK** 2020-10-22 20:49 UTC
