### ISSUE TITLE
OPSGenie integration should support Metric Rules

### ISSUE THREAD

**Issue by mdestagnol** [getsentry/sentry#50860] opened 2023-06-13 20:42 UTC
### Problem Statement

Currently, it's not possible to fire an on-call alert if a metric rule is getting triggered. It would be beneficial if it did.

### Product Area

Settings - Integrations

**Comment by scttcper** [comment] 2023-06-13 21:18
duplicate of https://github.com/getsentry/sentry/issues/37347

**Closed by scttcper** 2023-06-13 21:18 UTC
Labels: Status: Untriaged, Product Area: Settings - Integrations, Waiting for: Product Owner

**Comment by Dhrumil-Sentry** [comment] 2023-08-09 03:15
@mdestagnol Please have a look at our GH discussion about a new opsgenie integration: https://github.com/getsentry/sentry/discussions/54156
