### ISSUE TITLE
When attachment download in issuse's panel, the filename in the download pop-up is incorrect

### ISSUE THREAD

**Issue by zalatmza** [getsentry/sentry#55247] opened 2023-08-28 08:11 UTC
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. click download button.
![image](https://github.com/getsentry/sentry/assets/19297443/d0ba5431-114d-4ca0-82d0-93e69e02f4b5)

2. the default filename is not equal to `23f3be1c-148b-49b4-9bf8-6d8f3c309276.dmp` in step1
![image](https://github.com/getsentry/sentry/assets/19297443/3ea67c69-175f-48d4-95a2-3f616c0b297c)

### Expected Result

 the default filename in the download pop-up is `23f3be1c-148b-49b4-9bf8-6d8f3c309276.dmp`

### Actual Result

 the default filename in the download pop-up is `下载`

### Product Area

Issues

### Version

23.8.0

**Comment by zalatmza** [comment] 2023-08-28 08:18
my colleague said that this feature is good in V22, but work incorrectly in V23

**Comment by malwilley** [comment] 2023-08-28 22:06
I've attempted to reproduce this bug, but cannot. Will require some additional information.

@zalatmza could you let us know the value of the `Content-Disposition` response header of this response? You can find this by opening the network tab of the your browser dev tools before clicking the download button. Then find the request (should end with `?download=1)` and inspect the response headers.

**Comment by zalatmza** [comment] 2023-08-29 02:10
> I've attempted to reproduce this bug, but cannot. Will require some additional information.
> 
> @zalatmza could you let us know the value of the `Content-Disposition` response header of this response? You can find this by opening the network tab of the your browser dev tools before clicking the download button. Then find the request (should end with `?download=1)` and inspect the response headers.

@malwilley dear, i couldn't find `Content-Disposition` in response header.

the request like this `
https://xxxxx/api/0/projects/xxx/xxxx/events/46456d9ede834b6eb34beacfffe5dc27/attachments/8129340/?download=1`.

the response header, FYI.

![image](https://github.com/getsentry/sentry/assets/19297443/70ff6629-c317-480e-91dd-a3fdce2b46f7)

**Comment by malwilley** [comment] 2023-08-29 16:49
@zalatmza since you mentioned this was self-hosted, I'd check on your network configuration to ensure that nothing is intercepting the `Content-Disposition` header.

Since the feature works in SaaS, I'll close this issue for now. If you have issues related to configuration, feel free to open an issue in our self hosted repo: https://github.com/getsentry/self-hosted

**Closed by malwilley** 2023-08-29 16:49 UTC
Labels: Product Area: Issues, Waiting for: Product Owner

**Comment by zalatmza** [comment] 2023-08-30 03:21
I found the cause of the problem in https://github.com/getsentry/self-hosted/commit/8a5f333ca07df41d3bcabc6d742b7808123bdbaf.

I changed my ngnix.conf, and it works fine now.

> @zalatmza since you mentioned this was self-hosted, I'd check on your network configuration to ensure that nothing is intercepting the `Content-Disposition` header.
> 
> Since the feature works in SaaS, I'll close this issue for now. If you have issues related to configuration, feel free to open an issue in our self hosted repo: https://github.com/getsentry/self-hosted
