### ISSUE TITLE
Jira workflow statuses repeated in sync settings

### ISSUE THREAD

**Issue by jonesphillip** [getsentry/sentry#24332] opened 2021-03-09 04:00 UTC
## Important Details

What versions of Sentry does this impact?

Saas (sentry.io), Self-hosted

## Description

Jira workflow statuses are repeated in the status sync settings.

![issue-981-screenshot](https://user-images.githubusercontent.com/7978631/110416342-6d9df080-8048-11eb-990a-b52ee299a608.png)

### Expected behavior

Each workflow status should be distinct.

**Comment by GabeVillalobos** [comment] 2024-12-09 23:13
Duplicate of https://github.com/getsentry/sentry/issues/73733, which is being prioritized already.

**Closed by GabeVillalobos** 2024-12-09 23:13 UTC
Labels: Product Area: Settings - Integrations
