### ISSUE TITLE
Opening any issue raises TypeError: t.generationByIdentifier is not a function. 

### ISSUE THREAD

**Issue by mmajko** [getsentry/sentry#19590] opened 2020-06-28 14:35 UTC
## Important Details
On-Premise w/ Docker, version 20.7.0.dev0 c13b2f6

## Description

Opening any issue detail in UI displays the "There was an error loading a component." error, and event is pushed into the internal project. Can't display the internal event in the UI, but the notification mail contains following information:

```
TypeError: t.generationByIdentifier is not a function. (In 't.generationByIdentifier(n)', 't.generationByIdentifier' is undefined)
  at deviceNameMapper (./app/components/deviceName.tsx:12:35)
  at None (./app/components/group/tagDistributionMeter.jsx:72:19)
  at map ([native code])
  at context (./app/components/group/tagDistributionMeter.jsx:70:21)
  at iu ([native code])
...
(13 additional frame(s) were not displayed)
```

<img width="654" alt="Screenshot 2020-06-28 at 16 33 55" src="https://user-images.githubusercontent.com/3010503/85950483-480b0400-b95d-11ea-9533-bfb74b26bb79.png">

## Steps to Reproduce

1. Open any issue in Sentry UI

**Comment by clintmod** [comment] 2020-09-05 20:10
I just ran across this in the hosted version. Help?

**Comment by kooroshh** [comment] 2020-10-21 10:43
have the same issue too 
![image](https://user-images.githubusercontent.com/24514663/96709513-a6923d00-13a7-11eb-8ad8-a9d6938e481e.png)

**Comment by BYK** [comment] 2020-10-26 21:09
Can you share logs from your sentry web instance?

**Comment by kooroshh** [comment] 2020-10-26 23:44
> Can you share logs from your sentry web instance?

[logs.txt](https://github.com/getsentry/sentry/files/5442084/logs.txt)

**Comment by BYK** [comment] 2020-10-27 12:04
@kooroshh looks like your sentry web instance gets killed pretty frequently by `SIGILL`. Which version of Docker are you using?

**Comment by kooroshh** [comment] 2020-10-27 23:45
> @kooroshh looks like your sentry web instance gets killed pretty frequently by `SIGILL`. Which version of Docker are you using?

@BYK Docker version 19.03.13, build 4484c46d9d  On (Ubuntu 20.04.1 LTS)

**Comment by BYK** [comment] 2020-10-28 07:25
@kooroshh do you have any custom Docker config? Also can you share your CPU?

**Comment by mrserg161** [comment] 2020-10-28 08:20
Docker version 19.03.12, build 48a66213fe

**Comment by kooroshh** [comment] 2020-10-28 21:34
> @kooroshh do you have any custom Docker config? Also can you share your CPU?

@BYK 
```processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
stepping        : 1
microcode       : 0xb000036
cpu MHz         : 2099.998
cache size      : 20480 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 20
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 invpcid rtm rdseed adx smap xsaveopt arat md_clear flush_l1d arch_capabilities
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips        : 4199.99
clflush size    : 64
cache_alignment : 64
address sizes   : 43 bits physical, 48 bits virtual
power management:
```


it's all default configuration just installed the On-Premise using the default installer  
here is a screenshot of sentry-internal 
![image](https://user-images.githubusercontent.com/24514663/97498959-4fc9cc00-1982-11eb-9aed-b385a066afe1.png)

**Comment by kooroshh** [comment] 2020-10-28 21:40
> > @kooroshh do you have any custom Docker config? Also can you share your CPU?
> 
> @BYK
> 
> ```
> vendor_id       : GenuineIntel
> cpu family      : 6
> model           : 79
> model name      : Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
> stepping        : 1
> microcode       : 0xb000036
> cpu MHz         : 2099.998
> cache size      : 20480 KB
> physical id     : 0
> siblings        : 1
> core id         : 0
> cpu cores       : 1
> apicid          : 0
> initial apicid  : 0
> fpu             : yes
> fpu_exception   : yes
> cpuid level     : 20
> wp              : yes
> flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 invpcid rtm rdseed adx smap xsaveopt arat md_clear flush_l1d arch_capabilities
> bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
> bogomips        : 4199.99
> clflush size    : 64
> cache_alignment : 64
> address sizes   : 43 bits physical, 48 bits virtual
> power management:
> ```
> 
> it's all default configuration just installed the On-Premise using the default installer
> here is a screenshot of sentry-internal
> ![image](https://user-images.githubusercontent.com/24514663/97498959-4fc9cc00-1982-11eb-9aed-b385a066afe1.png)
# UPDATE 
ok i think I've found the problem , the problem is the nginx reverse proxy which doesn't allow to load/exec (Probably Content Security Policy) some scripts 


using the internal port , everything works fine

**Comment by BYK** [comment] 2020-10-29 18:33
@kooroshh alright then, closing out. That said I'd still investigate those SIGILLs (signal 4 termination).

**Closed by BYK** 2020-10-29 18:33 UTC
Labels: Component: On-Premise, Status: Needs More Information
