### ISSUE TITLE
Jira integration - Mark issue resolved in next release on "Done"

### ISSUE THREAD

**Issue by Aidan-Chey** [getsentry/sentry#19672] opened 2020-07-01 21:58 UTC
## Summary

One paragraph description of the feature.

## Motivation

Why should this be worked on? What problems or use cases does it solve or
improve?

## Additional Context

Any other context or screenshots or API request payload/responses that you
pertain to the feature.

**Comment by jonesphillip** [comment] 2020-07-06 18:02
Closing, duplicate of https://github.com/getsentry/sentry/issues/19673

**Closed by jonesphillip** 2020-07-06 18:02 UTC
