### ISSUE TITLE
Line charts for errors/transactions over time grouped by project

### ISSUE THREAD

**Issue by taidaid** [getsentry/sentry#63010] opened 2024-01-11 15:09 UTC
### Problem Statement

I want to show my errors and transactions over time, grouped by project. Currently, Sentry returns a 500 for this setup. I opened a ticket with support (111182) about this and was told that this is not yet supported.

### Solution Brainstorm

I would like to use the dashboard widget line chart
![image](https://github.com/getsentry/sentry/assets/39394303/25669a24-5383-4110-a032-f3bc0af72288)

### Product Area

Dashboards

**Comment by ale-cota** [comment] 2024-09-10 13:10
hi, @taidaid!
Sorry for the delayed update, but it should be possible to group again by project. Can you please confirm that the issue is resolved on your end as well?

Thank you.

**Comment by ale-cota** [comment] 2024-09-17 10:22
@taidaid I'll be closing this issue for now since we're not able to reproduce it, but let us know if you're still having trouble.

**Closed by ale-cota** 2024-09-17 10:22 UTC
Labels: Type: Bug, Product Area: Dashboards
