### ISSUE TITLE
Feature request: ignore until it happens one time shortcut

### ISSUE THREAD

**Issue by Intrepidd** [getsentry/sentry#8835] opened 2018-06-25 08:35 UTC
Hi there,

Following up the ticket from my colleague (#5456), there is another feature available in bugsnag that we would love to see in sentry !

It's the ability to ignore an error until it happens one time.
Right now, the lower we can go without clicking "Custom" is 10 times :

![](https://dha4w82d62smt.cloudfront.net/items/2h442r3s1j06343f3g3m/Screen%20Shot%202018-06-25%20at%2010.28.38.png?X-CloudApp-Visitor-Id=2626348&v=288b5a5d)

For front-end related errors it makes sense, however for backend, 90% of the time an error is ignored, we want to be notified the next time it happens.

Could you consider adding a "1 time" option in this dropdown ?

It would even be better if we could customize the options of the dropdown on a per-project basis !

Thanks a lot !

**Comment by mattrobenolt** [comment] 2018-06-25 15:05
You’d just click “Resolve”. That’s the same idea. After resolving the issue, the next time it happens would be flagged as a regression and notify you.

**Comment by mattrobenolt** [comment] 2018-06-25 15:08
Looking at your screenshot, you also do have the issue resolved. What behavior are you looking for by additionally ignoring for 1time?

**Comment by Intrepidd** [comment] 2018-06-25 15:10
The screenshot was only for demonstration purposes.

Resolving the issue doesn't work for me as the 2 things are very different :

- Error happens, Someone actually fixes the code, then we mark as resolve.
- Error happens, we don't want to look into it right now as it's an edge case, ignore once 

The semantic is very different and the response to either a "Regression" or a "Ignored error coming back up" is also very different.

Hope you see where I come from

**Comment by Intrepidd** [comment] 2018-06-25 15:13
We also rely a lot on the history of an error to track what happened as different contributors will look into it, and it's really import to see `xxx ignored this issue until it happens 1 time(s)` vs `xxx resolved this issue`, as it means 2 totally different things

**Comment by mattrobenolt** [comment] 2018-06-25 16:21
Interesting, so yeah, the behavior here is exactly the same. You just want it documented differently.

I don't see why this wouldn't be hard to add, but I guess I'd be slightly concerned about confusion for users.

@dcramer any reason we shouldn't add this?

**Comment by dcramer** [comment] 2018-06-25 17:14
Yeah I wouldn't be opposed to a quick "Until the next occurrence"

**Comment by xeor** [comment] 2018-12-05 06:49
This would be nice.. I'm doing mostly backend this days. And some errors happening random places in the codebase can't be fixed till I remake the whole CI-pipeline, which I can't do before ..., and ... :) But I don't want to mark them as "resolved". I want to ignore them once (since they all come from different places in the codebase)..

**Comment by dcramer** [comment] 2018-12-05 06:58
This was implemented a month or two ago

**Closed by dcramer** 2018-12-05 06:58 UTC
