### ISSUE TITLE
Unable to get SMTP working on Docker deployment

### ISSUE THREAD

**Issue by uhlhosting** [getsentry/sentry#13928] opened 2019-07-09 11:10 UTC
Can someone share a working Sentry/Nginx Proxified with SMTP working config? I have quite a hard time on passing over this integration, managed to solve nginx issues had with linking container to sentry config, yet this is a bit weird to me. I have read the sentry config, and nowhere found the real purpose of smtp image on docker, if is not documented or if does not work out of the box. 

Several SMTP configs all failed with different errors. Will be in future better email integration, from what i've seen if someone uses a 3rd party API to send mails and those work, is no reason not to support basic protocols, and thus by supporting them it means have a working sending email from the deployment stage. 

If by deploying sentry no mail was working what is here for us left to do, did we missed something on the smtp docker file, since nowhere are any changes mentioned there.

**Comment by uhlhosting** [comment] 2019-07-09 11:12
```
cosmic@sentry:~/sentry/onpremise$ telnet mail.uhlhosting.ch 465
Trying 151.80.200.229...
Connected to panel.uhlhosting.ch.
```

All the connections to the server were always working.

**Comment by BYK** [comment] 2019-07-24 13:03
This is not the place to ask configuration advice, our forums are, as you already posted: https://forum.sentry.io/t/smtp-no-suitable-authentication-method-found/7145/8

We do our best to support everyone w/ configurations but this is not a bug, feature request or anything related to Sentry code right now so closing the issue.

**Closed by BYK** 2019-07-24 13:03 UTC
