### ISSUE TITLE
Sentry build fails on Xcode 16.0 beta

### ISSUE THREAD

**Issue by ryanbrink** [getsentry/sentry#72595] opened 2024-06-12 13:46 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Install Xcode 16 beta (16A5171c)
2. Build a target that succeeded in previous versions of Xcode

Note that the target has Sentry 8.28.0 installed via Swift Package Manager.

### Expected Result

Build succeeds! 🥳

### Actual Result

Sentry compile fails 💔
<img width="463" alt="image" src="https://github.com/getsentry/sentry/assets/5272967/c93ffe25-e883-45f0-9902-9e463f55f3c5">

### Product Area

Other

**Comment by jtdaugh** [comment] 2024-06-12 19:12
`#include <exception>` on `SentryCrashMonitor_CPPException` fixes this

**Comment by kahest** [comment] 2024-06-12 20:21
Hey @jtdaugh thanks for writing in - this is a duplicate of https://github.com/getsentry/sentry-cocoa/issues/4050, we have a fix ready and will release this week.

**Closed by kahest** 2024-06-12 20:21 UTC
Labels: Waiting for: Support
