### ISSUE TITLE
Source map can't work on private server.

### ISSUE THREAD

**Issue by juan-imares** [getsentry/sentry#15438] opened 2019-11-05 04:40 UTC
## Important Details

How are you running Sentry?

* [√] On-Premise docker [Version 9.1.2]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

![image](https://user-images.githubusercontent.com/15643295/68177636-e956db80-ffc3-11e9-8508-708f44841002.png)

## Description

source map can't work well and with an 404 error:
![image](https://user-images.githubusercontent.com/15643295/68178540-5a4bc280-ffc7-11e9-89bb-19d8070c71f0.png)

## Steps to Reproduce

1. build sentry with docker, http://ip1:port.

2. my webpack config for upload files:
![image](https://user-images.githubusercontent.com/15643295/68178001-2f606f00-ffc5-11e9-8f34-1ed9acfd4343.png)
![image](https://user-images.githubusercontent.com/15643295/68178014-41421200-ffc5-11e9-9872-0ee451d9e406.png)

3. my sentry: http://ip1:port
my web client: http://ip2, and the the javascript files: http://ip2/static/scripts/test.js
![image](https://user-images.githubusercontent.com/15643295/68178348-aea27280-ffc6-11e9-8c1a-354dc09e9214.png)
 
4. upload .js and .js.map to http://ip1:port
![image](https://user-images.githubusercontent.com/15643295/68178468-1953ae00-ffc7-11e9-8090-e16fa7e57f9a.png)

5. report an error to http://ip1:port.

### What you expected to happen

source map works well on my private server.

### Possible Solution

I test on https://sentry.io also, it works very well on https://sentry.io, and my webpack upload config without any difference. Why it can match well on https://sentry.io but can't match on http://ip1:port??  If I missing some configurations on my private server? 
it already bothered me for days.
Could you help me? Thanks ^_^

**Comment by BYK** [comment] 2019-11-18 15:09
Did you upload the source maps before the errors happened? (trying to verify https://docs.sentry.io/platforms/javascript/sourcemaps/#verify-artifacts-are-uploaded-before-errors-occur is not the cause)

**Comment by juan-imares** [comment] 2019-11-21 04:01
Yes I uploaded the source maps before the errors happened. It still can't work...

**Comment by BYK** [comment] 2019-11-21 13:38
@juan-imares are you able to try Sentry 10 and see if the issue still happens?

**Comment by juan-imares** [comment] 2019-11-22 08:15
But the latest release is 9.1.2 on github. How can I try Sentry 10 please?

**Comment by lfyfly** [comment] 2019-12-29 09:57
I have same problem in Sentry@9.1.1

**Comment by BYK** [comment] 2019-12-30 18:35
@juan-imares you can try the beta: https://github.com/getsentry/onpremise

**Comment by calledT** [comment] 2020-02-20 08:25
I have same problem in Sentry@9.0.0. my upload sourcemap file url prefix is absolute path

**Comment by Amirresm** [comment] 2020-03-02 23:40
Can anyone confirm that Sentry 10 fixes this problem?

**Comment by calledT** [comment] 2020-03-03 01:51
> Can anyone confirm that Sentry 10 fixes this problem?

I've solved this problem follow this issue comment https://github.com/getsentry/sentry/issues/4168#issuecomment-341679115

**Comment by BYK** [comment] 2020-03-11 13:42
Closing due to staleness. Also, this should be solved with the latest version and using the onpremise setup. If you are having any issues see [@calledT's comment above](https://github.com/getsentry/sentry/issues/15438?email_token=AAA66PBNM4XFY72C76KMS6DRFQ7YHA5CNFSM4JI5QMFKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENRNN6A#issuecomment-593724324), referring to [another comment](https://github.com/getsentry/sentry/issues/4168#issuecomment-341679115) 😀

**Closed** 2020-03-11 13:43 UTC

**Comment by llisonly** [comment] 2020-09-07 10:43
> #4168 (comment)

@calledT how to config it
