### ISSUE TITLE
multiple requests to install github app, prevented app from being installed

### ISSUE THREAD

**Issue by susanev** [getsentry/sentry#33759] opened 2022-04-19 21:34 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. as not a github owner, submit a request to install the github app
2. as a github owner, install the app
3. notice it says installed on github but shows as uninstalled on sentry
4. reject all pending requests to install
5. uninstall current sintallation
6. install fresh
7. now it works

i know this is probably an edge case, but figured id report to yall how we fixed it

### Expected Result

i didnt even know about any of the pending requests, there were more than 10 of the same request
but either way i expected the installation to work without having to reject all pending request

### Actual Result

showed as installed on github
wasnt installed on sentry

**Comment by leeandher** [comment] 2022-04-20 21:24
Hi @susanev, thanks for the issue report! I wasn't able to reproduce the 'appearing uninstalled on Sentry' behaviour you described and was wondering what you meant by 'having to reject all the pending requests'? Are you referring to installation requests made by Sentry users or GitHub users?

**Comment by susanev** [comment] 2022-04-28 01:56
@leeandher im sorry, i should have taken a screenshot. but in github, below the installed apps, there were 10+ pending requests to install sentry, once i removed all those and then removed the current installation and reinstalled it, it worked.

**Comment by leeandher** [comment] 2022-04-28 17:58
@susanev Thanks for the follow up! I've added a ticket to our backlog to investigate this issue, thanks for letting us know!

**Comment by sentaur-athena** [comment] 2024-12-11 23:37
I'm going to close this since the ticket is old and we don't have any similar reports. @susanev please feel free to re-open if this is still blocking you.

**Closed by sentaur-athena** 2024-12-11 23:37 UTC
Labels: Component: Integrations

**Comment by susanev** [comment] 2024-12-11 23:42
no worries im not blocked, this was reported in 2022
