### ISSUE TITLE
Config SENTRY_MAX_MESSAGE_LENGTH does not work

### ISSUE THREAD

**Issue by nbhuy89** [getsentry/sentry#13585] opened 2019-06-07 04:19 UTC
Hi,
I config SENTRY_MAX_MESSAGE_LENGTH to another number, but the message always be truncated at 1000 characters, how can i make it work?
I'm using sentry server version Sentry 9.1.1
Thanks,

**Comment by untitaker** [comment] 2019-06-10 14:16
9.1.1 should have a limit of 8000 chars. Which message attribute do you mean? Could you provide a screenshot?

**Comment by untitaker** [comment] 2019-06-10 14:16
9.1.1 should have a limit of 8000 chars. Which message attribute do you mean? Could you provide a screenshot?

**Comment by nbhuy89** [comment] 2019-06-17 01:47
Sorry, I rechecked, I see it truncate at 8000 chars like you said, Is there any way to increase this limit number?

**Comment by caseyduquettesc** [comment] 2019-06-17 20:27
I found in 9.1 that `SENTRY_MAX_MESSAGE_LENGTH` was not working because the Rust processor (new) had a hardcoded message field size. Since 9.1's release, we've been running with this patch that disables the Rust processor trimming, which appears to be optional, with no problems. We increased max message length from 8KB to 256KB.

```diff
--- sentry/src/sentry-dev/src/sentry/event_manager_9.1.py	2019-04-25 10:06:31.000000000 -0700
+++ sentry/src/sentry-dev/src/sentry/event_manager_new.py	2019-04-25 10:06:48.000000000 -0700
@@ -444,7 +444,7 @@
             valid_platforms=list(VALID_PLATFORMS),
             max_secs_in_future=MAX_SECS_IN_FUTURE,
             max_secs_in_past=MAX_SECS_IN_PAST,
-            enable_trimming=True,
+            enable_trimming=False,
             is_renormalize=self._is_renormalize
         )
 ```
And in our Dockerfile,
```
patch /usr/local/lib/python2.7/site-packages/sentry/event_manager.py /etc/sentry/patchfiles/event_manager.patch
```

**Comment by BYK** [comment] 2019-06-18 12:51
@untitaker do you know whether this was intentional or not[/

**Comment by untitaker** [comment] 2019-06-18 13:35
We didn't think that people would care about this setting. I would be cool with a single setting that just turns of trimming altogether (like in @caseyduquettesc's patch). Just make sure it's `false` by default :)

**Comment by troyvo** [comment] 2019-06-26 07:31
> I found in 9.1 that `SENTRY_MAX_MESSAGE_LENGTH` was not working because the Rust processor (new) had a hardcoded message field size. Since 9.1's release, we've been running with this patch that disables the Rust processor trimming, which appears to be optional, with no problems. We increased max message length from 8KB to 256KB.
> 
> ```diff
> --- sentry/src/sentry-dev/src/sentry/event_manager_9.1.py	2019-04-25 10:06:31.000000000 -0700
> +++ sentry/src/sentry-dev/src/sentry/event_manager_new.py	2019-04-25 10:06:48.000000000 -0700
> @@ -444,7 +444,7 @@
>              valid_platforms=list(VALID_PLATFORMS),
>              max_secs_in_future=MAX_SECS_IN_FUTURE,
>              max_secs_in_past=MAX_SECS_IN_PAST,
> -            enable_trimming=True,
> +            enable_trimming=False,
>              is_renormalize=self._is_renormalize
>          )
> ```
> 
> And in our Dockerfile,
> 
> ```
> patch /usr/local/lib/python2.7/site-packages/sentry/event_manager.py /etc/sentry/patchfiles/event_manager.patch
> ```

I've tried this way but the issue is still there.
![event](https://user-images.githubusercontent.com/22233186/60160201-0d88fb80-981f-11e9-8a39-1823bfdb5e9d.png)

**Comment by jan-auer** [comment] 2019-07-17 16:47
It might be worth noting here that we're planning to move all of that code into a new, separate service. As part of this, many of these settings might no longer be configurable going forward (such as trimming, for instance).

Might I ask what the use case is for such large messages? With event attachments (basically file uploads that show up on the issue details screen), we might have a suitable alternative in Sentry 10.

**Comment by caseyduquettesc** [comment] 2019-07-17 17:32
@jan-auer 
One of our projects in our on-prem setup is for android crashes. But the crashes don't come directly to Sentry; they go through a proxy for automatic triaging, symbolication, and doing Jira integrations before it gets forwarded to Sentry using the standard java client to send. These crashes don't use the exception interface, and dump all the information into the message field plus tags. This data can be large (up to 0.5MB) if it includes thread dumps. I understand this is arguably improper use of the tool, but that process was before my time. Ideally it would use extra data and exception fields properly, but for now, this is what I'm stuck with.

I completely understand that your roadmap may not necessarily support my use case and we've accepted that we have sort of gone off book here. I appreciate that you asked though and hope you just continue to keep doing what's best for the product, it's great.

A warning for anyone else disabling trimming and inserting large messages - it will absolutely kill your snuba/clickhouse service with searching large messages. I had to just disable message searching entirely for this one project until I can figure out either how to reduce the message size just in clickhouse or migrating message searching to something like elastic search.

**Comment by BYK** [comment] 2020-10-22 20:00
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

Regarding @jan-auer's last message, this new service, Relay, is now part of Sentry deploys. You can find more information over at the docs: https://docs.sentry.io/product/relay/

**Closed by BYK** 2020-10-22 20:00 UTC
