### ISSUE TITLE
 sentry.utils.geo: GeoIP module not available

### ISSUE THREAD

**Issue by webofrxy** [getsentry/sentry#12827] opened 2019-04-18 02:00 UTC
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version sentry : 9.1.0-onbuild]
* [ ] docker-compose 1.24.0 docker 1.13.1

## Description

[What happened]
![image](https://user-images.githubusercontent.com/23710927/56331692-fa730300-61bf-11e9-96dd-d2218df8980f.png)

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/23710927/56331806-6b1a1f80-61c0-11e9-99e4-5abf721813ec.png)
then `docker-compose logs` you will find that

**Comment by untitaker** [comment] 2019-04-18 08:44
Duplicate of #12829

**Closed by untitaker** 2019-04-18 08:44 UTC

**Comment by webofrxy** [comment] 2019-04-19 01:09
i install GeoIP in web container ,but `docker-compose up -d ` will show this:
![image](https://user-images.githubusercontent.com/23710927/56399725-7170d000-6282-11e9-9b6e-aa3e0e7d374e.png)
![image](https://user-images.githubusercontent.com/23710927/56399743-8f3e3500-6282-11e9-9b4f-00b89c7c8c6c.png)

where should i install GeoIP?
