### ISSUE TITLE
Minimum Version Requirement Documentation Wrong for Replays in Python

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#67973] opened 2024-03-29 22:04 UTC
### Problem Statement

Minimum version in documentation is currently 1.20.0 in Python for Replays in backend errors setup documentation here: https://docs.sentry.io/product/session-replay/getting-started/#replays-for-backend-errors

It needs to be 1.25.x since the frontend integration needs to successfully pass the sentry-replay_id= header to the backend events.  The Python SDK version has to be at least 1.25.x in order for these baggage headers to be received per our documentation here: https://docs.sentry.io/platforms/python/usage/distributed-tracing/.

### Solution Brainstorm

Update to correct version

### Product Area

Other

**Comment by michellewzhang** [comment] 2024-04-01 16:55
fixed with https://github.com/getsentry/sentry-docs/pull/9594!

**Comment by ryan953** [comment] 2024-04-01 20:44
Turns out that the [tracing docs](https://docs.sentry.io/platforms/python/usage/distributed-tracing/) have this to say:
> However, if you use version 1.25.x or below, you need to have our [performance monitoring feature enabled](https://docs.sentry.io/platforms/python/performance/) for distributed tracing to work. If you don't want to activate performance monitoring, you can also setup a [custom instrumentation](https://docs.sentry.io/platforms/python/usage/distributed-tracing/custom-instrumentation/).

So it would work for versions <=1.25 if performance monitoring is enabled.
It'll also work for version >=1.26 without needed to enable anything

Confirmed by looking at the [release notes for 1.26](https://github.com/getsentry/sentry-python/releases/tag/1.26.0): 
> Tracing without performance (https://github.com/getsentry/sentry-python/pull/2136) by @antonpirker


We should update this line to point to v1.26 instead of 1.25

**Closed** 2024-04-01 21:05 UTC
Labels: Product Area: Replays
