### ISSUE TITLE
Breadcrumbs can have a timestamp that is outside the start/end times of the replay -> Hovering that crumb causes an overflow in the timeline

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#35512] opened 2022-06-09 13:47 UTC
Maybe an issue with timestamps in s vs ms?

![Image](https://user-images.githubusercontent.com/79684/172863139-bdfbbf15-6e8a-4656-8cea-67d2b5cdfb0a.png)

Related to #35912

**Comment by ryan953** [comment] 2022-06-24 22:35
@danecando In #36009 you mentioned this ticket saying:

> I haven't been able to reproduce it since the tooltip mentioned in the ticket is no longer part of the breadcrumb item UI.

I'm not sure the tooltip itself is related, for sure hovering over the breadcrumb is related. 

In the screenshot on this ticket I can see some other info:
1. the Timeline component ends at about the `5:57` mark, the replay is less than `6:00` long.
2. The breadcrumb shows a timestamp of `6:42` (the 19 hours part we can ignore, it was another bug related to timezones, now fixed)

![172863139-bdfbbf15-6e8a-4656-8cea-67d2b5cdfb0a](https://user-images.githubusercontent.com/187460/175716601-3279627b-91d6-47ce-8e26-eebea166b835.png)

So when we hover over that breadcrumb, we probably are highlighting the 6:42 timestamp, but the timeline thinks the end is at `5:57`. So it's going too far to the right.

There is some logic in static/app/utils/replays/replayDataUtils.tsx `replayTimestamps()` to figure out the start/end timestamps, so idk if that was broken when this bug got filed, or if there is something else afoot.

**Comment by danecando** [comment] 2022-06-28 18:20
@billyvg do you have any steps to reproduce this one or a replay you can link?

**Comment by billyvg** [comment] 2022-06-28 22:36
@danecando ugh unfortunately I don't atm - let's table this for now until we can get a repro.

**Comment by ryan953** [comment] 2022-06-29 18:12
The screenshot shows that the breadcrumb is outside the bounds of the start/end timestamp, which is the real problem.

That shouldn't be happening because of `replayTimestamps()` here: https://github.com/getsentry/sentry/blob/master/static/app/utils/replays/replayDataUtils.tsx#L143-L162

I'll close this, if it appears to be a problem again we can re-open.

**Closed by ryan953** 2022-06-29 18:12 UTC
Labels: Type: Bug, Status: Backlog, Team: Emerging Technology
