### ISSUE TITLE
Missed Cronjob Check-In too late

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#59607] opened 2023-11-08 11:24 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Have a cronjob miss the check-in
2. Check in 2 minutes later
3. Check out properly 30 minutes later

### Expected Result

The cronjob should first be marked as missed, and an additional check-in should be successful after 2 minutes.

### Actual Result

The successful check-in is marked to have happened after 32 minutes. So when the check-in is done for a previously missed check-in, that check-in isn't registered. Instead, when the check-out happens, the check-in is marked to have happened.

Also, in the cronjob overview, the duration is missing:

![image](https://github.com/getsentry/sentry/assets/51749023/9a428cfd-77b4-4fa2-9c9c-52e99e678860)

Noteworthy is also that the check-in is marked as "expected: 8.11.12 23 CET", but that's in the future at the time of writing.

### Product Area

Crons

### Link

https://prisjakt-ab.sentry.io/crons/update-products-no/?project=4505192926216192

**Comment by evanpurkhiser** [comment] 2023-11-09 22:14
Hey @jeengbe - I think this is a result of an incident the other day on our end.

See https://status.sentry.io/incidents/4h3k291m1p20

We were failing to ingest some check-ins. So what happened here is your first `in_progress` never made it through our ingestion pipeline. Your OK check-in then created a check-in with no in_progress check-in, this is why there was no duration, because if failed. This is also why it was marked as missed, because the `in_progress` never made it through.

Ingestion outages like this are an extraordinary case for us as we strive very hard to ensure we do **not** drop customer data.

> The cronjob should first be marked as missed, and an additional check-in should be successful after 2 minutes.

This actually isn't the expected behavior for your cron-job. It will only be marked as missed if you don't get a check-in within 5 minutes.

Let me know if that all makes sense!

**Closed by evanpurkhiser** 2023-11-09 22:14 UTC
Labels: Product Area: Crons, Waiting for: Product Owner

**Comment by jeengbe** [comment] 2023-11-09 22:55
Hi @evanpurkhiser! Looks a lot like that's related, all good then. 🙂 

An issue - maybe that's specifically when ingestion fails, I assume that's to be investigated - is that the span that only registered the check-out still displays the check-out time as "Started" in the dashboard. I have no suggestion of how to fix this, but the way it's currently is misleading. 

And, also, it matched the event to the wrong check-in. So "Expected at" displays "Nov 8, 23 CET" twice even though the event happened on the 7th at 23:25ish

**Comment by jeengbe** [comment] 2023-11-09 22:57
For outages like the one you mentioned, it would be nice if it actually showed that in the affected places in the UI. Even though there's an incident report popup, I rarely pay attention to that. A tiny alert box maybe alongside issues potentially related to an outage might help a lot.
