### ISSUE TITLE
"Removing Archived Issues from Metric Alerts" not Working

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#74186] opened 2024-07-12 00:06 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

This is following outlined process [here](https://sentry.io/changelog/removing-archived-issues-from-metric-alerts/)

1.) Create a Metric Alert
2.) Define Metric Alert for Steps 1 and 2 as shown here 
<img width="1082" alt="Screenshot 2024-07-11 at 5 00 59 PM" src="https://github.com/user-attachments/assets/9396591f-abc0-496a-b01c-17f0c4d7c32e">
3.) Save changes

### Expected Result

 errors that  are archived would not be included in the alert/message and alert graph would look something like the following:
<img width="686" alt="Screenshot 2024-07-11 at 5 03 36 PM" src="https://github.com/user-attachments/assets/73081a56-f53b-43da-aafc-58197a94a19a">

### Actual Result

The filter simply removes all errors and the alert graph does not look as expected
<img width="1033" alt="Screenshot 2024-07-11 at 5 03 47 PM" src="https://github.com/user-attachments/assets/aed2b834-e970-44a5-912a-ad05bc821ab2">

### Product Area

Alerts

**Comment by rachrwang** [comment] 2024-07-12 00:56
@ReneGreen27 - do you know if this example is EU or US?

**Comment by futornoi** [comment] 2024-07-12 07:26
> @ReneGreen27 - do you know if this example is EU or US?

EU

**Comment by rachrwang** [comment] 2024-07-12 17:09
Thank you! I think it's likely related to https://github.com/getsentry/sentry/issues/74063, so if you want to follow that ticket as well, we'll make sure to update it as we go along

**Comment by ceorourke** [comment] 2024-12-09 20:12
Closing as it's a dupe of the aforementioned issue.

**Closed by ceorourke** 2024-12-09 20:12 UTC
Labels: Product Area: Alerts
