### ISSUE TITLE
Creating issue w/JIRA integration causes description dialog to disappear

### ISSUE THREAD

**Issue by mikellykels** [getsentry/sentry#5177] opened 2017-03-31 22:57 UTC
When creating a JIRA ticket from Sentry, creating a new line or typing a lot in the description will cause the dialog modal to disappear.

To reproduce the issue:

1) use an ipad. 
2) open a sentry event. 
3) click the JIRA button and create an issue 
4) type lots and lots into the description field (especially new lines)

![img_0001](https://cloud.githubusercontent.com/assets/20312973/24572064/80d72158-162a-11e7-851c-78b4d47d5c98.PNG)

**Comment by benvinegar** [comment] 2018-10-01 04:14
We've since relaunched our [Jira integration for Sentry](https://blog.sentry.io/2018/09/10/atlassian-jira-bitbucket-update), and I can't reproduce this in the new version. Closing.

**Closed by benvinegar** 2018-10-01 04:14 UTC
