### ISSUE TITLE
Can't select Chinese locale in appearance page

### ISSUE THREAD

**Issue by hustcc** [getsentry/sentry#2562] opened 2016-01-18 09:14 UTC
Hello, sentry is very nice. But I `maybe find a bug`.
I have locale file In `src/sentry/locale`, but can not find `Simplified Chinese` option in appearance page. Exactly, **can not find the option which locale name contains `-`**. Look at below:

![issue_image](https://raw.githubusercontent.com/hustcc/hustcc/gh-pages/img/sentry/sentry_issue_locale.png)

 Search the code, I find code in `conf/server.py`

```py
from .locale import CATALOGS
LANGUAGES = tuple((code, name) for code, name in LANGUAGES
                  if code in CATALOGS)
```
the problem is at ` code in CATALOGS`. code is standard locale code, but CATALOGS is a dir name list, can not match. e.g. `zh_TW != zh-tw`.

**So need to updae code in `conf/locale.py`, below:**

```py
#change locale file dir name to locale code
def dirname_to_local(dir_name):
    if '_' in dir_name:
        pre, post = dir_name.split('_', 1)
        dir_name = '{}-{}'.format(pre, post.lower())
    return dir_name

with open(os.path.join(os.path.dirname(sentry.__file__),
                       'locale', 'catalogs.json'), 'r') as f:
    CATALOGS = json.load(f)['supported_locales']
    CATALOGS = [dirname_to_local(dirname) for dirname in CATALOGS]
```

If this solution is OK, **`can I push a request?`**

**Comment by dcramer** [comment] 2016-01-18 09:27
This file gets generated automatically — we do this to limit translations that we enable to only those that are reasonably localized.


On January 18, 2016 at 1:14:41 AM, atool (notifications@github.com) wrote:

Hello, sentry is very nice But I maybe find a bug
I have locale file In src/sentry/locale, but can not find Simplified Chinese option in appearance page Look at below:



Search the code, I find code in conf/serverpy

from locale import CATALOGS
LANGUAGES = tuple((code, name) for code, name in LANGUAGES
                  if code in CATALOGS)
the problem is at code in CATALOGS code is standard locale code, but CATALOGS is a dir name list, can not match eg zh_TW != zh-tw

So need to updae code in conf/localepy, below:

#change locale file dir name to locale code
def dirname_to_local(dir_name):
    if '_' in dir_name:
        pre, post = dir_namesplit('_', 1)
        dir_name = '{}-{}'format(pre, postlower())
    return dir_name

with open(ospathjoin(ospathdirname(sentry__file__),
                       'locale', 'catalogsjson'), 'r') as f:
    CATALOGS = jsonload(f)['supported_locales']
    CATALOGS = [dirname_to_local(dirname) for dirname in CATALOGS]
If this solution is OK, can I push a request?

**Comment by hustcc** [comment] 2016-01-18 09:32
So how to solve it?  if not update the code of `locale.py`, then all the locale file dir show be renamed!

**Comment by dcramer** [comment] 2016-01-18 09:51
Actually it looks like zh_TW is already in catalogs.json. Will check in the morning (PST) as something def appears wrong here.

**Comment by hustcc** [comment] 2016-01-18 10:27
yeah, zh_TW and zh_CN all exist, but because dir name is not match the locale code, so be Filtered.

**Comment by dcramer** [comment] 2016-01-18 23:58
Closing this out as was fixed in PR

**Closed by dcramer** 2016-01-18 23:58 UTC
