### ISSUE TITLE
Migration 0321 - could not create unique index

### ISSUE THREAD

**Issue by kralos** [getsentry/sentry#5529] opened 2017-06-07 00:47 UTC
Sentry upgrade from `8.16.0` -> `8.17.0` using docker.

After attempting to upgrade my sentry PGSQL database:
```
docker run \
    -it \
    --rm \
    --network=ops \
    -e SENTRY_REDIS_HOST=redis \
    -e SENTRY_POSTGRES_HOST=postgres \
    -e SENTRY_DB_USER=sentry \
    -e SENTRY_DB_PASSWORD='**********************' \
    -e SENTRY_SECRET_KEY='***************************' \
    -v /var/lib/sentry/files:/var/lib/sentry/files \
    sentry:8.17.0 upgrade
```

I got the following error:
```
 > sentry:0321_auto__add_field_projectkey_rate_limit_count__add_field_projectkey_rate
 > sentry:0321_auto__add_unique_environment_organization_id_name
FATAL ERROR - The following SQL query failed: CREATE UNIQUE INDEX CONCURRENTLY sentry_environment_organization_id_6c9098a3d53d6a9a ON sentry_environment (organization_id, name)
The error was: IntegrityError('could not create unique index "sentry_environment_organization_id_6c9098a3d53d6a9a"\nDETAIL:  Key (organization_id, name)=(1, ) is duplicated.\n',)
SQL: CREATE UNIQUE INDEX CONCURRENTLY sentry_environment_organization_id_6c9098a3d53d6a9a ON sentry_environment (organization_id, name)
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 160, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 60, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 29, in _upgrade
    verbosity=verbosity,
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/usr/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/usr/local/lib/python2.7/site-packages/south/migration/migrators.py", line 91, in run_migration
    south.db.db.rollback_transaction()
  File "/usr/local/lib/python2.7/site-packages/south/db/generic.py", line 1000, in rollback_transaction
    transaction.leave_transaction_management(using=self.db_alias)
  File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 78, in leave_transaction_management
    get_connection(using).leave_transaction_management()
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 310, in leave_transaction_management
    "This code isn't under transaction management")
django.db.transaction.TransactionManagementError: This code isn't under transaction management
```

**Comment by JannKleen** [comment] 2017-06-07 08:23
Hi, these instructions https://github.com/getsentry/sentry/issues/5502 fixed it for me

**Comment by kralos** [comment] 2017-06-07 09:50
Thanks @JannKleen I don't care about my deployment. I just rebuilt my sentry server from scratch and it worked fine migrating from no database up to `8.17.0`. I was more reporting the issue so migration 321 could be fixed in a later version (for people who haven't upgraded to `8.17.0+` yet).

**Comment by mattrobenolt** [comment] 2017-06-08 08:10
Closing as a dupe of #5502

**Closed by mattrobenolt** 2017-06-08 08:10 UTC
