### ISSUE TITLE
Allow Teams to select icon color or avatar

### ISSUE THREAD

**Issue by eswidler** [getsentry/sentry#65982] opened 2024-02-28 17:59 UTC
### Problem Statement

We've been setting up teams in Sentry and I saw that Sentry auto-selects a color for each team's icon.  Our teams are already associated w/ colors in our org, so it'd be nice to have matching colors in Sentry.

It seems like the color is directly tied to the slug.  Any slug name always produces the same color.  We could come up with some slug name that produces the color we want, but this does not seem ideal and might result in badly named teams.

### Solution Brainstorm

Allow users to select the icon color for their team.  Or, better yet, allow them to select an image file as an avatar.

### Product Area

Settings - Teams

**Comment by Dhrumil-Sentry** [comment] 2024-02-28 18:52
Thanks a lot for this feedback

This issue seems to be a duplicate of https://github.com/getsentry/sentry/issues/49864, I'll use the original issue to track this request

**Closed by Dhrumil-Sentry** 2024-02-28 18:52 UTC
Labels: Product Area: Settings - Teams, Waiting for: Product Owner

**Comment by eswidler** [comment] 2024-02-28 19:13
Thanks @Dhrumil-Sentry.  I'll just point out that the issue you linked to doesn't suggest the ability to choose team color from the ones Sentry already support.  To be particular, that would be a "good enough" resolution for our purposes.  Perhaps that's an easier feature to implement than full avatar support.
