### ISSUE TITLE
IntegrityError: insert or update on table "sentry_messagefiltervalue" violates foreign key constraint "group_id_refs_id_1fb6dc4e" (Sentry 6.3.0)

### ISSUE THREAD

**Issue by mgedmin** [getsentry/sentry#1036] opened 2013-10-14 12:37 UTC
Saw an internal error today:

    IntegrityError: insert or update on table "sentry_messagefiltervalue" violates foreign key constraint "group_id_refs_id_1fb6dc4e"
    DETAIL:  Key (group_id)=(7) is not present in table "sentry_groupedmessage".

Raw traceback:
```
  File "celery/task/trace.py", line 233, in trace_task
    R = retval = fun(*args, **kwargs)
  File "sentry/tasks/store.py", line 36, in save_event
    Group.objects.save_data(data.pop('project'), data)
  File "django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "django/db/transaction.py", line 217, in __exit__
    self.exiting(exc_value, self.using)
  File "django/db/transaction.py", line 281, in exiting
    commit(using=using)
  File "django/db/transaction.py", line 152, in commit
    connection.commit()
  File "django/db/backends/__init__.py", line 241, in commit
    self._commit()
  File "django/db/backends/postgresql_psycopg2/base.py", line 242, in _commit
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "django/db/backends/postgresql_psycopg2/base.py", line 240, in _commit
    return self.connection.commit()
```

More details:
- got an error notification for .../group/7 at Mon, 14 Oct 2013 07:50:56 -0000
- got an error notification for .../group/8 at Mon, 14 Oct 2013 07:50:56 -0000
- got this internal error, recorded as .../group/9 at Mon, 14 Oct 2013 07:50:57 -0000

Some kind of a race condition?

**Comment by camilonova** [comment] 2015-05-14 12:15
I got the same here:

```
update or delete on table "sentry_groupedmessage" violates foreign key constraint "group_id_refs_id_4b5aa2b" on table "sentry_searchdocument"
```

**Comment by dcramer** [comment] 2015-05-14 17:20
This table no longer exists in current versions and 6.x is not supported

**Comment by camilonova** [comment] 2015-05-15 17:24
I have Sentry 7.4.3 and I'm getting this error

**Comment by dcramer** [comment] 2015-05-15 20:03
Sorry, closed preemptively, the searchdocument table does not exist.

**Comment by camilonova** [comment] 2015-05-16 13:20
I'm getting the error 5180 times each day. Anything I could do to help?

**Comment by dcramer** [comment] 2015-05-26 08:19
Can anyone who's getting this confirm they're not setting EAGER=True ?

**Comment by camilonova** [comment] 2015-05-26 16:12
@dcramer I have:
```
CELERY_ALWAYS_EAGER = False
```

**Comment by camilonova** [comment] 2015-05-30 13:41
any other updates?

**Comment by camilonova** [comment] 2015-06-03 12:40
@dcramer I'm getting the error 5167 times each day. Should I remove the table manually and try to do a syncdb or something?

**Comment by dcramer** [comment] 2015-06-03 12:43
This sounds like a race condition and shouldn't be possible if:

- This is current Sentry
- Workers are configured correctly (i.e. CELERY_ALWAYS_EAGER = False)
- You're using Postgres

If you're having this error, can you confirm all of the above are true?

**Comment by camilonova** [comment] 2015-06-03 13:13
I have:

* sentry==7.4.3
* CELERY_ALWAYS_EAGER = False
* (PostgreSQL) 9.3.7

**Comment by dcramer** [comment] 2015-06-04 10:02
Can someone provide a full traceback of the error?

// @camilonova

**Comment by camilonova** [comment] 2015-06-04 13:06
I just upgraded to Sentry==7.5.4, run the upgrade command and now I'm getting this errors from postgres:

´´´
3575 times:
 [2015-06-03 05:00:06 +/-9 hour(s)]  update or delete on table "sentry_groupedmessage" violates foreign key constraint "group_id_refs_id_4b5aa2b" on table "sentry_searchdocument"

 5 times:
 [2015-06-03 17:27:28 +/-9 seconds]  column sentry_team.owner_id does not exist

 3 times:
 [2015-06-03 17:26:54 +/-0 seconds]  operator does not exist: json = json
´´´
@dcramer Can you tell me if I can take a look  somewhere else for more information?

**Comment by dcramer** [comment] 2015-06-04 13:11
```
truncate table sentry_searchdocument
```

**Comment by camilonova** [comment] 2015-06-04 14:07
I did this:
```
db_sentry=# truncate table sentry_searchdocument cascade;
NOTICE:  truncate cascades to table "sentry_searchtoken"
TRUNCATE TABLE
```

I'll wait to see if this works.

**Comment by dcramer** [comment] 2015-06-04 15:28
I'm going to assume this is purely because of that given table. Closing this and we'll reopen if anyone finds a different issue. For now assume the answer is to truncate that table as it's not used.

**Closed by dcramer** 2015-06-04 15:28 UTC

**Comment by camilonova** [comment] 2015-06-08 16:50
I can confirm it works for me. Thanks.
