### ISSUE TITLE
Sidebar positioning when merging issues

### ISSUE THREAD

**Issue by metaa** [getsentry/sentry#10053] opened 2018-10-09 11:45 UTC
## Important Details

How are you running Sentry?

* [X] On-Premise docker 9.0
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

When confirming an issue merge request, the sidebar slides out of place.
![image](https://user-images.githubusercontent.com/5056880/46667262-69482180-cbc9-11e8-9cc0-33c65b2abf46.png)

## Steps to Reproduce

1. Select two or more issues to merge.
2. Hit the merge button.

### What you expected to happen

The sidebar shouldn't move at all. The background is just meant to become blurry.

### Possible Solution

Fix the influence of the `.modal-open` selector in CSS.

**Comment by markstory** [comment] 2018-10-09 16:36
Thank you for submitting this issue. I can't reproduce this issue on master. I suspect it was fixed in #9935.

**Closed by markstory** 2018-10-09 16:36 UTC
Labels: Component: UI

**Comment by metaa** [comment] 2018-10-09 16:44
Thanks for your feedback @markstory

The weird thing is that it still happens on the 9.0 tagged image I pulled today which is reported as "pushed 5 days ago" on docker hub while the patch you referred to was merged 11 days ago.
