### ISSUE TITLE
Create project transfer error UI

### ISSUE THREAD

**Issue by dashed** [getsentry/sentry#52678] opened 2023-07-11 21:36 UTC
### Problem Statement

If a project transfer fails, we should communicate the reason. Typically the project transfer may fail if the project transfer link has expired, or if the project no longer exists.

Today we just display an unhelpful error message:
<img width="1065" alt="Screenshot 2023-07-11 at 5 34 43 PM" src="https://github.com/getsentry/sentry/assets/139499/a4e3857a-fb58-4d0b-bf97-080082fc3f45">

### Product Area

Settings - Projects

**Comment by Dhrumil-Sentry** [comment] 2023-07-12 16:17
This is a duplicate of https://github.com/getsentry/sentry/issues/52005 , So we can use that issue to track this

**Closed by Dhrumil-Sentry** 2023-07-12 16:17 UTC
