### ISSUE TITLE
Resolve All Events should honour Filter terms

### ISSUE THREAD

**Issue by anthonyryan1** [getsentry/sentry#1360] opened 2015-01-02 09:54 UTC
If a person filters the errors they're looking at, I think the Resolve All Events button should take the filter terms into account and resolve only those that are currently shown.

An example use case is if an error that generates many distinct stack traces is fixed. It allows the following work flow.

1. Fix bug that generates many stack traces.
2. Search by common error message.
3. Resolve all errors matching that error message.

**Comment by aldenquimby** [comment] 2015-01-08 13:54
:+1:

**Comment by daronstinnett** [comment] 2015-02-04 14:40
agree!

**Comment by LotharSee** [comment] 2015-02-24 19:56
+1

It also makes more sense. I got tricked the first time I used this button with filters, I was naturally expecting it to use the filters. But it resolved everything!

**Comment by smazurov** [comment] 2015-03-01 07:13
:+1: 

> It also makes more sense. I got tricked the first time I used this button with filters, I was naturally expecting it to use the filters. But it resolved everything!

I did the same thing, though more cautiously. RIP the "regression" inbox.

**Comment by dcramer** [comment] 2015-03-01 09:40
I do agree with everyone that it'd be ideal if "resolve all" was targeted, but the primary reason we haven't done it is because it's not a simple problem.

We generally design features with the idea of "when we rebuild this the way we want to, is this feature still going to be possible?" Right now the stream is based on SQL indexes, and it's *mostly* possible to do this, but we're planning to change this in the future to a new indexing engine. It's not certain whether or not a "do an action on [undefined # of] items" will be a reasonable feature or not. The main issue around this is that most indexing engines have limited filters. That is, they might let you pull in 1,000 items, but if you want to "mark all events as resolved where foo matches bar" it gets to be a bit tricky if the indexer can't return those results.

**Comment by smazurov** [comment] 2015-03-02 19:57
Personally, I would be more than happy with "mark all events on this page as resolved". Here's my use-case:

We have async workers that do various things on the multi-tenant platform.  One of the errors, which is fairly common, was incorrectly appending the tenantId to the message, which would generate hundreds of errors as they weren't properly grouped. I fixed the issue by using a tag for appended data, but in order to resolve those issues, i'd have to click on all 100 checkboxes individually. Doing it 4 or 5 times, as it would mark 1 page at a time, is much more manageable than doing it a 100. This, as you've mentioned doesn't scale to 1000s of events, but it 20x (accurately 15x as thats the number of items on the page) of what we can do currently.

As hackish as it is, if I'm ever in the same situation, a bit of javascript to trigger those click events might be what I'll have to do.

**Comment by dcramer** [comment] 2015-03-02 20:03
To be clear, I was trying to point out that any kind of "+1" wont get this done. We realize it's useful, but it's non-trivial which means it may or may not happen based on architectural decisions we'll make.

That said, search + bulk actions in the new design would solve the above issue.

**Comment by sergei-maertens** [comment] 2015-05-28 13:38
+1 for the bulk actions

**Comment by andybak** [comment] 2015-10-14 08:15
Crikey. I just assumed this is how it would work. I also assumed there would be a bulk 'unresolve' to fix if afterwards.

:-/

Looks like I'd better read up on the API to fix this mess...

**Comment by dcramer** [comment] 2015-10-14 08:16
@andybak if they happen again they will mark as regressions -- only side effect of doing resolve all is you might get more notifications

**Comment by dcramer** [comment] 2015-10-14 08:16
I'm actually going to close this out as its not actionable. We'll see about improving filters on new infrastructure but for now we don't have an async pipeline in place to do things like this.

**Closed by dcramer** 2015-10-14 08:16 UTC

**Comment by andybak** [comment] 2015-10-14 08:19
@dcramer ah thanks. that's good to know. Apologies for what was essentially a disguised +1 in the heat of the moment.

Your earlier comment is interesting: "we're planning to change this in the future to a new indexing engine. It's not certain whether or not a "do an action on [undefined # of] items" will be a reasonable feature or not."

Can I suggest that by saying this you've implicitly decided "optimising indexing" is more important than "bulk actions" which is a touch surprising to me as the latter feels like an rather vital feature which - to a newcomer - is surprising in it's absence.

In either case - ever without the help of the indexing engine, surely bulk actions are still possible, albeit they might need to run as background tasks?

**Comment by dcramer** [comment] 2015-10-14 08:22
@andybak we operate on massive installations as well as small projects, and many things become much more tricky for large installs. We don't want to focus a lot of time on building things that can only help a portion of our users. Generally with search indexer implementations you return a capped set of results, and that set sits around 1,000 commonly. You can imagine how awkward it would be if we said "you can do this with filtering, oh, but if you apply this action it will only apply to 1,000 items". The alternative lives in the map/reduce world, and quite simply we have no intention to implement something along that level of complexity for behavior we dont really think is needed.

The requests are commonly "I want to resolve all these search results", but really the actually problem is "I dont care about these results anymore" or "I want to get notified again". We have better solutions to solve this than allowng you to resolve arbitrary history

**Comment by andybak** [comment] 2015-10-14 08:26
@dramer - I've come from a world of 500 emails in my inbox and I'm still rather treating the stream like an inbox that I need to clear. i.e. I was treating 'resolve everything' as a maintenance goal

> I don't care about these results anymore

This is essentially my problem. I'd welcome any advice on how to modify my workflow.

(I realise I might be hijacking this issue to please tell if to take this elsewhere if so)

**Comment by dcramer** [comment] 2015-10-14 08:28
I think its important to ask what the goal of resolving them is. Is it to let your team members know that youve fixed it? Is it to remove them from the feed? Is it to ensure if they happen again you get notified?

There's a lot of behavior in Sentry to work around various things, and while we think resolution is helpful, it can be pretty hard to provide something like GMail's filtering/action ability without complex infrastructure.

**Comment by andybak** [comment] 2015-10-14 08:32
@dcramer it's to separate signal from noise.

Let's say one bug creates 1000 errors and is easily fixed.

Somewhere in my stream is another more serious bug that only creates a handful of errors (maybe payment is failing in a small set of cases). Unless I can clear my stream, I'm likely to miss it.

**Comment by dcramer** [comment] 2015-10-14 19:57
That's fair, and isn't something we can reasonable solve today. 

There might be a middle ground where we allow it to apply to some level of the filter but another challenge is figuring out UX. We can always go "resolve all" as we can simply set a marker, but others well likely have to do asynchronously and determine (and communicate) limitations.
