### ISSUE TITLE
Don't log sensitive POST parameters on auth failures

### ISSUE THREAD

**Issue by ctrochalakis** [getsentry/sentry#5216] opened 2017-04-07 09:37 UTC
Hello, I am using the latest Sentry version (8.15.0).

I am using the sentry ldap plugin (but that shouldn't be of importance), and I noticed that possible
exceptions raised in the authenticate request are exposed as-is in the console (or log files), I 'd expect those parameters to be treated as sensitive.

```
...
Apr  7 11:59:36 sentry1 sentry[3933]: 08:59:36 [ERROR] django.request: Internal Server Error: /auth/login/myorg/ (status_code=500 request=<WSGIRequest
Apr  7 11:59:36 sentry1 sentry[3933]: path:/auth/login/myorg/,
Apr  7 11:59:36 sentry1 sentry[3933]: GET:<QueryDict: {}>,
Apr  7 11:59:36 sentry1 sentry[3933]: POST:<QueryDict: {u'username': [u'user1'], u'csrfmiddlewaretoken': [u'HJ31jHJE77Rbjqt1ZN4g6NSNOGL4lQ6B'], u'password': [u'password1'], u'op': [u'login']}>,
...
```

**Comment by aleksihakli** [comment] 2017-09-05 13:45
I can confirm this happened on our setup as well. 

I'd expect the Sentry logging module is at fault. It also seems [the logging module crashes on Unicode encoding logging with errors](https://github.com/getsentry/sentry/issues/6029), so there might be a place for a more extensive review of the logging code here?

**Comment by aleksihakli** [comment] 2017-09-05 14:31
I backtraced this to Sentry having no password censoring logging processor:

http://www.structlog.org/en/stable/examples.html?highlight=password#processors

We should probably write a processor that replaces all `password` and other sensitive values from QueryDicts and other sensitive loggable objects so we do not accidentally expose them in plaintext.

**Comment by mattrobenolt** [comment] 2017-09-05 15:06
I guess there was another issue for this, but this has been fixed in https://github.com/getsentry/sentry/pull/5934

**Closed by mattrobenolt** 2017-09-05 15:06 UTC

**Comment by aleksihakli** [comment] 2017-09-05 16:21
Looks like a good approach 👍
