### ISSUE TITLE
Search does not work for custom tag "email"

### ISSUE THREAD

**Issue by Green7** [getsentry/sentry#17502] opened 2020-03-04 19:37 UTC
### Important Details

How are you running Sentry?

Saas (sentry.io)

### Description

In my exception raports I have a few custom tags. One of them is called email. When I search for issues for this tag, the search returns nothing. Search works for other tags.

**Comment by rhcarvalho** [comment] 2020-03-06 14:11
Hi @Green7! This seems unrelated to the SDKs in use, and apparently a problem with the search index, need some further investigation.

In the meantime, could you try setting the email as part of the user details instead of a tag?
https://docs.sentry.io/enriching-error-data/context/?platform=browser#capturing-the-user

This should not only work around the issue, but also unlock features like Gravatar and messaging.

Additionally, please consider migrating from https://github.com/getsentry/raven-csharp to https://github.com/getsentry/sentry-dotnet.

**Comment by rhcarvalho** [comment] 2020-03-06 14:33
@getsentry/sns FYI

**Comment by dashed** [comment] 2020-03-06 14:50
@Green7 Hi, `email` is a reserved field and thus would collide to the tag of the same name. To explicitly search by the `email`, use this form: `tags[email]:email_here`

Please see https://docs.sentry.io/workflow/search/?platform=node#explicit-tag-syntax

Hopefully that should clear things up. 👍

**Comment by Green7** [comment] 2020-03-06 15:25
@dashed: Thank you, it works 👍 
The UI should also handle this situation ...

One more question: how to get issues referring only to a given user?
For example: if I filter issues by tags[email]:email I will get issues for user but "grouped" with issues of the same type of other users. It is hard to view reports only for a specific user. How to solve it ?

**Comment by markstory** [comment] 2020-03-10 13:30
> It is hard to view reports only for a specific user. How to solve it ?

You would either need to redo your search on each issues events in the events subtab, or use discover to get only the events created by the specific user.

**Comment by Green7** [comment] 2020-03-10 16:47
I found it, thank you @markstory .

**Comment by rhcarvalho** [comment] 2020-03-18 17:43
I can still repro clicking on an `email` tag in the event detail page and landing on empty search results. Reopening.

**Comment by rhcarvalho** [comment] 2020-03-18 18:03
Turns out my reproduction was invalid, my browser landed in a search page for the wrong project.
I confirm this specific issue is fixed.

**Closed by rhcarvalho** 2020-03-18 18:03 UTC

**Comment by dashed** [comment] 2020-03-19 04:32
Thanks 👍
