### ISSUE TITLE
In Electron >= 9 IPC must send cloneable objects

### ISSUE THREAD

**Issue by ahallicks** [getsentry/sentry#17238] opened 2020-02-24 10:49 UTC
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Electron 8 shows deprecation warning for passing IPC events in a certain format. I just tested Electron v9.0.2-beta.2 and my renderer process is now throwing errors about IPC events that are being sent by Sentry.

## Steps to Reproduce

1. Install Electron API demos
2. Create and add Sentry to the renderer
3. Wait for the errors to show up in devtools.

Here's my renderer stack trace (line numbers are from the sourcemaps formatted code).
```
Uncaught Error: An object could not be cloned in D:\Electron\{{app}}\node_modules\@sentry\browser\dist\helpers.js:91
    at EventEmitter../lib/renderer/api/ipc-renderer.ts.ipcRenderer.send (ipc-renderer.ts:9)
    at D:\Electron\{{app}}\node_modules\@sentry\electron\dist\renderer\backend.js:45
    at D:\Electron\{{app}}\node_modules\@sentry\hub\dist\scope.js:50
    at Array.forEach (<anonymous>)
    at D:\Electron\{{app}}\node_modules\@sentry\hub\dist\scope.js:49
    at sentryWrapped (D:\Electron\{{app}}\node_modules\@sentry\browser\dist\helpers.js:74)
```

### What you expected to happen

No errors are thrown.

### Possible Solution

I'm assuming this is to do with what is being sent via IPC but as I don't know what that is I can't really comment. All I know is that the data sent must be cloneable by JavaScript if it is an object.

**Comment by davej** [comment] 2020-06-08 17:16
@ahallicks I noticed this too. I fixed it by upgrading to the latest sentry-electron@1.3.0.

**Comment by NaokiOtsu** [comment] 2020-06-27 19:48
In my application, it seems that an error occurred even when I raised it to @sentry/electron: 1.3.0.
I want to do something because many users get sentry errors every day.

electron: 9.0.5
@sentry/electron: 1.3.0

**Comment by NaokiOtsu** [comment] 2020-07-03 11:49
I was using 2 package.json and @sentry/electron of app/package.json was 1.2.0.
I raised it to 1.3.0 and confirmed the operation without any problems.
I apologize to you for a fuss over.

**Comment by BYK** [comment] 2020-10-26 11:02
Closing as this issue seems to be resolved.

**Closed by BYK** 2020-10-26 11:02 UTC
