### ISSUE TITLE
Internal Server Error on Asana Integration

### ISSUE THREAD

**Issue by DanEngelhardt** [getsentry/sentry#11022] opened 2018-12-12 14:19 UTC
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.0.0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I'm trying to link my dockered sentry onpremise installation to our companies asana.
Whenever I click on "Associate Identity" on the page /settings/my-org/my-proj/issue-tracking/ under "asana" it gives me an internal server error (500).

## Steps to Reproduce

1. visit the page /settings/my-org/my-proj/issue-tracking/
2. Under "Inactive Integrations" click on "asana"
3. In the "Asana"-section click on "Associate Identity"
4. you get send to /account/settings/social/associate/asana/?next=%2Fsettings%2Fmy-org%2Fmy-proj%2Fissue-tracking%2F and this shows the 500

docker logs sentry-onpremise_web_1 gives me the following information:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/social_auth/decorators.py", line 27, in wrapper
    raise WrongBackend(backend)
WrongBackend
12:37:59 [ERROR] django.request: Internal Server Error: /account/settings/social/associate/asana/ (status_code=500 request=<WSGIRequest: GET u'/account/settings/social/associate/asana/?next=%2Fsettings%2Fmy-org%2Fmy-project%2Fissue-tracking%2F'>)
```

### What you expected to happen

I expect to be able to enter credentials to link asana to sentry

**Comment by BYK** [comment] 2019-06-10 20:15
Duplicate of getsentry/sentry-plugins#483

**Closed by BYK** 2019-06-10 20:15 UTC
Labels: Component: Integrations, Component: On-Premise

**Comment by grv231** [comment] 2019-11-27 23:17
I just encountered the same issue. Is there any documented solution for it?

**Comment by alex88** [comment] 2020-11-02 11:25
Anyone was able to find a fix/workaround for this?

**Comment by alex88** [comment] 2020-11-02 11:27
It might be a duplicate of the above issue but that issue has been closed since the repo has been merged into this one, so maybe this should be reopened?

**Comment by BYK** [comment] 2020-11-09 14:34
@alex88 the last comment on that former issue still applies: you can submit a PR to fix this 🙂

**Comment by alex88** [comment] 2020-11-09 14:37
forgot to update, It actually works by setting
```
    ASANA_CLIENT_ID = 'xxx'
    ASANA_CLIENT_SECRET = 'xxx'
```

in the `sentryConfPy` section of the helm chart
