### ISSUE TITLE
An issue is seen more then {value} times in {interval} does not reset

### ISSUE THREAD

**Issue by KorbinianMossandl** [getsentry/sentry#17319] opened 2020-02-26 18:22 UTC
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x]  Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Alert gets triggered for every occurrence after {value} is met

## Steps to Reproduce

1. Set an alert if an issue is seen 100 times in 30 days
2. trigger the issue 100 times
3. see alert
4. trigger the issue 101th time
5. see alert

### What you expected to happen

I would expect the counter to reset so only after another 100 occurrences in 30 days would an alert be triggered

### Possible Solution
reset counter

**Comment by plammerts** [comment] 2020-04-08 12:19
Hi Korbinian, I followed the steps to reproduce your issue. Do note, however, that you can set up an action interval to prevent too many incoming alerts. Perhaps this will solve your issue. Otherwise, you can request a new alert condition that triggers every {value} occurrences of an error. You can do this by adding a new GitHub issue and select the 'feature request' option.

**Comment by BYK** [comment] 2020-10-25 20:36
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Closed by BYK** 2020-10-25 20:36 UTC
