### ISSUE TITLE
Dashboards - Be able to add "goal" lines or base lines in graph

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#78612] opened 2024-10-04 15:08 UTC
### Problem Statement

I want to be able to define a line in my graph which is separate of all metrics, just a straight line of what I think should be the baseline
So that I can spot if the data goes over or below it.

Now I basically have to make an equation and let it be a certain number on what I want which feels like a workaround![Image](https://github.com/user-attachments/assets/2210abf4-f9b2-4369-83b6-6692d652f7f1)

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2309) by [Unito](https://www.unito.io)

**Comment by Angelodaniel** [comment] 2024-10-07 15:41
@gggritso 100% so it's probably fine to close this one

**Comment by gggritso** [comment] 2024-10-07 17:06
Dupe of https://github.com/getsentry/sentry/issues/71564

**Closed by gggritso** 2024-10-07 17:06 UTC
Labels: Sync: Jira, Product Area: Dashboards, Waiting for: Product Owner
