### ISSUE TITLE
Impossible to select correct status in the Jira integration configuration

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#76382] opened 2024-08-19 14:20 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Install the Jira integration
2. Go to the Configurations page and click on Configure
3. Add a project
4. Select the status 
5. If the Jira workspace has a lot of statuses, it will be impossible to select the correct one for the project:

![Image](https://github.com/user-attachments/assets/9d2f95a4-39f7-47e4-b3a6-14bdd26ca709)

### Expected Result

the selector should only show the statuses belonging to the selected project

### Actual Result

the selector currently shows all statuses from the Jira workspace

### Product Area

Settings - Integrations

**Comment by GabeVillalobos** [comment] 2024-12-10 20:14
This appears to be a duplicate of https://github.com/getsentry/sentry/issues/73733.

**Closed by GabeVillalobos** 2024-12-10 20:14 UTC
Labels: Product Area: Settings - Integrations
