### ISSUE TITLE
[EU] Linear integration does not work both ways: changing state in linear does not change state in sentry

### ISSUE THREAD

**Issue by mfn** [getsentry/sentry#75314] opened 2024-07-31 05:34 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

This is basically a spin-off from https://github.com/getsentry/sentry/issues/70497#issuecomment-2147689956
> I still haven't seen a working "linear -> sentry" behaviour (i.e. when closing issues), but the reverse is more important for a start.

When you change state of an issue in linear, it propagated the state back to sentry.

Ever since we moved to sentry EU (see above linked issue), this isn't working anymore.

### Reproduce
- set up linear with sentry EU integration
- in sentry: create a linear issue
- go to that issue _in_ linear
- change state to done in linear

### Expected Result

State in sentry changes too to "resolved"

### Actual Result

There's no propagate of actions from linear -> sentry (only: sentry -> linear)

### Product Area

Settings - Integrations

**Comment by sentaur-athena** [comment] 2024-10-21 17:24
I suspect this is the same as https://github.com/getsentry/sentry/issues/75329. Will prioritize them together.

**Comment by Christinarlong** [comment] 2024-12-11 23:39
https://github.com/getsentry/sentry/issues/75329 was closed as completed so I'll close this one too. Please make another ticket and link this one if the issue is still occurring.

**Closed by Christinarlong** 2024-12-11 23:39 UTC
Labels: Product Area: Settings - Integrations
