### ISSUE TITLE
Assign the results of a search to a user

### ISSUE THREAD

**Issue by masochist** [getsentry/sentry#9417] opened 2018-08-17 14:12 UTC
We just found a bug in our sentry-monitored app that caused a lot of issues to be filed in sentry. These issues all resulted from the same bug. It would be nice to be able to search for these issues and then assign them all to the same developer, much like how we can resolve and otherwise act on search results.

**Comment by benvinegar** [comment] 2018-09-30 23:34
Duplicate of #3119

**Closed by benvinegar** 2018-09-30 23:34 UTC
