### ISSUE TITLE
SnubaError: HTTPConnectionPool(host='localhost', port=1218): Max retries exceeded with url: /query

### ISSUE THREAD

**Issue by bushiquanquan** [getsentry/sentry#13492] opened 2019-06-03 07:10 UTC
![image](https://user-images.githubusercontent.com/13992586/58782441-313a9680-8611-11e9-80ba-ea0fa8235344.png)
when response  url  http://xxxx:9000/organizations/sentry/issues/?project=2， error occurs

**Comment by markstory** [comment] 2019-06-03 14:12
What version of sentry are you using?

**Comment by markstory** [comment] 2019-06-03 14:13
Duplicate of #13494

**Closed by markstory** 2019-06-03 14:13 UTC
Labels: Status: Needs More Information
