### ISSUE TITLE
Issue Assignment based on Suspect Commits not applying to New Issues 

### ISSUE THREAD

**Issue by Prithvirajkumar** [getsentry/sentry#55364] opened 2023-08-29 17:10 UTC
### Problem Statement

Within Ownership Rules, I have set `Prioritize Auto Assignment` to `Auto-assign to suspect commits` as shown below:
![Screenshot 2023-08-29 at 12 49 05 PM](https://github.com/getsentry/sentry/assets/56081556/2ac4a0b6-47f4-4082-84f4-8b6a6530cce3)

Since there are no ownership rules configured, my expectation is that New Issues that have a related suspect commit will be assigned to the author of the suspect commit. 

However, when a New Issue is created with a related suspect commit, the author is added to the suggested assignee list but the issue is not assigned to the author of the suspect commit as shown in the example screenshot:
![Screenshot 2023-08-29 at 9 40 58 AM](https://github.com/getsentry/sentry/assets/56081556/b1a2c8b0-3cd6-43e0-a666-0fb110e40f37)

### Solution Brainstorm

The expected behaviour is that this issue should be assigned to the author of the suspect commit. 

### Product Area

Issues

**Comment by leeandher** [comment] 2024-02-07 18:14
I wasn't able to reproduce this, as my tests showed that the suspect commiter was assigned to the issue. There may have been a fix since this was reported, but here are a few scenarios in which this may not be happen and it's actually expected:
- If we find no sentry account associated with the commit email (doesn't appear to be the case from the UI)
- If the committers account is created after the issue has already been created (it will only auto-assign at the next event ingested)

If you are able to continue to reproduce this please let me know.

**Comment by leeandher** [comment] 2024-02-14 19:41
Cross posting here but I believe it can be addressed by #65178.

**Comment by mrduncan** [comment] 2024-03-21 00:24
Fixed in #66991

**Closed by mrduncan** 2024-03-21 00:24 UTC
Labels: Type: Bug, Product Area: Issues
