### ISSUE TITLE
All events wasted columns

### ISSUE THREAD

**Issue by mwarkentin** [getsentry/sentry#48329] opened 2023-05-02 13:00 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I'm using Sentry for a project which doesn't report information for a lot of the columns in the "All Events" view. This means that the page is mainly littered with "empty string" and "no data" while the useful stuff (title and timestamp mainly) are truncated so short they aren't helpful.

### Expected Result

Sentry could automatically hide the fields which are empty across all events in the page:

![image](https://user-images.githubusercontent.com/67560/235673135-c019a208-c67e-4d16-be9d-26953d7692b7.png)

Alternatively, provide a configuration option to let me chose which columns I want to see.

Last option would to be to replace the "empty string" and "no data" strings with actual blank cells, which I think would provide a little bit of extra room, but probably not enough to make the other columns that much more useful.

### Actual Result

![image](https://user-images.githubusercontent.com/67560/235672040-f18cffc2-e7c9-486f-b6cf-8c2bc8786803.png)

### Product Area

Issues

### Link

https://sentry.sentry.io/issues/4115309411/events/?project=4505048029986816&query=level%3Aerror&referrer=issue-stream&statsPeriod=1h&stream_index=0

**Comment by treb00** [comment] 2023-10-21 12:11
I have another mildly infuriating issue which would be solved if this feature would be implemented: I cannot see a the time in the timesptamp column. I always have to stretch the window's width almost two monitors wide just to see it. 

Also I don't use half of the columns either, so it just unnecessary data for me.

**Comment by ceorourke** [comment] 2023-10-24 19:03
I'm gonna close this as a dupe of https://github.com/getsentry/sentry/issues/54138 but feel free to add to it if there are missing things.

**Closed by ceorourke** 2023-10-24 19:03 UTC
Labels: Type: Feature Request, Product Area: Issues, Waiting for: Product Owner
