### ISSUE TITLE
Crons: Crontab schedule parsing error.

### ISSUE THREAD

**Issue by rbisol** [getsentry/sentry#44942] opened 2023-02-22 07:23 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a new Cron monitor
2. Under schedule type select `Crontab`
3. Set a schedule with 6 fields. For example `45 12 * * TUE,THU *`

### Expected Result

The following schedule to be used/shown:

```
At 12:45, only on Tuesday and Thursday
```

It is unclear whether it is only cosmetic or this affects the actual cron feature.

### Actual Result

Sentry reads the 1st field as Seconds "breaking" the parsing:

```
At 45 seconds past the minute, at 12 minutes past the hour, every hour, every day, only in undefined and undefined 
```

The current workaround is to set crontab schedule with 5 fields, from the example above: `45 12 * * TUE,THU`

**Comment by evanpurkhiser** [comment] 2023-02-22 09:34
I think the issue here is actually that we're not validating this syntax. A 6 field crontab is `seconds,minutes,hours,montheday,month,weekday`.

The humanized text has it right:

> At 45 seconds past the minute, at 12 minutes past the hour, every hour

**Comment by buckett** [comment] 2023-02-24 13:04
@evanpurkhiser I think 6 part cron expressions can be different in some places, for example AWS has 6 part for the year instead of seconds : -(

https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html

**Comment by evanpurkhiser** [comment] 2023-04-03 22:58
Duplicate of https://github.com/getsentry/sentry/issues/46824

**Closed by evanpurkhiser** 2023-04-03 22:58 UTC
Labels: Status: Backlog, Team: Crons

**Comment by rodolfoBee** [comment] 2023-04-07 09:38
To anyone still following this thread, please check:  https://github.com/getsentry/sentry/pull/47040
