### ISSUE TITLE
Bad Gatewaj 502 - when load many events

### ISSUE THREAD

**Issue by darton** [getsentry/sentry#43821] opened 2023-01-28 09:44 UTC
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.1.1

### Steps to Reproduce

When load "All events"

### Expected Result

Load "All events" correctly.

### Actual Result

frontend: Bad Gatewaj 502
backend:
docker container logs --follow sentry-self-hosted_nginx_1
logs:  upstream sent too big header while reading response header from upstream

**Comment by hubertdeng123** [comment] 2023-01-30 18:56
Closing this as it is a duplicate of this:
https://github.com/getsentry/self-hosted/issues/1927

**Closed by hubertdeng123** 2023-01-30 18:56 UTC
Labels: Status: Untriaged, Team: Open Source
