### ISSUE TITLE
Jira Integration Problem. Unable to create a task from Sentry when Tempo plugin is enabled.

### ISSUE THREAD

**Issue by olsh** [getsentry/sentry#59816] opened 2023-11-13 06:49 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Install the Tempo plugin https://marketplace.atlassian.com/apps/6572/timesheets-by-tempo-jira-time-tracking?tab=overview&hosting=cloud to Jira
2. Add a required field for the task creation form
3. Set up Sentry <> Jira Cloud integration
4. Go to any issue and create a task from the issue

Notes: In Jira, the required field is a combo box, but in Sentry it's just a text field. And when you leave it empty, the 400 error happens. When you fill the field with a value, the "Create a Jira issue" just hangs indefinitely.

### Expected Result

The Task is created in Jira or at least Sentry should highlight the required field when creating a task from a Sentry issue.

### Actual Result

> Error Communicating with Jira (HTTP 400): The Tempo Account field must be selected

### Product Area

Issues

### Link

https://vmedia-inc.sentry.io/issues/4556433773/?project=270641

**Comment by olsh** [comment] 2023-11-13 06:51
Related to https://github.com/getsentry/sentry/issues/46181 and https://github.com/getsentry/sentry/issues/45931

**Comment by scttcper** [comment] 2023-11-13 17:12
closing as duplicate of #46181

**Closed by scttcper** 2023-11-13 17:12 UTC
Labels: Product Area: Settings - Integrations, Waiting for: Product Owner

**Comment by olsh** [comment] 2023-11-13 17:18
@scttcper but nobody cares about the duplicate.
The issue is blocked and even voting is disabled. How do you know if the bug affects many of your clients or not?

**Comment by scttcper** [comment] 2023-11-13 20:53
unlocked that ticket
