### ISSUE TITLE
FieldError: Cannot resolve keyword 'member_set' into field.

### ISSUE THREAD

**Issue by devunt** [getsentry/sentry#1376] opened 2015-01-06 10:40 UTC
Traceback:

[ERROR] Internal Server Error: /manage/users/1/
Traceback (most recent call last):
  File "/home/sentry/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sentry/local/lib/python2.7/site-packages/sentry/web/decorators.py", line 237, in wrapped
    return func(request, *args, **kwargs)
  File "/home/sentry/local/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/sentry/local/lib/python2.7/site-packages/sentry/web/frontend/admin.py", line 194, in edit_user
    team__member_set__user=user,
  File "/home/sentry/local/lib/python2.7/site-packages/django/db/models/manager.py", line 163, in filter
    return self.get_queryset().filter(*args, **kwargs)
  File "/home/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 593, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 611, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/sentry/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1204, in add_q
    clause = self._add_q(where_part, used_aliases)
  File "/home/sentry/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1240, in _add_q
    current_negated=current_negated)
  File "/home/sentry/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1103, in build_filter
    allow_explicit_fk=True)
  File "/home/sentry/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1363, in setup_joins
    names, opts, allow_many, allow_explicit_fk)
  File "/home/sentry/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1283, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'member_set' into field. Choices are: accessgroup, date_added, id, name, organization, organizationmember, owner, pending_member_set, project, slug, status, teammember

**Comment by dcramer** [comment] 2015-01-06 18:51
Closing as duplicate of GH-1375

**Closed by dcramer** 2015-01-06 18:51 UTC
