### ISSUE TITLE
NextJS Profiling Onboarding Wizard

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#62412] opened 2023-12-29 00:10 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. sentry org
2. create a nextjs project
3. new project should be at an empty state for profiling
4. an in product side bar wizard appears which states that profiling is not available for NextJS

### Expected Result

I would expect in Product to be guided to (beta) browser profiling and potentially node profiling for backend NextJS

I am surprised discord is the only thing we have to direct people to. While I get that discord is popular with a lot of tech folks, i don;t think it is default. Is there a generic profiling "coming soon/roadmap" GH Discussion we could link to? GH is more or less a de facto staple of developers

### Actual Result

I cannot consistently reproduce getting the side bar wizard to be triggered actually, here is a screenshot from slack

<img width="912" alt="Screenshot 2023-12-28 at 18 08 15" src="https://github.com/getsentry/sentry/assets/47563310/f9461f43-0314-49e8-93eb-2713a6ae60f8">

### Product Area

Profiling

**Comment by JonasBa** [comment] 2023-12-29 00:39
@anonrig experienced the same thing and iirc it showed up for him later. I'll investigate why it fail

**Comment by anonrig** [comment] 2023-12-29 00:45
There are 2 issues in here I believe.

1. We don't ever cache the static content API requests. IMHO `docs/xxxx` requests should be at least cached on the browser side.
2. When https://us.sentry.io/api/0/projects/ORG/PROJ/docs/node-javascript-nextjs-profiling-onboarding-1-install/ fails, we don't retry.

**Comment by ArthurKnaus** [comment] 2024-12-11 07:59
Closing as I cannot reproduce the problem anymore.
The onboarding content is being rendered and and the docs mechanism was refactored, removing the loading of content via the docs endpoint.

**Closed by ArthurKnaus** 2024-12-11 07:59 UTC
