### ISSUE TITLE
Overlay remains fixed within Replay, covering useful information

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#68247] opened 2024-04-04 08:23 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When you open the replay in question, you can see that the overlay is blocking the view. The bug is not consistent, the menu item that activates the overlay does not always appear.

### Expected Result

The overlay shouldn't be vsisible

### Actual Result

The overlay remains visible throughout the recording

### Product Area

Replays

**Comment by michellewzhang** [comment] 2024-04-04 16:03
hi @dalnoki, can you expand on what you mean by "overlay"? a screenshot would be helpful!

**Comment by bruno-garcia** [comment] 2024-04-09 01:20
> When you open the replay in question

Also it seems we're missing a link to a replay

**Comment by michellewzhang** [comment] 2024-04-09 21:13
looks like this ticket is related and has more info: https://github.com/getsentry/team-replay/issues/412

**Comment by ryan953** [comment] 2024-04-18 16:08
I'm going to close this because it's a dupe of https://github.com/getsentry/team-replay/issues/412

**Closed by ryan953** 2024-04-18 16:08 UTC
Labels: Product Area: Replays
