### ISSUE TITLE
Possible race condition on group creation during large bursts of events within a single group.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#5085] opened 2017-03-16 00:21 UTC
A user on sentry.io received a burst of ~7,500 events over a 15 minute period the other day. Each of these events were fingerprinted with the same fingerprint. Somehow, this resulted in 5 different groups being created at one point. Two of those groups were eventually merged into the other groups, leaving 3 groups that were created during the burst. Only one of them was finally associated with the `GroupHash`, and this group contained the majority of the events.

From what I can tell, several workers must have been attempting to create the group at the same time, and when the [`_ensure_hashes_merged`](https://github.com/getsentry/sentry/blob/70f41bcf910e388ba5963f32d817c1167762b359/src/sentry/event_manager.py#L765-L790) method was called, it triggered merges into groups that themselves may have already been being merged (and subsequently deleted) so some of the merges triggered by the `_ensure_hashes_merged` method didn't complete successfully.

There's not enough logging to put together a comprehensive view of what merges were in flight during the time period and how far along they got, but this is what *seems* to have occurred given the final state of the records.

**Comment by christineyen** [comment] 2017-04-10 18:32
I've seen this too (also on sentry.io, ~31 events over a 2-second period. 2 events about 20 seconds later were correctly grouped combined into one of the existing groups.) The events were all fingerprinted with the same fingerprint but we ended up with about 7 different groups, each with a different "Issue #"

**Comment by BYK** [comment] 2020-10-20 18:46
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by tkaemming** [comment] 2020-10-20 20:31
This is very much still an issue (and an important one at that, IMO.)

**Comment by BYK** [comment] 2020-10-21 09:07
@tkaemming this hasn't been updated in over 3 years so even if it is important, it doesn't seem pressing or being prioritized. I'm reopening but we should surface this for planning if it is important to tackle.

**Comment by laurentgoudet** [comment] 2020-11-16 11:41
I can confirm I'm still seeing that all the time as well, e.g. https://sentry.io/organizations/freelancercom/issues/2021706113 vs. https://sentry.io/organizations/freelancercom/issues/2021706114 from a week ago. Given how important issue grouping is in the overall product experience, I'd really wish the Sentry team would prioritize fixing that.

**Comment by untitaker** [comment] 2021-02-10 18:50
We have recently observed that this particular race continues to happen more and more. We are not sure why but it may just be because Sentry keeps getting bigger, as do its customers. One other theory (by armin) involves contention on next_short_id, which may cause save_event to slow down *hard* for large projects.

There is a PR open at https://github.com/getsentry/sentry/pull/23577 to fix this. It uses [double-checked locking](https://en.wikipedia.org/wiki/Double-checked_locking) to avoid creating a DB transaction every time, but got pushback because our own production systems are too hot on the related tables (grouphash/group) to run database transactions on top. It may be that the workaround for that is to split off those tables into separate databases, which would require us to audit and remove any fast/non-app joins using those tables.

Alternatives discussed were to synchronize group creation using either a redis lock or a kafka consumer where the partition routing key is the event's group hashes. Like in https://github.com/getsentry/sentry/pull/23577 there's the potential for disabling either synchronization if the group has already been observed to exist outside of the transaction/consumer/redis-lock-acquisition

**Comment by untitaker** [comment] 2021-02-10 18:52
Oh, some other things discussed were LOCKED_IN_MIGRATION, which only seems to be executed in save_event to avoid *the group creation race interfering with merge/unmerge*. We think that the filter is not necessary if the race were not there. See also comments on #23577

**Comment by untitaker** [comment] 2021-02-22 17:00
In the context of hierarchical grouping we're running risk of introducing more race conditions. Hierarchical grouping as introduced in #23861 will produce a list of hashes that represent a path down a tree (from tree root to tree leaf), where each hash has strictly higher cardinality than the last.

The current plan for hierarchical grouping is to iterate through that hash list, and either attach the event to the first *singular* hash that is found in the DB and points to an existing group, or to create a group out of the last hash only.

How does one synchronize such a routine? By acquiring some sort of lock on all of those hashes, or by acquiring one lock on the first hash only. If we do this with db transactions we set our database even more on fire.

Best proposal so far is to make a kafka consumer out of save_event, synchronized by `primary_hash/hierarchical_hashes[0]` and to cache db reads using redis/memcached. The only other type of lock that would not introduce additional infrastructure on onpremise is a redis-based lock, and I am not sure if we find a good, performant implementation of that.

**Comment by untitaker** [comment] 2021-03-04 09:57
wups, not just fixed yet. We're trying this stuff out now to assess performance impact.

**Comment by untitaker** [comment] 2021-04-27 17:51
In master (and therefore on SaaS and on release 21.3.1), you should no longer observe the race condition that occurs with higher event volume. The database transaction turns out to be entirely tolerable in terms of performance.

The PR that fixes this is #24293 though the "feature"flag to fix this bug has been available for longer.

**Closed by untitaker** 2021-04-27 17:51 UTC
Labels: Component: Event Pipeline, Status: Backlog, Type: Bug
