### ISSUE TITLE
Spend allocation for the next billing period

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#69283] opened 2024-04-19 06:46 UTC
### Problem Statement

Users should be able to schedule a spend allocation setup that only gets activated when the new billing cycle starts

### Product Area

Settings - Spend Allocation

**Comment by brianthi** [comment] 2024-04-19 16:03
Thanks for suggesting the feature improvement. We'll backlog this for now and consider it if we were to invest in changes to the Spend Allocation feature.

**Comment by Angelodaniel** [comment] 2024-09-09 13:00
I second this! During contract signing we always confirm on round numbers (as much as possible) 
But the problem is that once the cycle starts these "round numbers" are not so round anymore or people need to wakeup at weird times to setup the allocation as quickly as possible so no data gets "lost"

Another example is that in some cases expansion of the quota, they want to pro-actively setup the allocation + growth for the next cycle.

**Comment by brianthi** [comment] 2024-12-05 00:39
Closing as this is a duplicate of https://github.com/getsentry/sentry/issues/51721

**Closed by brianthi** 2024-12-05 00:39 UTC
Labels: Product Area: Settings - Spend Allocation
