### ISSUE TITLE
Merged Events do not show up in the statistics bar graph on the issue

### ISSUE THREAD

**Issue by kcharwood** [getsentry/sentry#5107] opened 2017-03-20 15:11 UTC
We've noticed that we merge events in the user interface, the event counts do not properly roll up in the statistics view on the right hand side when viewing the complete merged event.

The bar graph does account for any of the merged events, and only for the original master event.

**Comment by mattrobenolt** [comment] 2017-03-20 15:47
Yeah, this is for sure a known issue, and I'm not sure if we're reasonably going to address it. The problem fundamentally is that the data we store for the time series data is much trickier to merge since it's all coming from redis.

**Comment by tkaemming** [comment] 2017-03-20 17:46
Closing as a duplicate of GH-3136.

I think we'll likely be tackling this relatively soon.

**Closed by tkaemming** 2017-03-20 17:46 UTC
