### ISSUE TITLE
Deeply nested interface data objects rendered incorrectly in UI

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3145] opened 2016-04-29 18:09 UTC
First reported here: https://twitter.com/obmarg/status/726060423435407360

![image](https://cloud.githubusercontent.com/assets/2153/14925159/d950680a-0dfa-11e6-806d-ae34dc899669.png)

**Comment by mitsuhiko** [comment] 2016-04-29 21:48
It basically happens because of lots of repr() because of stripping when we detect too deep nesting. Not entirely sure what the best way to fix this is.

**Comment by obmarg** [comment] 2016-05-03 14:24
I'm not sure what the definition of too deep nesting is, but the data in that screenshot is only about 4 levels deep

**Comment by dentarg** [comment] 2017-09-28 12:56
Seems like this is the same as https://github.com/getsentry/sentry/issues/5303

Anyway, I ran into this too, took me a while to understand where the problem was. Here's an easy [raven-ruby](https://github.com/getsentry/raven-ruby) repro:

```ruby
data = JSON.parse('{ "foo": [ { "bar": { "baz": "åäö" } } ] }')
Raven.extra_context(data: data)
```

**Comment by EvanPurkhiser** [comment] 2017-10-06 00:41
Duplicate of #5303. Let's track over there.

**Closed by EvanPurkhiser** 2017-10-06 00:41 UTC

**Comment by alex-hofsteede** [comment] 2017-12-13 21:55
This wasn't quite a duplicate of #5303, but related. This particular issue with the escaping was solved in 77655087
