### ISSUE TITLE
sentry-cli releases set-commits --auto not working -> trying to match repo url https to ssh

### ISSUE THREAD

**Issue by fmflame** [getsentry/sentry#11055] opened 2018-12-14 19:49 UTC
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

`not a match: git@gitlab.company.com:org/project_web.git != https://gitlab.company.com/org/project_web`
leading to
`error: Could not determine any commits to be associated automatically.`

## Steps to Reproduce

1. Integrate gitlab repository
2. Create a release
3. Fail to link commits with:
`npm run sentry-cli releases set-commits -- --auto VERSION --log-level=debug`

Good items to include here include:

- Include a stacktrace or other logs when relevant

```
DEBUG   2018-12-14 20:19:12.326369500 +02:00 body: [{"status": "active", "integrationId": "12221", "externalSlug": 583, "name": "Org / Project web", "provider": {"id": "integrations:gitlab", "name": "Gitlab"}, "url": "https://gitlab.company.com/org/project_web", "id": "19770", "dateCreated": "2018-12-14T04:06:46.300Z"}]
  INFO    2018-12-14 20:19:12.328322 +02:00 Resolving HEAD (Org / Project web@HEAD)
  DEBUG   2018-12-14 20:19:12.329297900 +02:00   Got reference URL for repo Org / Project web: https://gitlab.company.com/org/project_web
  DEBUG   2018-12-14 20:19:12.329297900 +02:00   Looking for reference URL https://gitlab.company.com/org/project_web
  DEBUG   2018-12-14 20:19:12.331250400 +02:00   not a match: git@gitlab.company.com:org/project_web.git != https://gitlab.company.com/org/project_web
  INFO    2018-12-14 20:19:12.340035100 +02:00   -> no matching revision found
  DEBUG   2018-12-14 20:19:12.341010600 +02:00 error: running update nagger
error: Could not determine any commits to be associated automatically.
```

- Include a redacted version of your configuration when relevant

### What you expected to happen

Maybe test both https and ssh urls or being able to configure this in Sentry? I am not sure what exactly I should be expecting here apart from not having to debug this and write an issue here.

### Possible Solution

Probably if I switch my repo url from ssh to https it will work.

**Comment by markstory** [comment] 2018-12-21 14:31
I can look into improving this as I think his situation works with githubn hosted repositories.

**Comment by markstory** [comment] 2019-01-03 18:16
Closing as the next release of sentry-cli will solve this problem.

**Comment by kolesoffac** [comment] 2019-03-29 14:56
I have same issue

**Comment by paaland** [comment] 2019-04-26 10:49
This issue is still not fixed. Please add option to relax/skip the check.

**Comment by markstory** [comment] 2019-04-26 13:10
@paaland how could I reproduce the problem you are having?

**Comment by paaland** [comment] 2019-04-26 13:24
I'm using Azure and the Azure pipeline to build and call the sentry-cli via the node package.

The git repo inside the docker vsts agent that builds is https://mydomain.visualstudio.com/project/repo/_git while what it compares with in Sentry seems to be https://project@mydomain.visualstudio.com/project/repo/_git

There is a username appended to the repo URL in Sentry which is not there for origin on the build agent.

**Comment by markstory** [comment] 2019-04-26 13:34
Thanks @Pearland I will see that scenario can be accounted for in how we match repository URLs.

**Comment by petterhoel** [comment] 2019-05-05 15:21
I am having what seems to be the same issue. 
- Installing sentry-cli via curl.
- Repo is on github. 
- Using netlify for builds (Ubuntu 16.04/bash). 
- Works fine locally from my macbook pro (mohave/zsh). 

This is my script: 
https://github.com/petterhoel/team-city-build-screen/blob/master/buildscript/associate-sentry-release-and-commit.sh

Here is a recent log with log level set to `debug`. 
https://app.netlify.com/sites/buildscreen/deploys/5ccef534f5f0a60008c442e0

**Comment by markstory** [comment] 2019-05-06 20:26
@petterhoel What is your repository's `origin` URL set to? sentry-cli is trying to match it against `https://github.com/petterhoel/team-city-build-screen`

**Comment by zlwaterfield** [comment] 2019-05-06 21:17
@markstory I've hit the same issue, here is my release script:
```
#!/bin/bash
VERSION=$(sentry-cli releases propose-version)

# Create a release
sentry-cli releases new -p cappa-staging $VERSION

# Associate commits with the release
sentry-cli releases set-commits --auto $VERSION --log-level=debug
```

Here are my logs: 
https://gist.github.com/zlwaterfield/bed5e49c7e8bde9b6739516aafd71ef2

The release is created but the commit setting failures from `-> no matching revision found`. The repo is set up at https://sentry.io/settings/padpiper/repo/ and this does work locally but not when deploying on Netlify. Anything I might be missing?

**Comment by petterhoel** [comment] 2019-05-07 08:53
@markstory Not sure how Netlify integrates (ssh or https). Tried to do a `git remote -v` in my script, but there was no output from Netlify. 

But this is my settings: 
![image](https://user-images.githubusercontent.com/1263775/57286672-0ca4da80-70b6-11e9-95d5-4af114639d27.png)

Locally I'm on ssh.

**Comment by markstory** [comment] 2019-05-07 14:23
Is it possible that netlify is removing the origin on the git repository after cloning? Based on your output @zlwaterfield the repository doesn't have an origin as you should see the following code path output something https://github.com/getsentry/sentry-cli/blob/d0117f7aed98f8959772ffe3aa8f606f178a9c74/src/utils/vcs.rs#L212-L226

**Comment by petterhoel** [comment] 2019-05-07 16:02
@markstory seems they do indeed rm the repo 😞
added `echo "$(cat .git/config)"` to my build script. This is the relevant output:
```
5:50:12 PM: git config
5:50:12 PM: [core]
5:50:12 PM: 	repositoryformatversion = 0
5:50:16 PM: Starting post processing
5:50:12 PM: 	filemode = true
5:50:16 PM: Post processing done
5:50:12 PM: 	bare = false
5:50:12 PM: 	logallrefupdates = true
5:50:12 PM: git config end
```
Full log [here](https://app.netlify.com/sites/buildscreen/deploys/5cd1a901cab3940009703ed6)

Knowing this, any suggestion as to to how integrate with Sentry? Could we perhaps just provide the url ourselves? Along the lines of what we do with auth tokens and organizations. 
`export SENTRY_GIT_REPO="https://github.com/petterhoel/team-city-build-screen"`

**Comment by markstory** [comment] 2019-05-07 17:30
You won't be able to use the `--auto` mode. Instead you're have to figure out the commit range for the release and pass that in as a parameter to `sentry-cli`.

**Comment by petterhoel** [comment] 2019-05-07 18:09
I see, thanks. Not sure how I can do that build time with netlify, but I'll look into it. 

Does that mean having the sentry cli looking for an environment variable as a last resort is not an option? I have never worked in rust, dont know the language, but i guess calling something like this if all else fails. 
```
fn get_env_repo_url(ini: &Ini) -> String {
    if let Ok(val) = env::var("SENTRY_GIT_REPO_URL") {
        val
    } else {
        String::new()
    }
}
```

**Comment by markstory** [comment] 2019-05-07 18:57
> Does that mean having the sentry cli looking for an environment variable as a last resort is not an option? 

Pulling the repository URL from an environment variable could work for finding the repository name. However, we still won't be able to generate a list of commits without the git history.

**Comment by paaland** [comment] 2019-05-07 19:08
I support the environment variable suggestion. Now the git repo url has to match exactly and that is causing me issues. The build server might use another username, or even ssh vs https when adding the repo to sentry (due to how Azure generates keys and such).

For me it fails since the two does not match. Either support specifying via environment, or if we only have one repo added on the sentry project, just assume it's that one.

**Comment by petterhoel** [comment] 2019-05-08 17:10
> However, we still won't be able to generate a list of commits without the git history.

@markstory I'm not sure what you guys do or need to read the history but, git history seems available😊
```
7:01:30 PM: git log
7:01:30 PM: commit 0490f64a418aec27974a0aaa73f514075d2ff9b1
7:01:30 PM: Author: Petter <1263775+petterhoel@users.noreply.github.com>
7:01:30 PM: Date:   Wed May 8 19:00:32 2019 +0200
7:01:30 PM:     Tries git log
7:01:30 PM: commit badd2123a7e22c770887427283315c3bf8ce4c4d
7:01:30 PM: Author: Petter <1263775+petterhoel@users.noreply.github.com>
7:01:30 PM: Date:   Tue May 7 17:49:20 2019 +0200
7:01:30 PM:     adds debugs some more
```
[Full log](https://app.netlify.com/sites/buildscreen/deploys/5cd30b31dbd198000813dc2e)

**Comment by markstory** [comment] 2019-05-08 17:26
@petterhoel Have you considered re-adding the `origin` remote to the clone that netlify made?

**Comment by petterhoel** [comment] 2019-05-08 18:30
> @petterhoel Have you considered re-adding the `origin` remote to the clone that netlify made?

@markstory  When I'm clearly unable to use my own 🧠, I'm happy to get a nudge from someone who can 😹

`git remote add origin $REPOSITORY_URL`
Simple and gets the job done, thanks! 
```
8:24:14 PM: Created release 3dbf8fd6de52f321593e099ad031c49dc5aea064.
8:24:14 PM: +-----------------------------------+--------------+
8:24:14 PM: | Repository                        | Revision     |
8:24:14 PM: +-----------------------------------+--------------+
8:24:14 PM: | petterhoel/team-city-build-screen | 3dbf8fd6de52 |
8:24:14 PM: +-----------------------------------+--------------+
8:24:15 PM: Finalized release 3dbf8fd6de52f321593e099ad031c49dc5aea064.
8:24:15 PM: Created new deploy unnamed for 'Production'
```

**Comment by zlwaterfield** [comment] 2019-05-13 14:05
Great idea @markstory and thanks for confirming it works @petterhoel!

**Comment by markstory** [comment] 2019-05-13 14:34
Going to close this as the azure issue has been resolved and adding an origin in will cover netlify.

**Closed by markstory** 2019-05-13 14:34 UTC

**Comment by mackelito** [comment] 2019-06-05 10:44
Perhaps not related but I have been wondering about "Created new deploy unnamed for"... unnamed?.. can we name it? :)

**Comment by jonyeezs** [comment] 2020-02-10 00:55
What is "unnamed"? I'm getting that on my deploy cmd as well. It looks worrying

**Comment by mamtach** [comment] 2020-02-11 05:40
@jonyeezs, I just fixed this so we will have to pass optional parameter --name for deploy 

> --name prod-deploy

Reference: https://docs.sentry.io/api/releases/post-release-deploys/

**Comment by jonyeezs** [comment] 2020-02-11 07:34
@mamtach if I don't pass an option does it still say unnamed?

**Comment by mamtach** [comment] 2020-02-13 03:44
@jonyeezs, yes, this will stay unnamed, its optional param and for my case - I give it a name

**Comment by nicholaslee119** [comment] 2020-02-26 03:26
`git remote set-url origin $REPOSITORY_URL`
The above command would be work if you got an error: `fatal: remote origin already exists.`

**Comment by hayderimran7** [comment] 2020-04-28 04:43
if `git` is missing , use `sed` as ` sed -ie "s|url =.*|url = $CI_PROJECT_URL|g" .git/config` .works on gitlab
