### ISSUE TITLE
Ignore Until "This Occurs again after X amount of Time" un-ignored after time period (even if not seen again)

### ISSUE THREAD

**Issue by MeredithAnya** [getsentry/sentry#5978] opened 2017-08-24 21:59 UTC
In the dropdown the option is described as 'ignore until this occurs again after x amount of time'

<img width="351" alt="screen shot 2017-08-24 at 2 51 44 pm" src="https://user-images.githubusercontent.com/15368179/29690426-c938240a-88db-11e7-8892-3927ac4c4c2d.png">

However, the activity message seems to suggest that the issues is only ignored for a specific amount of time - rather than being marked as ignored permanently unless it occurs again.

<img width="848" alt="screen shot 2017-08-24 at 2 52 35 pm" src="https://user-images.githubusercontent.com/15368179/29690573-65c74896-88dc-11e7-8cc7-9b0d4db08e58.png">

Someone writing into support experienced an issue being marked as not ignored after using this option and had not seen any other events in the issue come through.

If this _is_ the expected behavior perhaps the language should change?

cc @tkaemming

**Comment by ryno1234** [comment] 2017-08-25 01:26
Thanks @MeredithAnya, looking forward to understanding this feature better.

**Comment by dcramer** [comment] 2017-08-25 18:57
This might just be a UX quirk we need to sort out.

Here's the expectation:

1. I click "Ignore until this occurs again after 30 minutes"
2. It shows "ignored until [absolute datetime]"
3. On [absolute datetime] the issue is still ignored *unless* it happens again. This is important, because the goal of ignore is 'hide this unless its ongoing after [condition]'

I can understand why it'd be confusing to not just un-ignore it at the given timestamp, but maybe its as simple as changing some of the language to reflect the behavior above. I dont have a real quick suggestion on better language, but hopefully this helps with clarity.

**Comment by ryno1234** [comment] 2017-08-25 19:52
Hi @dcramer, I think there may be a misunderstanding (I was the one who reported the issue originally).

The problem I'm having is that the issue is un-ignored at [absolute datetime] regardless of whether or not the issue has occured since originally ignoring it.

**Comment by dcramer** [comment] 2017-08-25 20:16
@ryno1234 AH so then it would be a bug. I wouldn't expect it to be unignored *unless* it happened again. We'll look into that.

**Comment by dcramer** [comment] 2017-08-30 23:48
@macqueen so I think what needs to change, is we would simply check the 'ignored' state in event_manager (same way we do with auto resolve), and we'd remove the thing that clears the ignore status.

I think in the UI, we'd say "ignored until X", but once X is reached, say "this was ignored, and will automatically notify you if it happens again".

It's possible we need to rethink how we message ignore everywhere.

**Comment by mdomenjoud** [comment] 2017-10-30 10:02
Hi @macqueen, any news concerning this issue ?
We often had the problem several times these last weeks: we ignored an issue, using "ignore until this issue occurs again after 30 minutes", and the issue was shown again in searches with "is:unresolved" filter, but the no new occurrences of the issue were caught.

**Comment by raymondjplante** [comment] 2018-03-03 11:39
Seeing the same issue as @mdomenjoud 

- We ignore an issue until x times a day/hour etc... 
- In the comments for the issue, it shows that the issue was ignore with the whatever rate/time condition chosen
- After some period of time, it just reappears as unresolved with ignore unchecked. 
- Unlike when I manually remove an Ignore state, there is not entry in the comment section indicating someone unresolved or otherwise changed the ignore state.

**Comment by BYK** [comment] 2020-10-21 18:46
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

That said I think [metric alerts](https://docs.sentry.io/product/sentry-basics/guides/alert-notifications/metric-alerts/) are quite close to what is requested here and we are working on more features and improvements.

**Closed by BYK** 2020-10-21 18:46 UTC
Labels: Component: Workflow, Team: Workflow
