### ISSUE TITLE
SQL query failed  when running sentry upgrade with 9.1.1

### ISSUE THREAD

**Issue by liyangwei** [getsentry/sentry#13262] opened 2019-05-17 03:26 UTC
After upgrading from 9.0.0 to 9.1.1 using pip install -U sentry I ran sentry upgrade and An error was reported with the following prompt.

```
FATAL ERROR - The following SQL query failed: ALTER TABLE `sentry_sentryappinstallation` ADD CONSTRAINT `authorization_id_refs_id_549dc4aa` FOREIGN KEY (`authorization_id`) REFERENCES `sentry_apiauthorization` (`id`);
The error was: (1822, u"Failed to add the foreign key constaint. Missing index for constraint 'authorization_id_refs_id_549dc4aa' in the referenced table 'sentry_apiauthorization'")
 ! Error found during real run of migration! Aborting.

 ! Since you have a database that does not support running
 ! schema-altering statements in transactions, we have had 
 ! to leave it in an interim state between migrations.

! You *might* be able to recover with:   = DROP TABLE `sentry_sentryappinstallation` CASCADE; []
   = DROP TABLE `sentry_sentryapp` CASCADE; []
   - no dry run output for delete_foreign_key() due to dynamic DDL, sorry
   = ALTER TABLE `auth_user` DROP COLUMN `is_sentry_app` CASCADE; []

 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: sentry:0426_auto__add_sentryappinstallation__add_sentryapp__add_field_user_is_sent
Traceback (most recent call last):
  File "/www/sentry/bin/sentry", line 10, in <module>
    sys.exit(main())
  File "/www/sentry/lib/python2.7/site-packages/sentry/runner/__init__.py", line 162, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 75, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair)
  File "/www/sentry/lib/python2.7/site-packages/sentry/runner/commands/upgrade.py", line 30, in _upgrade
    ignore_ghost_migrations=True,
  File "/www/sentry/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/www/sentry/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/www/sentry/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/www/sentry/lib/python2.7/site-packages/south/management/commands/syncdb.py", line 125, in handle_noargs
    management.call_command('south_migrate', **options)
  File "/www/sentry/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/www/sentry/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/www/sentry/lib/python2.7/site-packages/south/management/commands/south_migrate.py", line 105, in handle
    ignore_ghosts=ignore_ghosts,
  File "/www/sentry/lib/python2.7/site-packages/south/migration/__init__.py", line 231, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/www/sentry/lib/python2.7/site-packages/south/migration/migrators.py", line 297, in migrate_many
    interactive=self.interactive)
  File "/www/sentry/lib/python2.7/site-packages/south/db/generic.py", line 1076, in send_pending_create_signals
    interactive=interactive)
  File "/www/sentry/lib/python2.7/site-packages/south/db/generic.py", line 1118, in really_send_create_signal
    db=self.db_alias,
  File "/www/sentry/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/www/sentry/lib/python2.7/site-packages/sentry/receivers/core.py", line 31, in wrapped
    return func(*args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/sentry/receivers/core.py", line 50, in create_default_projects
    verbosity=verbosity,
  File "/www/sentry/lib/python2.7/site-packages/sentry/receivers/core.py", line 96, in create_default_project
    **kwargs
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/manager.py", line 157, in create
    return self.get_queryset().create(**kwargs)
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 322, in create
    obj.save(force_insert=True, using=self.db)
  File "/www/sentry/lib/python2.7/site-packages/sentry/models/project.py", line 151, in save
    super(Project, self).save(*args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/base.py", line 582, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/www/sentry/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/www/sentry/lib/python2.7/site-packages/sentry/receivers/savedsearch.py", line 14, in create_default_saved_searches
    SavedSearch.objects.create(project=instance, **search_kwargs)
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/manager.py", line 157, in create
    return self.get_queryset().create(**kwargs)
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 322, in create
    obj.save(force_insert=True, using=self.db)
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/www/sentry/lib/python2.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 380, in execute
    return real_execute(self, sql, params)
  File "/www/sentry/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/www/sentry/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/www/sentry/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/www/sentry/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/www/sentry/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/www/sentry/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/www/sentry/lib/python2.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/www/sentry/lib/python2.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/www/sentry/lib/python2.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/www/sentry/lib/python2.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/www/sentry/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/www/sentry/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1054, u"Unknown column 'organization_id' in 'field list'")
```

Then I looked it up on the Internet and found that the two field types of database foreign keys must be the same, but I found that they are not the same in sentry. How to deal with this problem?

**Comment by mattrobenolt** [comment] 2019-05-17 03:41
So I notice that you're running MySQL, which we haven't really supported in a long time. So unfortunately, I'm not really sure what the issue is. But I assume you'll have to do some munging around with an ALTER statement to get things into a correct working state.

It's also worth repeating, that we've been recommending to switch to Postgres for a long time now since we don't have the capacity to support all of these backends properly.

**Comment by mattrobenolt** [comment] 2019-05-17 20:09
Just going to close this because I don't anticipate anything we'll do to fix this, and we likely won't have a fix for another release that even has MySQL capable code in it, unfortunately.

**Closed by mattrobenolt** 2019-05-17 20:09 UTC

**Comment by artemus717** [comment] 2019-05-21 08:10
Is there any method to migrate mysql to postgres ?

**Comment by harshul4274** [comment] 2020-05-04 11:11
Hello @mattrobenolt, I am using postgress db but this error come in sentry pod.
