### ISSUE TITLE
"Preview" in Issue Alerts does not filter correctly based on the environment defined in the Alert conditions

### ISSUE THREAD

**Issue by serglom21** [getsentry/sentry#60271] opened 2023-11-20 17:02 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create an alert
2. Filter Alert on environment from dropdown

### Expected Result

Issue examples in the "Preview" table should be filtered based on the environment specified.

### Actual Result

Issue examples in the "Preview" table display issues coming from different environments than the one specified.

### Product Area

Alerts

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2004) by [Unito](https://www.unito.io)

**Comment by ceorourke** [comment] 2024-12-10 00:39
This is a duplicate of https://github.com/getsentry/sentry/issues/45857

**Closed by ceorourke** 2024-12-10 00:39 UTC
Labels: Sync: Jira, Product Area: Alerts
