### ISSUE TITLE
Phone verification issue

### ISSUE THREAD

**Issue by jayjpatel9717** [getsentry/sentry#3814] opened 2016-07-27 03:24 UTC
Description :
i already verified my phone number,but when i make that request again,i can still getting messages.

Step to reproduce :
1.First verified your phone number
2.then make verification request again
3.you can see,you still getting messages about verification code

That Request :

POST /account/settings/2fa/sms/ HTTP/1.1
Host: app.getsentry.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://app.getsentry.com/account/settings/2fa/sms/
Cookie: [snip]
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded
Content-Length: 150

stage=pick_number&phone_number=<Already verified number>&csrfmiddlewaretoken=JFSwpiFZR9pcfbL8MCfnqsVCnrN5gmxJ&enroll=&totp_secret=[snip]

For Fix :
when user request for verification again it's give error like :

"This phone number is already  verified"

**Comment by mitsuhiko** [comment] 2016-07-27 10:24
Why are you making the verification request a second time. Did the flow not advance? I'm not entirely sure what the issue is here right now.

**Comment by benvinegar** [comment] 2016-08-09 17:53
I think he's manually triggering the verification endpoint, hence the POST request. This is probably not possible via the UI unless you had two windows open.

Should we bother patching this? Or just close as "works as expected"?

**Comment by BYK** [comment] 2020-09-30 13:01
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Closed by BYK** 2020-09-30 13:01 UTC
