### ISSUE TITLE
[Auth0] Username parsing is incorrect

### ISSUE THREAD

**Issue by yurymkomarov** [getsentry/sentry#28655] opened 2021-09-17 15:41 UTC
### Environment

self-hosted (`onpremise` deployment)

### Version

21.8.0

### Steps to Reproduce

1. Create multiorganisation deployment
2. Create few organisation
3. Configure Auth0 for few organisations
4. Login with the same account to few organisation

### Expected Result

Users with the same email should have one account in different organisations to prevent problems with quick switching between organisations.

### Actual Result

![image](https://user-images.githubusercontent.com/33968020/133815843-6b556f8d-7dc6-490d-951b-7e818212507a.png)

**Comment by yurymkomarov** [comment] 2021-09-17 15:50
@leedongwei hi!

am I right that my issue is connected with https://github.com/getsentry/sentry/issues/25345?

**Comment by JoshFerge** [comment] 2021-09-17 16:50
Hi @yurymkomarov, it is indeed related to that issue. We have started work on a fix and will let you know when it is available. Thanks.

**Comment by yurymkomarov** [comment] 2021-09-17 16:54
Hello @JoshFerge 
Thank you for quick response
Do you have estimation? Week? Month?
This issue is critical for me now...

**Comment by JoshFerge** [comment] 2021-09-17 18:18
@yurymkomarov the current ETA is a couple of months. There are security implications that we need to handle carefully and due to that complexity, this is not a quick easy change to make. For most sentry organizations, the separations of teams and projects (with open membership turned off), within a single organization is enough data / permissions separation.

Users may currently get around this duplicate issue by ensuring they're already logged in before joining a new organization, or by having a password set on their account.

You could also work around this by enabling the `"organizations:sso-migration` feature flag and manually creating OrganizationMember rows with the correct user_ids filled in the row, although this is more complicated and requires the users to already exist on your tenant.

**Comment by yurymkomarov** [comment] 2021-09-17 18:31
Hello @JoshFerge 

Thanks for your reply
Unfortunately I didn't find any info about "organizations:sso-migration". Can u share a link, please?

**Comment by JoshFerge** [comment] 2021-09-17 20:20
@yurymkomarov there is no documentation for this unfortunately, but you can find links on feature flags here: https://develop.sentry.dev/feature-flags/

**Comment by yurymkomarov** [comment] 2021-09-18 12:51
@JoshFerge got it, thank you :)

**Comment by chadwhitacre** [comment] 2021-12-06 16:29
I think I'm going to close this as a duplicate of #25345 ... 👀

**Comment by JoshFerge** [comment] 2021-12-06 17:56
@chadwhitacre makes sense. I'll provide an update on the other issue.

**Closed by JoshFerge** 2021-12-06 17:56 UTC
Labels: Status: In Progress, Team: Enterprise
