### ISSUE TITLE
Real time events not seen in sentry Dashboard

### ISSUE THREAD

**Issue by ajith-nataraj** [getsentry/sentry#50470] opened 2023-06-07 08:23 UTC
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Real time events not seen in sentry Dashboard, data gets pushed to sentry dashboard after every hour.

we are seeing delay in seeing events in our sentry dashboard

<img width="1294" alt="Screenshot 2023-06-07 at 13 47 25" src="https://github.com/getsentry/sentry/assets/107095805/b035e974-016a-4bd3-aab6-4b0fe21c5a53">

### Expected Result

want to see real time events in sentry dashboard. which helps us to resolve issue proactively 

### Actual Result

Should see real time events in dashboard

### Product Area

Dashboards

### Version

Sentry 9.0.0

**Comment by hubertdeng123** [comment] 2023-06-08 18:43
this is a duplicate of https://github.com/getsentry/self-hosted/issues/2191, so moving conversation there

**Closed by hubertdeng123** 2023-06-08 18:43 UTC
Labels: Status: Untriaged, Product Area: Dashboards, Waiting for: Product Owner
