### ISSUE TITLE
Add setting to enforce 2 factor authentication

### ISSUE THREAD

**Issue by danielkoster** [getsentry/sentry#6286] opened 2017-10-09 12:37 UTC
This is a feature request. We are using Sentry (8.20.0) within our organisation, most of our employees have access to Sentry. The addition of 2FA within Sentry is great! However, I would like to have a setting to enforce the use of 2FA for everyone within my organisation. This meaning that everyone who doesn't have 2FA setup, would be force to do so after logging in, before they can actually use Sentry. I believe this would greatly help secure the login and 2FA process.

**Comment by 2easy** [comment] 2018-01-23 10:40
Hi, we are using newest Sentry within our organization. It would be great to enforce 2 FA within organization, because people just won't do it if only asked. It would greatly improve our security, is there possibility it would be added in the next release?

**Comment by benvinegar** [comment] 2018-08-29 23:29
Duplicate of #6286, closing

**Closed by benvinegar** 2018-08-29 23:29 UTC

**Comment by ChristophWurst** [comment] 2018-09-03 06:47
> Duplicate of #6286, closing

You referenced the exact same ticket :wink:

**Comment by iSWORD** [comment] 2019-01-31 11:45
I can find the option when I search in the settings but when I click on it nothing happens.

**Comment by egorvinogradov** [comment] 2019-03-13 13:00
@benvinegar So what's the status on this? Can you either re-open the issue or reference the correct one so that's it's possible to see the status? Thanks

**Comment by krysopath** [comment] 2019-04-25 13:19
I would greatly appreciate an enforceable policy for 2FA.

**Comment by m-minning** [comment] 2019-06-12 08:25
You need to enable `Early Adopter` in the settings and refresh it to see the 2FA settings.

**Comment by chadwhitacre** [comment] 2022-03-08 21:41
> or reference the correct one

Pretty sure it's https://github.com/getsentry/sentry/issues/4603.
