### ISSUE TITLE
discord integration question

### ISSUE THREAD

**Issue by ovived** [getsentry/sentry#18547] opened 2020-04-30 17:26 UTC
## Summary

Integrate to Discord Webhooks so we can see updates

## Motivation

It used to work with the Slack (Legacy) integration but that is no longer an option when I search on sentry.

**Comment by jacc** [comment] 2020-05-01 14:12
+1, not really interested in setting up a Slack instance to get notifications. there is a Webhooks integration, can that be modified in the mean time to use it?

**Comment by ovived** [comment] 2020-05-01 14:20
I see theres a WebHooks integration but not sure if it's as easy to implement as the old Slack (legacy) integration that was on there

**Comment by jacc** [comment] 2020-05-01 14:21
just did a bit of testing with it, it seems like it doesn't support Discord webhooks (tried adding /slack at the end of it etc, no dice)

**Comment by StoneSet** [comment] 2020-05-18 20:19
Duplicate of #10925

**Comment by BYK** [comment] 2020-10-26 10:06
Closing as duplicate of ##10925.

**Closed by BYK** 2020-10-26 10:06 UTC
Labels: Component: Integrations
