### ISSUE TITLE
Integration interupted with Vercel and error on integration configuration page

### ISSUE THREAD

**Issue by dev-m-work** [getsentry/sentry#32905] opened 2022-03-24 13:24 UTC
### Environment

SaaS (https://sentry.io/)

### Version

"@sentry/nextjs": "^6.19.1"

### Steps to Reproduce

Go to https://sentry.io/settings/m-work/integrations/vercel/126395/

### Expected Result

See the configuration panel of the integration

### Actual Result

Error page...
And the integration with Vercel is broken, it crashed the build on Vercel stating that: 

error: API request failed
--
14:14:53.558 | caused by: sentry reported an error: Authentication credentials were not provided. (http status: 401)

When I go have a look the env vars, the api has been removed...

**Comment by ValentinH** [comment] 2022-03-24 13:51
Same problem here. Also experiencing #32902

**Comment by kevva** [comment] 2022-03-24 20:01
Also got a similar problem. I suddenly started to get the following error while deploying which breaks my builds:

> error: An organization slug is required (provide with --org)

**Comment by pablopunk** [comment] 2022-04-21 11:58
I started to have this today on Vercel. I can't reproduce it locally.

If I redeploy a vercel deployment that previously worked, it does still work. A new one always fails.

I added manually all my env vars to Vercel just in case but no luck

**Comment by pablopunk** [comment] 2022-04-23 09:06
Update. This seems to be failing only on side branches. I just tried pushing into `main` and it does work

**Comment by pablopunk** [comment] 2022-05-31 11:16
Update x2 ✅ Solved for me:

The Sentry integration on Vercel writes env variables only to production branches, so I went to edit manually ALL SENTRY ENV VARS on my vercel project settings and toggle ON the "preview" and "development" environment on each one:

![Captura de Pantalla 2022-05-31 a las 13 13 42](https://user-images.githubusercontent.com/4324982/171161191-ff29750f-2717-4197-a81a-b9476b53b26c.png)

**Comment by saifalfalah** [comment] 2022-07-20 20:49
@pablopunk this worked for me. Thanks!

**Comment by sentaur-athena** [comment] 2024-12-11 23:39
I'm going to close the issue since it's old and  seems resolved.

**Closed by sentaur-athena** 2024-12-11 23:39 UTC
Labels: Component: Integrations
