### ISSUE TITLE
AWS Lambda Problem

### ISSUE THREAD

**Issue by droegier** [getsentry/sentry#71556] opened 2024-05-28 13:06 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

- I follow all instructions precisely.
- The CloudFormation is mounted succesfully.
- I add account number and region and then get forwarded to this:
https://jurata-ag.sentry.io/extensions/aws_lambda/setup/?accountNumber=413271537631&awsExternalId=46bfd305-26de-602f-3ec3-2db40f1e380f&region=eu-central-1

### Expected Result

The integration installs correctly.

### Actual Result

The screen stays green, Sentry stalls, I get the following HTTP response
```
Awaiting solution to the halting problem.

You may need to disable adblocking extensions to load Sentry.
```

### Product Area

Settings - Integrations

### Link

https://jurata-ag.sentry.io/extensions/aws_lambda/setup/?accountNumber=413271537631&awsExternalId=46bfd305-26de-602f-3ec3-2db40f1e380f&region=eu-central-1

**Comment by droegier** [comment] 2024-06-03 07:20
@leedongwei Any news?

**Comment by sentaur-athena** [comment] 2024-12-11 23:20
Seem like a duplicate of https://github.com/getsentry/sentry/issues/71556. Will track there.

**Closed by sentaur-athena** 2024-12-11 23:20 UTC
Labels: Product Area: Settings - Integrations
