### ISSUE TITLE
Cursor at incorrect position in alert rule filters

### ISSUE THREAD

**Issue by taobojlen** [getsentry/sentry#66856] opened 2024-03-13 09:08 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create an alert rule, or go to edit an existing one.
2. Enter a lot of filters, such that you have more than 2 rows.
3. Try to click somewhere on the third row: it _looks_ like the cursor gets placed on the second row, but when you enter new text, it is written to the third row.

### Expected Result

The cursor is at the correct position.

### Actual Result

https://github.com/getsentry/sentry/assets/66130243/40f83149-297c-4b73-8abe-83c1fda964ec

### Product Area

Alerts

**Comment by evanpurkhiser** [comment] 2024-03-18 19:57
Hey @taobojlen 

Could you actually record a video starting from an empty textarea?

What would be **even more helpful** is if you could also turn the text color on for the texta area in the developer tools like this, so we can see why the text is becoming misaligned with the overlaying DOM elements:

<img width="1163" alt="image" src="https://github.com/getsentry/sentry/assets/1421724/8b5ac55d-bdcd-40e0-8056-b02ebe5f6b6d">

**Comment by taobojlen** [comment] 2024-03-27 13:20
hi @evanpurkhiser, i just opened the same alert to record this for you, but i can't actually reproduce the issue now! it works as expected now so i'll close this ticket.

**Comment by nhsiehgit** [comment] 2024-05-06 17:12
we've gotten another report of this

opening this ticket back up

**Comment by ceorourke** [comment] 2024-12-12 20:29
Closing as I can't reproduce.

**Closed by ceorourke** 2024-12-12 20:29 UTC
Labels: Component: Core Frontend (React), Product Area: Alerts
