### ISSUE TITLE
Email verification does not work for custom domain mails

### ISSUE THREAD

**Issue by ddeath** [getsentry/sentry#5903] opened 2017-08-17 04:16 UTC
I am using cloud version Sentry 8.20.0.dev0

It looks like the email notifications stopped because i have unverified account. (before it worked even without verified account) So I wanted to verify my email address. I click resend activation email but no luck. Interface printed successful message - I clicked on that button at least 10 times and after more than 24 hours there is no verification email.

It looks like when I add new gmail email it works. But when I try to verify xxx@nexteria.sk then it does not work.

**Comment by phenomax** [comment] 2017-08-18 13:07
I'm encountering a similar issue: My sentry instance is also using a custom e-mail adress. connected with mailgun.com for mail sending.
When hitting the 'Send a test email' in Admin->Mail everything works fine

Log output of successful send

`x.x.x.x - - [18/Aug/2017:13:02:32 +0000] "POST /manage/status/mail/ HTTP/1.0" 200 11420 "https://SENTRY_ADRESS/manage/status/mail/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
x.x.x.x - - [18/Aug/2017:13:02:36 +0000] "GET /api/0/organizations/?member=1 HTTP/1.0" 200 1125 "https://SENTRY_ADRESS/manage/status/mail/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"`

But when I then try to send the confirmation e-mail out of my profile (using the same target adress!), it doesn't work

Log output of failed send

`13:03:19 [INFO] sentry.mail: mail.queued (message_to=(u'phenomax@xxx.net',) user_id=1 message_id='<20170818130319.22.79761@mg.xxx.net>' message_type='user.confirm_email')
x.x.x.x - - [18/Aug/2017:13:03:19 +0000] "POST /account/confirm-email/ HTTP/1.0" 302 841 "https://SENTRY_ADRESS/account/settings/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
x.x.x.x - - [18/Aug/2017:13:03:19 +0000] "GET /account/settings/ HTTP/1.0" 200 14031 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
`
Beside of that no error can be found.

**Comment by mattrobenolt** [comment] 2017-08-18 14:20
@ddeath do you mind contacting support so we can look into it? We just hand off to SendGrid here for actual delivery, but we should be able to get insight into why it didn’t work. 

@phenomax you have a different issue. My guess is you’re not running workers. Or if there’s an error, the error would be coming from the logs over there. The web request is only queuing up the task as you can see in the log message.

**Comment by phenomax** [comment] 2017-08-18 14:55
@mattrobenolt Thanks for taking time!
My runner is up and running. When hitting the confirmation button 
`14:52:44 [INFO] sentry.mail: mail.sent (size=4641 message_id='<20170818145244.21.90107@mg.xxx.net>')`
is being printed in the worker's log.

**Comment by mattrobenolt** [comment] 2017-08-18 22:45
@phenomax So my guess is the problem is on Mailgun's side.

**Comment by phenomax** [comment] 2017-08-18 23:33
But the normal test mail was delivered as expected. The mailgun log also shows no error/notice about a Mail being sent.

**Comment by mattrobenolt** [comment] 2017-08-18 23:34
If Sentry is logging that it was delivered, then the error is beyond that. Maybe your workers are misconfigured and don't have the same mail credentials as the web processes?

**Comment by dcramer** [comment] 2017-08-28 16:27
I'm going to close this as it's noisy.

1. If you're a sentry.io customer, please ping support@ with details on email issues.
2. If you're an on-premise user, please use the appropriate support options available to you (probably the forum): https://forum.sentry.io

**Closed by dcramer** 2017-08-28 16:27 UTC

**Comment by ddeath** [comment] 2017-08-28 16:29
Thanks, I wrote to the support and we got it solved.
