### ISSUE TITLE
AD Group Members Not Syncing Correctly After SSO Identity Link and Team Slug Change in Sentry

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#76503] opened 2024-08-23 12:59 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

We created 2 AD groups under the Enterprise Application and added some AD users to those groups. 
The initial sync went fine. 
These AD groups where automatically mapped to a Team within Sentry (as expected). 
However, soon after some users logged in and linked their SSO account to already existing accounts ([sso-identity.link](http://sso-identity.link/) event), we noticed that members were taken out of the team, and never correctly synced again. 

One of the changes that we made was changing the slug of the team. We changed back the slug to the original name as coming from the AD group, where newly singed in users were mapped accordingly again, but some existing users remain without a team even after multiple syncs. 

We are kind of clueless why or how this is happening.

### Expected Result

For the members to be re-assigned

### Actual Result

Some existing users remain without a team even after multiple syncs. 

### Product Area

Settings - Auth

### Link

Org Link in Jira

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2263) by [Unito](https://www.unito.io)

**Comment by leedongwei** [comment] 2024-08-27 19:41
Closing because this is a support case that's specific to a customer and not a reproducible codebase bug.

**Closed by leedongwei** 2024-08-27 19:41 UTC
Labels: Sync: Jira, Product Area: Settings - Auth, Waiting for: Product Owner
