### ISSUE TITLE
Discarded invalid type for extra:<type ‘list'>

### ISSUE THREAD

**Issue by godfery** [getsentry/sentry#1306] opened 2014-11-04 12:44 UTC
just run ./raven test http://1a01ef8d996e4bb99fadcd3930b0300e:3a72c3c4674e49a18260f9142c519091@192.168.10.77:9000/3

console show "Discarded invalid type for extra:<type ‘list'>"

**Comment by redmine24** [comment] 2015-07-02 08:25
got same problem

**Comment by ram-nadella** [comment] 2015-07-08 23:24
Same issue. PHP 5.5.17 and latest raven-php cloned today from Github.

**Comment by dcramer** [comment] 2015-07-09 15:10
@ram-nadella Are you explicitly sending extra data?

**Comment by yangshiqi** [comment] 2015-07-10 10:50
got the same problem.


$client = new Raven_Client('http://4aca50bcdae04072a931d0daa15a1d38:9b7c757ff6b14d44a678cd5cf6c01e4b@10.3.12.4:9000/2');

// Capture a message
$event_id = $client->getIdent($client->captureMessage('my log message'));


Discarded invalid type for extra: <type 'list'>

**Comment by ram-nadella** [comment] 2015-07-10 13:16
@dcramer no, I am not sending any extra data, but when I do pass in key value pairs to `extra_context(["a" => "b"])` then I don't see the error. My guess is, the client must be sending a `[]` instead of `{}` for extra. (I haven't confirmed this, but will try to find out today).

**Comment by dcramer** [comment] 2015-07-10 17:26
That seems to be the case. I'll dig into this and try to come up with a test case to reproduce. I cant see how it'd be converting it to a JSON array with string keys, but I'm sure I'm missing something.

**Comment by dcramer** [comment] 2015-07-13 22:06
I tried reproducing this in a test case but couldn't come up with anything. I'm going to close this unless we can come up with a test to mimic the behavior, as that's the only reasonable way we'd be able to address it.

**Closed by dcramer** 2015-07-13 22:06 UTC

**Comment by ram-nadella** [comment] 2015-07-13 22:45
@dcramer you see the error only when extra is empty. Try not calling `extra_context` on the client and you'll see the log line on the server.

The issue comes from PHP using the same array type for both lists and dictionaries and when it's empty, it's going to be the empty array and `json_encode` will convert that into a `[]` rather than a `{}`

One way to fix this is to convert extra to an object when empty or remove the check on the server and expect extra to be an empty list.

**Comment by dcramer** [comment] 2015-07-13 22:46
Ah! That makes more sense. I was trying to reproduce it with data.
