### ISSUE TITLE
Monitor API Unreliable - Sometimes accepts check-in, sometimes returns 404

### ISSUE THREAD

**Issue by benjaminrussell-americor** [getsentry/sentry#63295] opened 2024-01-16 21:32 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

This curl command sometimes works and sometimes returns a 404.

I have sent it back-to-back within a few seconds and at first it worked and the next it didn't.

Is this related to load balancing/multiple servers?

More than half of our jobs are showing as missed because of this issue.
```
curl \
    -X POST \
    -H "Authorization: Bearer $SENTRY_AUTH_TOKEN" \
    -H "Content-Type: application/json" \
    -d '{"status": "in_progress"}' \
    --fail \
    --silent \
    --show-error \
    "https://sentry.io/api/0/organizations/americor/monitors/$monitor_id/checkins/"
```
Org is americor.

### Expected Result

API should consistently return good response in accordance with docs.

### Actual Result

```
curl: (22) The requested URL returned error: 404
```

### Product Area

Crons

**Comment by bensebborn** [comment] 2024-01-16 21:33
Same issue here. Seeing lots of these, at random times throughout the day.

Code on our end isn't changing but we're randomly seeing 404 from the checkin api

**Comment by bensebborn** [comment] 2024-01-16 21:37
Here's what Sentry is showing, with lots of timeouts (have verified the API is being hit, but we're getting 404, so sentry is thinking it timed out)

vs our AWS logs showing regular runs each minute

- each of these instances takes less than 2 seconds to return, so well within the 1 minute timeout we have set 

<img width="200" alt="Screenshot 2024-01-16 at 21 35 56" src="https://github.com/getsentry/sentry/assets/160988/4ee33f77-484c-494c-bd66-9cd7536c931e">
<img width="706" alt="Screenshot 2024-01-16 at 21 35 38" src="https://github.com/getsentry/sentry/assets/160988/f95bfdd5-41bb-4f3e-96c0-73ab1e31f149">

**Comment by craig-mcmahon** [comment] 2024-01-17 13:18
We are also experiencing this issue

**Comment by yanchenkoao** [comment] 2024-01-17 13:25
We are also experiencing this issue

**Comment by gaprl** [comment] 2024-01-17 15:16
Hey folks, thank you all for reaching out. 

Our endpoints starting with `https://sentry.io/api/0/organizations/` have been deprecated a while back, and although this issue is unrelated to our deprecation, we will be turning off these endpoints soon.

Please check-out our[ legacy endpoint migration guide](https://docs.sentry.io/product/crons/legacy-endpoint-migration/) for more information.

**Comment by iris-baton** [comment] 2024-01-17 18:01
fwiw, we're seeing this on endpoints without `organizations` in them, the issue seems to be on all endpoints with `api/0/`

**Comment by bensebborn** [comment] 2024-01-17 18:09
The URL we’re hitting is

https://sentry.io/api/0/monitors/xx/checkins/xx/

and we’re having this issue. It’s gotten much worse over the last 24 hours

**Comment by Xemptuous** [comment] 2024-01-17 18:12
The URL @gaprl shared shows any `/api/0` endpoints are deprecated, not just ones containing `organizations`. Have you tried the migration to the relay ingestion URL and see if the issue still persists?

**Comment by bensebborn** [comment] 2024-01-17 18:16
Will try that. Seems strange as we only integrated a few months back and followed the docs so surprised about the deprivation

**Comment by iris-baton** [comment] 2024-01-17 18:20
AFAIK we never received any communication about the deprecation (or the impending GA, which corresponds with when the legacy endpoints got unusably flaky, especially for end checkins...). A coworker is moving our implementation to the new endpoint today, will report back on the results 🤞

**Comment by gaprl** [comment] 2024-01-17 18:30
Hi folks, please let me know if you face any issues when migrating. We sent comms by email on this deprecation during the beta a few times, but I understand it could've been easily missed by some -- luckily the migration for most should be really simple!

I do want to mention we've increased the amount of SDKs with Crons support in the past few months, and this is our recommended way of instrumenting. You can see the available platforms here: https://docs.sentry.io/product/crons/getting-started/

**Comment by Xemptuous** [comment] 2024-01-17 21:20
after switching URLs according to the migration guide, things seem to be working. Will deploy overnight and see how things go on a larger scale.

**Comment by benjaminrussell-americor** [comment] 2024-01-17 22:46
@gaprl In migrating, I don't see a new endpoint for uploading attachments to check-ins. This is necessary for us to upload stdout and stderr of the cron job. Is there an endpoint for that on the ingest subdomain? I can make a new issue if needed

**Comment by Xemptuous** [comment] 2024-01-17 23:39
> @gaprl In migrating, I don't see a new endpoint for uploading attachments to check-ins. This is necessary for us to upload stdout and stderr of the cron job. Is there an endpoint for that on the ingest subdomain? I can make a new issue if needed

I ended up using
```sh
curl -X POST \
    -H "Authorization: Bearer $SENTRY_AUTH_TOKEN \
    -H 'Content-Type: multipart/form-data' \
    -F "file=@$attachment" \
    '/api/0/organizations/${ORG_SLUG}/monitors/${MONITOR_SLUG}/checkins/${CHECK_IN_ID}/attachment/'
``` 
for uploading attachments after generating the uuid for the check_in_id.
I only needed to use the new relay url for setting status' and the check_in_id.

**Comment by craig-mcmahon** [comment] 2024-01-19 09:15
Updating to the new endpoint resolved the checkin issue, but we still had a few issues marking jobs complete if they are very fast. As a work around we are waiting for a second before marking complete which is not ideal.

**Comment by gaprl** [comment] 2024-01-19 20:24
> @gaprl In migrating, I don't see a new endpoint for uploading attachments to check-ins. This is necessary for us to upload stdout and stderr of the cron job. Is there an endpoint for that on the ingest subdomain? I can make a new issue if needed

Hey @benjaminrussell-americor, please follow the instructions provided by @Xemptuous for now -- the attachments endpoint will continue working for the time being. We'll be implementing attachments and/or contextual support in Relay, more info to come soon!

**Comment by gaprl** [comment] 2024-01-19 20:25
> Updating to the new endpoint resolved the checkin issue, but we still had a few issues marking jobs complete if they are very fast. As a work around we are waiting for a second before marking complete which is not ideal.

Hey @craig-mcmahon, are you seeing this behavior with our updated HTTP endpoints? Can you share the monitor URL with us? You can send it to crons-feedback@sentry.io. Thank you.

**Comment by iris-baton** [comment] 2024-01-22 23:25
@gaprl after updating to the new HTTP endpoints, we're also seeing difficulty marking things complete at very short duration, but now our service logs are all happy HTTP codes (unlike the 404 issues from last week)

**Comment by kerenkhatiwada** [comment] 2024-01-23 17:27
Hey @gaprl, to confirm, do users who are using the API to mute and unmute (https://docs.sentry.io/api/crons/update-a-monitor/) monitors. Do these endpoints need to be updated as well?

**Comment by gaprl** [comment] 2024-01-23 22:40
> @gaprl after updating to the new HTTP endpoints, we're also seeing difficulty marking things complete at very short duration, but now our service logs are all happy HTTP codes (unlike the 404 issues from last week)

Hey @iris-baton (and @craig-mcmahon), we're investigating potential causes for issues with fast requests, but in the meantime, can I ask you to pass a pre-defined ID for both requests as described below?

Here's more info: https://docs.sentry.io/product/crons/getting-started/http/#overlapping-jobs-optional

**Comment by gaprl** [comment] 2024-01-23 22:56
> Hey @gaprl, to confirm, do users who are using the API to mute and unmute (https://docs.sentry.io/api/crons/update-a-monitor/) monitors. Do these endpoints need to be updated as well?

No, the "update a monitor" will not be deprecated and does not need to be updated. Thanks for asking.

To clarify: we're only deprecating our [API endpoints that create or update a check-in](https://docs.sentry.io/product/crons/legacy-endpoint-migration/#am-i-using-legacy-endpoints). Instead, these operations should go through our ingestion pipeline (Relay) - it's better suited for handling such requests.

**Comment by iris-baton** [comment] 2024-01-24 00:32
> > @gaprl after updating to the new HTTP endpoints, we're also seeing difficulty marking things complete at very short duration, but now our service logs are all happy HTTP codes (unlike the 404 issues from last week)
> 
> Hey @iris-baton (and @craig-mcmahon), we're investigating potential causes for issues with fast requests, but in the meantime, can I ask you to pass a pre-defined ID for both requests as described below?
> 
> Here's more info: https://docs.sentry.io/product/crons/getting-started/http/#overlapping-jobs-optional
> 
> Please let me know if this helps in any way.

@gaprl We're already doing that. It doesn't help at all

**Comment by gaprl** [comment] 2024-01-25 21:02
> > > @gaprl after updating to the new HTTP endpoints, we're also seeing difficulty marking things complete at very short duration, but now our service logs are all happy HTTP codes (unlike the 404 issues from last week)
> > 
> > 
> > Hey @iris-baton (and @craig-mcmahon), we're investigating potential causes for issues with fast requests, but in the meantime, can I ask you to pass a pre-defined ID for both requests as described below?
> > Here's more info: https://docs.sentry.io/product/crons/getting-started/http/#overlapping-jobs-optional
> > Please let me know if this helps in any way.
> 
> @gaprl We're already doing that. It doesn't help at all

Hey @iris-baton, any chance you could share your monitor URL and a snippets of the code you're using to send us check-ins? It could help us nailed down the cause. You can send it directly to me at crons-feedback@sentry.io. Thank you.

**Comment by gaprl** [comment] 2024-01-26 19:57
Hey folks, we've identified an issue where we can generate incorrect check-ins if they do happen extremely fast. I've created a new issue that you can track here: https://github.com/getsentry/sentry/issues/63969 (cc @iris-baton @craig-mcmahon).

I'll be closing this issue as resolved since our legacy endpoint is back online, however we strongly recommend following our [migration guide](https://docs.sentry.io/product/crons/legacy-endpoint-migration/) given we'll be turning them off in the near future.

**Closed by gaprl** 2024-01-26 19:57 UTC
Labels: Product Area: Crons
