### ISSUE TITLE
Sourcemaps not being applied

### ISSUE THREAD

**Issue by z418577198** [getsentry/sentry#15537] opened 2019-11-04 06:16 UTC
the files has uploaded to sentry successfully as in the image:
![image](https://user-images.githubusercontent.com/25921131/68102240-c61d2500-ff0c-11e9-8109-3e09ceb7b004.png)

However the code is still minified on the details/dashboard screen:
![image](https://user-images.githubusercontent.com/25921131/68102333-2744f880-ff0d-11e9-8b5d-6fad7c2fbe7c.png)

my webpack config ：
![image](https://user-images.githubusercontent.com/25921131/68102377-5b201e00-ff0d-11e9-8151-6b6c2b5a8521.png)

sentry init detail:
![image](https://user-images.githubusercontent.com/25921131/68102429-a803f480-ff0d-11e9-8903-d663042554f1.png)

Any assistance would be appreciated thank you

**Comment by kamilogorek** [comment] 2019-11-11 12:35
cc @BYK

**Comment by BYK** [comment] 2019-11-19 21:42
@z418577198 source maps need to be uploaded before the events. Sentry does not retroactively parse old events with source maps. Can that be the case for you?

**Comment by BYK** [comment] 2020-10-22 21:36
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Closed by BYK** 2020-10-22 21:36 UTC

**Comment by superman66** [comment] 2020-11-17 07:47
I have the same problem with self-hosted. But source-map work fine when i switch to sentry.io.
I have confirmed these things:
* event and source-map in the same release;
* souce-map was uploaded before event;
* sentry version is v9.1.2;
![image](https://user-images.githubusercontent.com/12592949/99360440-8ba1e280-28eb-11eb-94d4-9a85d33c7b75.png)
![image](https://user-images.githubusercontent.com/12592949/99360578-c4da5280-28eb-11eb-9ed2-db4d1093a1db.png)

**Comment by BYK** [comment] 2020-11-17 11:47
@superman66 please file a new issue with the issue template if you are having a similar problem.
