### ISSUE TITLE
[JIRA] Allow to filter by the ones without jira ticket assigned

### ISSUE THREAD

**Issue by MaicolBen** [getsentry/sentry#15725] opened 2019-05-20 22:26 UTC
It'd be great to filter by sentry issues which don't have a ticket in jira linked, so it's easy to triage them.

**Comment by feyyazesat** [comment] 2019-11-26 19:25
Would love to see such feature.

**Comment by josimar-silva** [comment] 2020-03-31 07:44
This would be very helpfull.

**Comment by rhaussmann** [comment] 2020-05-12 15:17
Thanks for all the work on this integration. It is saving me a ton of time. I wanted to voice a request for this feature as well. I just noticed the JIRA tag in gray under the title this morning. That's been helpful!

**Comment by scottapow** [comment] 2020-06-09 14:20
I see the tag too but am not sure how to build a search to target issues with(out) linked JIRA tickets.

**Comment by hackel** [comment] 2020-06-19 22:32
Dupe of #8338.  This is a critical issue for those of us who do not assign issues within Sentry.  I would really like to see this included in the "Needs Triage" filter.  A filter like this has got to be trivial to implement, right?

**Comment by saifelse** [comment] 2020-10-26 09:41
I put up a PR for this: #21593. It was pretty easy to pattern match off of the assigned filter!

**Comment by BYK** [comment] 2020-10-26 18:19
Duplicate of #8338

**Closed by BYK** 2020-10-26 18:19 UTC
Labels: Component: Integrations
