### ISSUE TITLE
Project-Specific Budgets for Errors & Transactions

### ISSUE THREAD

**Issue by chaitanyadeorukhkar** [getsentry/sentry#79881] opened 2024-10-29 07:47 UTC
### Problem Statement

**Project-Specific Budgets**
A critical feature request for us is the ability to set per-project budgets for errors and transactions. This functionality would allow us to allocate a specific quota for each project, ensuring that individual projects do not exceed their budgeted quota. Currently, projects can consume more than their intended share, impacting other projects due to overall quota usage. This is a high-priority requirement for us, and the lack of this feature is impacting us severely

### Product Area

Settings - Projects

**Comment by brianthi** [comment] 2024-10-29 23:17
Hi @chaitanyadeorukhkar, thank you for writing in and sharing this feedback. I'm going to close this as a duplicate of this ticket: https://github.com/getsentry/sentry/issues/18904. Please feel free to add your thoughts and feedback the ticket I linked if you feel like it doesn't already encapsulate your request.

**Closed by brianthi** 2024-10-29 23:17 UTC
Labels: Waiting for: Product Owner, Product Area: Settings - Spend Allocation
