### ISSUE TITLE
Add option to disable "common values" in grouping.

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#47458] opened 2023-04-11 12:34 UTC
Often customers reach out informing events are no grouping correctly, after checking the information the root cause is that Sentry is striping common values such as:

```
message Container Exited (Status: <int>)
or
message Request failed with status code <int>
```

Making different exit status, or http error code to be grouped together. The current workaround is to add fingerprint rules to manually add the exact message to grouping, edit grouping at the SDK side.

```
message:"Request failed with status code 400" -> error-400-type
message:"Request failed with status code 500" -> error-500-type
or
error.value:”Request failed with status code*” -> {{ error.value }}
``` 

Solution: Add an option to not strip common values.

**Comment by jjbayer** [comment] 2023-04-17 11:18
Transferred this to sentry because that's where the replacement happens:

https://github.com/getsentry/sentry/blob/7b100d16f0b8e52a6258fb3013f21ebef424f71c/src/sentry/grouping/strategies/message.py#L93-L96

@getsentry/issue-experience is this something you could look into?

**Comment by lobsterkatie** [comment] 2024-12-11 04:56
This is a duplicate of https://github.com/getsentry/sentry/issues/51232.

**Closed by lobsterkatie** 2024-12-11 04:56 UTC
Labels: Component: Grouping
