### ISSUE TITLE
Spend Allocation - I want to be able to set up spend allocation for at least 1 billing cycle in advance 

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#51277] opened 2023-06-20 14:44 UTC
### Problem Statement

Use case: My main application is eating up all quota on the first day, which makes us really need to pay close attention to when the billing cycle renews. As we can set the spend allocation on the first moment it renews.

### Solution Brainstorm

Being able to set the spend allocation for the next billing cycle

### Product Area

Settings - General

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1858) by [Unito](https://www.unito.io)

**Comment by Dhrumil-Sentry** [comment] 2023-06-20 22:25
Thanks for the feedback- We don't have any near to mid-term plans on enhancing this feature yet but I am adding this to our backlog to gauge interest from the community as well

**Comment by edzis** [comment] 2023-06-26 12:21
Why do we even have to do this every month?

I followed the "spend allocations page" link from the "organization has consumed 100% of its transactions spend allocation" email but could not do anything - of course, my limit for this month is depleted.

I would expect it to specify this once and then tune as necessary. Not expecting to remember going into these settings every month.

**Comment by Dhrumil-Sentry** [comment] 2023-06-27 19:25
Marking this issue as a duplicate of https://github.com/getsentry/sentry/issues/51721

@edzis Thanks for this feedback I've shared our rationale in the linked issue

**Closed by Dhrumil-Sentry** 2023-06-27 19:25 UTC
Labels: Status: Backlog, Sync: Jira, Product Area: Settings
