### ISSUE TITLE
Cron: Missed Checkin reported when no checkin was meant to happen

### ISSUE THREAD

**Issue by AlexDochioiu** [getsentry/sentry#46025] opened 2023-03-18 18:54 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

{
checkin_margin: 5, 
max_runtime: 2, 
schedule: 0 15 */1 * * *, 
schedule_type: 1, 
timezone: UTC
}

### Expected Result

A checkin should be expected `At 15 minutes past the hour, every hour, every day`

### Actual Result

A checkin is expected `At 15 minutes past the hour, every hour, every day` **and** a checkin is also expected every day at 3:05 PM UTC (and is always reported as missed)

**Comment by gaprl** [comment] 2023-03-20 18:37
Hey @AlexDochioiu, I'd love to further investigate why you got that missed check-in alert. I see you are using our SaaS. To further assist you, do you mind submitting a ticket to our customer support team with your organization name and monitor id, please?

You can do so by logging into your Sentry account > Clicking on Help > Contact customer support. Please mention my name on the ticket and we can take it from there.

<img width="286" alt="CleanShot 2023-03-20 at 11 34 36@2x" src="https://user-images.githubusercontent.com/1308394/226434757-8f49171e-cfef-446f-a020-80115016a6c1.png">

**Comment by evanpurkhiser** [comment] 2023-04-03 22:49
This is because the schedule `0 15 */1 * * *` has 6 fields, which I don't think we properly support.

**Comment by evanpurkhiser** [comment] 2023-04-03 23:03
Duplicate of https://github.com/getsentry/sentry/issues/46824

FYI @AlexDochioiu, I believe if you set your schedule to `0 15 */1 * *` this will work as expected

**Closed by evanpurkhiser** 2023-04-03 23:03 UTC
Labels: Status: Investigating, Team: Crons
