### ISSUE TITLE
Editing alert in alert menu not working

### ISSUE THREAD

**Issue by erfantkerfan** [getsentry/sentry#60541] opened 2023-11-24 12:23 UTC
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Install [23.10.0](https://github.com/getsentry/self-hosted/releases/tag/23.10.0)
updated to [23.11.0](https://github.com/getsentry/self-hosted/releases/tag/23.11.0)
after visiting this [url](https://sentry.company.com/organizations/MyOrgName/alerts/metric-rules/MyProject/44/) to edit an alert I'm getting an error (not sure if this updated killed it or previous updates)

### Expected Result

For this URL to work and allow my to edit my alerts

### Actual Result

![image](https://github.com/getsentry/sentry/assets/37825504/ebe0f02f-907f-4de4-9a1e-39d2f81703d3)

after digging more I found out that error is comming from this [url](https://sentry.company.com/api/0/organizations/MyOrgName/alert-rules/available-actions/)

![image](https://github.com/getsentry/sentry/assets/37825504/7c525b30-8551-4b83-a3e6-203502af0843)

 here us the log for container `web`:
 
![image](https://github.com/getsentry/sentry/assets/37825504/c9e00afc-16b4-4742-813c-0fabeb90c9e0)

### Product Area

Alerts

### Version

23.11.0

**Comment by erfantkerfan** [comment] 2023-11-24 12:23
text of error to make you life easier and say thanks:

```
sentry-self-hosted-web-1  | 20:45:28 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.project_environments.ProjectEnvironmentsEndpoint' response=200 user_id='38' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/projects/XXX/transport/environments/' caller_ip='46.224.72.18' user_agent='Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.18451833724975586 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
sentry-self-hosted-web-1  | Traceback (most recent call last):                                                                                                                                                                        sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 229, in handle_exception                                                                                                         sentry-self-hosted-web-1  |     response = super().handle_exception(exc)                                    
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
sentry-self-hosted-web-1  |     self.raise_uncaught_exception(exc)                                                                                                                                                                    sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception                                                                                            sentry-self-hosted-web-1  |     raise exc                                                                                                                                                                                             
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/api/base.py", line 353, in dispatch
sentry-self-hosted-web-1  |     response = handler(request, *args, **kwargs)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/incidents/endpoints/organization_alert_rule_available_action_index.py", line 117, in get
sentry-self-hosted-web-1  |     installs = app_service.get_installed_for_organization(
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/services/hybrid_cloud/app/impl.py", line 84, in get_installed_for_organization
sentry-self-hosted-web-1  |     return [fq.serialize_rpc(i) for i in installations]
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/services/hybrid_cloud/app/impl.py", line 84, in <listcomp>
sentry-self-hosted-web-1  |     return [fq.serialize_rpc(i) for i in installations]
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/services/hybrid_cloud/app/impl.py", line 183, in serialize_rpc
sentry-self-hosted-web-1  |     return serialize_sentry_app_installation(object)
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/services/hybrid_cloud/app/serial.py", line 60, in serialize_sentry_app_installation
sentry-self-hosted-web-1  |     sentry_app=serialize_sentry_app(app),
sentry-self-hosted-web-1  |   File "/usr/local/lib/python3.8/site-packages/sentry/services/hybrid_cloud/app/serial.py", line 27, in serialize_sentry_app
sentry-self-hosted-web-1  |     return RpcSentryApp(
sentry-self-hosted-web-1  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
sentry-self-hosted-web-1  | pydantic.error_wrappers.ValidationError: 1 validation error for RpcSentryApp
sentry-self-hosted-web-1  | application_id
sentry-self-hosted-web-1  |   none is not an allowed value (type=type_error.none.not_allowed)
sentry-self-hosted-web-1  | 20:45:28 [INFO] sentry.superuser: superuser.superuser_access (superuser_token_id='qEeavDLfz2Ud' user_id=38 user_email='erfan.gh@xxx.com' su_org_accessed='xxx')
sentry-self-hosted-web-1  | 20:45:28 [INFO] sentry.access.api: api.access (method='GET' view='sentry.incidents.endpoints.organization_alert_rule_available_action_index.OrganizationAlertRuleAvailableActionIndexEndpoint' response=50
0 user_id='38' is_app='False' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/xxx/alert-rules/available-actions/' caller_ip='46.224.72.18' user_agent='Mozilla/5.0 (X11; L
inux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.3841559886932373 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='
None' group='None' limit='None' remaining='None')
sentry-self-hosted-web-1  | 20:45:28 [ERROR] django.request: Internal Server Error: /api/0/organizations/xxx/alert-rules/available-actions/ (status_code=500 request=<WSGIRequest: GET '/api/0/organizations/xxx/alert-rules/availab
le-actions/'>)
sentry-self-hosted-web-1  | 20:45:28 [INFO] sentry.superuser: superuser.superuser_access (superuser_token_id='qEeavDLfz2Ud' user_id=38 user_email='erfan.gh@xxx.com' su_org_accessed='xxx')
sentry-self-hosted-web-1  | 20:45:28 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.organization_users.OrganizationUsersEndpoint' response=200 user_id='38' is_app='False' token_type='None' is_fronten
d_request='True' organization_id='1' auth_id='None' path='/api/0/organizations/xxx/users/' caller_ip='46.224.72.18' user_agent='Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0' rate_limited='False' rate_lim
it_category='None' request_duration_seconds=0.5192193984985352 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
```

**Comment by erfantkerfan** [comment] 2023-11-25 12:09
I can confirm that after revering to a backup from with Sentry 23.7.1 the menu works again

**Comment by hubertdeng123** [comment] 2023-11-28 20:07
Closing as duplicate of https://github.com/getsentry/self-hosted/issues/2595

**Closed by hubertdeng123** 2023-11-28 20:07 UTC
Labels: Product Area: Alerts, Waiting for: Product Owner
