### ISSUE TITLE
Can't create a new project with platform "javascript-react"

### ISSUE THREAD

**Issue by antoinebugni** [getsentry/sentry#52515] opened 2023-07-10 13:06 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Projects > Create Project
2. Select "React"
3. Click on "Create Project"

### Expected Result

Project should be created, and I should be redirected to the next step for project configuration.

### Actual Result

I get an error on screen : "invalid platform"

This error comes directly from the API:

```https://sorted.sentry.io/api/0/teams/sorted/sorted/projects/```

With the following payload:

```
{"name":"myproject","platform":"javascript-react","default_rules":true}
```

### Product Area

Projects

**Comment by christophflick-toast** [comment] 2023-07-10 13:14
Same error here when creating a new project.
URL: `/api/0/teams/<company>/<team>/projects/`
with the payload of `{name: "project-name", platform: "javascript-react", default_rules: false}`
Response: `{"platform":["Invalid platform"]}`

**Comment by Fwang36** [comment] 2023-07-10 16:09
Hi, 

Thanks for reporting, this is a duplicate of [52509](https://github.com/getsentry/sentry/issues/52509), and a fix should be ready shortly.

**Closed by Fwang36** 2023-07-10 16:09 UTC
Labels: Status: Unrouted, Waiting for: Support

**Comment by antoinebugni** [comment] 2023-07-10 16:11
Thanks, apologies for the duplication!

**Comment by priscilawebdev** [comment] 2023-07-10 18:30
The issue is now fixed @antoinebugni and @christophflick-toast 😉
