### ISSUE TITLE
Sentry login fails when cookie with {""} exists

### ISSUE THREAD

**Issue by dkpat12** [getsentry/sentry#8432] opened 2018-05-14 14:21 UTC
I've found that I can't log in to sentry when a cookie is set which has a value that contains a curly brace and parenthesis. (Think JSON formatted cookie) The login page appears to refresh when I attempt to login. I'm investigating whether or not we can just change the value of our cookie, but that seems like it will take considerable work, so I'm hoping you guys can fix this bug.

Example Cookie value: {"key1":"value1"}
Sentry 8.21.0 via Docker

**Comment by mattrobenolt** [comment] 2018-05-14 19:08
You mean just any other cookie on your domain?

**Comment by mattrobenolt** [comment] 2018-05-14 19:44
I can't seem to reproduce this on our production sentry.io, so maybe this is something that a web server like nginx would be fixing and escaping for you?

I feel like it might be tripping up the Django cookie parser, as just a guess. And nginx is handling it better and passing it along in a better way.

If you can do this, I'd highly suggest it anyways, you could also use nginx to strip an offending cookie.

Ironically, this also references Django: https://librenepal.com/article/remove-specific-cookies-with-nginx/

**Comment by dkpat12** [comment] 2018-05-15 19:19
Huh. It's weird that you can't seem to reproduce. I've verified in our setup that once we remove or change that cookie we are able to login without any problem so it is definitely attributed to the value it has.

I took a look at the workaround in the post you linked to and it does seem to solve the problem we have; and it was way easier to implement than changing our cookie. Thanks for that link!!

**Comment by BYK** [comment] 2020-10-21 19:06
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Closed by BYK** 2020-10-21 19:06 UTC
