### ISSUE TITLE
CppException - com.swmansion.reanimated.nativeProxy.EventHandler in receiveEvent

### ISSUE THREAD

**Issue by naheedsa** [getsentry/sentry#59976] opened 2023-11-15 11:36 UTC
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Fix one of the issues in the App.

### How are you getting stuck?

Cannot read property '__workletHash' of undefined

### Where in the product are you?

Issues

### Version

    "@sentry/react-native": "5.10.0",

**Comment by Fwang36** [comment] 2023-11-15 16:00
Closing Issue as Duplicate of [#3400 In React Native Repo](https://github.com/getsentry/sentry-react-native/issues/3400)

**Closed by Fwang36** 2023-11-15 16:00 UTC
Labels: Waiting for: Support
