### ISSUE TITLE
Bug when sentry createuser

### ISSUE THREAD

**Issue by edisonan** [getsentry/sentry#7015] opened 2018-01-19 09:13 UTC
## Reporting Bugs

When reporting bugs, include details about your configuration, such as:

- sentry, version 8.22.0
- Use Python
- Include a stacktrace or other logs when relevant

```
./sentry createuser
Email: axxxxx@126.com
Password: 
Repeat for confirmation: 
Error: the two entered values do not match
Password: 
Repeat for confirmation: 
Should this user be a superuser? [y/N]: y
User created: accacc@126.com
09:10:25 [ERROR] sentry.errors: Internal project (id=1) does not exist
Traceback (most recent call last):
  File "./sentry", line 11, in <module>
    sys.exit(main())
  File "/www/sentry/lib/python2.7/site-packages/sentry/runner/__init__.py", line 161, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/www/sentry/lib/python2.7/site-packages/sentry/runner/commands/createuser.py", line 95, in createuser
    org = Organization.get_default()
  File "/www/sentry/lib/python2.7/site-packages/sentry/models/organization.py", line 128, in get_default
    )[0]
  File "/www/sentry/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
```

**Comment by radski** [comment] 2018-01-22 00:30
I'm having same issue, believe this is due to the default project not having been created after running "sentry upgrade"

**Comment by plamen-nikolov** [comment] 2018-05-16 19:27
The same issue here. I tried to rebuild the database, but still doesn't work

**Comment by falstack** [comment] 2018-05-16 23:02
same issue

**Comment by nopium** [comment] 2018-08-17 07:11
The problem is with SINGLE_ORGANIZATION option. 
Set it to false in sentry.config
and then create it manually from $ sentry shell
Check this for reference (How do I script the Sentry installation to bootstrap things): 
https://docs.sentry.io/server/faq/

**Comment by atlas1119** [comment] 2018-10-31 02:32
same issue,why?

**Comment by alexandernst** [comment] 2018-12-23 23:58
I'm also hitting this

**Comment by lorn** [comment] 2019-08-30 14:56
> The problem is with SINGLE_ORGANIZATION option.
> Set it to false in sentry.config
> and then create it manually from $ sentry shell
> Check this for reference (How do I script the Sentry installation to bootstrap things):
> https://docs.sentry.io/server/faq/

I just followed this and my problem was fixed :+1:

**Comment by joseluisq** [comment] 2019-11-07 10:18
**Docker users:**

If you are using Docker append `SENTRY_SINGLE_ORGANIZATION=false` to your existing environment variables.

**Comment by BYK** [comment] 2019-11-07 22:19
Closing as a working solution is provided both at https://github.com/getsentry/sentry/issues/7015#issuecomment-413778501 and https://github.com/getsentry/sentry/issues/7015#issuecomment-551015592.

Please use the [community forums](https://forum.sentry.io) for any further discussion.

**Closed by BYK** 2019-11-07 22:19 UTC
