### ISSUE TITLE
Sentry CLI Plugin: Command failed: /app/node_modules/@sentry/cli/sentry-cli releases new ... error: project not found

### ISSUE THREAD

**Issue by SeungHeeMun-GGQ** [getsentry/sentry#63657] opened 2024-01-23 08:33 UTC
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

This error occurs when deploying intermittently.
In some cases, this can be resolved by re-running the job, but it is very inconvenient.

I am curious as to why this error occurs, the cause, and the solution.

### How are you getting stuck?

 > [8/8] RUN yarn build:DEV:
60.24 Sentry CLI Plugin: Command failed: /app/node_modules/@sentry/cli/sentry-cli releases new ...OOOOOO
60.24 error: project not found

### Where in the product are you?

Unknown

### Version

    "@sentry/nextjs": "^7.63.0",

**Comment by 17hogeju** [comment] 2024-01-25 00:32
> This error occurs when deploying intermittently.

@SeungHeeMun-GGQ Can you tell me more about when this started happening?

It would be helpful to have some additional information like your DSN to debug this issue.

**Comment by natemoo-re** [comment] 2024-12-09 21:32
Hello, thanks for opening an issue! Since we don't have much information for a reproduction and there hasn't been any activity here recently, I'm going to close this issue so our backlog remains actionable.

If anyone is still running into this problem, please feel free to open a new issue.

**Closed by natemoo-re** 2024-12-09 21:32 UTC
Labels: Product Area: Releases
