### ISSUE TITLE
New identical issues received at the same time aren't grouped

### ISSUE THREAD

**Issue by laurentgoudet** [getsentry/sentry#15744] opened 2019-11-21 08:58 UTC
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I couldn't tell if it only started recently or not, but it seems that the first few events of new identical issues aren't grouped properly.

By identical issues I mean that the grouping configs are the same (`newstyle:2019-05-08`) and the exception stack-trace & in-app exception stack-trace hashes are identical (as per the "Event grouping information" beta feature), i.e. these should definitely have been grouped together.

It seems to happen when the new events are received at the exact same time, e.g. as it was the case for:
https://sentry.io/organizations/freelancercom/issues/1347654434/events/00691c9bb9954ab4b1418002919e5f7d/
https://sentry.io/organizations/freelancercom/issues/1347654435/events/3a72f125aa044b82ae1a569526756e44/
https://sentry.io/organizations/freelancercom/issues/1347654436/events/e92c8dc7c97846ffbc65c2f37139533c/

It doesn't seem specific to that particular project (nor client SDKs), as another project with different technologies (still using `newstyle:2019-05-08` grouping though) shows similar grouping issues:
https://sentry.io/organizations/freelancercom/issues/1346323369/events/bfa0dc9a95604406b32fd14df893e4f4
https://sentry.io/organizations/freelancercom/issues/1346323368/events/16bec445c571456e8b677c1f107441ff/

In addition, when re-triggering the errors the next events are then grouped properly, so it does seem to only happen when the issue is first created and/or is due to how Sentry handles incoming events with the similar timestamps.

### What you expected to happen

All events with identical grouping hashes should be grouped together.

### Possible Solution

I'm guessing this could be due to some cache propagation delays/slave drift, i.e. the incoming processing logic not finding any current match for the event hashes & defaulting to create a new issue.

Not sure if something changed on the Sentry side & made that worst, or I've just haven't noticed it beforehand.

**Comment by tkaemming** [comment] 2019-11-21 19:21
This is likely a duplicate of #5085.

**Comment by BYK** [comment] 2020-10-22 21:43
Closing in favor of #5085.

**Closed by BYK** 2020-10-22 21:43 UTC
