### ISSUE TITLE
Jira Integration Problem

### ISSUE THREAD

**Issue by tommy31** [getsentry/sentry#63821] opened 2024-01-25 10:04 UTC
### Environment

We are running on prem Sentry 21.3.096d5172

### Steps to Reproduce

We start an integration fo Jira through Sentry > Integration > Jira.
After we finish the setup on jira we click on "Finish installation" on jira that redirect us on our Sentry.

Then we end up with this error :

`09:59:12 [INFO] sentry.integrations.client: integration.http_response (integration='jira' status_string='403' error='403 Client Error: Forbidden for url: https://xxxxxxx.atlassian.net/rest/api/2/status?jwt=XXXXXXXXXXXX' org_id=1 integration_id=1 org_integration_id=7)`

This setup was running for years and stop working on 22/01/2024, that why we try to reinstall it.

**Comment by sentaur-athena** [comment] 2024-01-29 18:06
Thank you for reporting. I'll look into it.

**Comment by hermzz** [comment] 2024-02-01 18:35
Turns out the issue is that JIRA stopped supporting passing the jwt as a query parameter and instead now it needs to be an Authorization header (https://developer.atlassian.com/cloud/jira/platform/understanding-jwt-for-connect-apps/#creating-a-jwt-token). This has already been fixed in the later versions of Sentry by d9f5e5fa9ceec614e6deedd2f8f7c484d8a99e0b. However, if like me, you can't also easily update Sentry I created a small change to backport the change to older versions of Sentry: 25752b180f3c92047dccec05e065c72e01792a22.

**Closed** 2024-02-02 23:19 UTC
Labels: Product Area: Settings - Integrations, Waiting for: Product Owner
