### ISSUE TITLE
Incorrect issue order with environment filter

### ISSUE THREAD

**Issue by stellaatsentry** [getsentry/sentry#53928] opened 2023-08-01 13:50 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Go to the issues tab and choose an environment from the dropdown filter. Make sure that the sorting order is on "Last Seen".

### Expected Result

The issues show up with the "last seen" timestamp in order from newest to oldest.

### Actual Result

The order of the issues seems to be mixed. For example, an issue that was last seen 2 weeks ago is higher up than an issue that was last seen 18 minutes ago.

A similar behavior is observed if we manually set the environment in the search bar. It gives a different order from the previous case, but we can still see older issues higher than newer ones.

Please see the internal ticket for further details.

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1898) by [Unito](https://www.unito.io)

**Comment by malwilley** [comment] 2023-08-01 18:03
Duplicate of https://github.com/getsentry/sentry/issues/53922

**Closed by malwilley** 2023-08-01 18:03 UTC
Labels: Sync: Jira
