### ISSUE TITLE
Broker URL does not support Redis SSL configuration

### ISSUE THREAD

**Issue by thomas-mcdonald** [getsentry/sentry#7108] opened 2018-01-30 16:47 UTC
I started a [discussion on the forum](https://forum.sentry.io/t/configuring-redis-w-ssl/2893) about this at the end of last year, figured I should follow up on it.

Sentry is using a very old version of Kombu (somewhere backing celery, from memory) that does not support configuring Redis w/SSL through a urlstring. We have Elasticache configured to force SSL connections and it took a lot of time flailing around to realise that the broker configuration w/Kombu was the issue. I am having to monkeypatch the library to hardcode usage of `redis.SSLConnection` since there is no exposed/working configuration options.

(There's a second issue here, that BROKER_URL is configured very differently from the rest of the Redis options)

Sentry 8.22, Docker install.

**Comment by trondhindenes** [comment] 2019-10-16 10:53
bump on this - this hurts us too.

**Comment by GabrielRivera21** [comment] 2019-12-21 01:00
Hi @thomas-mcdonald mind sharing the "patched" version of the kombu library to support SSL? Currrently having to do the same thing :(

**Comment by BYK** [comment] 2020-10-23 19:09
I think this is a duplicate of another issue which I happily closed by stating that we are now on a much recent version of `kombu` that supports this.

Comment if this is not the case or it is still not working for you.

**Closed by BYK** 2020-10-23 19:09 UTC
