### ISSUE TITLE
[Node] Take me to Session Replay maybe shouldn't be in the nodejs setup?

### ISSUE THREAD

**Issue by obostjancic** [getsentry/sentry#76814] opened 2024-09-02 12:55 UTC

**Comment by obostjancic** [comment] 2024-09-02 12:57
https://github.com/getsentry/sentry/blob/d836df040b66bc9439c32c3958353acde2687957/static/app/data/platformCategories.tsx#L407

**Comment by matejminar** [comment] 2024-09-09 09:29
Duplicate of https://github.com/getsentry/sentry/issues/77138

**Closed by matejminar** 2024-09-09 09:29 UTC
