### ISSUE TITLE
[Bug?] All the email notifications are disabled, but Sentry ignores it and sends emails about regressions

### ISSUE THREAD

**Issue by dmitry-fedyuk** [getsentry/sentry#4850] opened 2017-01-31 10:57 UTC
I use Sentry **8.13.0.dev0** (SaaS version).
I have described the problem on the Sentry forum: https://forum.sentry.io/t/839
Looks like it is a bug?

**Comment by tkaemming** [comment] 2017-01-31 21:46
This is not a bug, and I'm closing this ticket accordingly. Discussion on the merit of this as a feature request can happen on the forum, or at GH-4681.

**Closed by tkaemming** 2017-01-31 21:46 UTC
