### ISSUE TITLE
Long query times when accessing an event with MySQL

### ISSUE THREAD

**Issue by deejay1** [getsentry/sentry#1290] opened 2014-10-08 11:32 UTC
When I try to access a recent event, for example something via a URL like https://sentry/proj/app/group/7174/ it results in very long query times and timeouts.
The query is
```sql
explain SELECT `sentry_message`.`id`, `sentry_message`.`group_id`, `sentry_message`.`message_id`, `sentry_message`.`project_id`, `sentry_message`.`logger`, `sentry_message`.`level`, `sentry_message`.`message`, `sentry_message`.`view`, `sentry_message`.`checksum`, `sentry_message`.`num_comments`, `sentry_message`.`platform`, `sentry_message`.`datetime`, `sentry_message`.`time_spent`, `sentry_message`.`server_name`, `sentry_message`.`site`, `sentry_message`.`data` FROM `sentry_message` WHERE (`sentry_message`.`group_id` = 7174 AND NOT (`sentry_message`.`id` = 30556877 ) AND `sentry_message`.`datetime` <= '2014-10-08 10:44:24' ) ORDER BY `sentry_message`.`datetime` DESC LIMIT 1\G
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: sentry_message
         type: range
possible_keys: PRIMARY,sentry_message_d8a12f30,sentry_message_5f412f9a
          key: sentry_message_d8a12f30
      key_len: 5
          ref: NULL
         rows: 4892469
        Extra: Using index condition; Using where
1 row in set (0.35 sec)
```

Dropping the limit clause results in faster searches:
```sql
mysql> explain SELECT `sentry_message`.`id`, `sentry_message`.`group_id`, `sentry_message`.`message_id`, `sentry_message`.`project_id`, `sentry_message`.`logger`, `sentry_message`.`level`, `sentry_message`.`message`, `sentry_message`.`view`, `sentry_message`.`checksum`, `sentry_message`.`num_comments`, `sentry_message`.`platform`, `sentry_message`.`datetime`, `sentry_message`.`time_spent`, `sentry_message`.`server_name`, `sentry_message`.`site`, `sentry_message`.`data` FROM `sentry_message` WHERE (`sentry_message`.`group_id` = 7174 AND NOT (`sentry_message`.`id` = 30556877 ) AND `sentry_message`.`datetime` <= '2014-10-08 10:44:24' ) ORDER BY `sentry_message`.`datetime`\G
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: sentry_message
         type: range
possible_keys: PRIMARY,sentry_message_d8a12f30,sentry_message_5f412f9a
          key: sentry_message_5f412f9a
      key_len: 9
          ref: NULL
         rows: 4
        Extra: Using index condition; Using where; Using filesort
1 row in set (0.66 sec)
```
Actually using any other limit number than 1 results in fast searches.

Sentry version 6.4.4

Any ideas?

**Comment by rhugh** [comment] 2015-01-13 23:47
This is a bit long, as there's multiple aspects to this problem, and I'm not convinced my solution is the best, nor that it'll be ideal for everyone.  As such, I'm describing both the aspects of the problem, and why I chose a particular way of solving it.  Hope this helps others.  @deejay1 and @adampetrovic, this is likely your problem.


Overview: If you have a Sentry database contains a high quantity of events, and you see ridiculously slow queries occur for events where there's only 1 event in the "group", or the adjacent event is distant in the overall event stream e.g. last one was 30 days ago), you may be seeing a query planner problem. 

Symptoms: Unexpected delay, up to and including timeout, when attempting to view an event in the web view "http://sentry/*team*/*project*/group/*group_id*".  Inspecting processlist/pg_stat_activity will show a query on sentry_messages with "AND NOT (`sentry_message`.`id` = *id* )" in the WHERE clause, and ending in "LIMIT 1".

Disclaimer: I am not a DBA, and more critically, I am not your DBA.  My explanation and solution may be right for the wrong reasons, etc.  YMMV.

Root cause: Your sentry_message table is comprised almost entirely of rows that have a non-unique value in group_id.  "One-time events" are the exception.  The database engine will probably use the date index to decide a starting point, but the query planner believes a sequential scan will be the lowest cost method to retrieve the next row containing the desired group_id.  Lower cost than utilizing the available id and/or group_id indexes, and reading the row from the table.  There may also be some transactional "viewability" implications involved.

Aggravating factors: If you're not using buffering/queueing, it's likely there'll be more total rows in a high-volume instance.  But more critically, it'll increase the tendency to have "hot" group_id keys, which reinforced the query planner's assumptions about this.  Tuning more aggressive sampling rates would likely reduce hot group_id's.

Indexes: Availability of a composite index may change the query planner's cost analysis.  I decided not to test at this time.  Do remember that indexes aren't free; every index created, must be written with each row inserted/updated.  The higher the volume of events you ingest, the greater the cumulative penalty.  If you decide to test, be aware postgres will lock tables by default, and that on a large table it'll take a while; if you're seeing timeouts now, assume the index will take a few days, esp. if creating concurrently (and it'll lock tables if you don't.)  For the analysis of potential benefit of adding any index, I'll yield to a DBA familiar with _your_ database and usage model.

A Solution: Within web/frontend/groups.py, render_with_group_context, I extended order_by to include '-id' for prev_event, and 'id' for next_event.  This doesn't benefit the query itself, it just modifies the cost analysis of the query planner.  I like this change because it's minimally invasive in the code, and appears to have no significant detrimental effects elsewhere.  Single event queries now return as fast as those for multiple events.

Alternate solutions: Composite indexes might help; see caveats.  Depending on the row count ratio of sentry_groupedmessage to sentry_message, the table is an ideal candidate for refinement; noop if first_seen = last_seen, otherwise use these values to yield ranged boundaries, a composite index on 'id' and 'times_seen' in this table might also be suitable as a cheap noop test.  Sharding high-volume publishers to a separate instance/database would likely help with what is fundamentally a diversity issue, and potentially simplify some throttling efforts, esp. if you have some particularly noisy publishers, or in conjunction with indexes to reduce their cost.  Sharding can be done transparently with location/rewrite rules.

Scope: I would guess that @dcramer hasn't seen the same problems with hosted instances, as there's probably much greater diversity in the group_id's, better sharding of data, lower overall volume per project, or other changes to the _data_ itself.  It's also possible they're running composite indexes that avoid this problem.  Whatever the outcome, not everyone will encounter this problem, as it's not a 'bug", but a limitation of the database engine's query planner.  These "one-time events" are a statistical anomaly in the eyes of the query planner, for those experiencing this problem.

Extra: I also found that for my database engine (postgres), there was benefit to tuning checkpoint and auto-vacuum behavior.  Vacuuming can significantly affect the performance of queries on large tables, e.g. sentry_message, and their related indexes.  (Insufficient auto-vacuuming negatively impacts performance.)

**Comment by tgross** [comment] 2015-03-10 18:02
I ran into this at [DramaFever](https://github.com/DramaFever) a while back and we ended up forcing the correct index to use via index hinting. This is less portable than @rhugh's suggestion (IIRC it might be MySQL-specific) but has been working for us:

https://gist.github.com/tgross/de1e75f01f7978bb0c25

**Comment by NotSqrt** [comment] 2015-04-16 09:22
Just ran into this issue with PostgreSQL.

Is there any index that I could create to improve this ?

**Comment by NotSqrt** [comment] 2015-05-05 17:24
After some investigations, on PostgreSQL, this is primarily due to huge discrepancies in the table statistics : groups of events can range from 1 event to several hundred thousands, which disorientates the query planner.

**Comment by dcramer** [comment] 2015-05-07 02:58
@NotSqrt you can create an index across (group_id, datetime)

**Comment by mattrobenolt** [comment] 2016-02-12 07:34
Closing since this is old. If this is still an issue, feel free to reopen.

**Closed by mattrobenolt** 2016-02-12 07:34 UTC
