### ISSUE TITLE
Most of plugins dead after you changed NotifyPlugin to NotificationPlugin

### ISSUE THREAD

**Issue by fangli** [getsentry/sentry#2264] opened 2015-11-03 10:27 UTC
If a plugin is still inherit from NotifyPlugin with sentry7.7.0, it won't work anymore, even if you have a backward compatible design.

You export NotifyPlugin here,
https://github.com/getsentry/sentry/blob/4fe795403fb5e082d5be3ecd4b60d983f9e843a9/src/sentry/plugins/bases/notify.py#L146

But if a plugin is using NotifyPlugin instead of NotificationPlugin, the notify_users will still never be called.

Here is a fix example:
https://github.com/linovia/sentry-hipchat/pull/38/files

IMHO, it's sentry's responsibility to fix it since it still guarantee the backward capacity.

Due to this issue, most of plugins will be broken when upgrade to sentry 7.7.0

**Comment by mitsuhiko** [comment] 2015-11-03 15:22
Yes, that does seem odd.  I will look into why this broke in the first place.

**Comment by mattrobenolt** [comment] 2015-11-03 15:24
Hmmm, I'm not entirely sure why `NotifyPlugin` would behave differently from `NotificationPlugin`. They should be treated identically.

In 7.7.x, it doesn't matter what base class a plugin uses, technically. There's only two methods that matter, `should_notify` and `rule_notify`.

See: https://github.com/getsentry/sentry/blob/7.7.1/src/sentry/rules/actions/notify_event.py#L38-L43

And it also checks for `NotificationPlugin` instances when collecting plugins to notify: https://github.com/getsentry/sentry/blob/7.7.1/src/sentry/rules/actions/notify_event_service.py#L59-L66

But this all seems to work the same:

```
>>> from sentry.plugins.bases.notify import NotifyPlugin
>>> class FooPlugin(NotifyPlugin): pass
...
>>> isinstance(FooPlugin(), NotificationPlugin)
True
>>> FooPlugin().__version__
1
```

I'm not entirely sure what would be going on here to cause different behavior. We definitely didn't intentionally break backwards compatibility here. :/

**Comment by mitsuhiko** [comment] 2015-11-03 15:27
Cannot reproduce.  I'm going to close this.  In case you have a clear repro of what exactly is broken please open a second issue.

**Closed by mitsuhiko** 2015-11-03 15:27 UTC

**Comment by mattrobenolt** [comment] 2015-11-03 15:28
Also, as another datapoint, we use that plugin (linova/sentry-hipchat) in production ourselves and haven't had any issues from it because of this.

**Comment by fangli** [comment] 2015-11-03 15:32
thanks for the reply, it's really late here. I'd like to reproduce this issue in a clean env and provide you details tomorrow. pretty odd:(
