### ISSUE TITLE
Issues not moving out of Archived state

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#59612] opened 2023-11-08 13:46 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Pick an issue from the Issues Tab and click Archive > Until this occurs again... > one time... > from now. The issue triaging options should change to the following:
![image](https://github.com/getsentry/sentry/assets/81985895/90c569e4-0024-4825-82c5-dd132dcec7ef)

2. Manually trigger the error in your app again

### Expected Result

Once the new event is received, the issue status changes from `Archived` to `Unresolved`, and therefore, the issue should be visible in the Unresolved tab.

### Actual Result

The issue is never moved back to the `Unresolved` tab, and instead remains in the `Archived` tab. However, when looking at the issue, it's triaging options change back to those that appear when an issue is on unresolved status.
![image](https://github.com/getsentry/sentry/assets/81985895/7fcd99cf-8336-43a0-8def-18b5399a9974)

[Issue link](https://dragonfruit-dev.sentry.io/issues/4612563738/?project=4504179109068800&query=is%3Aarchived&referrer=issue-stream&statsPeriod=24h&stream_index=0)

### Product Area

Issues

**Comment by jangjodi** [comment] 2023-11-09 18:03
I was able to replicate this issue. It seems that _sometimes_, the issue archive condition will be exceeded, but the issue will not escalate. Instead, it will become `ongoing` and stay in the `Archived` tab.

**Incorrect Archived -> Ongoing Example**
<img width="1252" alt="Screenshot 2023-11-09 at 9 47 48 AM" src="https://github.com/getsentry/sentry/assets/116035587/af84b73e-a851-4f7b-8659-3f598b301f80">
<img width="1026" alt="Screenshot 2023-11-09 at 9 56 40 AM" src="https://github.com/getsentry/sentry/assets/116035587/acbc7d43-5027-4a31-9a0c-8c5f4940bb06">

**Correct Archived -> Escalating Example**
<img width="1258" alt="Screenshot 2023-11-09 at 9 47 40 AM" src="https://github.com/getsentry/sentry/assets/116035587/71ed5c66-e448-403a-b340-2754c572624a">

Any ideas why this might be happening @NisanthanNanthakumar?

**Comment by InterstellarStella** [comment] 2023-11-14 14:10
@jangjodi So I noticed that the issue acquired the "Ongoing" label eventually, however, it never moved out of the "Archived" tab. I needed to delete the issue today for some other testing, but until that point it had remained in Archived.

**Comment by scttcper** [comment] 2023-11-14 22:09
closing this as a duplicate of #53161

**Closed by scttcper** 2023-11-14 22:09 UTC
Labels: Product Area: Issues, Waiting for: Product Owner
