### ISSUE TITLE
Creating an alert using `release.stage: adopted` in the Sentry web UI throws a 500 error

### ISSUE THREAD

**Issue by arifken** [getsentry/sentry#70666] opened 2024-05-10 16:43 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Navigate to Alerts > Create Alert > Crash free user rate
2. Select a project and environment
3. for filters, enter `release.stage:adopted` 
4. Set some thresholds below (I used 99.5 as critical, 99.7 as warning and 99.75 as recovery)
5. Name the alert
6. Click "Add alert"

### Expected Result

The alert should be created and visible in the Alert list.

### Actual Result

An error appears in lower right of the screen:
<img width="547" alt="Screenshot 2024-05-10 at 9 38 57 AM" src="https://github.com/getsentry/sentry/assets/98625/ac82af13-d3f7-4562-ac54-47f4e0430450">

And in the console the message 
```
Failed to load resource: the server responded with a status of 400 ()
us.sentry.io/api/0/organizations/REDACTED/alert-rules/?duplicateRule=false&referrer=alert_stream&sessionId=REDACTED&wizardV3=true:1 

Failed to load resource: the server responded with a status of 500 ()
```

### Product Area

Alerts

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2203) by [Unito](https://www.unito.io)

**Comment by ceorourke** [comment] 2024-05-13 19:07
@iambriccardo I reproduced this and tracked the error id to [this Sentry issue](https://sentry.sentry.io/issues/5089561941/events/5d6c9686f26d4fbbba127253b574d14f/?project=1&referrer=issue-list&statsPeriod=14d) that's assigned to your team, can you take a look? I don't see a telemetry team on GitHub to assign this to.

**Comment by rachrwang** [comment] 2024-07-01 14:59
@iambriccardo - do you have any updates to share on this ticket? Thanks!

**Comment by iambriccardo** [comment] 2024-07-05 10:29
Hi, sorry, I completely missed the notification. I will check it out!

**Comment by matejminar** [comment] 2024-07-05 11:27
There seems to be a bug in UI that let's you add all kinds of filters to session alerts. Session alerts support only a very small subset of filter conditions and I believe release.stage is not one of them. We'll get this fixed 🙏

**Closed** 2024-07-11 06:38 UTC
Labels: Sync: Jira, Product Area: Alerts
