### ISSUE TITLE
Crash Free Rates separated by Mobile Platform type Android and iOS - React Native

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry#56470] opened 2023-09-19 14:07 UTC
### Problem Statement
defined previously here:
https://getsentry.atlassian.net/browse/FEEDBACK-1397
https://getsentry.atlassian.net/browse/FEEDBACK-1673

Can't separate crash free rates by Android vs iOS
- Release Health
- Project Details
- Dashboards Widgets

OS type at the minimum, and if that's just a tag then maybe offer it for tags: "filter and aggregate crash-free rates based on tags (OS, browser, etc) "

### Product Area

Unknown

**Comment by Dhrumil-Sentry** [comment] 2023-09-19 21:03
We don't have concrete plans for this at this moment, We know this has been a long pending ask from customers -esp mobile customers. But this involved making changes to how Sessions are being stored and is a non-trivial change.

I don't expect this to be supported in the next 2-3 quarters

**Comment by Dhrumil-Sentry** [comment] 2023-09-19 23:32
cc @kahest for visibility

**Comment by Dhrumil-Sentry** [comment] 2023-12-07 06:13
This GH issue is a duplicate of https://github.com/getsentry/sentry/issues/58348 , closing this one

**Closed by Dhrumil-Sentry** 2023-12-07 06:13 UTC
Labels: Product Area: Releases
