### ISSUE TITLE
Slack Integration: 

### ISSUE THREAD

**Issue by amirhossein-smo-kd** [getsentry/sentry#23361] opened 2021-01-27 10:36 UTC
Does any one know why sentry doesn't send notification to slack , It was sending until last night  , nothing changed , but today no notification sends to slack

**Comment by cocorossello** [comment] 2021-01-27 12:34
Same as https://github.com/getsentry/sentry/issues/23362

**Comment by BYK** [comment] 2021-01-27 21:13
Duplicate of #23362.

**Closed by BYK** 2021-01-27 21:13 UTC
