### ISSUE TITLE
List a Project's Issues，GET /api/0/projects/{organization_slug}/{project_slug}/issues/

### ISSUE THREAD

**Issue by yysfwls** [getsentry/sentry#55750] opened 2023-09-06 06:25 UTC
### Problem Statement

Path Parameters Can be supported time intervals ？
only "24h", "14d", and "" Now

### Product Area

APIs

**Comment by yysfwls** [comment] 2023-09-06 06:32
Reference document：https://docs.sentry.io/api/events/list-a-projects-issues/

**Comment by Dhrumil-Sentry** [comment] 2023-09-06 21:16
@schew2381 @sentaur-athena some helpful feedback for our issues endpoint- I believe the time windows are fixed to these values today for several endpoints

**Comment by yysfwls** [comment] 2023-09-07 05:14
Are there plans to support this feature？like this
xxx?startTime=1693977220000&endTime=1694063620000

**Comment by Dhrumil-Sentry** [comment] 2023-09-07 16:05
Hi @yysfwls we don't have concrete plans for this as of now, but we'll keep this issue updated if we have any news to share

**Comment by jangjodi** [comment] 2024-12-10 22:26
I'm closing this issue as it's a duplicate of these two issues: https://github.com/getsentry/sentry/issues/38439 and https://github.com/getsentry/sentry/issues/45815

**Closed by jangjodi** 2024-12-10 22:26 UTC
Labels: Product Area: APIs
