### ISSUE TITLE
Unable to add Jira integration to EU orga

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#74335] opened 2024-07-16 07:20 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Follow the steps on this guide to install Jira integration: https://docs.sentry.io/organization/integrations/issue-tracking/jira/

[Edit]: I'm now able to reproduce it on my test organisation. 

### Expected Result

The integration is installed.

### Actual Result

The page auto closes and the integration is not installed. 

Steps performed so far from which none solved the issue:
- The same Jira instance was added to an US organisation, [due to this existing](https://github.com/getsentry/sentry/issues/68338) issue it cannot be added to both regions, the user has already removed the organisation from the US org.
- Usual browser errors: disable extensions, use private/incognito window, clear cache and cookies. 
- Removing the Sentry app in Jira and do a new install of it during the set up process. 

Adding information on the affected organisation in the shadow Jira ticket due to PII. 

### Product Area

Settings - Integrations

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2223) by [Unito](https://www.unito.io)

**Comment by GabeVillalobos** [comment] 2024-08-07 22:53
@rodolfoBee Do you have any additional context on this issue? I've only been able to reproduce it when I have an existing Jira integration to the same Jira org in another region. This also includes when the Jira integration is listed as `pending deletion`, meaning it's necessary to wait for the integration to be fully deleted before attempting to set up Jira in another region.

**Comment by rodolfoBee** [comment] 2024-08-08 09:55
unfortunately not, all the context I have is added to this ticket and to the internal jira ticket.

**Comment by GabeVillalobos** [comment] 2024-08-13 16:32
At this point, I'd advise the customer reattempt to install the integration in the EU since I don't see any more remnants of the old Jira installation on their organizations. I'll try to add a bit more logging around the Jira installation process in the meantime and will try to push a patch that shows error messages on the UI with a reason as to why their install failed.

**Comment by rodolfoBee** [comment] 2024-08-20 05:21
Surfacing the message in the UI will be helpful.

**Comment by GabeVillalobos** [comment] 2024-08-20 17:56
> Surfacing the message in the UI will be helpful

Agreed. I'm balancing a couple of other tickets related to Jira at the moment, but have this on my priority list of things to fix. I'll keep this ticket open until that's finished.

**Comment by Jeroenkeesom** [comment] 2024-10-30 03:32
Kobby Bawuah advice me to let you know that we experience the same issue, helpdesk ticket 135630. 
I'm not able to relink jira, also not after reinstall of the integration.

**Comment by sentaur-athena** [comment] 2024-10-31 23:00
Thank you. At this point we know the problem but it's not a trivial fix. @GabeVillalobos will look into it and post an update as soon as we have any.

**Comment by GabeVillalobos** [comment] 2024-12-11 00:07
This is a duplicate of https://github.com/getsentry/sentry/issues/74335, closing this issue in the meantime, but will prioritize a fix for this accordingly.

**Comment by GabeVillalobos** [comment] 2024-12-11 00:08
This is a duplicate of https://github.com/getsentry/sentry/issues/68338, closing this in the meantime, but will prioritize a fix for this accordingly.

**Closed by GabeVillalobos** 2024-12-11 00:08 UTC
Labels: Sync: Jira, Product Area: Settings - Integrations
