### ISSUE TITLE
Userfeedback UI error

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#62212] opened 2023-12-21 19:48 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

**Description:**
A customer wrote in encountering the following error when accessing one of userFeedback for one of their errors:
<img width="1222" alt="Screenshot 2023-12-21 at 10 00 46 AM" src="https://github.com/getsentry/sentry/assets/8451987/1bfbda2c-f528-4518-be67-a61f9c0824a8">

Steps to reproduce:
1. Support ticket with customer org and example issue where this is occurring - https://sentry.zendesk.com/agent/tickets/109996

Associated Sentry issue: https://sentry.sentry.io/discover/sentry:acae2b7763bb42b1941beb8bd3a3b85b/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&homepage=true&name=All+Events&query=organization.slug%3Amatt-rogowski&sort=-timestamp&statsPeriod=24h&yAxis=count%28%29

### Expected Result

User feedback to display as multiple feedbacks are indicated

### Actual Result

Encounters _"There was an error loading data."_ error

### Product Area

User Feedback

**Comment by ryan953** [comment] 2023-12-22 03:16
Dupe of https://github.com/getsentry/sentry/issues/62166

**Comment by bruno-garcia** [comment] 2024-01-05 20:35
Resolved: https://github.com/getsentry/sentry/pull/62487

**Closed by bruno-garcia** 2024-01-05 20:35 UTC
Labels: Product Area: User Feedback
