### ISSUE TITLE
Issues missing from the Issues page

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#76380] opened 2024-08-19 11:11 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open the Issues page
2. Open Discover for the same time range
3. In Discover, events are shown that belong to an issue that is not present on the Issues page

Please see video in the Jira ticket. I couldn't reproduce the behaviour, it could be some cache issue.

### Expected Result

All issues should appear on the Issues page at all times

### Actual Result

Sometimes Issues are missing from the Issues page

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2258) by [Unito](https://www.unito.io)

**Comment by mrduncan** [comment] 2024-08-19 18:29
I haven’t been able to reproduce, if you are able to - try adding the environment column to discover, that’ll help us narrow down whether it’s discover or issues which is potentially returning incorrect data.

On a related note, we have some search backend improvements which will be rolling out in a couple of weeks which reduce some of the one-off nature of our querying.

Added a few more customer-specific details to the Jira link.

**Comment by mrduncan** [comment] 2024-11-06 20:51
I'm going to close this for now given it's age as we were not able to reproduce. Please reopen if you are able to provide a repro.

**Closed by mrduncan** 2024-11-06 20:51 UTC
Labels: Sync: Jira, Product Area: Issues
