### ISSUE TITLE
Not able to create a Crash free user rate SLO Alert for a specific release version

### ISSUE THREAD

**Issue by rajikanchu** [getsentry/sentry#74169] opened 2024-07-11 20:36 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

create alert crash free user rate 
under filter events select Project Name and environments and select release.version:x.x.1
Set thresholds and action and create alert 

### Expected Result

Save the alert and fire when the thresholds cross.

### Actual Result

 receiving Error msg: Unable to save alert: Internal Error

### Product Area

Alerts

**Comment by rachrwang** [comment] 2024-07-12 00:57
Thanks for filing this ticket! @priscilawebdev - do you know if your recent updates will fix this issue?

**Comment by priscilawebdev** [comment] 2024-07-12 06:42
Thanks for creating this ticket @rajikanchu. Recently, another user reported a similar issue, which we fixed here: https://github.com/getsentry/sentry/pull/74059. 

When selecting the alert option "crash free *", the only valid tag key is "release", and filtering by "release.version" is not allowed. This caused the validation error when you tried to save the alert. There was a UI issue that allowed these queries, but it should be fixed now.

**Comment by ceorourke** [comment] 2024-12-09 20:22
This is a duplicate of https://github.com/getsentry/sentry/issues/71712

**Closed by ceorourke** 2024-12-09 20:22 UTC
Labels: Product Area: Alerts
