### ISSUE TITLE
Merging issues in bulk does not honor search query and results in all issues being merged instead of filtered issues being merged

### ISSUE THREAD

**Issue by danclaroni** [getsentry/sentry#80365] opened 2024-11-07 11:39 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. In an environment with a lot of issues with the error message: "Error: Not found: *" and other issues
2. Go to the "Issues" view and filter by `is unresolved` and `message is Error: Not found: *`
3. Click the checkbox to select all the issues
4. Click the additional select all link that Sentry provides. It should say something like "Select all 753 issues" or something like that
5. Attempt to merge the isuses
6. Continue with merge (I believe the dialog that warns you about your bulk merge does not include the `Error: Not found: *` query despite the selection being limited to your 753 issues rather than all your projects issues)

### Expected Result

1. The selection should be honored and only the 753 issues should be merged matching the "Error: Not found: *" query.

### Actual Result

This process resulted in ALL my issues being merged into a single one rather than just the not found issues.

### Product Area

Issues

### Link

https://rapidtee.sentry.io/issues

### DSN

https://7b0b731f6cdb9356639a6692b67bba91@o4507470262304768.ingest.us.sentry.io/4507470507016192

**Comment by danclaroni** [comment] 2024-11-07 11:43
i'm ok with deleting these issues all together so i dont have to manually unmerge them, but if you can unmerge the ones that do not match the `Error: Not found: *` pattern, that would also work

**Comment by leeandher** [comment] 2024-11-07 14:51
@danclaroni Thanks for writing in! I wasn't able to reproduce the issue in testing, but I also didn't have as large a query to merge for test data as described in this issue. Since you were able to work around the issue, I will be closing this ticket out, but if you are able to reproduce it, or it anyone else experiences this issue, please reopen so we can dig a bit deeper.

As for this workflow, I suggest taking a look at [Fingerprint Rules](https://docs.sentry.io/concepts/data-management/event-grouping/fingerprint-rules/) for the project instead since this will avoid having to manually merge in the future, as Sentry will continue bucketing them into unique issues going forward.

**Closed by leeandher** 2024-11-07 14:51 UTC
Labels: Product Area: Issues, Waiting for: Product Owner
