### ISSUE TITLE
"Source code was not found for index.android.bundle" error

### ISSUE THREAD

**Issue by webzepter** [getsentry/sentry#3120] opened 2016-04-26 17:38 UTC
Hello. We integrate our application with Sentry error reporting service, but can't make JavaScript's sourcemaps work. We added `index.android.bundle file` with `sourceMappingURL=index.andorid.map` statement at the end, successfully uploaded index.android.map file to release, but sourcemaps in sentry don't work. What do we do wrong?

**Comment by mattrobenolt** [comment] 2016-04-26 17:39
If this is for getsentry.com, can you open a support ticket and we can investigate?

**Comment by webzepter** [comment] 2016-04-26 17:42
@mattrobenolt  I found, that this error may happed because of https://github.com/getsentry/sentry/blob/master/src/sentry/lang/javascript/processor.py#L254
Is it correct behavior?

**Comment by mattrobenolt** [comment] 2016-04-26 17:43
Yes, we expect a full url for sourcemaps, as a browser would.

**Comment by mattrobenolt** [comment] 2016-04-26 17:45
@benvinegar can probably help here on what to do since this is for React Native, but I'm closing this issue since it's not a bug against Sentry itself.

**Closed by mattrobenolt** 2016-04-26 17:45 UTC
