### ISSUE TITLE
Source SDK versions from release registry

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry#54088] opened 2023-08-03 07:00 UTC
**Problem Statement**
Today for platforms Java and Android (that I know of) the SDK versions are hard coded in the copy-paste snippets during the Project Onboarding. This requires manual updates every time there is a new release of the SDKs.

**Solution Brainstorm**
The SDK version should be dynamically retrieved from the registry, similar to how it is done in static-sites now. See PR below for reference

https://github.com/getsentry/static-sites/pull/1721

Related issue https://github.com/getsentry/sentry/issues/53921

**Comment by matejminar** [comment] 2023-08-14 17:16
Duplicate of https://github.com/getsentry/sentry/issues/53921

**Closed by matejminar** 2023-08-14 17:16 UTC
