### ISSUE TITLE
Truncate long user IDs in context interface (issue details)

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#5327] opened 2017-05-02 17:21 UTC
![](https://cloud.githubusercontent.com/assets/2153/25455274/114d29cc-2a84-11e7-857e-64a563a3c66d.png)

**Comment by mattrobenolt** [comment] 2017-05-02 17:22
Dupe of https://github.com/getsentry/sentry/issues/4447

**Closed by mattrobenolt** 2017-05-02 17:22 UTC
