### ISSUE TITLE
Error when install.sh "Argument list too long"

### ISSUE THREAD

**Issue by LocalHeroPro** [getsentry/sentry#64011] opened 2024-01-27 20:18 UTC
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

```bash
$ docker compose stop
$ git checkout master
$ git pull
$ ./install.sh
```
last lines of output:
```bash
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/django/caching.py", line 108, in sentry_create_connection
    cache = original_create_connection(self, alias)
  File "/usr/local/lib/python3.10/site-packages/django/core/cache/__init__.py", line 49, in create_connection
    raise InvalidCacheBackendError(
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django.core.cache.backends.memcached.MemcachedCache': Module "django.core.cache.backends.memcached" does not define a "MemcachedCache" attribute/class
Error in install/set-up-and-migrate-database.sh:12.
'$dcr web upgrade' exited with status 1
install/error-handling.sh: line 194: /usr/bin/yes: Argument list too long
install/error-handling.sh: line 194: /usr/bin/head: Argument list too long
install/error-handling.sh: line 194: /usr/bin/tr: Argument list too long
install/error-handling.sh: line 204: /usr/bin/docker: Argument list too long
```

### Expected Result

Can install application.

### Actual Result

Can't install application.

### Product Area

Issues

**Comment by syxolk** [comment] 2024-01-28 11:44
I get the same erron on the `24.1.1` branch:

```
```

**Comment by sander85** [comment] 2024-01-28 21:32
Had the same issue. Then I diffed changes and saw this in sentry/sentry.conf.example.py:

-        "BACKEND": "django.core.cache.backends.memcached.MemcachedCache",
+        "BACKEND": "django.core.cache.backends.memcached.PyMemcacheCache",

You need to make the same change in your sentry.conf.py to make it work.

**Comment by hubertdeng123** [comment] 2024-01-29 18:19
Looks like a duplicate of https://github.com/getsentry/self-hosted/issues/2728, so will close this

**Closed by hubertdeng123** 2024-01-29 18:19 UTC
Labels: Waiting for: Support
