### ISSUE TITLE
Custom Widget "Filter your results" does not allow for wildcard and or condition to be used concurrently

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#80425] opened 2024-11-07 22:32 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

- Navigate to create a custom widget
- Go the "Filter your results" section
- You'll find that using a wildcard works, or using the OR condition, but not both. For example:

Both of these work: 
plugin_sdk_version is 1.1.* 
plugin_sdk_version is 1.1.4 or 1.2.2

This does not work:
plugin_sdk_version is 1.1.* or 1.2.* 

The last filter results in no results being shown. Results are shown for both of the previous filters. 

Internal ticket contains example #137334

### Expected Result

Customer expects that both conditions be able to be used concurrently since they can be used separately to provide results

### Actual Result

No results shown when both wildcard and OR used

### Product Area

Dashboards

**Comment by gggritso** [comment] 2024-11-08 19:16
@ReneGreen27 thanks for raising this! That syntax is [not supported](https://docs.sentry.io/concepts/search/#multiple-values-on-the-same-key) by design. You can express this query like this: `(plugin_sdk_version:1.1.* OR plugin_sdk_version:1.2.*)`

I can add this as a feature request if you want. I'm also going to talk to the query builder team about maybe showing to the user that wildcards aren't supported in this way.

**Comment by rohit-gohri** [comment] 2024-11-09 10:26
@gggritso thanks for sharing that doc, I opened the original support request, the OR works 👍 

I guess I assumed the syntax would work because the UI kinda prompts you to add multiple values with the checkboxes:

 ![Image](https://github.com/user-attachments/assets/1a22e606-6336-456a-8594-9f6e538a03d7)


Maybe the multi select UI should be disabled once the wildcard key is added?

**Comment by gggritso** [comment] 2024-11-12 15:30
@rohit-gohri that's fair, I had the same thought! I filed a feature request on your behalf: https://github.com/getsentry/sentry/issues/80597 you can follow progress there. Closing this issue for now. Thanks 🙏🏻

**Closed by gggritso** 2024-11-12 15:30 UTC
Labels: Product Area: Dashboards, Waiting for: Product Owner
