### ISSUE TITLE
Timestamp column not possible to resize

### ISSUE THREAD

**Issue by Rarta** [getsentry/sentry#56637] opened 2023-09-21 05:55 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I have a very bad experience when I need to check issue all events. The TIMESTAMP column is half visible. And it's very difficult to expand it. I have to drag and resize other columns until there's enough space to make the Timestamp column wide enough to see the date and time in it. 
This column is most important in most of my cases and it's really annoying when you have to work so hard to see the full event date and time.

**Steps to reproduce:**
Open Sentry issue
Press on the All events tab
Try to resize "TIMESTAMP" column width. 

### Expected Result

Would be nice if this column would be moved to another position (not to be the last one) or added an option to expand it wider. 

### Actual Result

It's not possible to resize it. To do that you need to drag and resize other columns. 
[issue.webm](https://github.com/getsentry/sentry/assets/41193096/e063c18f-c355-4fc2-846a-56b298221670)

### Product Area

Issues

**Comment by ceorourke** [comment] 2023-09-21 23:04
Dupe of https://github.com/getsentry/sentry/issues/54636

**Closed by ceorourke** 2023-09-21 23:04 UTC
Labels: Product Area: Issues, Waiting for: Product Owner
