### ISSUE TITLE
Metric alerts constantly triggering while on critical status

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#52956] opened 2023-07-17 07:05 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a metric alert with a critical status:
2. Set any action for critical status
3. Trigger the alert
Example: 
![Screenshot 2023-07-17 at 09 00 52](https://github.com/getsentry/sentry/assets/64906376/36b6a6ad-b53e-45a9-a03a-b2a3f5d618ed)

### Expected Result

it sends ONE alert while on Critical status.

### Actual Result

It sends one message per minute while on critical, see screenshots from my slack and email:

![Screenshot 2023-07-17 at 09 03 26](https://github.com/getsentry/sentry/assets/64906376/d01f57c7-e903-47b3-b74c-7f147b6eac16)
![Screenshot 2023-07-17 at 09 03 04](https://github.com/getsentry/sentry/assets/64906376/b14e1389-e033-4f23-a4f0-2cbbe99522cc)

### Product Area

Alerts

**Comment by rodolfoBee** [comment] 2023-07-17 07:10
[link to test alert](https://dev-curumas.sentry.io/alerts/metric-rules/react/44717/)

**Comment by rodolfoBee** [comment] 2023-07-17 07:21
https://github.com/getsentry/sentry/pull/52930

**Comment by damnitrahul** [comment] 2023-07-17 08:33
Can confirm. Facing the same issue. Our Slack is being spammed by stale alert messages.

**Comment by n1ngu** [comment] 2023-07-17 10:39
Same. An alert is created aprox every minute 
![imatge](https://github.com/getsentry/sentry/assets/47453810/b7ca0964-c912-4140-94f8-bc079cc8e7cb)

**Comment by cleptric** [comment] 2023-07-17 12:36
I just wanted to give folks reading this a quick update that we're aware of the issue and are actively investigating the root cause.

**Comment by cleptric** [comment] 2023-07-17 20:50
A fix was deployed on production (https://github.com/getsentry/sentry/pull/52979) and with that I'm closing this 😄

**Closed by cleptric** 2023-07-17 20:50 UTC
Labels: Type: Bug, Product Area: Alerts, Waiting for: Product Owner

**Comment by Saniumarshamaki** [comment] 2023-07-18 04:16
Hello

**Comment by damnitrahul** [comment] 2023-07-20 09:14
This is happening again for Resolved status alert.
@cleptric @mitsuhiko

**Comment by wedamija** [comment] 2023-07-20 17:27
@damnitrahul I don't see any indications on our side that this is still happening, would you mind linking me to the specific alert? Feel free to send it via email dfuller@sentry.io if you'd prefer to not post here.

**Comment by damnitrahul** [comment] 2023-07-21 06:40
@wedamija Sent the links to your email.

**Comment by wedamija** [comment] 2023-07-25 19:53
Ok, I've pushed out a fix for this now and it should be mitigated. A small number of customers were having issues where a lot of alerts had triggered and were slowly resolving.
