### ISSUE TITLE
Search queries containing a ':' character do not work

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1968] opened 2015-09-16 20:09 UTC
We need to add some checking for tags that actually exist, as well as likely support quotes around it.

**Comment by jeremyhaile** [comment] 2015-09-16 20:58
I reported this error when searching for the name of an exception class: `Rack::Timeout::RequestTimeoutError`

**Comment by mattrobenolt** [comment] 2015-09-28 21:48
This was fixed with bd1a8e60051a318b063e0178839481fa22923ad1

**Closed by mattrobenolt** 2015-09-28 21:48 UTC
Labels: Component: Issues

**Comment by jaydorsey** [comment] 2020-07-10 18:19
This still doesn't work as expected (but maybe as designed). If anyone else stumbles across this issue, you have to create your search as `message:"Rack::Timeout"`

As expected (at least, for me):

![image](https://user-images.githubusercontent.com/191564/87185615-ee7cd080-c29e-11ea-9bd3-ec4f4f735c4e.png)

As works/designed:

![image](https://user-images.githubusercontent.com/191564/87185662-fc325600-c29e-11ea-829e-11d6a3161c65.png)

(I didn't open another issue because I reached out to support with this and it seems this is as-designed)
