### ISSUE TITLE
API error: APIError(No JSON data was found)

### ISSUE THREAD

**Issue by saytik** [getsentry/sentry#9813] opened 2018-09-19 14:53 UTC
sentry 9
raven==6.9.0
Debian9 + Python 2.7.11

```
python manage.py raven test --traceback
lib/python2.7/site-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
from django.utils import simplejson

Client configuration:
base_url : http://sentryall
project : 21
public_key : 52eb9f528d527901a6d52c
secret_key : f7544272da85db5a74b8b

Sending a test message... Event ID was '9be155397ae0df34b33'
ERROR 2018-09-19 17:43:52,070 Sentry responded with an API error: APIError(No JSON data was found)
ERROR 2018-09-19 17:43:52,070 [u'This is a test message generated using raven test']



```

My configuration:
```
INSTALLED_APPS = INSTALLED_APPS + (
    'raven.contrib.django.raven_compat',
)
RAVEN_CONFIG = {
    'dsn': 'http://5d527901a6d52c:f754427b54db5a74b8b@sentryall/21',
    }
LOGGING['handlers']['sentry.errors'] = {
    'level':'DEBUG',
    'class':'logging.StreamHandler',
    'formatter': 'simple'
}
LOGGING['loggers']['sentry.errors'] = {
    'level':'DEBUG',
    'handlers':['sentry.errors'],
    'propagate': True
}
```

**Comment by Alexgmin** [comment] 2019-06-11 10:40
As I said in #6978 

> 
> While I'm very late on this. I'm leaving this for future visitors.
> 
> I was having the same problem, and the reason was that Sentry was redirecting HTTP requests to HTTPS, and if you redirect a POST request, the body is lost, which causes this error.

**Comment by BYK** [comment] 2019-06-18 20:58
Closing this as the original author did not respond and the issue is pretty old.

**Closed by BYK** 2019-06-18 20:58 UTC
Labels: Component: On-Premise
