### ISSUE TITLE
Tracking which DSN generated an Event

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2709] opened 2016-02-18 17:52 UTC
A question came up if we could determine given an Event, which DSN was responsible for reporting it. I can imagine this being a scenario for abuse, and you'd want to shut down the DSN, but you'd need to know which one was compromised, etc.

I'm _sure_ there are other use cases, this one just came to mind.

Should we track this data with the Event? It seems reasonable to me to do so, and we could display it in the UI.

/cc @dcramer

**Comment by fermayo** [comment] 2016-02-18 17:58
+1!

**Comment by amegianeg** [comment] 2016-02-18 18:06
+1

**Comment by mattrobenolt** [comment] 2016-02-18 18:36
@fermayo @amegianeg If we added this meta data onto the Event, would that be useful even if it didn't have metrics attached to it?

**Comment by fermayo** [comment] 2016-02-18 18:41
Yes it would as a first approach.

**Comment by amegianeg** [comment] 2016-02-26 09:21
Hey @mattrobenolt , any updates about this? :)

**Comment by mattrobenolt** [comment] 2016-02-26 15:54
Nothing specific. Lemme see if I can cram this in for a Friday.

**Comment by amegianeg** [comment] 2016-02-26 15:56
Thank you @mattrobenolt

**Comment by amegianeg** [comment] 2016-03-15 17:27
Hey @mattrobenolt , is there any limit on the number of Client Keys that can be created per project?

**Comment by dcramer** [comment] 2016-03-15 17:31
@amegianeg no limits, though we haven't thoroughly tested flows with large numbers of keys

**Comment by amegianeg** [comment] 2016-03-15 18:14
Thank you @dcramer , can you tell me what _large_ means here?

**Comment by dcramer** [comment] 2016-03-15 18:15
Probably <10. The system doens't do anything inefficient with large numbers of keys though, so as far as I know it'll work fine. If this is on getsentry.com and you intend to create a million keys let us know since we might not like that ;)

**Comment by amegianeg** [comment] 2016-03-15 18:18
Looks like you are not going to like it, no... as we plan to have at least one DSN key per user :)

**Comment by dcramer** [comment] 2016-03-15 18:19
I would say go for it, and if you see any problems with slowness let us know. Most pages are optimized to paginate correctly, but in some areas we say "there will likely never be more than X results, so dont paginate just enforce a limit".

**Comment by amegianeg** [comment] 2016-03-15 18:23
Well the UI is not our problem, maybe I did not explained correctly: we are going to create them and use them (for example to avoid abuse scenarios) and only wanted to know if there can be any issue with the number of keys created, as we are going to create a couple... or more ;)

**Comment by dcramer** [comment] 2016-03-15 18:25
Nope, we build things with perf in mind, so the API won't have any issues with this.

**Comment by amegianeg** [comment] 2016-03-15 18:33
Cool! Thank you David

**Comment by BYK** [comment] 2020-09-30 12:49
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Closed by BYK** 2020-09-30 12:49 UTC
Labels: Status: Accepted, Type: Discussion, Type: User Feedback

**Comment by AndreKR** [comment] 2020-09-30 13:21
I think you should. Currently Javascript error tracking is pretty much impossible because it would leak the secret key which would allow adversaries to create fake error reports.

**Comment by BYK** [comment] 2020-09-30 13:38
@AndreKR just looked this up and I think this is now available: https://docs.sentry.io/accounts/quotas/#limiting-events

Does that solve your problem?

**Comment by mattrobenolt** [comment] 2020-09-30 14:14
We tag with key_id in the raw event payload for a while now. We don’t surface it in the UI though, but the data is there since https://github.com/getsentry/sentry/pull/6488

To me, this was the PR meant to close this Issue. If we wanted to expose this in the UI, that’s a further product decision.

**Comment by AndreKR** [comment] 2020-09-30 14:25
@BYK Your link shows something about quotas. Did you put the correct link?

**Comment by BYK** [comment] 2020-09-30 14:56
@AndreKR - yes. If you follow the link you'll see that it starts with 

>Per-key rate limits allow you to set the maximum volume of error events a key will accept during a period of time.

Sounds like it's a solution to the problem you mentioned?

**Comment by AndreKR** [comment] 2020-09-30 18:39
@BYK I think we're thinking of quite different scenarios. Here' the one I mean:

Imagine you're running an installation of a certain software. This software uses Sentry to track errors and since it uses a lot of Javascript code it forwards a Sentry DSN to Raven.js running in the browser. You have configured different DSNs for backend and frontend, but you have only one *project* configured because you want all the reports in one place. So now you're getting error reports from the backend and error reports from the frontend. You know that you can't really trust error reports from the frontend because they could be deliberately faked (or simply caused by browser extensions and such), no problem.

Now someone else wants to cause you trouble, so they set up another installation of the same software and they take your DSN from your frontend and generate bogus error reports.

You will then have error reports in your Sentry project that *look* like they come from your backend and thus can be trusted and *need* to be thoroughly investigated but in reality they came via the frontend DSN and are just fake.

**Comment by BYK** [comment] 2020-09-30 18:56
>You have configured different DSNs for backend and frontend, but you have only one project configured because you want all the reports in one place.

This is not how we intend you to use Sentry. You can see issues/events across multiple projects for quite a while now.

>You know that you can't really trust error reports from the frontend because they could be deliberately faked (or simply caused by browser extensions and such), no problem.

I mean, here at sentry.io we do as it is easy to filter out and ignore the chaff from the wheat with these filters we document.

>Now someone else wants to cause you trouble, so they set up another installation of the same software and they take your DSN from your frontend and generate bogus error reports.

Then you change your DSN and remove the old one. Or even better, start filtering the events from that old DSN.

>You will then have error reports in your Sentry project that look like they come from your backend and thus can be trusted and need to be thoroughly investigated but in reality they came via the frontend DSN and are just fake.

Again, see my earlier point: just use different projects for these as this is how Sentry is designed/intended to be used.

**Comment by AndreKR** [comment] 2020-09-30 19:19
> just use different projects for these as this is how Sentry is designed/intended to be used

Fair point, this would obviate the need to expose the particular DSN that generated an event.
