### ISSUE TITLE
Cannot create issue with ClickUp integration

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#78195] opened 2024-09-26 08:00 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. add the clickup integration
2. try creating a clickup issue using the integration
3. the external-issue-actions endpoint throws a 400 - bad request with the following response: 
`{"error":"Error communicating with Sentry App service"}`

### Expected Result

users should be able to create clickup issues using the integration

### Actual Result

![Image](https://github.com/user-attachments/assets/f355c2e2-888b-44bc-8265-8e7f7489d352)

### Product Area

Settings - Integrations

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2305) by [Unito](https://www.unito.io)

**Comment by sentaur-athena** [comment] 2024-09-27 22:42
@dalnoki is this issue reported by clickUp or a clickUp customer? Asking because clickUp is a 3rd party integration created by ClickUp and they're the ones providing support for it.

Looking at the dashboards on our side it looks mostly healthy.

**Comment by SkyhopperZH** [comment] 2024-09-30 09:28
Hello @sentaur-athena. I'm the original issue reporter.
I'm a customer of sentry & clickup.
I did start out by contacting clickup to get this fixed.
They sent me over to sentry.

I'd appreciate if you could just connect between Sentry & Clickup to get this on it's way. ;-)

Best regards
Martin

**Comment by sentaur-athena** [comment] 2024-09-30 17:36
@SkyhopperZH thanks for the details. The way we support 3rd party integrations is that we provide support for the platform and ensure the platform is healthy while the integration provider provides support for the health of their integration. Checking the logs I don't see any platform issues, I also don't see this as persisting problem with clickup.

Here are some errors that I see some clickup users are facing.
```
404 Client Error: for url: https://api.clickup.com/sentry/webhook
SafeHTTPSConnectionPool(host='api.clickup.com', port=443): Read timed out. (read timeout=2.0)
```
Either can throw a bad request from external-issue-endpoint.

I can't look further without more details. @dalnoki is there a support ticket associated with this?

**Comment by SkyhopperZH** [comment] 2024-10-01 08:45
@sentaur-athena: I'd be happy to assist if  you need me as the end user to run something. I'd require instructions though, as Sentrys UI is providing no guidance or context at all on why the call to create an issue is failing. 

I sent Dominic from the clickup team a link to this issue.
He was handling the ticket of the investigation from the clickup side.
Maybe it helps. 

Best regards
Martin

**Comment by sentaur-athena** [comment] 2024-10-02 20:12
I got some more pointers from @dalnoki. Will take a look.

**Comment by rodolfoBee** [comment] 2024-11-05 10:10
@sentaur-athena can we have an update on this issue? The issue continues to affect the original reporter of the issue.

For your investigation: I could not reproduce the issue on my organisations (both on the same plan as the affected user, one in the US and one in the EU data region):
[Link1](https://ent-curumas.sentry.io/issues/8711320/?project=-1&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=90d&stream_index=0)
[Link2](https://dev-curumas.sentry.io/issues/6011502720/?project=5242419&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=14d&stream_index=0)

**Comment by sentaur-athena** [comment] 2024-11-06 17:41
Yes, will prioritize investigation. I couldn't repro too but seems like @dalnoki has an example from the Jira ticket attached.

**Comment by SkyhopperZH** [comment] 2024-11-29 17:41
Uhm folks, would you mind taking care of this issue? Its been 2 months already.

**Comment by Christinarlong** [comment] 2024-12-03 20:09
@SkyhopperZH  hi! Rodolfo's comment above is the findings for the investigation. The main thing we found was we were only able to reproduce on only one user in the org. When that user tries to create a ticket and Sentry communicates that to Clickup, Sentry got back a "500 Server Error: Internal Server Error for url: https://api.clickup.com/sentry/create" from Clickup. 

At this point we can't debug further as we don't know why Clickup is sending back 500s for only one user. I'd point you to Clickup to see if they can give more insight to the 500.

**Comment by SkyhopperZH** [comment] 2024-12-05 08:27
@Christinarlong 
Both parties keep pointing to the other side.
I need you guys working together with clickup to fix your customers issue!
After all it's you claiming that it's clickups problem. I can only see your system throwing a generic error.

**Comment by sentaur-athena** [comment] 2024-12-05 18:44
@SkyhopperZH that's the nice thing about being open source. Please refer this ticket in your ClickUp communications and ask their engineers to follow-up about the error. They can also comment on the github issue and we would be happy to work with them. At this point it is clear to us that this is internal issue with their server though so I close the issue.

**Closed by sentaur-athena** 2024-12-05 18:44 UTC
Labels: Sync: Jira, Product Area: Settings - Integrations, Waiting for: Product Owner
