### ISSUE TITLE
Unable to Select Organization when setting up GitHub Auth 

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#68091] opened 2024-04-02 17:46 UTC
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Auth settings of org.
2. Click Configure next to GitHub 
3. Observe you are unable to select an organization

https://github.com/getsentry/sentry/assets/99350819/48e44d1d-1d34-4c2c-997f-4be63b32fd46

### Expected Result

Drop-down of organizations

### Actual Result

Unable to select an organization 

### Product Area

Settings - Auth

### Link

https://org2-w7.sentry.io/settings/auth/

**Comment by nhsiehgit** [comment] 2024-04-03 22:04
https://github.com/getsentry/sentry/assets/6186377/77a49061-ae69-4f03-a1b4-c6baaf677d7f

Hey @kerenkhatiwada - i'm unfortunately unable to reproduce this.
I wonder if this is a symptom of an incorrect github setting/permission?

going to close this issue out since i cannot reproduce.
Please reopen if we get more reported cases of this

**Closed by nhsiehgit** 2024-04-03 22:04 UTC
Labels: Product Area: Settings - Auth
