### ISSUE TITLE
Invalid configuration with redis

### ISSUE THREAD

**Issue by brunowego** [getsentry/sentry#15535] opened 2019-11-10 02:44 UTC
## Important Details

How are you running Sentry?

* [x] On-Premise docker
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Following the steps below, I'm getting a issue with redis. Perhaps a false negative?

## Steps to Reproduce

```sh
docker run -d \
  $(echo $DOCKER_RUN_OPTS) \
  -h redis.example.com \
  -e REDIS_PASSWORD='sentry' \
  -v sentry-redis-data:/data \
  -p 6379:6379 \
  --name sentry-redis \
  --restart always \
  docker.io/library/redis:5.0.5-alpine3.9 /bin/sh -c 'redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}'
```

```sh
docker run -d \
  $(echo $DOCKER_RUN_OPTS) \
  -h postgres.example.com \
  -e POSTGRES_USER=sentry \
  -e POSTGRES_PASSWORD=sentry \
  -e POSTGRES_DB=sentry \
  -v sentry-postgres-data:/var/lib/postgresql/data \
  -p 5432:5432 \
  --name sentry-postgres \
  --restart always \
  docker.io/library/postgres:11.2-alpine
```

```sh
# Before continue, pull sentry image.
docker pull docker.io/getsentry/sentry:5623682

export SECRET_KEY=$(docker run --rm docker.io/getsentry/sentry:5623682 config generate-secret-key | tail -n 1)
```

```sh
docker run -d \
  $(echo $DOCKER_RUN_OPTS) \
  -h sentry.example.com \
  -e SENTRY_POSTGRES_HOST='sentry-postgres' \
  -e SENTRY_DB_NAME='sentry' \
  -e SENTRY_DB_USER='sentry' \
  -e SENTRY_DB_PASSWORD='sentry' \
  -e SENTRY_REDIS_HOST='sentry-redis' \
  -e SENTRY_REDIS_PASSWORD='sentry' \
  -e SENTRY_SECRET_KEY="$SECRET_KEY" \
  -v sentry-data:/var/lib/sentry/files \
  -p 9000:9000 \
  --name sentry-base \
  --restart always \
  --link sentry-postgres \
  --link sentry-redis \
  docker.io/getsentry/sentry:5623682
```

```sh
docker run -d \
  $(echo $DOCKER_RUN_OPTS) \
  -h sentry-cron.example.com \
  -e SENTRY_POSTGRES_HOST='sentry-postgres' \
  -e SENTRY_DB_NAME='sentry' \
  -e SENTRY_DB_USER='sentry' \
  -e SENTRY_DB_PASSWORD='sentry' \
  -e SENTRY_REDIS_HOST='sentry-redis' \
  -e SENTRY_SECRET_KEY="$SECRET_KEY" \
  -v sentry-data:/var/lib/sentry/files \
  --name sentry-cron \
  --restart always \
  --link sentry-postgres \
  --link sentry-redis \
  docker.io/getsentry/sentry:5623682
```

```sh
docker run -d \
  $(echo $DOCKER_RUN_OPTS) \
  -h sentry-worker.example.com \
  -e SENTRY_POSTGRES_HOST='sentry-postgres' \
  -e SENTRY_DB_NAME='sentry' \
  -e SENTRY_DB_USER='sentry' \
  -e SENTRY_DB_PASSWORD='sentry' \
  -e SENTRY_REDIS_HOST='sentry-redis' \
  -e SENTRY_SECRET_KEY="$SECRET_KEY" \
  -v sentry-data:/var/lib/sentry/files \
  --name sentry-worker \
  --restart always \
  --link sentry-postgres \
  --link sentry-redis \
  docker.io/getsentry/sentry:5623682
```

Good items to include here include:

```sh
$ docker logs -f sentry-base
02:39:18 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
02:39:22 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 164, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 68, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 29, in inner
    configure()
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 127, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/settings.py", line 153, in configure
    skip_service_validation=skip_service_validation,
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 326, in initialize_app
    setup_services(validate=not skip_service_validation)
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 368, in setup_services
    service.validate()
  File "/usr/local/lib/python2.7/site-packages/sentry/utils/services.py", line 104, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "/usr/local/lib/python2.7/site-packages/sentry/buffer/redis.py", line 92, in validate
    raise InvalidConfiguration(six.text_type(e))
sentry.exceptions.InvalidConfiguration: invalid literal for int() with base 10: 'tcp://1.1.0.2:6379'
```

**Comment by BYK** [comment] 2019-11-19 22:56
Looks like your `REDIS_HOST` variable is getting set to something else somewhere. If you can trace the source of this `tcp://1.1.0.2:6379` value you should be able to find the cause of the issue.

Also, we strongly recommend using the [onpremise](https://github.com/getsentry/onpremise) repo setup for running sentry off of master. You don't seem to be running Kafka, Snuba, and Clickhouse which are all needed for running the latest version of Sentry properly.

I'm going go close this issue as this belongs more to [the forums](https://forum.sentry.io/) and would be happy to continue the discussion there.

**Closed by BYK** 2019-11-19 22:56 UTC

**Comment by SanderCrols** [comment] 2020-04-14 23:20
After having this issue myself, I discovered that the redis host 'sentry-redis' causes problems. Changing my redis instance to listen on 'sentryredis' and changing the env var fixed this problem

**Comment by iStrataDigital** [comment] 2020-05-12 19:13
Hey @SanderCrols Can i ask you what exactly you did ? Possible to paste the file name (config.yml) and the line. I just have like this. 
tcp://localhost:6379

- JK

**Comment by SanderCrols** [comment] 2020-05-12 19:17
I run this using docker on a kubernetes cluster. My redis instance could be found at “sentry-redis” which gave me the error above. I changed the url to the redis to “sentryredis” and that fixed it. I don’t use a config file because I inject all my variables using ENV variables.
