### ISSUE TITLE
Sentry is spamming all configured notification channels for the project

### ISSUE THREAD

**Issue by tinycogio** [getsentry/sentry#1403] opened 2015-01-27 01:31 UTC
We have Sentry notify our Hipchat room & Datadog stream when a new exception pops up. 
Starting at 5:17PM PST, it looks like Sentry is reporting every instance of the exception to Hipchat & Datadog instead of reporting only the first instance. Since there are a few exceptions that very often, it will spam our HipChat room making it unusable.

Maybe related to https://github.com/getsentry/sentry/issues/1401

**Comment by dcramer** [comment] 2015-01-27 01:32
@tinycogio unrelated to that specific commit. Is it still happening?

**Comment by dcramer** [comment] 2015-01-27 01:40
Confirmed this is resolved for users. Sorry about the trouble!

**Comment by dcramer** [comment] 2015-01-27 01:52
As we'll need to look back on this, here's the root cause:

- EventManager.save() was failing/rolling back (I'm not entirely sure how at the moment)
- That failure seemingly happened after the block returned, which is after queue jobs are dispatched
- When queue jobs were dispatched we saw foreign key failures (i.e. GroupRuleStatus couldn't pin to a missing Group.id)
- Due to the failures saving the group, and the followups of dispatching the events, they repeatedly fired off new notification/etc processors

I'm not entirely sure why this affected external customers (i.e. outside of internal sentry code), as stacktraces shouldn't have changed, but the gist of this is we need to fix the transactional behavior here. Ideally it's all autocommit and we intelligent use the responses of each statement.

**Comment by tinycogio** [comment] 2015-01-27 02:12
Yes, it seemed to already stop by the time I posted. 

Thanks for fixing it quickly and updating us with the root cause!

**Comment by tinycogio** [comment] 2015-01-27 02:14
Err.. go figure. It just started happening again at 6:12PM

**Comment by dcramer** [comment] 2015-01-27 02:15
It's possible this is something else then (and actually related to preventing the dupe notifications + refactor).

**Comment by dcramer** [comment] 2015-01-27 02:20
Yep. I'm an idiot. I see the issues :)

We rolled back again, and will get a fix/test to ensure this is resolved correctly.

(The other issue is unrelated)

**Comment by dcramer** [comment] 2015-01-27 02:25
Resolved in 7a83a7e8a13047a9471756d679e2deb596cc2ca1

**Comment by dcramer** [comment] 2015-01-27 02:25
(The problem was it just assumed every time an event was passed it was a regression, which is obviously wrong)

**Closed by dcramer** 2015-01-27 02:25 UTC
