### ISSUE TITLE
Show VueJS logo when stack trace is from a file `.vue`

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#80840] opened 2024-11-15 18:34 UTC
We currently show the "other" icon

![Image](https://github.com/user-attachments/assets/db523a37-89e1-4d12-807a-e039dd4e0022)

**Comment by mrduncan** [comment] 2024-11-15 18:35
Closing as this is a duplicate of #78826

**Closed by mrduncan** 2024-11-15 18:35 UTC
Labels: Product Area: Issues
