### ISSUE TITLE
Fix count of replays when error event is not tagged with replayId

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#48955] opened 2023-05-11 19:28 UTC
[Explanation](https://github.com/getsentry/team-replay/issues/68#issuecomment-1522026799) of how this happens.

This affects the count in Replays tab in Issue Details and the Issue tab in Replay Details. The counts are "0" in this case when the error event does not have a replay id. The Replay Details is solvable with a second query since the replay will have a list of error event ids. However, the Issue Details will not have any references to replays.

Other potential solutions:

* Attach listeners as early as possible
* Tag event with a second id that we can later query for (not sure if this will work as we still need a listener in order to tag event with id)

Ref https://github.com/getsentry/team-replay/issues/68

**Comment by ryan953** [comment] 2023-08-16 15:32
Related to, or duplicate of https://github.com/getsentry/team-replay/issues/106

closing.

**Closed** 2023-09-18 14:39 UTC
Labels: Product Area: Replays
