### ISSUE TITLE
Search for transactions and average duration of http.client request made

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry#50049] opened 2023-05-31 10:56 UTC
### Problem Statement

**Question:** "How do i filter to see in which transaction this url request is present?"

**Context:**
User's react native app makes requests to a 3rd party app, we'll call it http.url:"http://api.3rdpartyapp.com/. There are many transactions in the Performance Dashboard that include this http.client span.

They want to know 2 things
1. how long is this request taking
2. what are the transactions where it is present?

User does not control api.3rdpartyapp.com and therefore cannot install a Sentry SDK there.

User not looking to custom instrument a transaction for this yet, because there would be too many places in their codebase to have to custom instrument for every http.client request by their React Native App.

### Solution Brainstorm

**Solution**
Indexed spans and allow reporting of them, perhaps. At least for these http.client ones specifically. 

**Attempted Workarounds:**
can search in Discover by `http.url:"http://api.3rdpartyapp.com/**"` but this is URL of the transaction (frontend route name, or backend endpoint name usually) and not 1 http client request made _by_ the frontend route or backend itself, of which there may be many http.client requests made.

can search in Discover by `spans.http:[value in milliseconds]` but this is not the URL being called by the http.client request...This is searching all http.client requests. The search is being done by milliseconds and not http://api.3rdpartyapp.com

Performance dashboard shows Transactions and not http.client spans.

### Product Area

Performance

**Comment by zoesyc** [comment] 2023-06-02 15:33
hey @thinkocapo - This is a use case we're working on within Performance and aiming to capture in the near future. I'd be curious to understand what the 'next steps' for this user would be: 

- Are they looking to understand whether it's a third-party problem?
- Are they looking to understand whether it's a set of parameters they can change within their request?

All this to say, do we know what are the user is looking to understand with this information?

**Comment by zoesyc** [comment] 2024-02-29 19:47
@MisterJimson Thanks for the additional input! We are working on a workflow that focuses on aggregating network requests spans and identifying or troubleshooting hosts that trigger a significant number of 400 or 500 response codes. 

To follow up:
- When it comes to third-party APIs, what would you do with this information (or alternatively, what are your next steps)? Is it more about understanding whether the problem is within your control to fix?

**Comment by MisterJimson** [comment] 2024-02-29 21:28
One specific example that came up recently was a third party API provider contacting us and asking why our usage of a specific endpoint was so high. We used a log aggregation tool to measure requests to that specific endpoint per minute. This data exists in Sentry spans but we couldn't query it. We also used the same tool to graph it so we could monitor our improvements.

Another example was while investigating a bug, we wanted to see all requests to a specific third party endpoint, grouped by status code, and then graph the result. We would then determine if we need to make changes, reach out to vendors/customers, etc.

In general, understanding and visualizing outgoing http requests and their meta data is our goal.

**Comment by zoesyc** [comment] 2024-03-04 21:22
This is great feedback!

I've shared our proposed solution (with mockups) in our Discussions section (https://github.com/getsentry/sentry/discussions/66252) and would really appreciate any feedback or thoughts on how the vision may/ may not align with what you're looking for

**Comment by TomPridham** [comment] 2024-03-04 23:58
It would also be really useful to be able to pinpoint slow requests. We recently added `startSpan` to all our fetch and grpc calls and a lot of them get grouped automatically under the page load transaction. The hope was that we would be able to identify slow endpoints after adding the spans, but because they are grouped into other transactions they aren't usable or easily visible. It's also not clear when a span will generate a new transaction or will be grouped under an existing one. I spent a few hours today trying to figure out why only some of these spans weren't showing up in the Performance dashboard until I figured out that some were being grouped as child spans under the pageload. Also because they are child spans, we have to iterate through the list of spans and do the same scrubbing/normalization stuff we do to the top level transaction. None of this is horrible, it's just not intuitive and took a few hours of reading docs(mostly unfruitful) and digging through console logs(more fruitful) to actually figure out what's happening. It's also confusing because there isn't a way to mark them as separate transactions afaict. I would use `startTransaction`, but it's going to be removed in the next major, so I don't want to switch to that.


Also, an actual bug afaict. Once you are in the list of spans for a transactions, the search function doesn't seem to work on the span name. Neither a plain text search, nor the advanced syntax of `message: "my span"` or `"title: "my span"` worked
![Screenshot 2024-03-04 at 4 15 15 PM](https://github.com/getsentry/sentry/assets/8271228/144fa1dd-0c41-48aa-b60f-204cc7246f29)
![Screenshot 2024-03-04 at 4 15 29 PM](https://github.com/getsentry/sentry/assets/8271228/14bf0770-6ec1-4839-89ab-0e0e47c93e8f)

**Comment by AbhiPrasad** [comment] 2024-03-05 15:54
You can pass in `forceTransaction` into your `startSpan` constructor and it will force the span to be a transaction. See: https://github.com/getsentry/sentry-javascript/blob/1ff893bf9958c06c5d92d4565bc7e10062805d58/packages/types/src/startSpanOptions.ts#L23-L28C3

**Comment by TomPridham** [comment] 2024-03-05 20:29
That property looks like exactly what I was looking for. Thanks!

**Comment by MisterJimson** [comment] 2024-03-15 13:53
With the recent update to metrics, it seems like a lot of what I was requesting is doable. spans counted, grouped by status code, and filtered per domain.

**Comment by gggritso** [comment] 2024-03-18 13:58
Great! Closing this issue. For folks who have feature suggestions and/or questions about tracking HTTP requests, please contribute to the [discussion in GitHub](https://github.com/getsentry/sentry/discussions/66252)

**Closed by gggritso** 2024-03-18 13:58 UTC
Labels: Product Area: Performance, Waiting for: Product Owner
